const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const runtime=process.env.SILK_NODE_MODULES||'node_modules';
const {chromium}=require(path.join(runtime,'playwright'));
const root=path.join(__dirname,'..'),out=path.join(root,'dist/xhs'),release=path.join(root,'release'),L=require('../levels.js').levels,E=require('../engine.js');
const key='mini-polish:silk-loop-studio:v1:save';
const report={artifact:'dist/xhs: exact candidate contents',status:'RUNNING',viewports:[],checks:[],screenshots:[],errors:[],externalRequests:[]};
const server=http.createServer((req,res)=>{const file=path.resolve(out,'.'+(req.url.split('?')[0]==='/'?'/index.html':decodeURIComponent(req.url.split('?')[0])));if(!file.startsWith(out+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end('missing');return;}res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json'})[path.extname(file)]||'application/octet-stream','Content-Security-Policy':"default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'; worker-src 'none'"});res.end(fs.readFileSync(file));});
let browser;
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,args:['--disable-gpu'],executablePath:process.env.SILK_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
async function make(width,height,touch=width<500,extra={}){const c=await browser.newContext(Object.assign({viewport:{width,height},hasTouch:touch,deviceScaleFactor:1},extra));const p=await c.newPage();p.on('pageerror',e=>report.errors.push(String(e)));p.on('request',r=>{if(!r.url().startsWith(url))report.externalRequests.push(r.url());});return {c,p};}
async function snap(p,name){await p.evaluate(()=>window.scrollTo(0,0));await p.waitForTimeout(200);await p.screenshot({path:path.join(release,name+'.png'),fullPage:false});report.screenshots.push(name+'.png');}
async function overflow(p){const o=await p.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));assert.ok(o.scroll<=o.width,JSON.stringify(o));}
async function saved(p){await p.waitForTimeout(50);return p.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);}
async function click(p,id){if(await p.evaluate(()=>navigator.maxTouchPoints>0))await p.locator('#'+id).tap();else await p.locator('#'+id).click();}
async function selectMove(p,a){await click(p,a.axis+'-mode');await click(p,'track-'+a.index);await click(p,a.direction===1?'move-plus':'move-minus');await p.waitForTimeout(240);}
async function goLevel(p,n){await click(p,'brand');await click(p,'chapters');await p.locator('[data-level="silk-'+String(n).padStart(2,'0')+'"]').click();}
for(const [w,h] of [[320,720],[390,844],[1280,720]]){
 const {c,p}=await make(w,h);await p.goto(url);await p.locator('#tutorial-board').waitFor();
 for(let i=0;i<3;i++){assert.deepEqual((await p.locator('#tutorial-board .board').getAttribute('data-board')).split(',').map(Number),E.tutorial[i]);await overflow(p);await snap(p,'tutorial-'+(i+1)+'-'+w);if(i<2)await click(p,'tutorial-next');}
 await click(p,'tutorial-skip');await snap(p,'home-'+w);await click(p,'chapters');await overflow(p);assert.equal(await p.locator('.level-button').count(),48);await snap(p,'chapters-'+w);
 await p.locator('[data-level="silk-46"]').click();await overflow(p);await snap(p,'game-'+w);
 const sizes=await p.locator('.numbers button,.directions button,.axis-switch button').evaluateAll(bs=>bs.map(b=>{const r=b.getBoundingClientRect();return {width:r.width,height:r.height};}));sizes.forEach(b=>assert.ok(b.width>=48&&b.height>=48,JSON.stringify(b)));
 const grid=await p.locator('#game-board .board').boundingBox();report.viewports.push({width:w,height:h,boardWidth:grid.width,numberFont:await p.locator('.tag').first().evaluate(e=>getComputedStyle(e).fontSize),inputSizes:sizes});
 await selectMove(p,{axis:'row',index:0,direction:1});let s=await saved(p);assert.deepEqual(E.replay(L[45].initial,s.run.actions),E.shift(L[45].initial,{axis:'row',index:0,direction:1}));
 await click(p,'undo');assert.equal((await saved(p)).run.actions.length,0);await click(p,'redo');assert.equal((await saved(p)).run.actions.length,1);await p.reload();await p.locator('#continue').waitFor();await click(p,'continue');assert.equal((await saved(p)).run.actions.length,1);
 await click(p,'hint');await click(p,'deeper-hint');await click(p,'deeper-hint');await snap(p,'hint-'+w);await click(p,'apply-hint');await p.waitForTimeout(240);assert.equal((await saved(p)).run.practice,true);
 await click(p,'restart');await click(p,'restart-confirm');assert.equal((await saved(p)).run.practice,false);assert.equal((await saved(p)).run.actions.length,0);
 await click(p,'show-route');await snap(p,'strategy-'+w);await click(p,'replay-next');assert.equal((await p.locator('#replay-board .board').getAttribute('data-board')),E.shift(L[45].initial,L[45].solution[0]).join(','));await click(p,'modal-close');
 // Solve by real controls, then repeat the same independent win; the first claim stays single.
 await goLevel(p,1);await selectMove(p,L[0].solution[0]);await p.locator('.win').waitFor();await snap(p,'complete-'+w);s=await saved(p);assert.equal(s.claims.length,1);await p.reload();await p.locator('#continue').waitFor();assert.equal((await saved(p)).claims.length,1);
 await goLevel(p,1);await click(p,'restart');await click(p,'restart-confirm');await selectMove(p,L[0].solution[0]);assert.equal((await saved(p)).claims.length,1);
 await click(p,'win-collection');await overflow(p);await snap(p,'collection-'+w);await click(p,'brand');await click(p,'settings');await snap(p,'settings-'+w);await click(p,'settings-tutorial');await click(p,'tutorial-next');await click(p,'tutorial-next');await click(p,'tutorial-skip');assert.equal((await saved(p)).claims.length,1);await c.close();
}
report.checks.push('320/390 touch taps and desktop clicks: true tutorial, navigation, 48 levels, board dimensions, input >=48px, moves, undo/redo, refresh, current-state hint, restart, sandbox replay, repeat-win claim dedupe, collection, settings');
// Keyboard axis lock, animation lock, navigation cancellation, focus and scroll handling.
{
 const {c,p}=await make(1280,720,false);await p.goto(url);await p.locator('#tutorial-board').waitFor();await click(p,'tutorial-skip');await click(p,'continue');await p.keyboard.press('c');await p.keyboard.press('1');await p.keyboard.press('ArrowLeft');assert.equal((await saved(p)).run.actions.length,0);await p.keyboard.press('r');await p.keyboard.press('1');await p.keyboard.press('ArrowLeft');await p.keyboard.press('ArrowLeft');await p.waitForTimeout(240);assert.equal((await saved(p)).run.actions.length,1);assert.ok(E.solved(E.replay(L[0].initial,(await saved(p)).run.actions)));await p.keyboard.press('z');assert.equal((await saved(p)).run.actions.length,0);await p.keyboard.press('y');assert.equal((await saved(p)).run.actions.length,1);
 await goLevel(p,46);await click(p,'move-plus');await click(p,'brand');await click(p,'continue');await p.waitForTimeout(240);assert.equal(await p.locator('#game-board .tile[data-value]').count(),16);assert.deepEqual((await p.locator('#game-board .board').getAttribute('data-board')).split(',').map(Number),E.replay(L[45].initial,(await saved(p)).run.actions));
 await click(p,'tutorial-open');await p.locator('#modal-body').evaluate(e=>e.scrollTop=300);await click(p,'tutorial-next');assert.equal(await p.locator('#modal-body').evaluate(e=>e.scrollTop),0);await p.keyboard.press('Shift+Tab');assert.ok(await p.evaluate(()=>document.getElementById('modal').contains(document.activeElement)));await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'tutorial-open');await c.close();
}
report.checks.push('Keyboard R/C, 1–4, axis-mismatched arrows no-op, animation repeat input locked; navigation cancels old animation; 16 canonical tiles remain; tutorial internal scroll reset, focus trap/Escape return');
for(const w of [358,359,360,798,799,800]){const {c,p}=await make(w,720);await p.goto(url);await p.locator('#tutorial-board').waitFor();await click(p,'tutorial-skip');await goLevel(p,48);await overflow(p);await snap(p,'breakpoint-'+w);await c.close();}
for(const h of [649,650,651]){const {c,p}=await make(390,h);await p.goto(url);await p.locator('#tutorial-board').waitFor();await click(p,'tutorial-skip');await overflow(p);await snap(p,'height-'+h);await c.close();}
{
 const {c,p}=await make(320,720,true,{reducedMotion:'reduce'});await p.goto(url);await p.locator('#tutorial-board').waitFor();await click(p,'tutorial-skip');await goLevel(p,48);await p.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');document.body.style.fontSize='20px';});await overflow(p);await snap(p,'safe-large-reduced-320');await click(p,'tutorial-open');await snap(p,'safe-modal-320');await click(p,'modal-close');await p.setViewportSize({width:720,height:320});await overflow(p);await snap(p,'landscape-720');await c.close();
}
report.checks.push('width/height breakpoints ±1px, 44/34 safe areas, 20px body text, reduced motion, landscape');
{
 const {c,p}=await make(320,720,true);await p.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw Error('blocked');}});window.hostCount=0;window.SilkCompletionHost=()=>{window.hostCount++;return true;};});await p.goto(url);await p.locator('#tutorial-board').waitFor();await click(p,'tutorial-skip');assert.ok(await p.locator('#storage-warning').isVisible());await click(p,'continue');await selectMove(p,L[0].solution[0]);await p.locator('.win').waitFor();assert.equal(await p.evaluate(()=>window.hostCount),0);await snap(p,'storage-blocked-320');await c.close();
}
report.checks.push('Blocked storage remains playable and does not deliver unpersisted rewards');
assert.deepEqual(report.errors,[]);assert.deepEqual(report.externalRequests,[]);report.status='BROWSER_SIMULATION_PASSED';report.chromium=await browser.version();fs.writeFileSync(path.join(release,'browser-report.json'),JSON.stringify(report,null,2));console.log('Browser simulation passed:',report.screenshots.length,'screenshots; zero page errors/external requests');
})().catch(e=>{report.status='FAILED';report.failure=e.stack;fs.writeFileSync(path.join(release,'browser-report.json'),JSON.stringify(report,null,2));console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await new Promise(r=>server.close(r));});
