const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(path.join(process.env.SILK_NODE_MODULES||'node_modules','playwright'));
const root=path.join(__dirname,'..'),out=path.join(root,'dist/xhs'),L=require('../levels.js').levels,E=require('../engine.js'),key='mini-polish:silk-loop-studio:v1:save';
const report={status:'RUNNING',source:'final local candidate, real keyboard events; reduced-motion simulation',levels:[],pageErrors:[],externalRequests:[]};
const server=http.createServer((req,res)=>{const p=path.resolve(out,'.'+(req.url==='/'?'/index.html':decodeURIComponent(req.url)));if(!p.startsWith(out+path.sep)||!fs.existsSync(p)){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.svg')?'image/svg+xml':'text/html','Content-Security-Policy':"default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'none'; object-src 'none'; worker-src 'none'"});res.end(fs.readFileSync(p));});
let browser;
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,args:['--disable-gpu'],executablePath:process.env.SILK_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const c=await browser.newContext({viewport:{width:1280,height:720},reducedMotion:'reduce'});await c.addInitScript(()=>{window.received=[];window.SilkCompletionHost=p=>{window.received.push(p.eventId);return true;};});const p=await c.newPage();p.on('pageerror',e=>report.pageErrors.push(String(e)));p.on('request',r=>{if(!r.url().startsWith(url))report.externalRequests.push(r.url());});await p.goto(url);await p.locator('#tutorial-board').waitFor();await p.locator('#tutorial-skip').click();await p.locator('#continue').click();
for(const l of L){
 for(const a of l.solution){await p.keyboard.press(a.axis==='row'?'r':'c');await p.keyboard.press(String(a.index+1));await p.keyboard.press(a.axis==='row'?(a.direction===1?'ArrowRight':'ArrowLeft'):(a.direction===1?'ArrowDown':'ArrowUp'));}
 await p.locator('.win').waitFor();assert.equal(await p.locator('#game-board .board').getAttribute('data-board'),E.goal.join(','));await p.waitForTimeout(50);const d=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);assert.equal(d.run.actions.length,l.referenceMoves);assert.equal(d.claims.length,l.number);report.levels.push({id:l.id,referenceMoves:l.referenceMoves,uiMoves:d.run.actions.length,complete:true});
 if([3,21,46].includes(l.number)){await p.evaluate(()=>window.scrollTo(0,0));await p.waitForTimeout(200);await p.screenshot({path:path.join(root,'release/representative-'+l.number+'-complete-1280.png'),fullPage:false});}
 if(l.number<48)await p.locator('#next-level').click();
}
await p.locator('#win-collection').click();assert.equal(await p.locator('.chapter-cloth.earned').count(),6);assert.equal(await p.locator('.sample-card:not(.locked)').count(),12);await p.evaluate(()=>window.scrollTo(0,0));await p.waitForTimeout(200);await p.screenshot({path:path.join(root,'release/collection-full-1280.png'),fullPage:false});await p.setViewportSize({width:390,height:844});await p.evaluate(()=>window.scrollTo(0,0));await p.waitForTimeout(200);await p.screenshot({path:path.join(root,'release/collection-full-390.png'),fullPage:false});await p.locator('#brand').click();await p.evaluate(()=>window.scrollTo(0,0));await p.waitForTimeout(200);await p.screenshot({path:path.join(root,'release/home-full-390.png'),fullPage:false});
const events=await p.evaluate(()=>window.received);assert.equal(events.length,48);assert.equal(new Set(events).size,48);await p.reload();await p.locator('#continue').waitFor();await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>window.received.length),0);const d=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);assert.equal(d.claims.length,48);assert.equal(Object.keys(d.receipts).length,48);assert.equal(d.outbox.length,0);assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.externalRequests,[]);report.status='PASSED';report.claims=48;report.earnedChapters=6;report.strategyCards=12;report.hostDeliveries=48;report.duplicateDeliveries=0;console.log('48/48 campaign UI solved; 6 chapter cloths and 12 strategy cards; 48 single host deliveries; refresh causes zero re-delivery');
})().catch(e=>{report.status='FAILED';report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(root,'release/campaign-browser-report.json'),JSON.stringify(report,null,2));if(browser)await browser.close();await new Promise(r=>server.close(r));});
