const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),crypto=require('node:crypto');
const root=path.join(__dirname,'..'),repo=path.resolve(root,'../..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'silk-clean-')),game=path.join(temp,'standalone/silk-loop-studio');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const report={status:'RUNNING',sourceCommit:cp.execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),commands:[]};
try{
 const archive=cp.execFileSync('git',['archive','HEAD','standalone/silk-loop-studio'],{cwd:repo,maxBuffer:20*1024*1024});cp.execFileSync('tar',['-x','-C',temp],{input:archive});
 for(const args of [['scripts/assets.cjs'],['scripts/generate.cjs'],['--test','tests/core.test.cjs','tests/storage.test.cjs'],['scripts/build.cjs'],['scripts/audit.cjs'],['scripts/contrast.cjs']]) {const r=cp.spawnSync(process.execPath,args,{cwd:game,encoding:'utf8'});report.commands.push({command:'node '+args.join(' '),exitCode:r.status,output:r.stdout.trim(),error:r.stderr.trim()});if(r.status!==0)throw Error('Clean command failed');}
 for(const target of ['dist/xhs','dist/silk-loop-studio-xhs.zip']){const r=cp.spawnSync('python3',['platform/audit_artifact.py',target],{cwd:game,encoding:'utf8'});report.commands.push({command:'python3 platform/audit_artifact.py '+target,exitCode:r.status,output:r.stdout.trim(),error:r.stderr.trim()});if(r.status!==0)throw Error('Spec audit failed');}
 const files=['assets/atelier.svg','assets/icon.svg','levels.js','dist/silk-loop-studio-xhs.zip'];report.reproduction=files.map(f=>({file:f,originalHash:hash(path.join(root,f)),cleanHash:hash(path.join(game,f)),match:hash(path.join(root,f))===hash(path.join(game,f))}));if(report.reproduction.some(r=>!r.match))throw Error('Reproducibility mismatch');report.status='PASSED';fs.rmSync(temp,{recursive:true,force:true});report.temporaryCheckoutRemoved=true;console.log('Clean archive verification passed; generated levels/artwork and full candidate ZIP byte-identical');
}catch(e){report.status='FAILED';report.failure=String(e.stack);report.recoveryDirectory=temp;console.error(e);process.exitCode=1;}finally{fs.writeFileSync(path.join(root,'release/clean-check.json'),JSON.stringify(report,null,2));}
