// Generated by tools/generate-levels.mjs. Handcrafted tutorial + deterministically curated layouts.
const CAMPAIGN_DATA = [
  {
    "id": "campaign-01",
    "name": "点火",
    "chapter": 0,
    "number": 1,
    "campaignIndex": 0,
    "mode": "campaign",
    "briefing": "向右点火，回收第一枚能源芯。",
    "lesson": "飞船一旦启动就会滑行，直到前方是舱壁。",
    "grid": [
      "######",
      "#@..e#",
      "#....#",
      "#....#",
      "#....#",
      "######"
    ],
    "seed": "handcrafted-1",
    "par": 1,
    "solution": [
      "E"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 1,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 0,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 0,
      "dangerOptions": 0,
      "directionVariety": 1
    }
  },
  {
    "id": "campaign-02",
    "name": "借墙转向",
    "chapter": 0,
    "number": 2,
    "campaignIndex": 1,
    "mode": "campaign",
    "briefing": "先想好停在哪里，再决定下一次点火。",
    "lesson": "舱壁可以当刹车，撞墙不会受损。",
    "grid": [
      "######",
      "#@..e#",
      "#....#",
      "#....#",
      "#...e#",
      "######"
    ],
    "seed": "handcrafted-2",
    "par": 2,
    "solution": [
      "E",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 4,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 0,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 0,
      "dangerOptions": 0,
      "directionVariety": 2
    }
  },
  {
    "id": "campaign-03",
    "name": "斜线航道",
    "chapter": 0,
    "number": 3,
    "campaignIndex": 2,
    "mode": "campaign",
    "briefing": "尝试右下方向，穿过对角线上的能源芯。",
    "lesson": "八个方向都可航行；斜行只检查下一格。",
    "grid": [
      "######",
      "#@...#",
      "#....#",
      "#..e.#",
      "#....#",
      "######"
    ],
    "seed": "handcrafted-3",
    "par": 1,
    "solution": [
      "SE"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 2,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 1,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 0,
      "dangerOptions": 0,
      "directionVariety": 1
    }
  },
  {
    "id": "campaign-04",
    "name": "掠过星光",
    "chapter": 0,
    "number": 4,
    "campaignIndex": 3,
    "mode": "campaign",
    "briefing": "沿整条航段回收能源，留意最终停靠的位置。",
    "lesson": "能源芯不会刹车；同一航段可以连续回收多枚。",
    "grid": [
      "#######",
      "#@e.e.#",
      "#.....#",
      "#.....#",
      "#.....#",
      "#.....#",
      "#######"
    ],
    "seed": "handcrafted-4",
    "par": 1,
    "solution": [
      "E"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 1,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 0,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 0,
      "dangerOptions": 0,
      "directionVariety": 1
    }
  },
  {
    "id": "campaign-05",
    "name": "引力停泊",
    "chapter": 0,
    "number": 5,
    "campaignIndex": 4,
    "mode": "campaign",
    "briefing": "斜向停在中央引力锚，再向上寻找能源。",
    "lesson": "引力锚强制停船，让你能在航区中途改线。",
    "grid": [
      "#######",
      "#.....#",
      "#..e..#",
      "#..o..#",
      "#.....#",
      "#@....#",
      "#######"
    ],
    "seed": "handcrafted-5",
    "par": 2,
    "solution": [
      "NE",
      "N"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 5,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 1,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 1,
      "dangerOptions": 0,
      "directionVariety": 2
    }
  },
  {
    "id": "campaign-06",
    "name": "归航信标",
    "chapter": 0,
    "number": 6,
    "campaignIndex": 5,
    "mode": "campaign",
    "briefing": "原点也是引力锚。把返航作为航线的一部分。",
    "lesson": "离开起点之后，再次进入它会立刻停下。",
    "grid": [
      "#######",
      "#ee...#",
      "#.....#",
      "#..@..#",
      "#..e..#",
      "#.....#",
      "#######"
    ],
    "seed": "handcrafted-6",
    "par": 4,
    "solution": [
      "N",
      "W",
      "SE",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 33,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 1,
      "anchorStops": 1,
      "homeStops": 1,
      "emptyMoves": 2,
      "dangerOptions": 0,
      "directionVariety": 4
    }
  },
  {
    "id": "campaign-07",
    "name": "危险余程",
    "chapter": 0,
    "number": 7,
    "campaignIndex": 6,
    "mode": "campaign",
    "briefing": "能源芯后方仍有失控反应堆，先绕到安全的一侧。",
    "lesson": "收齐后仍须完成本次滑行；途中撞上反应堆仍然失败。",
    "grid": [
      "#######",
      "#@.e.x#",
      "#.....#",
      "#..o..#",
      "#.....#",
      "#.....#",
      "#######"
    ],
    "seed": "handcrafted-7",
    "par": 2,
    "solution": [
      "SE",
      "N"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 3,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 1,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 1,
      "dangerOptions": 2,
      "directionVariety": 2
    }
  },
  {
    "id": "campaign-08",
    "name": "试航毕业",
    "chapter": 0,
    "number": 8,
    "campaignIndex": 7,
    "mode": "campaign",
    "briefing": "把墙面、斜线与引力锚组合成一条完整回收路线。",
    "lesson": "出发前看清整条航段；需要时可无限撤销。",
    "grid": [
      "#######",
      "#e....#",
      "#..xe.#",
      "#..o..#",
      "#.....#",
      "#@..e.#",
      "#######"
    ],
    "seed": "handcrafted-8",
    "par": 4,
    "solution": [
      "E",
      "N",
      "SW",
      "NW"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 53,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 2,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 1,
      "dangerOptions": 1,
      "directionVariety": 4
    }
  },
  {
    "id": "campaign-09",
    "name": "折光门",
    "chapter": 1,
    "seed": "star-drift-campaign-v1-9:0",
    "generatorVersion": 1,
    "grid": [
      "#######",
      "#@....#",
      "#.#e..#",
      "#.e...#",
      "#...#e#",
      "##....#",
      "#######"
    ],
    "briefing": "利用舱壁，把远处的能源串成回收链。",
    "par": 4,
    "solution": [
      "S",
      "NE",
      "E",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 33,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 1,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 2,
      "dangerOptions": 0,
      "directionVariety": 3
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-9",
      "attempt": 0,
      "fallback": false
    },
    "number": 9,
    "campaignIndex": 8,
    "mode": "campaign",
    "lesson": "借墙制动与斜向切入。"
  },
  {
    "id": "campaign-10",
    "name": "边界回声",
    "chapter": 1,
    "seed": "star-drift-campaign-v1-10:0",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#@.e...#",
      "#.....##",
      "#....e##",
      "#..e...#",
      "#...#..#",
      "########"
    ],
    "briefing": "短暂停留也有价值：先规划下一段直线。",
    "par": 4,
    "solution": [
      "E",
      "SW",
      "E",
      "NE"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 32,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 2,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 1,
      "dangerOptions": 0,
      "directionVariety": 3
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-10",
      "attempt": 0,
      "fallback": false
    },
    "number": 10,
    "campaignIndex": 9,
    "mode": "campaign",
    "lesson": "借墙制动与斜向切入。"
  },
  {
    "id": "campaign-11",
    "name": "舷窗之间",
    "chapter": 1,
    "seed": "star-drift-campaign-v1-11:2",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#..#.@##",
      "#....#.#",
      "#.....e#",
      "#...e.e#",
      "#......#",
      "########"
    ],
    "briefing": "平直的边缘中，藏着跨越航区的斜线。",
    "par": 4,
    "solution": [
      "SE",
      "S",
      "N",
      "SW"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 25,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 2,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 2,
      "dangerOptions": 0,
      "directionVariety": 4
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-11",
      "attempt": 2,
      "fallback": false
    },
    "number": 11,
    "campaignIndex": 10,
    "mode": "campaign",
    "lesson": "借墙制动与斜向切入。"
  },
  {
    "id": "campaign-12",
    "name": "切角航线",
    "chapter": 1,
    "seed": "star-drift-campaign-v1-12:7",
    "generatorVersion": 1,
    "grid": [
      "#######",
      "#.e.#@#",
      "#.....#",
      "#e#...#",
      "##....#",
      "#e....#",
      "#######"
    ],
    "briefing": "试着从目标的反方向推算停靠点。",
    "par": 5,
    "solution": [
      "SW",
      "E",
      "NW",
      "E",
      "SW"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 30,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 3,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 2,
      "dangerOptions": 0,
      "directionVariety": 3
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-12",
      "attempt": 7,
      "fallback": false
    },
    "number": 12,
    "campaignIndex": 11,
    "mode": "campaign",
    "lesson": "借墙制动与斜向切入。"
  },
  {
    "id": "campaign-13",
    "name": "双层船坞",
    "chapter": 1,
    "seed": "star-drift-campaign-v1-13:24",
    "generatorVersion": 1,
    "grid": [
      "#######",
      "#..ee.#",
      "#....##",
      "#..#..#",
      "#.....#",
      "#.e.#@#",
      "#######"
    ],
    "briefing": "不要只看最近的能源，留意整条返回路线。",
    "par": 5,
    "solution": [
      "N",
      "SW",
      "W",
      "N",
      "E"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 59,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 1,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 3,
      "dangerOptions": 0,
      "directionVariety": 4
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-13",
      "attempt": 24,
      "fallback": false
    },
    "number": 13,
    "campaignIndex": 12,
    "mode": "campaign",
    "lesson": "借墙制动与斜向切入。"
  },
  {
    "id": "campaign-14",
    "name": "残骸缺口",
    "chapter": 1,
    "seed": "star-drift-campaign-v1-14:3",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#..e...#",
      "##.....#",
      "##.@...#",
      "#.#..e.#",
      "#e.....#",
      "########"
    ],
    "briefing": "缺口能改变停靠位置，也能打开新的航线。",
    "par": 5,
    "solution": [
      "N",
      "SE",
      "W",
      "SE",
      "W"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 83,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 2,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 2,
      "dangerOptions": 0,
      "directionVariety": 3
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-14",
      "attempt": 3,
      "fallback": false
    },
    "number": 14,
    "campaignIndex": 13,
    "mode": "campaign",
    "lesson": "借墙制动与斜向切入。"
  },
  {
    "id": "campaign-15",
    "name": "长距折返",
    "chapter": 1,
    "seed": "star-drift-campaign-v1-15:77",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#e.@...#",
      "##.....#",
      "##e.#.e#",
      "#......#",
      "#......#",
      "########"
    ],
    "briefing": "有些能源需要先飞远，再折返回收。",
    "par": 6,
    "solution": [
      "SW",
      "S",
      "E",
      "N",
      "W",
      "W"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 142,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 1,
      "anchorStops": 1,
      "homeStops": 1,
      "emptyMoves": 3,
      "dangerOptions": 0,
      "directionVariety": 5
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-15",
      "attempt": 77,
      "fallback": false
    },
    "number": 15,
    "campaignIndex": 14,
    "mode": "campaign",
    "lesson": "借墙制动与斜向切入。"
  },
  {
    "id": "campaign-16",
    "name": "几何之眼",
    "chapter": 1,
    "seed": "star-drift-campaign-v1-16:115",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#....e.#",
      "#.....@#",
      "#.e.#..#",
      "##.#...#",
      "#.....e#",
      "########"
    ],
    "briefing": "综合运用八向滑行，完成这个航区的几何考验。",
    "par": 6,
    "solution": [
      "N",
      "W",
      "S",
      "E",
      "SE",
      "E"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 126,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 1,
      "anchorStops": 0,
      "homeStops": 0,
      "emptyMoves": 3,
      "dangerOptions": 0,
      "directionVariety": 5
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-16",
      "attempt": 115,
      "fallback": false
    },
    "number": 16,
    "campaignIndex": 15,
    "mode": "campaign",
    "lesson": "借墙制动与斜向切入。"
  },
  {
    "id": "campaign-17",
    "name": "微引力井",
    "chapter": 2,
    "seed": "star-drift-campaign-v1-17:7",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#.#e...#",
      "#....o.#",
      "#......#",
      "#eo...o#",
      "##.@...#",
      "#..e#.e#",
      "########"
    ],
    "briefing": "引力锚是改变航线的支点。",
    "par": 6,
    "solution": [
      "N",
      "SE",
      "S",
      "NW",
      "S",
      "SE"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 213,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 3,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 2,
      "dangerOptions": 0,
      "directionVariety": 4
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-17",
      "attempt": 7,
      "fallback": false
    },
    "number": 17,
    "campaignIndex": 16,
    "mode": "campaign",
    "lesson": "利用锚点建立中途转向路线。"
  },
  {
    "id": "campaign-18",
    "name": "双锚接力",
    "chapter": 2,
    "seed": "star-drift-campaign-v1-18:0",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#...#...#",
      "#oe.#e..#",
      "#..o....#",
      "#o......#",
      "#.e....##",
      "#.#.e.@.#",
      "#########"
    ],
    "briefing": "借助多个引力锚，连续调整航向。",
    "par": 6,
    "solution": [
      "E",
      "NW",
      "S",
      "NE",
      "S",
      "W"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 265,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 2,
      "anchorStops": 1,
      "homeStops": 1,
      "emptyMoves": 3,
      "dangerOptions": 0,
      "directionVariety": 5
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-18",
      "attempt": 0,
      "fallback": false
    },
    "number": 18,
    "campaignIndex": 17,
    "mode": "campaign",
    "lesson": "利用锚点建立中途转向路线。"
  },
  {
    "id": "campaign-19",
    "name": "停泊顺序",
    "chapter": 2,
    "seed": "star-drift-campaign-v1-19:3",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#.#e..#.#",
      "#.e.#...#",
      "#..o..ee#",
      "#.......#",
      "#..#..o.#",
      "#..@..o.#",
      "#########"
    ],
    "briefing": "同样的停泊点，不同的访问顺序会改变效率。",
    "par": 6,
    "solution": [
      "NE",
      "S",
      "W",
      "NW",
      "N",
      "SW"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 158,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 3,
      "anchorStops": 2,
      "homeStops": 0,
      "emptyMoves": 2,
      "dangerOptions": 0,
      "directionVariety": 6
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-19",
      "attempt": 3,
      "fallback": false
    },
    "number": 19,
    "campaignIndex": 18,
    "mode": "campaign",
    "lesson": "利用锚点建立中途转向路线。"
  },
  {
    "id": "campaign-20",
    "name": "中途改线",
    "chapter": 2,
    "seed": "star-drift-campaign-v1-20:25",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#...e..#",
      "#..e...#",
      "#....e.#",
      "#.#.#o.#",
      "#....oo#",
      "#@.#..e#",
      "########"
    ],
    "briefing": "在航区内部停下来，为下一条斜线找好角度。",
    "par": 7,
    "solution": [
      "NE",
      "W",
      "SE",
      "N",
      "SE",
      "S",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 275,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 3,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 3,
      "dangerOptions": 0,
      "directionVariety": 5
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-20",
      "attempt": 25,
      "fallback": false
    },
    "number": 20,
    "campaignIndex": 19,
    "mode": "campaign",
    "lesson": "利用锚点建立中途转向路线。"
  },
  {
    "id": "campaign-21",
    "name": "环心停靠",
    "chapter": 2,
    "seed": "star-drift-campaign-v1-21:69",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "##...o..#",
      "#...e...#",
      "##@.o..o#",
      "#.......#",
      "##.....e#",
      "#.e..#e.#",
      "#########"
    ],
    "briefing": "先进入中心，再决定如何驶向边缘。",
    "par": 7,
    "solution": [
      "NE",
      "S",
      "NE",
      "S",
      "NE",
      "W",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 267,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 3,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 3,
      "dangerOptions": 0,
      "directionVariety": 3
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-21",
      "attempt": 69,
      "fallback": false
    },
    "number": 21,
    "campaignIndex": 20,
    "mode": "campaign",
    "lesson": "利用锚点建立中途转向路线。"
  },
  {
    "id": "campaign-22",
    "name": "远近之间",
    "chapter": 2,
    "seed": "star-drift-campaign-v1-22:67",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#...#.#.#",
      "#......@#",
      "#oe.....#",
      "#..#..e.#",
      "#o.e....#",
      "#eo..#..#",
      "#########"
    ],
    "briefing": "远处的锚点可能通向最近的能源。",
    "par": 7,
    "solution": [
      "N",
      "SW",
      "N",
      "E",
      "SE",
      "W",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 244,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 2,
      "anchorStops": 2,
      "homeStops": 0,
      "emptyMoves": 3,
      "dangerOptions": 0,
      "directionVariety": 6
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-22",
      "attempt": 67,
      "fallback": false
    },
    "number": 22,
    "campaignIndex": 21,
    "mode": "campaign",
    "lesson": "利用锚点建立中途转向路线。"
  },
  {
    "id": "campaign-23",
    "name": "交叉中继",
    "chapter": 2,
    "seed": "star-drift-campaign-v1-23:1031",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#..e#o.e#",
      "#....o..#",
      "#.e.....#",
      "#.#..e..#",
      "#@......#",
      "#...#o.##",
      "#########"
    ],
    "briefing": "把锚点视作航线网络中的中继。",
    "par": 8,
    "solution": [
      "N",
      "E",
      "SE",
      "N",
      "W",
      "S",
      "S",
      "NW"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 305,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 2,
      "anchorStops": 3,
      "homeStops": 0,
      "emptyMoves": 4,
      "dangerOptions": 0,
      "directionVariety": 6
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-23",
      "attempt": 1031,
      "fallback": false
    },
    "number": 23,
    "campaignIndex": 22,
    "mode": "campaign",
    "lesson": "利用锚点建立中途转向路线。"
  },
  {
    "id": "campaign-24",
    "name": "无声枢纽",
    "chapter": 2,
    "seed": "star-drift-campaign-v1-24:684",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "##......#",
      "#....e.o#",
      "#.......#",
      "#....oo.#",
      "#@#.....#",
      "#e.#e#e.#",
      "#########"
    ],
    "briefing": "选择停靠顺序，将散落能源连接起来。",
    "par": 8,
    "solution": [
      "S",
      "N",
      "N",
      "E",
      "S",
      "W",
      "N",
      "SW"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 293,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 1,
      "anchorStops": 3,
      "homeStops": 1,
      "emptyMoves": 4,
      "dangerOptions": 0,
      "directionVariety": 5
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-24",
      "attempt": 684,
      "fallback": false
    },
    "number": 24,
    "campaignIndex": 23,
    "mode": "campaign",
    "lesson": "利用锚点建立中途转向路线。"
  },
  {
    "id": "campaign-25",
    "name": "红区边缘",
    "chapter": 3,
    "seed": "star-drift-campaign-v1-25:1",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#e..x.o#",
      "#..e#..#",
      "###...##",
      "#e...x.#",
      "#....e@#",
      "#..x..o#",
      "########"
    ],
    "briefing": "每次点火前，沿整条航段查看危险。",
    "par": 8,
    "solution": [
      "SW",
      "NW",
      "N",
      "W",
      "SE",
      "N",
      "W",
      "N"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 122,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 3,
      "anchorStops": 2,
      "homeStops": 1,
      "emptyMoves": 4,
      "dangerOptions": 10,
      "directionVariety": 5
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-25",
      "attempt": 1,
      "fallback": false
    },
    "number": 25,
    "campaignIndex": 24,
    "mode": "campaign",
    "lesson": "检查完整航段，避免收齐后的致命余程。"
  },
  {
    "id": "campaign-26",
    "name": "危险尾迹",
    "chapter": 3,
    "seed": "star-drift-campaign-v1-26:8",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#....o.#",
      "#xe..###",
      "#..e...#",
      "#...e.x#",
      "#..#ox.#",
      "#..#.e@#",
      "########"
    ],
    "briefing": "即使能源就在前方，也要看清它的后方。",
    "par": 7,
    "solution": [
      "W",
      "N",
      "N",
      "E",
      "SW",
      "E",
      "N"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 52,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 1,
      "anchorStops": 2,
      "homeStops": 0,
      "emptyMoves": 3,
      "dangerOptions": 6,
      "directionVariety": 4
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-26",
      "attempt": 8,
      "fallback": false
    },
    "number": 26,
    "campaignIndex": 25,
    "mode": "campaign",
    "lesson": "检查完整航段，避免收齐后的致命余程。"
  },
  {
    "id": "campaign-27",
    "name": "安全着陆",
    "chapter": 3,
    "seed": "star-drift-campaign-v1-27:1",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#e....x#",
      "##e.#@.#",
      "#.#..x.#",
      "#...#.e#",
      "#.....o#",
      "#x.o..e#",
      "########"
    ],
    "briefing": "回收之后仍需安全停靠。",
    "par": 7,
    "solution": [
      "N",
      "W",
      "SE",
      "S",
      "NE",
      "S",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 145,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 2,
      "anchorStops": 2,
      "homeStops": 0,
      "emptyMoves": 3,
      "dangerOptions": 10,
      "directionVariety": 5
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-27",
      "attempt": 1,
      "fallback": false
    },
    "number": 27,
    "campaignIndex": 26,
    "mode": "campaign",
    "lesson": "检查完整航段，避免收齐后的致命余程。"
  },
  {
    "id": "campaign-28",
    "name": "侧翼切入",
    "chapter": 3,
    "seed": "star-drift-campaign-v1-28:4",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#.#e#...#",
      "#.......#",
      "##.x..oe#",
      "#.e...#.#",
      "#x#xo...#",
      "#.....e@#",
      "#########"
    ],
    "briefing": "从侧翼接近，绕开正面的失控反应堆。",
    "par": 8,
    "solution": [
      "N",
      "S",
      "W",
      "E",
      "NW",
      "N",
      "SW",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 276,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 2,
      "anchorStops": 2,
      "homeStops": 2,
      "emptyMoves": 4,
      "dangerOptions": 5,
      "directionVariety": 6
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-28",
      "attempt": 4,
      "fallback": false
    },
    "number": 28,
    "campaignIndex": 27,
    "mode": "campaign",
    "lesson": "检查完整航段，避免收齐后的致命余程。"
  },
  {
    "id": "campaign-29",
    "name": "余程检查",
    "chapter": 3,
    "seed": "star-drift-campaign-v1-29:22",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#...#.e.#",
      "#ex.ox..#",
      "#..e...##",
      "#.#.x..@#",
      "#....#..#",
      "#..#..eo#",
      "#########"
    ],
    "briefing": "收齐能源之后的余程同样重要。",
    "par": 9,
    "solution": [
      "SW",
      "NW",
      "N",
      "E",
      "SE",
      "SW",
      "E",
      "N",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 255,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 4,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 5,
      "dangerOptions": 12,
      "directionVariety": 6
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-29",
      "attempt": 22,
      "fallback": false
    },
    "number": 29,
    "campaignIndex": 28,
    "mode": "campaign",
    "lesson": "检查完整航段，避免收齐后的致命余程。"
  },
  {
    "id": "campaign-30",
    "name": "穿针航道",
    "chapter": 3,
    "seed": "star-drift-campaign-v1-30:27",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#.e.#@x.#",
      "#......o#",
      "##....ex#",
      "#.......#",
      "#...e.#.#",
      "##ox.#e.#",
      "#########"
    ],
    "briefing": "用斜向航路穿越反应堆之间的空隙。",
    "par": 8,
    "solution": [
      "S",
      "SE",
      "NE",
      "NW",
      "W",
      "S",
      "SE",
      "NE"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 199,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 5,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 4,
      "dangerOptions": 6,
      "directionVariety": 5
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-30",
      "attempt": 27,
      "fallback": false
    },
    "number": 30,
    "campaignIndex": 29,
    "mode": "campaign",
    "lesson": "检查完整航段，避免收齐后的致命余程。"
  },
  {
    "id": "campaign-31",
    "name": "窄门之后",
    "chapter": 3,
    "seed": "star-drift-campaign-v1-31:14",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#x..@x#e#",
      "#....x.##",
      "#.eo....#",
      "#.#.o...#",
      "#.#....e#",
      "#.e...#.#",
      "#########"
    ],
    "briefing": "进入狭窄航道之前，先确认出口。",
    "par": 9,
    "solution": [
      "S",
      "NE",
      "SW",
      "N",
      "SW",
      "S",
      "E",
      "NE",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 292,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 4,
      "anchorStops": 3,
      "homeStops": 1,
      "emptyMoves": 5,
      "dangerOptions": 10,
      "directionVariety": 5
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-31",
      "attempt": 14,
      "fallback": false
    },
    "number": 31,
    "campaignIndex": 30,
    "mode": "campaign",
    "lesson": "检查完整航段，避免收齐后的致命余程。"
  },
  {
    "id": "campaign-32",
    "name": "寂静雷区",
    "chapter": 3,
    "seed": "star-drift-campaign-v1-32:25",
    "generatorVersion": 1,
    "grid": [
      "########",
      "#.e....#",
      "#ox#.###",
      "#......#",
      "#..ex..#",
      "#.eo#..#",
      "#..xe.@#",
      "########"
    ],
    "briefing": "保持冷静，把高风险路线拆成安全的短段。",
    "par": 10,
    "solution": [
      "N",
      "SW",
      "E",
      "SW",
      "NE",
      "NW",
      "W",
      "S",
      "SE",
      "SW"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 234,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 6,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 6,
      "dangerOptions": 10,
      "directionVariety": 8
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-32",
      "attempt": 25,
      "fallback": false
    },
    "number": 32,
    "campaignIndex": 31,
    "mode": "campaign",
    "lesson": "检查完整航段，避免收齐后的致命余程。"
  },
  {
    "id": "campaign-33",
    "name": "多点回收",
    "chapter": 4,
    "seed": "star-drift-campaign-v1-33:14",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#e....e.#",
      "##x....##",
      "####@e..#",
      "#..xo..o#",
      "#.e.#.#x#",
      "#.x.....#",
      "#....o.e#",
      "#########"
    ],
    "briefing": "能源更加分散，试着让每次折返都有收获。",
    "par": 9,
    "solution": [
      "N",
      "W",
      "E",
      "SW",
      "SE",
      "W",
      "W",
      "N",
      "SE"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 330,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 3,
      "anchorStops": 2,
      "homeStops": 0,
      "emptyMoves": 4,
      "dangerOptions": 8,
      "directionVariety": 5
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-33",
      "attempt": 14,
      "fallback": false
    },
    "number": 33,
    "campaignIndex": 32,
    "mode": "campaign",
    "lesson": "预先安排能源访问顺序与无收获的定位航段。"
  },
  {
    "id": "campaign-34",
    "name": "逆向思考",
    "chapter": 4,
    "seed": "star-drift-campaign-v1-34:0",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#.e.x.#x#",
      "##...##e#",
      "#.......#",
      "#...o.ee#",
      "#eo..#..#",
      "#.#.x@..#",
      "#..#x..o#",
      "#########"
    ],
    "briefing": "从最后一枚能源倒推你的安全停靠点。",
    "par": 9,
    "solution": [
      "SE",
      "N",
      "NE",
      "S",
      "NW",
      "E",
      "NW",
      "S",
      "W"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 651,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 4,
      "anchorStops": 2,
      "homeStops": 0,
      "emptyMoves": 4,
      "dangerOptions": 9,
      "directionVariety": 7
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-34",
      "attempt": 0,
      "fallback": false
    },
    "number": 34,
    "campaignIndex": 33,
    "mode": "campaign",
    "lesson": "预先安排能源访问顺序与无收获的定位航段。"
  },
  {
    "id": "campaign-35",
    "name": "错层废墟",
    "chapter": 4,
    "seed": "star-drift-campaign-v1-35:4",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#.@.....#",
      "#..#..x##",
      "#.e....##",
      "#.#.#..e#",
      "#o.ox#x.#",
      "##xe.e..#",
      "#.e...o.#",
      "#########"
    ],
    "briefing": "废墟让长直线分成多个层次。",
    "par": 11,
    "solution": [
      "S",
      "E",
      "SE",
      "S",
      "NW",
      "SW",
      "N",
      "S",
      "NW",
      "S",
      "W"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 514,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 4,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 6,
      "dangerOptions": 13,
      "directionVariety": 7
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-35",
      "attempt": 4,
      "fallback": false
    },
    "number": 35,
    "campaignIndex": 34,
    "mode": "campaign",
    "lesson": "预先安排能源访问顺序与无收获的定位航段。"
  },
  {
    "id": "campaign-36",
    "name": "最后一枚",
    "chapter": 4,
    "seed": "star-drift-campaign-v1-36:6",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#..e...##",
      "#x....#@#",
      "#o.xe..##",
      "#....xe##",
      "#...ex..#",
      "##.o##..#",
      "#....o.e#",
      "#########"
    ],
    "briefing": "提前安排最后一枚，避免在末段被迫绕路。",
    "par": 10,
    "solution": [
      "NW",
      "SW",
      "NW",
      "NE",
      "S",
      "W",
      "N",
      "NE",
      "SE",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 190,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 6,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 5,
      "dangerOptions": 12,
      "directionVariety": 7
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-36",
      "attempt": 6,
      "fallback": false
    },
    "number": 36,
    "campaignIndex": 35,
    "mode": "campaign",
    "lesson": "预先安排能源访问顺序与无收获的定位航段。"
  },
  {
    "id": "campaign-37",
    "name": "内环外环",
    "chapter": 4,
    "seed": "star-drift-campaign-v1-37:2",
    "generatorVersion": 1,
    "grid": [
      "##########",
      "#...x...##",
      "#e..#.o..#",
      "##@...#.##",
      "#x.....e##",
      "#........#",
      "#.o..#o.##",
      "#xexee...#",
      "##########"
    ],
    "briefing": "连接内部锚点与外围舱壁。",
    "par": 10,
    "solution": [
      "SE",
      "S",
      "E",
      "NW",
      "SW",
      "SE",
      "SE",
      "SW",
      "NE",
      "E"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 853,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 7,
      "anchorStops": 1,
      "homeStops": 1,
      "emptyMoves": 5,
      "dangerOptions": 11,
      "directionVariety": 6
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-37",
      "attempt": 2,
      "fallback": false
    },
    "number": 37,
    "campaignIndex": 36,
    "mode": "campaign",
    "lesson": "预先安排能源访问顺序与无收获的定位航段。"
  },
  {
    "id": "campaign-38",
    "name": "一线之隔",
    "chapter": 4,
    "seed": "star-drift-campaign-v1-38:9",
    "generatorVersion": 1,
    "grid": [
      "##########",
      "#....x..e#",
      "#..exx..e#",
      "#.###....#",
      "#..o.x#oe#",
      "#o.e...#.#",
      "#..#....##",
      "#...@...##",
      "##########"
    ],
    "briefing": "关键停靠点可能只隔着一格墙。",
    "par": 10,
    "solution": [
      "N",
      "NE",
      "E",
      "S",
      "SW",
      "NW",
      "S",
      "NW",
      "NE",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 366,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 5,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 6,
      "dangerOptions": 7,
      "directionVariety": 6
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-38",
      "attempt": 9,
      "fallback": false
    },
    "number": 38,
    "campaignIndex": 37,
    "mode": "campaign",
    "lesson": "预先安排能源访问顺序与无收获的定位航段。"
  },
  {
    "id": "campaign-39",
    "name": "曲折星桥",
    "chapter": 4,
    "seed": "star-drift-campaign-v1-39:19",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "#..e@.e.#",
      "#...ex#.#",
      "#x....#.#",
      "#..ox.###",
      "#...e#.o#",
      "#.....o##",
      "#ex....##",
      "#########"
    ],
    "briefing": "在多个转向点之间架起回收航线。",
    "par": 12,
    "solution": [
      "E",
      "W",
      "SW",
      "E",
      "N",
      "SE",
      "NW",
      "S",
      "SE",
      "N",
      "W",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 333,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 4,
      "anchorStops": 4,
      "homeStops": 1,
      "emptyMoves": 7,
      "dangerOptions": 17,
      "directionVariety": 7
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-39",
      "attempt": 19,
      "fallback": false
    },
    "number": 39,
    "campaignIndex": 38,
    "mode": "campaign",
    "lesson": "预先安排能源访问顺序与无收获的定位航段。"
  },
  {
    "id": "campaign-40",
    "name": "航线编织",
    "chapter": 4,
    "seed": "star-drift-campaign-v1-40:1",
    "generatorVersion": 1,
    "grid": [
      "#########",
      "##...oe.#",
      "#..e..x.#",
      "###.#@..#",
      "##ex..x##",
      "#....x.##",
      "#..e...o#",
      "#..oe...#",
      "#########"
    ],
    "briefing": "把一路积累的技巧织成完整航图。",
    "par": 11,
    "solution": [
      "N",
      "E",
      "W",
      "W",
      "SE",
      "NE",
      "SE",
      "SW",
      "N",
      "SE",
      "W"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 395,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 5,
      "anchorStops": 3,
      "homeStops": 0,
      "emptyMoves": 6,
      "dangerOptions": 12,
      "directionVariety": 6
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-40",
      "attempt": 1,
      "fallback": false
    },
    "number": 40,
    "campaignIndex": 39,
    "mode": "campaign",
    "lesson": "预先安排能源访问顺序与无收获的定位航段。"
  },
  {
    "id": "campaign-41",
    "name": "深空入口",
    "chapter": 5,
    "seed": "star-drift-campaign-v1-41:1",
    "generatorVersion": 1,
    "grid": [
      "##########",
      "#..#e.o..#",
      "#x.@.o.o##",
      "#e##..#x.#",
      "#.eo#..e.#",
      "#.e....#.#",
      "#x....#.x#",
      "#x#.....##",
      "#....x..e#",
      "##########"
    ],
    "briefing": "星图到这里变得稀疏，耐心读懂每一处停靠点。",
    "par": 12,
    "solution": [
      "NE",
      "SW",
      "NW",
      "S",
      "SW",
      "SE",
      "E",
      "NW",
      "W",
      "NW",
      "E",
      "NE"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 1407,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 8,
      "anchorStops": 1,
      "homeStops": 1,
      "emptyMoves": 6,
      "dangerOptions": 13,
      "directionVariety": 7
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-41",
      "attempt": 1,
      "fallback": false
    },
    "number": 41,
    "campaignIndex": 40,
    "mode": "campaign",
    "lesson": "综合规划墙、锚点、反应堆与多点能源的访问顺序。"
  },
  {
    "id": "campaign-42",
    "name": "失落造船厂",
    "chapter": 5,
    "seed": "star-drift-campaign-v1-42:1",
    "generatorVersion": 1,
    "grid": [
      "##########",
      "#.#@....o#",
      "#e....x.x#",
      "#.eoe...x#",
      "##e#o....#",
      "#.o.xx##.#",
      "##...###e#",
      "#...#....#",
      "#.....xe.#",
      "##########"
    ],
    "briefing": "大型残骸的缺口能成为意外的制动器。",
    "par": 12,
    "solution": [
      "S",
      "SW",
      "NE",
      "W",
      "N",
      "SE",
      "SE",
      "N",
      "SE",
      "S",
      "NW",
      "S"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 1122,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 6,
      "anchorStops": 4,
      "homeStops": 0,
      "emptyMoves": 6,
      "dangerOptions": 11,
      "directionVariety": 7
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-42",
      "attempt": 1,
      "fallback": false
    },
    "number": 42,
    "campaignIndex": 41,
    "mode": "campaign",
    "lesson": "综合规划墙、锚点、反应堆与多点能源的访问顺序。"
  },
  {
    "id": "campaign-43",
    "name": "无光中继",
    "chapter": 5,
    "seed": "star-drift-campaign-v1-43:3",
    "generatorVersion": 1,
    "grid": [
      "##########",
      "###ox.x..#",
      "#...ex..##",
      "#x.x.....#",
      "#.e...##e#",
      "#o....#.x#",
      "###....e.#",
      "#.@.e....#",
      "#..eoo#.##",
      "##########"
    ],
    "briefing": "追踪能源之间的安全交点。",
    "par": 12,
    "solution": [
      "E",
      "NW",
      "SW",
      "NW",
      "E",
      "NW",
      "N",
      "SE",
      "SW",
      "S",
      "E",
      "NE"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 658,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 7,
      "anchorStops": 3,
      "homeStops": 0,
      "emptyMoves": 6,
      "dangerOptions": 19,
      "directionVariety": 7
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-43",
      "attempt": 3,
      "fallback": false
    },
    "number": 43,
    "campaignIndex": 42,
    "mode": "campaign",
    "lesson": "综合规划墙、锚点、反应堆与多点能源的访问顺序。"
  },
  {
    "id": "campaign-44",
    "name": "暗潮航路",
    "chapter": 5,
    "seed": "star-drift-campaign-v1-44:31",
    "generatorVersion": 1,
    "grid": [
      "##########",
      "##....o..#",
      "#@....e.##",
      "#.xoxo#.##",
      "#.x#..oe.#",
      "##e#.#...#",
      "#x.......#",
      "#e.exx...#",
      "##..e#...#",
      "##########"
    ],
    "briefing": "多次空航也许是抵达目标必需的准备。",
    "par": 15,
    "solution": [
      "E",
      "S",
      "NW",
      "SW",
      "SE",
      "N",
      "NW",
      "N",
      "E",
      "S",
      "NW",
      "SW",
      "W",
      "NE",
      "SE"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 729,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 8,
      "anchorStops": 1,
      "homeStops": 1,
      "emptyMoves": 9,
      "dangerOptions": 23,
      "directionVariety": 8
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-44",
      "attempt": 31,
      "fallback": false
    },
    "number": 44,
    "campaignIndex": 43,
    "mode": "campaign",
    "lesson": "综合规划墙、锚点、反应堆与多点能源的访问顺序。"
  },
  {
    "id": "campaign-45",
    "name": "反应堆群",
    "chapter": 5,
    "seed": "star-drift-campaign-v1-45:16",
    "generatorVersion": 1,
    "grid": [
      "##########",
      "#..e...x.#",
      "#.#.....x#",
      "#.e##.#..#",
      "#e.x@ex..#",
      "#o.......#",
      "#.o#....e#",
      "#.o.x.####",
      "#.#x#..oe#",
      "##########"
    ],
    "briefing": "所有能源都在危险航区；每次停靠都要留出后路。",
    "par": 13,
    "solution": [
      "SE",
      "E",
      "W",
      "SE",
      "E",
      "E",
      "W",
      "W",
      "N",
      "SW",
      "NW",
      "S",
      "SW"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 1157,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 5,
      "anchorStops": 2,
      "homeStops": 0,
      "emptyMoves": 8,
      "dangerOptions": 16,
      "directionVariety": 7
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-45",
      "attempt": 16,
      "fallback": false
    },
    "number": 45,
    "campaignIndex": 44,
    "mode": "campaign",
    "lesson": "综合规划墙、锚点、反应堆与多点能源的访问顺序。"
  },
  {
    "id": "campaign-46",
    "name": "破碎星环",
    "chapter": 5,
    "seed": "star-drift-campaign-v1-46:5",
    "generatorVersion": 1,
    "grid": [
      "##########",
      "#xo#....##",
      "#.e..o.#e#",
      "#.#e.xx.o#",
      "##...x#o##",
      "#....x..##",
      "#..e.x...#",
      "##..e#..e#",
      "#.....@..#",
      "##########"
    ],
    "briefing": "在破碎星环中寻找连续的安全航段。",
    "par": 13,
    "solution": [
      "N",
      "SE",
      "W",
      "SW",
      "NW",
      "N",
      "NE",
      "E",
      "SE",
      "SW",
      "NW",
      "S",
      "W"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 1256,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 7,
      "anchorStops": 1,
      "homeStops": 0,
      "emptyMoves": 8,
      "dangerOptions": 11,
      "directionVariety": 8
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-46",
      "attempt": 5,
      "fallback": false
    },
    "number": 46,
    "campaignIndex": 45,
    "mode": "campaign",
    "lesson": "综合规划墙、锚点、反应堆与多点能源的访问顺序。"
  },
  {
    "id": "campaign-47",
    "name": "引力交响",
    "chapter": 5,
    "seed": "star-drift-campaign-v1-47:115",
    "generatorVersion": 1,
    "grid": [
      "##########",
      "#...##o..#",
      "#..e#e.#.#",
      "#o..eo.xe#",
      "#x...x#..#",
      "#..x#..ex#",
      "#x@#..#..#",
      "#..#.#.o.#",
      "#.e......#",
      "##########"
    ],
    "briefing": "协调多个引力锚，让复杂航线形成节奏。",
    "par": 17,
    "solution": [
      "N",
      "SW",
      "E",
      "NW",
      "S",
      "S",
      "E",
      "NW",
      "NE",
      "NW",
      "NE",
      "N",
      "W",
      "S",
      "NW",
      "S",
      "W"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 1287,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 7,
      "anchorStops": 5,
      "homeStops": 1,
      "emptyMoves": 11,
      "dangerOptions": 26,
      "directionVariety": 7
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-47",
      "attempt": 115,
      "fallback": false
    },
    "number": 47,
    "campaignIndex": 46,
    "mode": "campaign",
    "lesson": "综合规划墙、锚点、反应堆与多点能源的访问顺序。"
  },
  {
    "id": "campaign-48",
    "name": "向星海进发",
    "chapter": 5,
    "seed": "star-drift-campaign-v1-48:138",
    "generatorVersion": 1,
    "grid": [
      "###########",
      "##.e..o#x.#",
      "#..o...#..#",
      "#..e#.....#",
      "##....x.xx#",
      "#...o.e..x#",
      "#..e.#e...#",
      "#.##.#....#",
      "#e#o@#..#x#",
      "###########"
    ],
    "briefing": "最后一次远行，把整片航区重新点亮。",
    "par": 15,
    "solution": [
      "N",
      "N",
      "SE",
      "N",
      "E",
      "NW",
      "E",
      "SW",
      "W",
      "SW",
      "W",
      "S",
      "N",
      "NE",
      "W"
    ],
    "proof": {
      "algorithm": "BFS",
      "visited": 2153,
      "shortest": true
    },
    "metrics": {
      "diagonalMoves": 5,
      "anchorStops": 2,
      "homeStops": 0,
      "emptyMoves": 9,
      "dangerOptions": 17,
      "directionVariety": 8
    },
    "generation": {
      "inputSeed": "star-drift-campaign-v1-48",
      "attempt": 138,
      "fallback": false
    },
    "number": 48,
    "campaignIndex": 47,
    "mode": "campaign",
    "lesson": "综合规划墙、锚点、反应堆与多点能源的访问顺序。"
  }
];
// END GENERATED CAMPAIGN
import { createLevel } from './core.mjs';
import { generateProvenLevel, hashSeed } from './generate.mjs';

export const CHAPTERS = Object.freeze([
  { id: 0, name: '蓝港启航', subtitle: '认识惯性', color: '#6ce9f4', description: '8 次短途试航：学会启动、制动、斜行与安全回收。' },
  { id: 1, name: '折光船坞', subtitle: '以墙为舵', color: '#9cc8ff', description: '把舱壁当作航线的一部分，在折角之间找到高效路径。' },
  { id: 2, name: '引力群岛', subtitle: '停靠的艺术', color: '#b5a3ff', description: '一枚锚点，打开新的方向。决定在哪里停，也决定能去哪里。' },
  { id: 3, name: '红移禁区', subtitle: '检查整条航段', color: '#ffac82', description: '失控反应堆封锁直线。每次回收，都要预留安全的余程。' },
  { id: 4, name: '星桥织网', subtitle: '规划回收顺序', color: '#98e8bf', description: '分散的能源、交错的停靠点，等待你连成完整航图。' },
  { id: 5, name: '无垠深空', subtitle: '成为航线设计师', color: '#f0cf8f', description: '更大的航区与更长的回收链，把积累的技巧交给星海。' },
].map(Object.freeze));

export const LEVELS = Object.freeze(CAMPAIGN_DATA.map(raw => createLevel({ ...raw,
  solution: Object.freeze([...raw.solution]), proof: Object.freeze({ ...raw.proof }),
  metrics: Object.freeze({ ...raw.metrics }),
})));
const levelsById = new Map(LEVELS.map(level => [level.id, level]));
const generatedCache = new Map();

export function getLevel(id) {
  if (id && typeof id === 'object') return createLevel(id);
  return levelsById.get(id) ?? generatedCache.get(id) ?? null;
}

function cacheLevel(level) {
  if (generatedCache.size >= 64) generatedCache.delete(generatedCache.keys().next().value);
  generatedCache.set(level.id, level);
  return level;
}

function provenGenerated(seed, chapter, metadata) {
  const existing = generatedCache.get(metadata.id);
  if (existing && existing.generation?.inputSeed === String(seed)) return existing;
  const candidate = generateProvenLevel(seed, chapter, { attempts: 96, maxStates: 18_000 });
  const fallbackPool = LEVELS.filter(level => level.chapter === chapter);
  const fallback = fallbackPool[hashSeed(seed) % fallbackPool.length];
  const source = candidate ?? fallback;
  return cacheLevel(createLevel({ ...source, ...metadata, number: null, campaignIndex: null,
    seed: String(seed), sourceSeed: source.seed, par: source.par,
    solution: Object.freeze([...source.solution]),
    generation: Object.freeze({ ...(source.generation ?? {}), inputSeed: String(seed), fallback: !candidate,
      fallbackLevelId: candidate ? null : source.id }),
  }));
}

/** The caller supplies a local calendar date. No time-zone dependency inside. */
export function createDailyLevel(dateString) {
  if (typeof dateString !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(dateString)) {
    throw new RangeError('Date must use YYYY-MM-DD.');
  }
  const parsed = new Date(`${dateString}T12:00:00Z`);
  if (Number.isNaN(parsed.valueOf()) || parsed.toISOString().slice(0, 10) !== dateString) {
    throw new RangeError('Date must be a real calendar date.');
  }
  const seed = `daily-v1-${dateString}`;
  const chapter = 2 + hashSeed(seed) % 3;
  return provenGenerated(seed, chapter, {
    id: `daily-${dateString}`, name: '今日星图', mode: 'daily', date: dateString,
    difficulty: chapter - 2, chapter, briefing: '同一天，同一张星图。用自己的路线完成这次回收。',
    lesson: '先读图，再点火；比较自己的航线与最短步数。',
  });
}

/** Seeded expedition, with an explicit proven fallback after a bounded search. */
export function createExpeditionLevel(seed, difficulty = 1) {
  if (!['string', 'number'].includes(typeof seed) || String(seed).length < 1 || String(seed).length > 160) {
    throw new RangeError('Expedition seed must be a non-empty string or number up to 160 characters.');
  }
  if (!Number.isInteger(difficulty) || difficulty < 0 || difficulty > 2) {
    throw new RangeError('Difficulty must be 0, 1, or 2.');
  }
  const inputSeed = String(seed);
  const chapter = [1, 3, 5][difficulty];
  const labels = ['轻航', '巡游', '深潜'];
  const level = provenGenerated(`expedition-v1-${difficulty}-${inputSeed}`, chapter, {
    id: `expedition-${difficulty}-${hashSeed(inputSeed).toString(36)}`, name: `${labels[difficulty]}远航`,
    mode: 'expedition', difficulty, chapter,
    briefing: '探索一张经过求解验证的星图；保留种子，下次可以重返这里。',
    lesson: '先寻找关键停靠点，再安排能源访问顺序。',
  });
  // Store the public seed, so reconstruction never needs to know version prefixes.
  const publicLevel = createLevel({ ...level, seed: inputSeed });
  return cacheLevel(publicLevel);
}
