import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import {
  MODULES, SIZE, START_SCRIPT, START_STATE, SUGGESTED_STEPS, TARGET_ORDER, TUTORIAL_AFTER_ACTION,
  TUTORIAL_COMPLETE, TUTORIAL_INITIAL, applyShift, createState, freshState, isComplete,
  isReachableOrder, moduleAt, networkReport, normalizeState, shiftColumn, shiftRow, tutorialCards,
} from "./logic.mjs";

assert.equal(SIZE, 9);
assert.equal(MODULES.length, 9);
assert.equal(isReachableOrder(TARGET_ORDER), true);
assert.equal(isReachableOrder([1, 0, 2, 3, 4, 5, 6, 7, 8]), false, "an odd permutation cannot be created by 3-cell cycles");
assert.equal(normalizeState({ order: TARGET_ORDER, moves: -1 }), null);
assert.equal(normalizeState({ order: [0, 1, 2], moves: 0 }), null);
assert.equal(isComplete(createState(TARGET_ORDER)), true, "victory uses the full Net condition, not a visual target flag");
const targetReport = networkReport(createState(TARGET_ORDER));
assert.equal(targetReport.dangling.length, 0);
assert.equal(targetReport.mismatches.length, 0);
assert.equal(targetReport.connected.length, 9);
assert.equal(targetReport.edgeCount, 8);
assert.equal(targetReport.solved, true);
assert.equal(moduleAt(createState(TARGET_ORDER), 5).ports, "NSW");

const rowShift = shiftRow(createState(TARGET_ORDER), 1, 1);
assert.deepEqual(rowShift.order, [0, 1, 2, 5, 3, 4, 6, 7, 8]);
assert.deepEqual(shiftRow(rowShift, 1, -1).order, TARGET_ORDER, "opposite row shift reverses exactly");
const columnShift = shiftColumn(createState(TARGET_ORDER), 0, 1);
assert.deepEqual(columnShift.order, [6, 1, 2, 0, 4, 5, 3, 7, 8]);
assert.deepEqual(shiftColumn(columnShift, 0, -1).order, TARGET_ORDER, "opposite column shift reverses exactly");
assert.deepEqual(shiftRow(createState(TARGET_ORDER), 5, 1).order, TARGET_ORDER, "invalid commands do not change state");
assert.equal(isComplete(START_STATE), false);
assert.equal(SUGGESTED_STEPS, START_SCRIPT.length);
assert.deepEqual(freshState().order, START_STATE.order);
assert.equal(freshState().moves, 0);

assert.equal(isComplete(TUTORIAL_INITIAL), false);
assert.deepEqual(TUTORIAL_AFTER_ACTION.order, shiftRow(createState(TARGET_ORDER), 1, 1).order, "the action card is generated by the documented actual column inverse");
assert.equal(isComplete(TUTORIAL_AFTER_ACTION), false);
assert.equal(isComplete(TUTORIAL_COMPLETE), true);
assert.deepEqual(TUTORIAL_COMPLETE.order, TARGET_ORDER);
assert.equal(networkReport(TUTORIAL_COMPLETE).edgeCount, SIZE - 1);
assert.equal(applyShift(TUTORIAL_COMPLETE, { axis: "diagonal", index: 0, direction: 1 }), TUTORIAL_COMPLETE);

const cards = tutorialCards();
assert.equal(cards.length, 3);
for (const [index, card] of cards.entries()) {
  assert.match(card.svg, /<svg\b[^>]*viewBox="0 0 540 320"/);
  assert.match(card.svg, /preserveAspectRatio="xMidYMid meet"/);
  assert.match(card.svg, /data-tutorial-game="orbital-formation"/);
  assert.match(card.svg, new RegExp(`data-stage="${["elements", "action", "complete"][index]}"`));
  assert.equal((card.svg.match(/data-formation-cell=/g) ?? []).length, 9, "each card contains every real module");
  assert.doesNotMatch(card.svg, /<image\b|(?:href|xlink:href)=["']https?:\/\//);
}
assert.match(cards[2].svg, /data-order="0,1,2,3,4,5,6,7,8"/);
assert.match(cards[2].svg, /data-edge-count="8"/);
assert.match(cards[1].svg, /data-action-axis="column" data-action-direction="-1"/, "the tutorial arrow metadata agrees with its documented upward move");
assert.match(cards[2].svg, /data-action-axis="row" data-action-direction="-1"/, "the victory card marks the final leftward row cycle");

const [html, app, css] = await Promise.all([
  readFile(new URL("./index.html", import.meta.url), "utf8"),
  readFile(new URL("./app.mjs", import.meta.url), "utf8"),
  readFile(new URL("./styles.css", import.meta.url), "utf8"),
]);
assert.match(html, /<html[^>]+data-realm="orbital-formation"/);
assert.match(html, /href="\.\.\/\.\.\/"/);
assert.match(html, /shared\/game-kit\.css/);
assert.match(html, /shared\/realm-ui\.mjs/);
assert.match(app, /mountPuzzle\(/);
assert.match(css, /min-width:\s*44px/);

console.log("orbital-formation: Netslide row/column cycles, true Net connectivity, tutorial truth chain and mobile controls passed.");
