(function(){
 'use strict';var E=window.TerraceEngine,V=window.TerraceView,S=window.TerraceSession,Storage=window.TerraceStorage,C=window.TerraceLevels,levels=C.levels;
 var data=null,page='home',message='',saveFailed=false,repairNotice=false,modal=null,focusBefore=null,scrollBefore=0,queue=Promise.resolve(),busy=false;
 var app=document.getElementById('app'),overlay=document.getElementById('modal-root'),announce=document.getElementById('announcement');
 function level(){return levels.find(function(l){return l.id===data.current.levelId;});}
 function button(text,action,cls,attrs){return '<button type="button" class="'+(cls||'button')+'" data-action="'+action+'" '+(attrs||'')+'>'+text+'</button>';}
 function heading(kicker,title,desc){return '<div class="page-heading"><span class="eyebrow">'+kicker+'</span><h1>'+title+'</h1>'+(desc?'<p>'+desc+'</p>':'')+'</div>';}
 function completedCount(ch){return levels.filter(function(l){return (!ch||l.chapter===ch)&&data.completed[l.id];}).length;}
 function save(){var snapshot=JSON.parse(JSON.stringify(data));queue=queue.then(async function(){var ok=await Storage.write(snapshot);saveFailed=!ok;var warning=document.getElementById('save-warning');if(warning){warning.hidden=ok;warning.textContent='本局可玩，进度暂无法保存。请保持页面打开。';}return ok;});return queue;}
 async function flushRewards(){if(busy||!window.TerraceHost||typeof window.TerraceHost.claimReward!=='function'||!data.outbox.length)return;busy=true;
   try{if(await save()){var pending=data.outbox.slice();for(var i=0;i<pending.length;i++){var p=pending[i];try{var accepted=await window.TerraceHost.claimReward(p);if(accepted===true || accepted&&accepted.rewardClaimId===p.rewardClaimId){data.outbox=data.outbox.filter(function(x){return x.rewardClaimId!==p.rewardClaimId;});await save();}}catch(e){break;}}}}finally{busy=false;}
 }
 function notify(text){message=text;announce.textContent=text;}
 function render(){if(!data)return;
   var previous=app.contains(document.activeElement)?document.activeElement:null,focusSelector=null;
   if(previous && previous.tagName==='BUTTON'){focusSelector=previous.hasAttribute('data-action')?'[data-action="'+previous.getAttribute('data-action')+'"]':previous.hasAttribute('data-cell')?'button[data-cell="'+previous.getAttribute('data-cell')+'"]':null;
     ['data-id','data-row','data-value','data-cell'].forEach(function(a){if(focusSelector&&previous.hasAttribute(a))focusSelector+='['+a+'="'+previous.getAttribute(a)+'"]';});}
   var nav='<header class="site-header"><button class="brand" data-action="home" aria-label="朱陶阶庭首页"><img src="./assets/icon.svg" alt=""><span>朱陶阶庭</span></button><span class="workshop">陶艺逻辑工坊</span>'+button('玩法','tutorial','small-button')+'</header>';
   var html=nav+'<main id="main"><p id="save-warning" class="warning"'+(!saveFailed?' hidden':'')+'>本局可玩，进度暂无法保存。请保持页面打开。</p>'+(repairNotice?'<p class="warning">当前局存档已修复；已通过复验的完成陶砖保留。损坏的数字不计完成。</p>':'');
   if(page==='home')html+=home();if(page==='chapters')html+=chapters();if(page==='play')html+=play();if(page==='collection')html+=collection();
   html+='</main><footer class="footer">朱陶阶庭 <span>·</span> 慢慢推理，安放一座小院</footer>';app.innerHTML=html;if(focusSelector&&!modal){var restore=app.querySelector(focusSelector);if(restore){try{restore.focus({preventScroll:true});}catch(e){restore.focus();}}}
 }
 function home(){var l=level(),count=completedCount();return '<section class="hero"><div class="hero-copy"><span class="eyebrow">CINNABAR TERRACES / 01</span><h1>让高低有序，<br>让小庭成形。</h1><p class="intro">读懂陶片间的大小刻印，<br>把每一行、每一列安放齐备。</p>'+button((E.evaluate(l,data.current.state.values).complete?'回看':'继续')+'第 '+l.id.slice(3)+' 庭 <span aria-hidden="true">→</span>','continue','button primary')+'<p class="hero-detail">'+l.n+'×'+l.n+' · '+l.title+' · 已安放 '+E.evaluate(l,data.current.state.values).filled+' 格</p></div><div class="hero-scene">'+V.courtyard([1,2,3,4,3,4,1,2,2,1,4,3,4,3,2,1],4)+'<div class="scene-caption"><span>赤土 / 砂岩 / 暮色</span><strong>一块一块，推到答案。</strong></div></div></section><section class="home-bottom"><div class="progress-slab"><span class="eyebrow">工坊手记</span><div class="big-stat">'+count+' <small>/ 60 庭</small></div><div class="progress-line"><i style="width:'+count/60*100+'%"></i></div><p>六段庭院，从四阶走到六阶。<br>提示也能收获陶砖，没有计时压力。</p></div><div class="home-links">'+button('<span class="menu-icon">▦</span><span><b>六章阶庭</b><small>按链型递进，自由选关</small></span><span>→</span>','chapters','menu-link')+button('<span class="menu-icon">◇</span><span><b>陶砖集</b><small>每一枚来自真实完成的小庭</small></span><span>→</span>','collection','menu-link')+button('<span class="menu-icon">◷</span><span><b>今日复习</b><small>固定 60 题，按上海日期轮换</small></span><span>→</span>','daily','menu-link')+'</div></section>';}
 function chapters(){return heading('六段庭院 / CAMPAIGN','选一块陶板，开始推理','每章十庭；全部开放，随时回看已完成的庭院。')+'<div class="chapter-list">'+C.chapters.map(function(ch){var list=levels.filter(function(l){return l.chapter===ch.id;}),count=completedCount(ch.id);return '<section class="chapter-card"><div class="chapter-title"><div class="chapter-seal">'+ch.id+'</div><div><span class="eyebrow">'+list[0].n+'阶 · '+count+' / 10 完成</span><h2>'+ch.title+'</h2><p>'+ch.description+'</p></div></div><div class="level-grid">'+list.map(function(l){return button('<b>'+l.id.slice(3)+'</b><span>'+l.title+'</span><small>'+(data.completed[l.id]?'✓ 已成庭':l.id===data.current.levelId?'正在雕庭':'未完成')+'</small>','level','level-button'+(data.completed[l.id]?' done':''),'data-id="'+l.id+'"');}).join('')+'</div></section>';}).join('')+'</div>';}
 function play(){var l=level(),c=data.current,s=c.state,n=l.n,status=E.evaluate(l,s.values),row=Math.floor(c.selected/n),col=c.selected%n;
   var stateText=status.complete?'✓ 行、列、刻印全部成立':status.errors.length?status.errors[0].text:message||'每行每列各含 1–'+n+'；只有显示的刻印需要比较。';
   var board='<section class="board-slab"><div class="board-top"><span>'+n+'阶 · '+l.relations.length+'道刻印</span><span>'+status.filled+' / '+n*n+' 格</span></div>'+V.board(l,s,c.selected,true)+'<div class="board-bottom"><span>尖端朝小 <b>&lt; &gt; ∧ ∨</b></span>'+button('读刻印','relations','small-button')+'</div><p class="board-caption">选格只选位置；数字从右侧或下方数字盘输入。</p></section>';
   var focus=n>=5?'<div class="focus-panel"><h3>① 选行</h3><div class="row-keys">'+Array.from({length:n},function(_,r){return button(String(r+1),'row','row-key'+(row===r?' active':''),'data-row="'+r+'" aria-label="选择第'+(r+1)+'行" aria-pressed="'+(row===r)+'"');}).join('')+'</div><h3>② 选第 '+(row+1)+' 行的格子</h3><div class="cell-keys">'+Array.from({length:n},function(_,j){var cell=row*n+j;return button('<small>'+E.position(cell,n)+'</small><b>'+(s.values[cell]||'空')+'</b>','cell','cell-key'+(cell===c.selected?' active':''),'data-cell="'+cell+'" aria-label="选择'+E.position(cell,n)+'" aria-pressed="'+(cell===c.selected)+'"');}).join('')+'</div></div>':'';
   var controls='<aside class="input-slab">'+focus+'<div class="selected-label"><span>'+(n>=5?'③ ':'')+E.position(c.selected,n)+'</span><strong>'+ (c.mode==='note'?'笔记模式':'填写模式')+'</strong></div><div class="digit-keys">'+Array.from({length:n},function(_,i){return button(String(i+1),'digit','digit-key','data-value="'+(i+1)+'" aria-label="'+(c.mode==='note'?'标记候选':'填入')+(i+1)+'"');}).join('')+'</div><div class="tools">'+button(c.mode==='note'?'切换到填写':'切换到笔记','mode','tool-button','aria-pressed="'+(c.mode==='note')+'"')+button('擦除','erase','tool-button')+button('撤销','undo','tool-button',s.history.length?'':'disabled')+button('提示','hint','tool-button')+'</div><div class="status '+(status.errors.length?'conflict':'')+'" role="status">'+V.escape(stateText)+'</div><div class="secondary-tools">'+button('自动候选','candidates','text-button')+button('重开本庭','restart','text-button')+button('选关','chapters','text-button')+'</div><p class="keyboard-note">键盘：方向键选格 · 数字填写 · N 切模式 · Ctrl/⌘ Z 撤销。候选不计完成。</p>'+(status.complete?button('查看成庭','result','button primary'):'')+'</aside>';
   return '<div class="play-heading"><div><span class="eyebrow">第 '+l.id.slice(3)+' 庭 / '+C.chapters[l.chapter-1].title+'</span><h1>'+l.title+'</h1></div>'+button('回工坊','home','small-button')+'</div><div class="game-layout">'+board+controls+'</div>';
 }
 function collection(){return heading('陶砖集 / YOUR WORK','把学到的刻印，留在庭中','每完成一庭添一枚陶砖。提示不扣奖励；完整解法演示只算练习。')+'<div class="collection-grid">'+C.chapters.map(function(ch){var count=completedCount(ch.id),ids=levels.filter(function(l){return l.chapter===ch.id;});return '<section class="collection-card"><div class="ceramic-badge badge-'+ch.id+'"><span>'+['Ⅰ','Ⅱ','Ⅲ','Ⅳ','Ⅴ','Ⅵ'][ch.id-1]+'</span></div><h2>'+ch.title+'</h2><p>'+ch.description+'</p><div class="brick-strip">'+ids.map(function(l){return '<span class="brick'+(data.completed[l.id]?' earned':'')+'" title="第'+l.id.slice(3)+'庭'+(data.completed[l.id]?'已获得':'未获得')+'">'+(data.completed[l.id]?'✓':'·')+'</span>';}).join('')+'</div><p><b>'+count+' / 10</b> 枚陶砖'+(count===10?' · 章庭已修成':'')+'</p>'+button('回看这一章','chapter-detail','text-button','data-chapter="'+ch.id+'"')+'</section>';}).join('')+'</div>';}
 function openModal(kind,body,title){if(!modal){focusBefore=document.activeElement;scrollBefore=window.pageYOffset;document.body.style.top=-scrollBefore+'px';document.body.classList.add('modal-open');app.setAttribute('aria-hidden','true');}
   modal={kind:kind};overlay.innerHTML='<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-header"><h2 id="modal-title">'+title+'</h2>'+button('关闭','close','small-button','aria-label="关闭'+title+'"')+'</div><div class="modal-scroll">'+body+'</div></section></div>';
   overlay.querySelector('.modal-scroll').scrollTop=0;overlay.querySelector('button').focus();
 }
 function closeModal(){var oldKind=modal&&modal.kind;modal=null;overlay.innerHTML='';app.removeAttribute('aria-hidden');document.body.classList.remove('modal-open');document.body.style.top='';window.scrollTo(0,scrollBefore);if(focusBefore&&document.contains(focusBefore))focusBefore.focus();else{var fallback=app.querySelector('[data-action="'+(oldKind==='hint'?'hint':oldKind==='result'?'result':'tutorial')+'"]');if(fallback)fallback.focus();}}
 function tutorial(index,n){n=n||level().n;var l=levels.find(function(x){return x.n===n;}),initial=E.blank(n),h=E.nextHint(l,initial.values),action=E.apply(initial,n,h.cell,h.value,'fill'),solved=E.blank(n);solved.values=l.solution.slice();var states=[initial,action,solved],titles=['读懂平面阶庭','选格，再安放数字','三项全对，才算成庭'];
   var descriptions=['每行、每列含 1–'+n+' 各一次。没有数独宫，也不要求对角不同。<、> 与 ∧、∨ 的尖端都朝较小的数字。缺符号的相邻格没有额外限制。','同一题的真实操作：选中 '+E.position(h.cell,n)+'，在填写模式按 '+h.value+'。这是一次合法安放。笔记模式只标候选，不算填数；空格不是数字 0 的台阶。','同一题的完整真实数盘。'+n+' 行与 '+n+' 列各含 1–'+n+'，'+l.relations.length+' 道显示关系全部成立。大小关系只要求严格大小，并不总是相差 1。'];
   var text='<div class="tutorial-tabs">'+[4,5,6].map(function(size){return button(size+'阶','tutorial-size','small-button'+(size===n?' active':''),'data-n="'+size+'"');}).join('')+'</div><span class="eyebrow">'+(index+1)+' / 3 · '+l.id+' · 同题真实状态</span><h3>'+titles[index]+'</h3><div class="tutorial-art">'+V.svg(l,states[index],['initial','action','complete'][index],index===1?h.cell:-1)+'</div><p>'+descriptions[index]+'</p>'+(index===1?'<p class="reason">这一步的依据：'+V.escape(h.reason)+'。'+button('展开推理链','tutorial-proof','text-button','data-n="'+n+'"')+'</p>':'')+'<p class="tutorial-extra">上下刻印：上格 &lt; 下格画 ∧；上格 &gt; 下格画 ∨。只读刻印可在「读刻印」大按钮里逐条查看。5/6阶先选行，再用大格键选位置，最后从数字盘填写。</p><div class="modal-actions">'+button(index?'上一张':'跳过','tutorial-prev','button','data-index="'+index+'" data-n="'+n+'"')+button(index===2?'看完，去雕庭':'下一张','tutorial-next','button primary','data-index="'+index+'" data-n="'+n+'"')+'</div>';
   openModal('tutorial',text,'玩法 · '+n+'阶');modal.index=index;modal.n=n;
 }
 function hint(tier,h){var l=level();h=h||E.nextHint(l,data.current.state.values);if(h.error){openModal('hint','<p class="warning">'+V.escape(h.error)+'</p>'+button('回去检查','close','button primary'),'先检查数字');return;}
   var body='<span class="eyebrow">'+tier+' / 3 · 只用规则推理</span><h3>'+E.position(h.cell,l.n)+'</h3>';
   if(tier===1)body+='<p>先看这一格与相邻刻印、同行同列。高低链限制上下界，行列排除已经确定的数字。</p>';
   if(tier>=2)body+='<p>下面按发生顺序列出候选删除。每步都给出依据，可用笔记复现。</p><ol class="proof-list">'+h.trace.map(function(t){return '<li><b>'+E.position(t.cell,l.n)+'</b><br>'+V.escape(t.reason)+'<br><small>'+t.before.join('、')+' → '+(t.after.join('、')||'空')+'</small></li>';}).join('')+'</ol>';
   if(tier===3)body+='<p class="reason">所以 '+E.position(h.cell,l.n)+' 只能填 <b>'+h.value+'</b>。提示可获陶砖，完整演示属于练习。</p>';
   body+='<div class="modal-actions">'+button('自己试试','close','button')+button(tier<3?'再具体一点':'填入这一步',tier<3?'hint-more':'hint-apply','button primary')+'</div>'+button('完整推理演示（练习）','solution-confirm','text-button');openModal('hint',body,'推理提示');modal.tier=tier;modal.hint=h;
 }
 function relations(){var l=level();openModal('relations','<p>尖端朝小，开口朝大。以下每条按钮显示真实端点，点击后定位两格；刻印不能修改。</p><div class="relation-list">'+l.relations.map(function(e,i){return button('<b>'+V.escape(E.glyph(e,l.n))+'</b> '+E.position(e.a,l.n)+' '+(e.sign==='<'?'小于':'大于')+' '+E.position(e.b,l.n),'relation-locate','relation-button','data-relation="'+i+'"');}).join('')+'</div>','读刻印');}
 function result(){var l=level(),c=data.current,status=E.evaluate(l,c.state.values);if(!status.complete)return;var first=data.completed[l.id],body='<span class="eyebrow">'+(c.practice?'练习完成':first&&first.runId===c.runId?'已收下一枚陶砖':'再次成庭 · 陶砖已收藏')+'</span><h3>这一庭，高低有序。</h3><div class="result-landscape">'+V.courtyard(c.state.values,l.n)+'</div><p>'+l.n+' 行、'+l.n+' 列与 '+l.relations.length+' 道刻印全部成立。'+(c.practice?'演示不发首通奖励。':'本庭陶砖只收藏一次。')+'</p><div class="result-board">'+V.board(l,c.state,-1,false)+'</div><div class="modal-actions">'+button('回看数盘','close','button')+button(l.id==='ct-60'?'回工坊':'下一庭','next-level','button primary')+'</div>'+button('回看完整推理','review-proof','text-button')+' · '+button('去陶砖集','collection-modal','text-button');openModal('result',body,'成庭 · '+l.title);}
 async function commit(){var l=level(),run=data.current.runId,complete=E.evaluate(l,data.current.state.values).complete;if(complete)S.settle(data,l);render();await save();if(complete && data.current.runId===run && page==='play' && !modal){result();flushRewards();}}
 function enter(l){if(data.current.levelId!==l.id)data.current=S.newRun(l);page='play';message='';render();save();window.scrollTo(0,0);}
 function start(l){if(data.current.levelId!==l.id&&data.current.state.values.some(Boolean)&&!E.evaluate(level(),data.current.state.values).complete){openModal('switch','<p>切换到「'+l.title+'」会替换当前未完成数盘。已收藏的陶砖会保留。</p><div class="modal-actions">'+button('继续当前庭','close','button')+button('切换庭院','switch-confirm','button primary','data-id="'+l.id+'"')+'</div>','切换庭院');}else enter(l);}
 async function onAction(target){var action=target.getAttribute('data-action'),l=level(),c=data.current;
   if(action==='home'||action==='chapters'||action==='collection'){page=action;message='';render();save();window.scrollTo(0,0);return;}
   if(action==='continue'){enter(l);if(data.tutorial<1)tutorial(0,l.n);return;}
   if(action==='level'){start(levels.find(function(x){return x.id===target.getAttribute('data-id');}));return;}
   if(action==='chapter-detail'){page='chapters';render();var idx=Number(target.getAttribute('data-chapter'))-1;app.querySelectorAll('.chapter-card')[idx].scrollIntoView();return;}
   if(action==='daily'){var d=new Date(Date.now()+8*3600000),days=Math.floor(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())/86400000),idx=((days-20718)%60+60)%60;start(levels[idx]);return;}
   if(action==='tutorial'){tutorial(0,l.n);return;}
   if(action==='close'){if(modal&&modal.kind==='tutorial'){data.tutorial=1;save();}closeModal();return;}
   if(action==='tutorial-size'){tutorial(0,Number(target.getAttribute('data-n')));return;}
   if(action==='tutorial-next'||action==='tutorial-prev'){var i=Number(target.getAttribute('data-index')),n=Number(target.getAttribute('data-n'));if(action==='tutorial-next'&&i<2)tutorial(i+1,n);else if(action==='tutorial-prev'&&i>0)tutorial(i-1,n);else{data.tutorial=1;save();closeModal();}return;}
   if(action==='tutorial-proof'){var n=Number(target.getAttribute('data-n')),tl=levels.find(function(x){return x.n===n;}),h=E.nextHint(tl,E.blank(n).values);openModal('tutorial-proof','<ol class="proof-list">'+h.trace.map(function(t){return '<li>'+E.position(t.cell,n)+'：'+V.escape(t.reason)+' → '+t.after.join('、')+'</li>';}).join('')+'</ol>'+button('返回操作卡','tutorial-proof-back','button primary','data-n="'+n+'"'),'教程操作依据');return;}
   if(action==='tutorial-proof-back'){tutorial(1,Number(target.getAttribute('data-n')));return;}
   if(action==='switch-confirm'){closeModal();enter(levels.find(function(x){return x.id===target.getAttribute('data-id');}));return;}
   if(action==='cell'||target.tagName==='BUTTON'&&target.hasAttribute('data-cell')&&!action){c.selected=Number(target.getAttribute('data-cell'));notify('已选 '+E.position(c.selected,l.n)+'，从数字盘'+(c.mode==='note'?'标候选。':'填入数字。'));render();save();return;}
   if(action==='row'){c.selected=Number(target.getAttribute('data-row'))*l.n+c.selected%l.n;render();save();return;}
   if(action==='mode'){c.mode=c.mode==='fill'?'note':'fill';render();save();return;}
   if(action==='digit'||action==='erase'){var next=E.apply(c.state,l.n,c.selected,action==='erase'?0:Number(target.getAttribute('data-value')),c.mode);if(next===c.state){notify(c.mode==='note'&&c.state.values[c.selected]?'先擦除正式数字，再标候选。':'这一格没有变化。');render();return;}c.state=next;message='';await commit();return;}
   if(action==='undo'){c.state=E.undo(c.state);message='已撤销；收藏台账保留。';render();save();return;}
   if(action==='candidates'){var next=E.snapshot(c.state);next.notes=next.values.map(function(v,cell){return v?[]:E.candidates(l,next.values,cell);});next.history=c.state.history.concat([E.snapshot(c.state)]).slice(-160);c.state=next;notify('自动候选只按当前已填数字、同行同列和相邻刻印排除，不代替完整推理。');render();save();return;}
   if(action==='restart'){openModal('restart','<p>擦去当前数字、笔记与提示记录，从空盘重新开始。本庭已收藏的陶砖会保留。</p><div class="modal-actions">'+button('保留数盘','close','button')+button('重开','restart-confirm','button primary')+'</div>','重开本庭');return;}
   if(action==='restart-confirm'){closeModal();data.current=S.newRun(l);message='';render();save();return;}
   if(action==='hint'){c.hints++;save();hint(1);return;}
   if(action==='hint-more'){hint(modal.tier+1,modal.hint);return;}
   if(action==='hint-apply'){var h=modal.hint;closeModal();c.selected=h.cell;c.state=E.apply(c.state,l.n,h.cell,h.value,'fill');message='已按推理填写 '+E.position(h.cell,l.n)+' = '+h.value;await commit();return;}
   if(action==='solution-confirm'){openModal('solution-confirm','<p>将展示本题的真实完整数盘与推理链，并把当前局标为练习。练习不发本庭首通陶砖；重开后可重新正式解题。</p><div class="modal-actions">'+button('继续自己推理','close','button')+button('看演示','solution','button primary')+'</div>','完整解法 · 练习');return;}
   if(action==='solution'){closeModal();var proof=E.deduce(l,E.blank(l.n).values);c.practice=true;c.state=E.blank(l.n);c.state.values=proof.domains.map(function(a){return a[0];});await commit();return;}
   if(action==='relations'){relations();return;}
   if(action==='relation-locate'){var edge=l.relations[Number(target.getAttribute('data-relation'))];closeModal();c.selected=edge.a;notify(E.position(edge.a,l.n)+(edge.sign==='<'?'小于':'大于')+E.position(edge.b,l.n)+'。尖端朝较小值。');render();save();return;}
   if(action==='result'){result();return;}
   if(action==='review-proof'){var p=E.deduce(l,E.blank(l.n).values);openModal('proof','<p>从本庭空盘出发，按顺序删去候选。以下每步依据只来自行列与显示刻印。</p><ol class="proof-list">'+p.trace.map(function(t){return '<li><b>'+E.position(t.cell,l.n)+'</b><br>'+V.escape(t.reason)+'<br>'+t.before.join('、')+' → '+t.after.join('、')+'</li>';}).join('')+'</ol>'+button('回看成庭','result','button primary'),'完整推理手记');return;}
   if(action==='next-level'){closeModal();var index=levels.indexOf(l);if(index===59){page='home';render();}else enter(levels[index+1]);return;}
   if(action==='collection-modal'){closeModal();page='collection';render();window.scrollTo(0,0);return;}
 }
 document.addEventListener('click',function(e){var target=e.target.closest('[data-action],[data-cell],[data-relation]');if(!target||!data||target.disabled)return;
   if(target.hasAttribute('data-relation')&&!target.hasAttribute('data-action')){var edge=level().relations[Number(target.getAttribute('data-relation'))];notify(E.position(edge.a,level().n)+(edge.sign==='<'?'小于':'大于')+E.position(edge.b,level().n)+'。可用「读刻印」大按钮精确查看。');render();return;}
   if(modal && !overlay.contains(target))return;
   onAction(target).catch(function(){saveFailed=true;notify('本局可玩，进度暂无法保存。');render();});
 });
 document.addEventListener('keydown',function(e){if(!data)return;if(modal){if(e.key==='Escape'){e.preventDefault();if(modal.kind==='tutorial'){data.tutorial=1;save();}closeModal();}if(e.key==='Tab'){var buttons=Array.from(overlay.querySelectorAll('button:not([disabled])'));var i=buttons.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();buttons[buttons.length-1].focus();}else if(!e.shiftKey&&i===buttons.length-1){e.preventDefault();buttons[0].focus();}}return;}
   if(page!=='play'||e.altKey)return;var n=level().n,c=data.current,dir={ArrowLeft:-1,ArrowRight:1,ArrowUp:-n,ArrowDown:n}[e.key];
   if(dir){e.preventDefault();c.selected=(c.selected+dir+n*n)%(n*n);render();save();return;}
   var action=null;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z')action='undo';else if(!e.ctrlKey&&!e.metaKey){if(/^[1-6]$/.test(e.key)&&Number(e.key)<=n)action='digit';if(e.key==='Backspace'||e.key==='Delete')action='erase';if(e.key.toLowerCase()==='n')action='mode';}
   if(action){e.preventDefault();var t=document.createElement('button');t.setAttribute('data-action',action);t.setAttribute('data-value',e.key);onAction(t);}
 });
 document.addEventListener('visibilitychange',function(){if(data){save();if(!document.hidden)flushRewards();}});
 window.addEventListener('pagehide',function(){if(data)save();});
 async function init(){await Storage.init();var raw=await Storage.read(),restored=S.restore(raw.value,levels);data=restored.data;saveFailed=!raw.ok;repairNotice=restored.repaired;if(restored.repaired)notify('本游戏存档已修复：完成台账复验保留，损坏的当前局回到空盘。');S.settle(data,level());render();if(!saveFailed)await save();if(data.tutorial<1){page='play';render();tutorial(0,level().n);}flushRewards();}
 init();
})();
