import { copyFile, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Script } from "node:vm";

const root = fileURLToPath(new URL(".", import.meta.url));
const dist = resolve(root, "dist/xhs");
const zipFile = resolve(root, "dist/firefly-nocturne-offline.zip");
const marker = resolve(dist, ".generated-by-firefly-build");
const moduleOrder = ["logic.mjs", "solver.mjs", "levels.mjs", "app.mjs"];
const assets = ["garden-cover.svg", "firefly-icon.svg",
  ...Array.from({ length: 6 }, (_, i) => `chapter-${i + 1}.svg`),
  ...Array.from({ length: 6 }, (_, i) => `plant-${i + 1}.svg`)];

async function bundleModules() {
  const sources = [];
  for (const name of moduleOrder) {
    let source = await readFile(resolve(root, name), "utf8");
    source = source.replace(/^import\s*(?:\{[\s\S]*?\}|[^;]+?)\s*from\s*["']\.\/[\w.-]+\.mjs["'];\s*/gm, "");
    if (/^import\s/m.test(source)) throw new Error(`Unhandled import in ${name}`);
    source = source.replace(/^export\s+(?=(?:const|function)\b)/gm, "");
    if (/^export\s/m.test(source)) throw new Error(`Unhandled export in ${name}`);
    sources.push(`// ${name}\n${source}`);
  }
  const noticePattern = /source\.innerHTML = '规则参考 [^']*';/;
  if (!noticePattern.test(sources[sources.length - 1])) throw new Error("Cannot locate the web-only source links.");
  sources[sources.length - 1] = sources[sources.length - 1].replace(noticePattern,
    'source.textContent = "规则参考 Simon Tatham’s Portable Puzzle Collection 与 ebnbin/puzzles（MIT License）。本作保留规则语义，题面、界面与素材为独立制作。";');
  const license = await readFile(resolve(root, "LICENSE"), "utf8");
  const bundle = `/*\n${license}\n*/\n"use strict";\n(() => {\n${sources.join("\n\n")}\n})();\n`;
  new Script(bundle, { filename: "app.js" });
  if (/\b(?:fetch|XMLHttpRequest|WebSocket|Worker|ServiceWorker|eval|Function)\s*\(/.test(bundle)) {
    throw new Error("Offline bundle contains a restricted network or dynamic-code call.");
  }
  return bundle;
}

async function build() {
  try {
    const existing = await stat(dist);
    if (existing.isDirectory()) {
      await stat(marker).catch(() => { throw new Error("Refusing to replace an unmarked output directory."); });
      await rm(dist, { recursive: true });
    }
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  await mkdir(resolve(dist, "assets"), { recursive: true });
  await writeFile(marker, "Generated by build-offline.mjs. This directory may be replaced by the same script.\n");
  const html = await readFile(resolve(root, "index.html"), "utf8");
  const moduleTag = '<script type="module" src="./app.mjs"></script>';
  if (!html.includes(moduleTag)) throw new Error("Cannot locate the module entry in index.html.");
  await writeFile(resolve(dist, "index.html"), html.replace(moduleTag, '<script defer src="./app.js"></script>'));
  await writeFile(resolve(dist, "app.js"), await bundleModules());
  for (const name of ["styles.css"]) {
    await copyFile(resolve(root, name), resolve(dist, name));
  }
  for (const name of assets) await copyFile(resolve(root, "assets", name), resolve(dist, "assets", name));
  const files = await readdir(dist);
  if (!files.includes("index.html") || !files.includes("app.js") || files.includes("app.mjs")) {
    throw new Error("Offline output structure is invalid.");
  }
  await mkdir(resolve(root, "dist"), { recursive: true });
  await rm(zipFile, { force: true });
  const result = spawnSync("zip", ["-X", "-q", "-r", zipFile,
    "index.html", "app.js", "styles.css", "assets"],
  { cwd: dist, encoding: "utf8" });
  if (result.status !== 0) throw new Error(result.stderr || "zip failed");
  const size = (await stat(zipFile)).size;
  if (size >= 10 * 1024 * 1024) throw new Error("Offline package exceeds 10 MiB.");
  process.stdout.write(`Built ${zipFile} (${size} bytes).\n`);
}

build().catch((error) => { console.error(error); process.exitCode = 1; });
