// Generated by generate-campaign.mjs (garden-gen-1).
import { createPuzzle } from "./logic.mjs";

export const CHAPTERS = Object.freeze([
  {
    "id": "gate",
    "title": "门前一盏",
    "subtitle": "看见光穿过花径"
  },
  {
    "id": "zero",
    "title": "零灯石庭",
    "subtitle": "听懂石上的数字"
  },
  {
    "id": "corridor",
    "title": "花墙夹径",
    "subtitle": "循着唯一的光源"
  },
  {
    "id": "bamboo",
    "title": "竹影相借",
    "subtitle": "让两处线索彼此照应"
  },
  {
    "id": "water",
    "title": "水榭回光",
    "subtitle": "追踪穿庭而过的光路"
  },
  {
    "id": "stars",
    "title": "满庭星火",
    "subtitle": "收拢稀疏的星点"
  }
].map((chapter) => Object.freeze(chapter)));

export const LEVELS = Object.freeze([
  {
    "id": "firefly-01-01",
    "title": "门阶小夜灯",
    "chapterId": "gate",
    "rows": [
      "1...",
      "1.##",
      "..#.",
      "..##"
    ],
    "solution": [
      "0:1",
      "2:0",
      "2:3"
    ],
    "seed": 272488,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-01-02",
    "title": "苔砖初亮",
    "chapterId": "gate",
    "rows": [
      "#0#..",
      "..##.",
      ".1...",
      ".....",
      "..10."
    ],
    "solution": [
      "0:3",
      "1:0",
      "2:2",
      "3:4",
      "4:1"
    ],
    "seed": 131084,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-01-03",
    "title": "花径留光",
    "chapterId": "gate",
    "rows": [
      ".2.1.",
      ".#...",
      "###..",
      "1##.0",
      "..#.."
    ],
    "solution": [
      "0:0",
      "0:2",
      "1:4",
      "4:0",
      "4:3"
    ],
    "seed": 139275,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-01-04",
    "title": "檐下微萤",
    "chapterId": "gate",
    "rows": [
      ".#..#",
      "###..",
      "0...#",
      "##01.",
      "....."
    ],
    "solution": [
      "0:0",
      "0:2",
      "1:4",
      "2:3",
      "4:4"
    ],
    "seed": 177385,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-01-05",
    "title": "双墙之间",
    "chapterId": "gate",
    "rows": [
      "0..0#",
      "....#",
      "....#",
      "#.#..",
      "..1.0"
    ],
    "solution": [
      "1:2",
      "2:0",
      "3:3",
      "4:1"
    ],
    "seed": 165630,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-01-06",
    "title": "曲角灯语",
    "chapterId": "gate",
    "rows": [
      "##..1",
      "1..#.",
      "01...",
      ".....",
      "##.0."
    ],
    "solution": [
      "0:3",
      "1:1",
      "2:4",
      "3:2"
    ],
    "seed": 163848,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-01-07",
    "title": "露台斜影",
    "chapterId": "gate",
    "rows": [
      ".#.1.",
      "...0#",
      "#0.#.",
      ".....",
      "..1.."
    ],
    "solution": [
      "0:4",
      "1:0",
      "3:2",
      "4:0",
      "4:4"
    ],
    "seed": 172039,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-01-08",
    "title": "园门四望",
    "chapterId": "gate",
    "rows": [
      "...2.",
      "....1",
      "..#..",
      "0....",
      "...0."
    ],
    "solution": [
      "0:2",
      "0:4",
      "1:0",
      "2:3",
      "3:4",
      "4:1"
    ],
    "seed": 190203,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-01-09",
    "title": "石径错落",
    "chapterId": "gate",
    "rows": [
      ".#.#.",
      ".0#..",
      "...1.",
      "#....",
      ".2.1."
    ],
    "solution": [
      "0:2",
      "1:3",
      "2:0",
      "3:4",
      "4:0",
      "4:2"
    ],
    "seed": 188421,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-01-10",
    "title": "初庭长明",
    "chapterId": "gate",
    "rows": [
      ".0.1.",
      ".....",
      ".2...",
      "...01",
      "#..#."
    ],
    "solution": [
      "0:4",
      "1:0",
      "2:2",
      "3:1",
      "4:4"
    ],
    "seed": 196612,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-02-01",
    "title": "零灯石",
    "chapterId": "zero",
    "rows": [
      "....#",
      "#.1..",
      "...2.",
      ".01..",
      ".#..."
    ],
    "solution": [
      "0:1",
      "1:3",
      "2:0",
      "3:3",
      "4:4"
    ],
    "seed": 237595,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-02-02",
    "title": "两处数字",
    "chapterId": "zero",
    "rows": [
      "...#.",
      ".1#.#",
      "....2",
      ".00..",
      "....."
    ],
    "solution": [
      "0:1",
      "0:4",
      "2:3",
      "3:4",
      "4:0"
    ],
    "seed": 245786,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-02-03",
    "title": "三瓣花",
    "chapterId": "zero",
    "rows": [
      ".0...",
      ".....",
      ".#.0.",
      ".00##",
      "....0"
    ],
    "solution": [
      "0:4",
      "1:2",
      "4:0"
    ],
    "seed": 263950,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-02-04",
    "title": "石纹邻光",
    "chapterId": "zero",
    "rows": [
      "....2",
      ".0...",
      ".....",
      "2..00",
      "....."
    ],
    "solution": [
      "0:3",
      "1:4",
      "2:0",
      "3:1",
      "4:2"
    ],
    "seed": 262168,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-02-05",
    "title": "空心花坛",
    "chapterId": "zero",
    "rows": [
      "###0.1",
      "#.....",
      "#.....",
      ".1..2.",
      ".0##..",
      "..#.#0"
    ],
    "solution": [
      "1:5",
      "2:4",
      "3:2",
      "4:4",
      "5:0",
      "5:3"
    ],
    "seed": 270359,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-02-06",
    "title": "数字之间",
    "chapterId": "zero",
    "rows": [
      ".#0.##",
      "......",
      "1#....",
      "###2..",
      "1.....",
      ".#.00#"
    ],
    "solution": [
      "1:0",
      "2:3",
      "3:4",
      "4:2",
      "5:0"
    ],
    "seed": 278550,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-02-07",
    "title": "月痕不落",
    "chapterId": "zero",
    "rows": [
      "###.##",
      ".00100",
      "......",
      ".1....",
      ".0...1",
      ".....#"
    ],
    "solution": [
      "0:3",
      "2:0",
      "3:2",
      "4:4",
      "5:3"
    ],
    "seed": 286741,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-02-08",
    "title": "苔石绕灯",
    "chapterId": "zero",
    "rows": [
      "..#.2.",
      ".0.##.",
      ".#.0#.",
      "...1#0",
      "#1..##",
      "......"
    ],
    "solution": [
      "0:0",
      "0:3",
      "0:5",
      "3:1",
      "4:3",
      "5:2"
    ],
    "seed": 284959,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-02-09",
    "title": "四邻有数",
    "chapterId": "zero",
    "rows": [
      "..##..",
      "#.001.",
      ".#....",
      ".#.#..",
      "..##1.",
      ".1..0."
    ],
    "solution": [
      "0:1",
      "0:4",
      "2:5",
      "3:2",
      "3:4",
      "4:0",
      "5:2"
    ],
    "seed": 293150,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-02-10",
    "title": "静庭归零",
    "chapterId": "zero",
    "rows": [
      "..#.#1",
      ".##...",
      "0#.#..",
      "1.20..",
      "......",
      ".#.#.."
    ],
    "solution": [
      "0:0",
      "0:3",
      "1:5",
      "2:2",
      "3:1",
      "4:4",
      "5:0",
      "5:2"
    ],
    "seed": 301341,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-03-01",
    "title": "单灯长廊",
    "chapterId": "corridor",
    "rows": [
      "###...",
      "##....",
      ".1..2.",
      "...2..",
      "0.....",
      "##..1."
    ],
    "solution": [
      "0:3",
      "1:4",
      "2:0",
      "3:2",
      "3:4",
      "4:5",
      "5:3"
    ],
    "seed": 372243,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-03-02",
    "title": "花墙折径",
    "chapterId": "corridor",
    "rows": [
      "......",
      "....#.",
      ".100.0",
      "#....#",
      "..#...",
      ".....1"
    ],
    "solution": [
      "0:5",
      "1:0",
      "3:1",
      "4:0",
      "4:3",
      "5:4"
    ],
    "seed": 360488,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-03-03",
    "title": "隔墙借光",
    "chapterId": "corridor",
    "rows": [
      "....0#",
      "..1###",
      "#...#.",
      "..#0.1",
      "......",
      "0.0..#"
    ],
    "solution": [
      "0:0",
      "2:2",
      "2:5",
      "3:0",
      "4:1",
      "5:4"
    ],
    "seed": 378652,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-03-04",
    "title": "短径深处",
    "chapterId": "corridor",
    "rows": [
      "##...#",
      ".#...0",
      ".0..#.",
      ".1....",
      "0.....",
      "0...1."
    ],
    "solution": [
      "0:4",
      "1:0",
      "3:2",
      "4:5",
      "5:3"
    ],
    "seed": 386843,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-03-05",
    "title": "回身看灯",
    "chapterId": "corridor",
    "rows": [
      "..#.##",
      "..3...",
      ".2...#",
      ".0..#.",
      ".0....",
      ".0...0"
    ],
    "solution": [
      "0:0",
      "1:1",
      "1:3",
      "2:2",
      "3:5",
      "4:4"
    ],
    "seed": 365115,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-03-06",
    "title": "双廊交会",
    "chapterId": "corridor",
    "rows": [
      "..0#..",
      "#.....",
      ".2#...",
      "#.#..#",
      "......",
      "....2#"
    ],
    "solution": [
      "0:0",
      "1:5",
      "2:0",
      "3:1",
      "4:4",
      "5:3"
    ],
    "seed": 373306,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-03-07",
    "title": "篱影收束",
    "chapterId": "corridor",
    "rows": [
      "..2..0",
      "1..##0",
      ".1....",
      "......",
      ".....#",
      "#.1.0#"
    ],
    "solution": [
      "0:1",
      "0:3",
      "2:0",
      "2:4",
      "3:2",
      "4:3",
      "5:1"
    ],
    "seed": 381497,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-03-08",
    "title": "暗角唯一",
    "chapterId": "corridor",
    "rows": [
      "..#.#.",
      ".0#10.",
      ".#....",
      ".2..##",
      "..2.#.",
      "#....."
    ],
    "solution": [
      "0:0",
      "0:3",
      "2:5",
      "3:2",
      "4:1",
      "4:5",
      "5:3"
    ],
    "seed": 389688,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-03-09",
    "title": "曲径与石",
    "chapterId": "corridor",
    "rows": [
      "..###.",
      "0....2",
      "...1..",
      ".01...",
      "......",
      "..2..."
    ],
    "solution": [
      "0:1",
      "0:5",
      "1:4",
      "2:2",
      "3:5",
      "4:0",
      "5:1",
      "5:3"
    ],
    "seed": 397879,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-03-10",
    "title": "花墙尽头",
    "chapterId": "corridor",
    "rows": [
      "#..0..",
      "1##...",
      "...#.#",
      "......",
      "###.2.",
      ".1..##"
    ],
    "solution": [
      "0:1",
      "1:5",
      "2:0",
      "3:4",
      "4:5",
      "5:0",
      "5:3"
    ],
    "seed": 435989,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-04-01",
    "title": "竹节相连",
    "chapterId": "bamboo",
    "rows": [
      "#..20.",
      "##....",
      "......",
      "..10.#",
      "#.....",
      "..#0.#"
    ],
    "solution": [
      "0:2",
      "1:3",
      "2:5",
      "3:1",
      "4:4",
      "5:0"
    ],
    "seed": 457026,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-04-02",
    "title": "两石共影",
    "chapterId": "bamboo",
    "rows": [
      ".3...0",
      "#..#..",
      ".#...1",
      ".#....",
      "..##..",
      "2...#."
    ],
    "solution": [
      "0:0",
      "0:2",
      "1:1",
      "1:4",
      "2:3",
      "3:5",
      "4:0",
      "5:1"
    ],
    "seed": 445271,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-04-03",
    "title": "竹林空格",
    "chapterId": "bamboo",
    "rows": [
      "2....#",
      "..#.1.",
      "1.1...",
      "...#..",
      ".0#.#.",
      "....#0"
    ],
    "solution": [
      "0:1",
      "1:0",
      "1:3",
      "2:5",
      "3:2",
      "3:4",
      "4:3",
      "5:0"
    ],
    "seed": 473408,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-04-04",
    "title": "枝叶交错",
    "chapterId": "bamboo",
    "rows": [
      ".1..1.",
      "...#.#",
      "......",
      "1.0...",
      "......",
      "0.1..."
    ],
    "solution": [
      "0:2",
      "0:5",
      "2:0",
      "3:4",
      "4:1",
      "5:3"
    ],
    "seed": 461653,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-04-05",
    "title": "石隙藏萤",
    "chapterId": "bamboo",
    "rows": [
      ".....#.",
      "..0#...",
      "....1..",
      "1..##..",
      "#0.#.1.",
      ".2....#",
      ".#.0.#."
    ],
    "solution": [
      "0:1",
      "1:6",
      "2:0",
      "2:5",
      "4:4",
      "5:0",
      "5:2",
      "6:6"
    ],
    "seed": 479817,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-04-06",
    "title": "数字相借",
    "chapterId": "bamboo",
    "rows": [
      ".......",
      "......1",
      "##.#0..",
      "#01...2",
      "....#..",
      "...01..",
      "..##..0"
    ],
    "solution": [
      "0:5",
      "1:2",
      "2:6",
      "3:3",
      "4:0",
      "4:6",
      "5:1",
      "6:4"
    ],
    "seed": 517927,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-04-07",
    "title": "疏竹照径",
    "chapterId": "bamboo",
    "rows": [
      "#2.....",
      "...##..",
      ".....0.",
      "...1.##",
      "##....0",
      ".....1#",
      "##...#."
    ],
    "solution": [
      "0:2",
      "1:1",
      "1:6",
      "2:0",
      "4:3",
      "5:4",
      "6:6"
    ],
    "seed": 506172,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-04-08",
    "title": "交错灯位",
    "chapterId": "bamboo",
    "rows": [
      ".##.0.0",
      ".1..1..",
      "#......",
      "..1...#",
      ".1##.0.",
      "....#..",
      ".#.1#.."
    ],
    "solution": [
      "0:0",
      "1:2",
      "1:5",
      "2:3",
      "3:1",
      "3:4",
      "5:0",
      "5:6",
      "6:2",
      "6:5"
    ],
    "seed": 514363,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-04-09",
    "title": "竹影回廊",
    "chapterId": "bamboo",
    "rows": [
      "##0....",
      "....01.",
      "0.##...",
      ".#...3.",
      "..#....",
      ".1##...",
      "#..##.."
    ],
    "solution": [
      "0:6",
      "1:1",
      "2:5",
      "3:4",
      "4:0",
      "4:5",
      "6:1"
    ],
    "seed": 522554,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-04-10",
    "title": "月下成双",
    "chapterId": "bamboo",
    "rows": [
      "1..##..",
      "1....1.",
      "...#..0",
      ".......",
      "...1#..",
      ".##.#.#",
      "###..0#"
    ],
    "solution": [
      "0:1",
      "0:6",
      "1:4",
      "2:0",
      "3:5",
      "4:2",
      "4:6",
      "6:3"
    ],
    "seed": 520772,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-05-01",
    "title": "水榭初映",
    "chapterId": "water",
    "rows": [
      "......#",
      "..0....",
      "....0..",
      "2..###2",
      ".#...#.",
      "#000.#.",
      "....#.#"
    ],
    "solution": [
      "0:1",
      "1:5",
      "2:0",
      "2:6",
      "3:2",
      "4:0",
      "4:4",
      "4:6",
      "6:0",
      "6:5"
    ],
    "seed": 561755,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-05-02",
    "title": "池畔长光",
    "chapterId": "water",
    "rows": [
      "....3..",
      "###..2.",
      "##..#0.",
      ".......",
      "#..#0.#",
      "0..#...",
      "#.1.1.."
    ],
    "solution": [
      "0:3",
      "0:5",
      "1:4",
      "2:2",
      "3:6",
      "4:1",
      "5:5",
      "6:3",
      "6:6"
    ],
    "seed": 569946,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-05-03",
    "title": "曲桥倒影",
    "chapterId": "water",
    "rows": [
      "#..#.#.",
      ".1...0.",
      "......#",
      "#0...#.",
      "..#...#",
      "..#....",
      "##.2.0#"
    ],
    "solution": [
      "0:2",
      "0:6",
      "1:0",
      "2:4",
      "3:6",
      "4:0",
      "4:5",
      "5:1",
      "5:3",
      "6:2"
    ],
    "seed": 558191,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-05-04",
    "title": "隔水见灯",
    "chapterId": "water",
    "rows": [
      "....11#",
      "....#..",
      "#...#.#",
      "..0...#",
      "..#0.#.",
      "0..##0.",
      "...0..."
    ],
    "solution": [
      "0:3",
      "1:2",
      "1:5",
      "3:0",
      "3:4",
      "5:2",
      "6:1",
      "6:6"
    ],
    "seed": 566382,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-05-05",
    "title": "双岸微明",
    "chapterId": "water",
    "rows": [
      "0..2.#.#",
      "..1.....",
      "........",
      "....0...",
      "2..1..#.",
      "..#.....",
      ".#.....1",
      ".#...3.."
    ],
    "solution": [
      "0:2",
      "0:4",
      "1:6",
      "2:1",
      "3:0",
      "4:2",
      "5:0",
      "5:7",
      "6:5",
      "7:4",
      "7:6"
    ],
    "seed": 574573,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-05-06",
    "title": "荷影穿庭",
    "chapterId": "water",
    "rows": [
      ".....#..",
      "#.2.#...",
      ".3...0.2",
      ".#......",
      ".#####..",
      "2..##...",
      ".....#..",
      ".#.....1"
    ],
    "solution": [
      "0:3",
      "1:1",
      "1:7",
      "2:0",
      "2:2",
      "3:7",
      "5:1",
      "5:5",
      "6:0",
      "7:6"
    ],
    "seed": 582764,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-05-07",
    "title": "回廊映水",
    "chapterId": "water",
    "rows": [
      "....#.0.",
      ".01.#...",
      "##....#.",
      "#..2#..2",
      "#.2...#.",
      "....1..2",
      "..#...##",
      ".0#..##."
    ],
    "solution": [
      "0:0",
      "1:3",
      "1:7",
      "2:5",
      "3:2",
      "3:6",
      "4:3",
      "4:7",
      "5:1",
      "5:6",
      "6:0",
      "6:4",
      "7:7"
    ],
    "seed": 630847,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-05-08",
    "title": "石桥相望",
    "chapterId": "water",
    "rows": [
      ".......#",
      ".1.2.##.",
      "1...3.#.",
      "........",
      "1.#.....",
      "...#01..",
      "..1.##10",
      "..0.#..."
    ],
    "solution": [
      "0:2",
      "1:0",
      "1:4",
      "2:3",
      "2:5",
      "3:1",
      "4:7",
      "5:0",
      "5:6",
      "6:3",
      "7:5"
    ],
    "seed": 599146,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-05-09",
    "title": "临池灯阵",
    "chapterId": "water",
    "rows": [
      "1.##....",
      "....#.1#",
      "..1.....",
      "...1##.0",
      "1.......",
      "#.0....1",
      ".....0#.",
      "0....#0."
    ],
    "solution": [
      "0:5",
      "1:0",
      "2:6",
      "3:2",
      "4:1",
      "5:4",
      "6:3",
      "6:7",
      "7:2"
    ],
    "seed": 677148,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-05-10",
    "title": "水榭回光",
    "chapterId": "water",
    "rows": [
      "0.0#...2",
      ".....0..",
      "..#.....",
      "........",
      "1....1##",
      ".2.1..2.",
      "#..#####",
      "0..#..0#"
    ],
    "solution": [
      "0:6",
      "1:1",
      "1:7",
      "2:0",
      "2:4",
      "3:2",
      "4:3",
      "5:0",
      "5:5",
      "5:7",
      "6:1",
      "7:4"
    ],
    "seed": 745177,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-06-01",
    "title": "星点入庭",
    "chapterId": "stars",
    "rows": [
      "........",
      "..1.1.00",
      "...#....",
      ".10...#.",
      ".#...###",
      "....2##.",
      ".#...#.1",
      "...#.1.."
    ],
    "solution": [
      "0:0",
      "1:3",
      "2:1",
      "2:5",
      "3:4",
      "3:7",
      "5:3",
      "5:7",
      "6:4",
      "7:2",
      "7:6"
    ],
    "seed": 865944,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-06-02",
    "title": "深夜疏光",
    "chapterId": "stars",
    "rows": [
      ".....1..",
      "....2...",
      "0.#...#1",
      "0..1..##",
      "#...2...",
      ".0.1..##",
      "......#.",
      "...1...#"
    ],
    "solution": [
      "0:1",
      "0:6",
      "1:3",
      "1:7",
      "2:4",
      "4:3",
      "4:5",
      "6:2",
      "6:7",
      "7:0",
      "7:4"
    ],
    "seed": 794351,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-06-03",
    "title": "幽径藏星",
    "chapterId": "stars",
    "rows": [
      "0.1.#0#.",
      "....#...",
      "#...1#..",
      "...#...#",
      "...#.0.#",
      "0.......",
      "...2.#..",
      "#...2..1"
    ],
    "solution": [
      "0:3",
      "1:1",
      "1:7",
      "3:0",
      "3:4",
      "5:6",
      "6:2",
      "6:7",
      "7:3",
      "7:5"
    ],
    "seed": 662920,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-06-04",
    "title": "九曲水榭",
    "chapterId": "stars",
    "rows": [
      "....#...",
      "01..#...",
      "...1#.0.",
      "#...1...",
      "..#...1.",
      "#....1..",
      ".#.2....",
      "#.#1..#."
    ],
    "solution": [
      "0:2",
      "0:6",
      "1:3",
      "2:1",
      "3:5",
      "4:0",
      "5:3",
      "5:6",
      "6:0",
      "6:2",
      "6:7",
      "7:1",
      "7:4"
    ],
    "seed": 691057,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-06-05",
    "title": "花窗远照",
    "chapterId": "stars",
    "rows": [
      ".1....1..",
      "#0#0...#.",
      ".........",
      "#.......2",
      "..#......",
      "..0.##0..",
      "0.......1",
      ".........",
      "#00...0.."
    ],
    "solution": [
      "0:0",
      "0:4",
      "0:7",
      "1:5",
      "2:8",
      "3:1",
      "4:0",
      "4:8",
      "6:7",
      "7:3",
      "8:4",
      "8:8"
    ],
    "seed": 769059,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-06-06",
    "title": "石庭连锁",
    "chapterId": "stars",
    "rows": [
      "#..01...#",
      ".##......",
      "#2...#..1",
      "..##...#.",
      ".#1......",
      "..1..#.0#",
      ".....#...",
      ".#0..#.#0",
      ".##1....#"
    ],
    "solution": [
      "0:1",
      "0:5",
      "1:0",
      "1:7",
      "2:2",
      "3:1",
      "3:5",
      "3:8",
      "4:3",
      "5:1",
      "6:0",
      "6:6",
      "8:4"
    ],
    "seed": 727385,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-06-07",
    "title": "露影回环",
    "chapterId": "stars",
    "rows": [
      ".12..#1..",
      "....1...#",
      ".......#.",
      "#...#.00.",
      ".....#...",
      "..#1...1.",
      "0..#.....",
      "..#...#..",
      "...1.##.."
    ],
    "solution": [
      "0:0",
      "0:3",
      "0:7",
      "1:2",
      "1:5",
      "2:1",
      "4:0",
      "4:8",
      "5:4",
      "6:2",
      "6:7",
      "7:3",
      "8:0"
    ],
    "seed": 745549,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-06-08",
    "title": "满庭灯语",
    "chapterId": "stars",
    "rows": [
      "#..#2...#",
      "#.....##.",
      "#0...0...",
      "#........",
      "...0.#0..",
      "1...##...",
      "....1...#",
      "#......3.",
      ".....#.##"
    ],
    "solution": [
      "0:1",
      "0:5",
      "1:4",
      "2:3",
      "2:8",
      "3:2",
      "4:0",
      "6:3",
      "6:7",
      "7:6",
      "7:8",
      "8:1"
    ],
    "seed": 743767,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-06-09",
    "title": "星河落园",
    "chapterId": "stars",
    "rows": [
      "#..###...",
      "0....#.0.",
      "..##..##.",
      ".0.#.1...",
      "....##...",
      "#..10....",
      "###....#.",
      ".1.##0#0.",
      "...1.1..."
    ],
    "solution": [
      "0:1",
      "0:6",
      "1:4",
      "2:5",
      "4:0",
      "5:2",
      "5:7",
      "6:6",
      "7:2",
      "8:0",
      "8:4",
      "8:8"
    ],
    "seed": 811796,
    "generatorVersion": "garden-gen-1"
  },
  {
    "id": "firefly-06-10",
    "title": "满庭星火",
    "chapterId": "stars",
    "rows": [
      "....0#...",
      "......1.#",
      ".1#......",
      ".....0...",
      "....1..1.",
      "..1...#..",
      "10....##.",
      "..#.1....",
      ".#.#..00."
    ],
    "solution": [
      "0:0",
      "0:7",
      "1:3",
      "2:6",
      "3:1",
      "4:2",
      "5:4",
      "5:7",
      "6:5",
      "7:0",
      "7:8",
      "8:2",
      "8:4"
    ],
    "seed": 730230,
    "generatorVersion": "garden-gen-1"
  }
].map((level) => createPuzzle(Object.assign({}, level, { solution: Object.freeze(level.solution) }))));

export function findLevel(id) { return LEVELS.find((level) => level.id === id) || null; }
