import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {runtime,root,json} from '../scripts/lib.mjs';import {oracle,canonical,graphSignature,isomorphic} from '../scripts/oracle.mjs';
const {BellEngine:E,BellLevels:D,BellStore:S}=runtime();
const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),map};};
test('60 stable puzzles: valid, nontrivial, symmetry-distinct, independently minimum-proven',()=>{assert.equal(D.levels.length,60);const seen=new Set();for(const l of D.levels){assert(E.valid(l));assert(!E.won(l,E.replay(l,[])));const solution=E.solve(l,l.initial),independent=oracle(json(l));assert.equal(solution.minimum,independent.length,l.id);assert.equal(l.minimum,independent.length,l.id);assert(E.won(l,E.replay(l,independent)));assert(!seen.has(canonical(l)),l.id);seen.add(canonical(l));}for(let c=0;c<6;c++)assert.equal(D.levels.filter(l=>l.chapter===c).length,10);});
test('every bell: exact XOR, double-press inverse, immutable templates, commutation, undo',()=>{for(const l of D.levels){const initial=E.replay(l,[]),snapshot=JSON.stringify(l);for(let i=0;i<l.initial.length;i++){const a=E.press(l,initial,i);assert.deepEqual(json(a.lights),json(l.initial.map((x,j)=>x^(l.templates[i].includes(j)?1:0))));assert.deepEqual(json(E.press(l,a,i).lights),json(initial.lights));assert.deepEqual(json(E.undo(l,a)),json(initial));const j=(i+1)%l.initial.length;assert.deepEqual(json(E.press(l,a,j).lights),json(E.press(l,E.press(l,initial,j),i).lights));}assert.equal(JSON.stringify(l),snapshot);}});
test('invalid actions are atomic; untrusted light flags never confer victory',()=>{const l=D.levels[0],s=E.replay(l,[]);for(const i of [-1,99,1.5,NaN,'1',null])assert.equal(E.press(l,s,i),s);assert.equal(E.replay(l,[99]),null);assert.equal(E.replay(l,Array(10001).fill(0)),null);assert.equal(E.won(l,{history:[],lights:Array(l.initial.length).fill(1)}),false);assert.equal(E.replay({...json(l),initial:[2]},[]),null);assert.equal(E.solve(l,[]),null);});
test('three SVG tutorial states are engine-derived, same board; two-step proof',()=>{const paths=[[],[0],[0,4]];paths.forEach((h,i)=>{const st=E.replay(D.tutorial,h),svg=fs.readFileSync(new URL('assets/tutorial-'+i+'.svg',root),'utf8');assert(svg.includes('data-level="'+D.tutorial.id+'"'));assert(svg.includes('data-state="'+st.lights.join('')+'"'));assert.equal((svg.match(/data-cell=/g)||[]).length,9);for(let j=0;j<9;j++)assert(svg.includes('data-cell="'+j+'" data-light="'+st.lights[j]+'"'));});assert.deepEqual(json(D.tutorial.templates[0]),[0,1,3]);assert.deepEqual(json(D.tutorial.templates[4]),[1,3,4,5,7]);assert(E.won(D.tutorial,E.replay(D.tutorial,[0,4])));assert.equal(oracle(json(D.tutorial)).length,2);});
test('restore replays history; corrupt session does not destroy valid records or other keys',()=>{const st=memory(),l=D.levels[2],s=S.fresh(),sol=E.solve(l,l.initial);const session={key:l.id,runId:'run-test-a',history:json(sol.presses),assisted:false};S.settle(s,session,'2026-09-14T00:00:00.000Z');s.session={key:l.id,runId:'run-test-b',history:[999]};st.setItem('another-game','untouched');S.save(st,s);const loaded=S.load(st);assert.equal(loaded.session,null);assert(loaded.records[l.id].solo);assert.equal(st.getItem('another-game'),'untouched');st.setItem(S.key,'{broken');assert.deepEqual(json(S.load(st)),json(S.fresh()));assert.equal(st.getItem('another-game'),'untouched');});
test('repeated completion, replay, hints and improving result cannot duplicate claims',()=>{const s=S.fresh(),l=D.levels[4],path=json(E.solve(l,l.initial).presses);const make=(id,h=path,assisted=false)=>({key:l.id,runId:'run-'+id,history:h,assisted});const a=S.settle(s,make('a',path.concat(0,0)),'2026-09-14T00:00:00.000Z');assert.equal(a.rewardClaims.length,1);assert.equal(S.settle(s,make('a',path.concat(0,0)),'later').completionId,a.completionId);assert.equal(s.outbox.length,1);const b=S.settle(s,make('b'),'2026-09-14T00:00:01.000Z');assert.equal(b.rewardClaims.length,1);const c=S.settle(s,make('c'),'2026-09-14T00:00:02.000Z');assert.equal(c.rewardClaims.length,0);const loaded=S.normalize(json(s));assert.equal(S.claimsFor(loaded).length,2);const h=S.fresh();S.settle(h,make('hint',path,true),'2026-09-14T00:00:00.000Z');assert.equal(S.claimsFor(h).length,0);assert(h.records[l.id].best);S.settle(h,make('solo'),'2026-09-14T00:00:00.000Z');assert.equal(S.claimsFor(h).length,2);});
test('outbox writes before host, survives errors, retries same ID and stops after ack',()=>{const s=S.fresh(),st=memory(),l=D.levels[0];const payload=S.settle(s,{key:l.id,runId:'run-host-test',history:json(E.solve(l,l.initial).presses),assisted:false},'2026-09-14T00:00:00.000Z');let calls=0;S.flush(st,s,p=>{calls++;assert.equal(JSON.parse(st.getItem(S.key)).outbox[0],p.completionId);throw Error('offline');});assert.equal(s.outbox.length,1);S.flush(st,s,p=>{calls++;assert.equal(p.completionId,payload.completionId);return true;});assert.equal(s.outbox.length,0);S.flush(st,s,()=>{calls++;});assert.equal(calls,2);const noStorage={setItem(){throw Error('quota');}};const s2=S.normalize(JSON.parse(st.getItem(S.key)));s2.outbox=[payload.completionId];assert.equal(S.flush(noStorage,s2,()=>{throw Error('must not notify');}),false);});
test('daily bank version + date stable, distinct reward namespace, local calendar',()=>{assert.equal(S.daily('2026-09-14').id,S.daily('2026-09-14').id);const id='daily-v1-2026-09-14',l=S.resolve(id);assert(l);const s=S.fresh();S.settle(s,{key:id,runId:'run-daily',history:json(E.solve(l,l.initial).presses),assisted:false},'2026-09-14T00:00:00.000Z');assert.equal(S.claimsFor(s).length,2);assert(!s.records[l.id]);assert.equal(S.dateKey(new Date(2026,0,2)),'2026-01-02');});

test('no arbitrary relabeling duplicates in coloured influence graphs',()=>{for(let i=0;i<D.levels.length;i++)for(let j=0;j<i;j++)if(graphSignature(D.levels[i])===graphSignature(D.levels[j]))assert(!isomorphic(D.levels[i],D.levels[j]),D.levels[i].id+' '+D.levels[j].id);const a=json(D.levels[5]),map=a.initial.map((_,i)=>a.initial.length-1-i),b={size:a.size,initial:[],templates:[]};a.initial.forEach((v,i)=>b.initial[map[i]]=v);a.templates.forEach((t,i)=>b.templates[map[i]]=t.map(j=>map[j]));assert(isomorphic(a,b));});

test('malformed states and unreachable targets fail closed',()=>{const l=D.levels[0];for(const s of [{},{history:null},{history:'x'},null]){assert.equal(E.press(l,s,0),s);assert.equal(E.undo(l,s),s);}assert.equal(E.press(null,{},0).history,undefined);const unreachable={size:2,templates:[[0,1],[1,2],[2,3],[0,3]],initial:[0,1,1,1]};assert(E.valid(unreachable));assert.equal(E.solve(unreachable,unreachable.initial),null);assert.equal(oracle(unreachable),null);});

test('receipt metrics are reconstructed, malformed daily dates and forged claims are rejected',()=>{const s=S.fresh(),l=D.levels[0],session={key:l.id,runId:'run-repair',history:json(E.solve(l,l.initial).presses),assisted:false};const p=S.settle(s,session,'2026-09-14T00:00:00.000Z');p.metrics.moves=-500;p.gameId='foreign';p.rewardClaims.push('foreign:claim');const rebuilt=S.normalize(json(s)).receipts['run-repair:complete'].payload;assert.equal(rebuilt.gameId,'evening-bell-garden');assert.equal(rebuilt.runId,'run-repair');assert.equal(rebuilt.metrics.moves,session.history.length);assert.equal(rebuilt.rewardClaims.length,2);assert.equal(S.resolve('daily-v1-2026-99-44'),null);assert.equal(S.settle(s,null,'x'),null);});
