import {LEVELS,CHAPTERS} from './levels.mjs';
import {UNKNOWN,WHITE,BLACK,clueAt,beam,evaluate,initial,setMark} from './core.mjs';
import {fresh,restore,ensure,state,mark,undo,restart,settle,progress,hint,TUTORIAL} from './session.mjs';
import {backend,commit} from './storage.mjs';
import {model,boardSvg,tutorialFrames} from './view.mjs';
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal'),live=$('#live');
const chapterNotes=['数字含脚下这格；遇遮屏才停。','把总数拆成北、东、南、西与自身。','黑屏四邻留白；对角接触允许。','看得见也要走得通，角点不是桥。','长臂交错，读数与白路共同推理。','不加新规则，完成公共庭的竣图。'];
const chapterGardens=['入口小庭','回廊庭','框景庭','连廊庭','层叠庭','中央公共庭'];
let data=fresh(LEVELS),store,page='home',tool='cycle',busy=false,dialog=null,dialogFocus=null,dialogFocusSelector=null,preview=null,highlight=null,chapterPage=1,collectionPlane=false,readBlocked=false;
const level=()=>LEVELS.find(l=>l.id===data.current)||LEVELS[0],run=()=>ensure(level(),data),pad=n=>String(n).padStart(2,'0'),xy=(l,i)=>`${Math.floor(i/l.width)+1}行${i%l.width+1}列`,button=(action,label,klass='')=>`<button class="${klass}" data-action="${action}">${label}</button>`,done=id=>progress(data,id).length>0;
function announce(s){live.textContent=s;}
function render(){document.body.classList.toggle('playing',page==='play');document.body.classList.toggle('quiet',data.preferences.quiet);if(page==='play')renderPlay();else if(page==='book')renderBook();else if(page==='collection')renderCollection();else renderHome();}
function renderHome(){const count=new Set(data.evidence.map(e=>e.levelId)).size;app.innerHTML=`<div class="home"><span class="eyebrow">PUBLIC SPACE / FIELD NOTES 01—48</span><div class="hero"><div class="hero-copy"><span class="eyebrow">把光的范围，画成一座庭院</span><h1 class="hero-title">留一面屏，<br>留一条路。</h1><p>你是公共庭院的测绘师。用珊瑚遮屏截短视线，让每座数字台读得准确，也让白地处处相通。</p><div class="home-actions">${button('continue',count?'继续测绘':'展开第一张图','primary')}${button('tutorial','先读光')}</div></div><div class="hero-art"><img src="./assets/hero.svg" alt="米白庭院与珊瑚低屏的装饰模型，没有谜题数字" width="540" height="330" style="width:100%;height:auto;display:block"><div class="folio-label"><span>NO. 01 / PUBLIC COURTYARD</span><span>装饰模型</span></div></div></div><div class="home-footer"><div><span class="collection-count">${pad(count)}</span> / 48 张竣图 · 六册课程</div><div>${data.xp} 测绘积分</div></div><div class="principles"><span><b>读光</b>四向计数含自身</span><span><b>留隙</b>黑屏不共边</span><span><b>连通</b>白地正交相连</span></div><p class="home-meta">无计时失败 · 白点只作笔记 · ${button('book','庭院图簿','flat')}${button('collection','竣图画册','flat')}</p></div>`;}
function renderBook(){app.innerHTML=`<div class="page"><div class="page-title"><div><span class="eyebrow">SIX VOLUMES / 48 SURVEYS</span><h1>庭院图簿</h1><p class="muted">先读光，再留路。关卡可自由选择。</p></div>${button('home','回测绘所')}</div>${CHAPTERS.map((name,ch)=>`<section class="chapter"><div class="chapter-head"><span class="chapter-number">${pad(ch+1)}</span><div><h2>${name}</h2><p>${chapterNotes[ch]}</p><span class="eyebrow">${LEVELS.filter(l=>l.chapter===ch+1&&done(l.id)).length} / 8 · ${chapterGardens[ch]}</span></div></div><div class="level-list">${LEVELS.filter(l=>l.chapter===ch+1).map(l=>{const i=LEVELS.indexOf(l),p=progress(data,l.id);return `<button class="level-button" data-level="${l.id}"><span><span class="level-number">${pad(i+1)}</span>${l.title}<small>${l.width}×${l.height} · ${i%8<2?'引导':i%8<6?'组合':'综合'}${p.length?' · 提示'+Math.min(...p.map(e=>e.run.hintLevel))+'级':''}</small></span><span class="check">${p.length?'✓':'↗'}</span></button>`;}).join('')}</div></section>`).join('')}</div>`;}
function renderPlay(){document.body.classList.add('playing');const oldPane=$('.play-body'),oldLevel=$('.play'),keepScroll=oldPane&&oldLevel&&oldLevel.dataset.level===data.current?oldPane.scrollTop:0;const l=level(),r=run(),s=state(l,r),e=evaluate(l,s),sel=preview===null?r.selected:preview,b=beam(l,s.marks,sel),cellLabel=i=>`${xy(l,i)}，${clueAt(l,i)?'数字台'+clueAt(l,i):s.marks[i]===1?'黑色遮屏':s.marks[i]===0?'白点笔记':'未笔记白格'}`;const conflict=new Set([].concat(...e.pairs,...(e.groups.length>1?e.groups:[])));
app.innerHTML=`<section class="play" data-level="${l.id}"><div class="play-title"><div><span class="eyebrow">VOL. ${pad(l.chapter)} / SURVEY ${pad(LEVELS.indexOf(l)+1)}</span><h1>${l.title}</h1></div>${button('tutorial','读光手册')}</div><div class="play-body"><div class="drafting"><div class="readout"><span>${xy(l,sel)} · 测距台</span><strong>当前 ${b?b.count:'—'} / ${b?b.target:'—'}</strong></div><div class="board-wrap"><div class="ruler">N ↑ &nbsp; PLAN / ${l.width} × ${l.height}</div><div class="board" data-cols="${l.width}" role="group" aria-label="${l.title}测绘盘">${s.marks.map((v,i)=>`<button id="cell-${i}" class="cell ${clueAt(l,i)?'clue':''} ${v===1?'black':v===0&&!clueAt(l,i)?'white':''} ${b&&b.cells.includes(i)?'beam':''} ${sel===i?'selected':''} ${conflict.has(i)?'conflict':''} ${highlight===i?'hint-cell':''}" data-cell="${i}" aria-label="${cellLabel(i)}" ${clueAt(l,i)?`aria-pressed="${sel===i}"`:''}>${clueAt(l,i)?`<span>${clueAt(l,i)}</span>`:''}</button>`).join('')}</div><p class="board-legend">深顶珊瑚边 = 黑屏 &nbsp; ◆ = 白点笔记</p></div><div class="arms" aria-label="四臂贡献">${['北','东','南','西'].map((d,i)=>`<button data-arm="${i}">${d}<b>${b?b.arms[i].length:'—'}</b></button>`).join('')}<button class="self" data-arm="4">自身<b>1</b></button></div></div><div class="instrument"><span class="eyebrow">READ / PLACE / VERIFY</span><div class="verification"><span class="${e.readings.every(b=>b.count===b.target)?'pass':''}">${e.readings.every(b=>b.count===b.target)?'✓':'○'} 读数</span><span class="${e.pairs.length?'':'pass'}">${e.pairs.length?'!':'✓'} 间距</span><span class="${e.groups.length===1?'pass':''}">${e.groups.length===1?'✓':'!'} 连通</span></div><p class="status" role="status">${e.complete?'三项核验合格。剩余未笔记格已经算白。':e.pairs.length?'有黑屏共边，请留出一格白地。':e.groups.length>1?`白地分成${e.groups.length}片；角点接触不能通行。`:'读数仍需调整。点击数字查看四臂，未知格本来就算白。'}</p>${l.guide&&data.preferences.guide?`<div class="guide-note">${chapterNotes[l.chapter-1]} ${button('hide-guide','收起引导','flat')}</div>`:''}<div class="toolbox"><div class="tool-row">${[['black','▰ 黑屏'],['white','◆ 白点'],['erase','清除']].map(t=>`<button data-tool="${t[0]}" class="${tool===t[0]?'active':''}" aria-pressed="${tool===t[0]}">${t[1]}</button>`).join('')}</div><div class="tool-row">${button('undo','↶ 撤销')}${button('hint','逻辑提示')}${button('restart','重开')}</div><div class="tool-extra"><button data-tool="cycle" class="${tool==='cycle'?'primary':''}">点击循环${tool==='cycle'?' ✓':''}</button><button data-tool="reverse" class="${tool==='reverse'?'primary':''}">反向循环${tool==='reverse'?' ✓':''}</button><span>正式 ${s.moves} 次</span></div></div><p class="keyboard">方向键移焦点 · B 黑屏 · W 白点<br>Delete 清除 · 空格循环 · Shift+空格反向<br>白点不计正式动作；提示记录最高使用级别。</p>${e.complete?button('success','观察竣图模型','primary'):''}</div></div></section>`;
if(window.innerWidth<=760){$('.play').appendChild($('.toolbox'));$('.play-body').scrollTop=keepScroll;}
}
function viewOrder(l,r){return r.views.length?r.views.slice(0,20).map(i=>xy(l,i)).join(' → ')+(r.views.length>20?'（仅列前20次）':''):'未主动切换数字台';}
function renderCollection(){const count=new Set(data.evidence.map(e=>e.levelId)).size,ls=LEVELS.filter(l=>l.chapter===chapterPage&&done(l.id));app.innerHTML=`<div class="page"><div class="page-title"><div><span class="eyebrow">AS-BUILT / ARCHIVE</span><h1>公共庭画册</h1><p>${count} 张认证竣图 · 首次竣图各获10积分</p></div>${button('home','回测绘所')}</div><div class="collection-tabs">${CHAPTERS.map((c,i)=>`<button data-chapter="${i+1}" class="${chapterPage===i+1?'primary':''}">${pad(i+1)} ${c}</button>`).join('')}</div>${ls.length?ls.map(l=>{const records=progress(data,l.id),e=records[0],best=records.reduce((a,b)=>a.run.hintLevel<=b.run.hintLevel?a:b),s=state(l,e.run);return `<article class="model-card"><div class="meta"><div><span class="eyebrow">SURVEY ${pad(LEVELS.indexOf(l)+1)}</span><h2>${l.title}</h2></div><span class="check">✓</span></div>${(collectionPlane||data.preferences.quiet)?boardSvg(l,s.marks,e.run.selected):model(l,s.marks,{labels:true})}<p class="muted">${collectionPlane?'真实平面':'庭院模型 · 装饰高度不参与规则'} · 最低提示${Math.min(...progress(data,l.id).map(e=>e.run.hintLevel))}级</p><details class="view-order"><summary>对照读数查看顺序</summary><p>首通：${viewOrder(l,e.run)}</p><p>最低提示记录：${viewOrder(l,best.run)}</p></details>${button('toggle-plane',collectionPlane?'观察模型':'切回平面')}<button data-level="${l.id}">再测一遍</button></article>`;}).join(''):'<div class="empty"><h2>这一册还没有竣图</h2><p>完成测绘后，真实布局会自动收入画册。</p>'+button('book','去图簿选一张','primary')+'</div>'}<p class="achievement">${data.claims.filter(c=>c.includes(':chapter:')).length} / 6 枚庭院竣工章</p></div>`;}
function focusReturn(){if(dialogFocus&&dialogFocus.isConnected)dialogFocus.focus();else if(dialogFocusSelector&&document.querySelector(dialogFocusSelector))document.querySelector(dialogFocusSelector).focus();else if(page==='play')$('#cell-'+run().selected).focus();else $('.brand').focus();}
function openDialog(kind,opts={}){dialogFocus=document.activeElement;dialogFocusSelector=dialogFocus&&dialogFocus.id?'#'+dialogFocus.id:dialogFocus&&dialogFocus.dataset&&dialogFocus.dataset.action?'[data-action="'+dialogFocus.dataset.action+'"]':null;dialog=Object.assign({kind,step:0},opts);modal.hidden=false;document.body.style.overflow='hidden';paintDialog();$('.sheet').focus();}
function closeDialog(){const was=dialog;dialog=null;modal.hidden=true;document.body.style.overflow='';if(was&&was.kind==='tutorial'){data.seenTutorial=true;data.tutorialVersion=TUTORIAL;save();}focusReturn();}
function paintDialog(){const l=level(),r=run(),s=state(l,r);let html='';if(dialog.kind==='tutorial'){const f=tutorialFrames(LEVELS[0])[dialog.step],titles=['先数四条直线','放一面屏，光在这里停','三项合格，图就完成'],texts=[`数字含自己一次，另一个数字台不会挡光。蓝格是当前可见白地，总数${f.reading.count}，目标${f.reading.target}。`,`在${xy(LEVELS[0],f.cell)}放入一面真实合法遮屏，当前读数变成${f.reading.count}。白点只记“这里留白”，不会改变视线。`,'这是同一题的正确黑屏布局。仍有未加白点的白格，但已经完成：读数精确，黑屏不共边，白地正交连通。'];html=`<div class="step-counter">${pad(dialog.step+1)} / 03 · 同一认证题的真实状态</div><h2 id="modal-title">${titles[dialog.step]}</h2><img src="./assets/tutorial-${dialog.step+1}.svg" alt="${texts[dialog.step]}"><div class="frame-reading">北${f.reading.arms[0].length} + 东${f.reading.arms[1].length} + 南${f.reading.arms[2].length} + 西${f.reading.arms[3].length} + 自身1 = ${f.reading.count}</div><p>${texts[dialog.step]}</p><div class="sheet-actions">${button('close','跳过 / 关闭')}${dialog.step?button('guide-prev','上一张'):''}${button(dialog.step===2?'guide-finish':'guide-next',dialog.step===2?'开始测绘':'下一张','primary')}</div><div class="rule-item"><b>黑屏不共边</b>；对角接触允许。<br><b>白地正交连通</b>；只碰角点不算路。<br><b>未知 = 白地</b>；不用把白点填满。</div>${button('connectivity','看真实断连反例','flat')}`;}
 if(dialog.kind==='connectivity'){const ex=LEVELS[26],a=ex.disconnectedExample,ev=evaluate(ex,{marks:a});html=`<h2 id="modal-title">读数正确，白路却断了</h2>${boardSvg(ex,a,ex.clues[0][0],ev.groups)}<p>第27题的另一种布局：全部${ex.clues.length}个读数正确，黑屏没有共边，却分成${ev.groups.length}片白地。因此不能竣工。图中的白格只以角点相遇，不能走通。</p><p class="dialog-note">断连分片：${ev.groups.map((g,i)=>'区域'+String.fromCharCode(65+i)+'含'+g.length+'格').join('；')}。可回到第27题尝试连通桥推理。</p><div class="sheet-actions">${button('tutorial','回三图手册')}${button('close','明白了','primary')}</div>`;}
 if(dialog.kind==='settings')html=`<h2 id="modal-title">测绘偏好</h2><div class="settings-row"><span>章节前两题的读光引导</span><button data-pref="guide">${data.preferences.guide?'开启':'关闭'}</button></div><div class="settings-row"><span>轻声音（设备支持时）</span><button data-pref="sound">${data.preferences.sound?'开启':'关闭'}</button></div><div class="settings-row"><span>平面优先与简化装饰</span><button data-pref="quiet">${data.preferences.quiet?'开启':'关闭'}</button></div><p class="dialog-note">进度保存在此设备。白点、工具与正式黑布局分开。存储失败会提示重试。</p>${button('close','返回','primary')}`;
 if(dialog.kind==='restart')html=`<h2 id="modal-title">重新展开这张图？</h2><p>本题的黑屏和笔记会清空。已经认证的竣图与积分保留。</p><div class="sheet-actions">${button('close','继续当前图')}${button('restart-confirm','重新测绘','primary')}</div>`;
 if(dialog.kind==='hint'){const h=hint(l,r,dialog.tier),b=h&&h.source!==undefined?beam(l,s.marks,h.source):null;html=`<span class="eyebrow">LOGIC / LEVEL ${dialog.tier}</span><h2 id="modal-title">${h?(dialog.tier===1?'先看约束':dialog.tier===2?'为什么这一格必然如此':'确认执行这一步'):'当前布局已按推理链完成'}</h2><p>${h?h.text:'所有必然结论已标记。请查看三项核验。'}</p>${b?`<div class="frame-reading">当前四臂：${b.arms.map(a=>a.length).join(' + ')} + 自身1 = ${b.count} / 目标${b.target}</div>`:''}${h&&h.premises.length?`<p class="hint-premise">原题推理的前置结论：${h.premises.join('、')}。这些来自认证推理链；白点笔记不作为证明前提。</p>`:''}<p class="dialog-note">提示使用原题线索的完整推理链，不把你写的白点当成事实。记录本局使用的最高提示级别，不扣已有积分。</p><div class="sheet-actions">${button('close','我来试试')}${h?button(dialog.tier<3?'hint-next':'hint-apply',dialog.tier<3?'展开推理':'执行这一步','primary'):''}</div>`;}
 if(dialog.kind==='success'){const e=evaluate(l,s);html=`<span class="eyebrow">AS-BUILT / ${pad(LEVELS.indexOf(l)+1)}</span><h2 id="modal-title">${e.complete?'这座庭院，读光合格。':'已离开合格布局'}</h2><div class="success-flags"><span>✓ 读数</span><span>✓ 间距</span><span>✓ 连通</span></div><div class="success-hero">${data.preferences.quiet?boardSvg(l,s.marks,r.selected):model(l,s.marks,{labels:true})}</div><p>${l.title}已收入画册。最高提示${r.hintLevel}级；白点不需要填满。</p><p class="dialog-note">这是当前真实解的庭院模型。建筑高度和阴影只作展示，不改变平面规则。</p><div class="sheet-actions">${button('collection','看竣图册')}${button('next','下一张图','primary')}</div>${button('close','继续查看平面','flat')}`;}
 $('#modal-body').innerHTML=html;$('.sheet').scrollTop=0;}
let saveQueue=Promise.resolve();
function save(){saveQueue=saveQueue.then(()=>readBlocked?{ok:false,error:'存档读取失败；本页暂不覆盖旧记录。请重新读取旧存档。'}:commit(store,data,window.onCourtyardComplete)).then(result=>{const el=$('#save-error');el.hidden=result.ok;if(!result.ok){el.innerHTML=result.error+(readBlocked?' <button data-action="read-retry">重新读取旧存档</button>':' <button data-action="save-retry">重试保存</button>');announce(result.error);}return result;});return saveQueue;}
async function change(fn,{cell=null}={}){if(busy)return;busy=true;try{const beforeComplete=page==='play'?evaluate(level(),state(level(),run())).complete:false;const changed=fn();if(changed===false){if(page==='play'&&run().actions.length>=4096)announce('本局已达4096条操作上限，请重开后继续；已认证竣图保留。');return;}const l=level(),event=page==='play'?settle(LEVELS,l,data):null;await save();render();if(cell!==null&&page==='play'&&$('#cell-'+cell))$('#cell-'+cell).focus();if(page==='play'&&!beforeComplete&&evaluate(level(),state(level(),run())).complete){tone(true);openDialog('success');}else tone(false);}finally{busy=false;}}
function navigate(to){if(dialog)closeDialog();page=to;highlight=null;render();window.scrollTo(0,0);announce(to==='book'?'庭院图簿':to==='collection'?'竣图画册':'光庭测绘');}
function start(id){if(dialog)closeDialog();data.current=id;ensure(level(),data);page='play';highlight=null;save();render();window.scrollTo(0,0);}
function cycle(value,back=false){const order=back?[-1,0,1]:[-1,1,0];return order[(order.indexOf(value)+1)%3];}
function actCell(i,override){if(busy||dialog)return;const l=level(),r=run(),s=state(l,r);if(clueAt(l,i)){r.selected=i;r.views.push(i);if(r.views.length>4096)r.views.shift();save();renderPlay();$('#cell-'+i).focus();const b=beam(l,s.marks,i);announce(`${xy(l,i)}，北${b.arms[0].length}东${b.arms[1].length}南${b.arms[2].length}西${b.arms[3].length}，自身1，总数${b.count}，目标${b.target}`);return;}const mode=override||tool,value=mode==='black'?1:mode==='white'?0:mode==='erase'?-1:cycle(s.marks[i],mode==='reverse');highlight=null;change(()=>mark(l,data,i,value),{cell:i});}
function handle(action){if(action==='home'||action==='book'||action==='collection'){navigate(action);return;}if(action==='continue'){start(data.current);return;}if(action==='close'){closeDialog();return;}if(action==='tutorial'){openDialog('tutorial');return;}if(action==='connectivity'){openDialog('connectivity');return;}if(action==='settings'){openDialog('settings');return;}if(action==='save-retry'){save();return;}if(action==='read-retry'){reloadSaved();return;}if(action==='guide-next'||action==='guide-prev'){dialog.step+=action==='guide-next'?1:-1;paintDialog();return;}if(action==='guide-finish'){closeDialog();if(page==='home')start(data.current);return;}if(action==='hide-guide'){data.preferences.guide=false;save();render();return;}if(action==='restart'){openDialog('restart');return;}if(action==='restart-confirm'){closeDialog();change(()=>{restart(level(),data);return true;});return;}if(action==='undo'){change(()=>undo(level(),data));return;}if(action==='hint'){run().hintLevel=Math.max(1,run().hintLevel);save();openDialog('hint',{tier:1});return;}if(action==='hint-next'){dialog.tier++;run().hintLevel=Math.max(dialog.tier,run().hintLevel);const h=hint(level(),run(),dialog.tier);if(h){highlight=h.cell;if(h.source!==undefined&&clueAt(level(),h.source))run().selected=h.source;}save();renderPlay();paintDialog();return;}if(action==='hint-apply'){const h=hint(level(),run(),3);closeDialog();if(h)change(()=>mark(level(),data,h.cell,h.mark),{cell:h.cell});return;}if(action==='success'){openDialog('success');return;}if(action==='next'){const i=LEVELS.indexOf(level());if(i===47){navigate('collection');return;}start(LEVELS[i+1].id);return;}if(action==='toggle-plane'){collectionPlane=!collectionPlane;renderCollection();}}
let suppressCell=null;document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b||busy)return;if(suppressCell!==null&&Number(b.dataset.cell)===suppressCell){suppressCell=null;return;}if(b.hasAttribute('data-cell')){actCell(Number(b.dataset.cell));return;}if(b.dataset.level){start(b.dataset.level);return;}if(b.dataset.tool){tool=b.dataset.tool;renderPlay();document.querySelector('[data-tool="'+tool+'"]').focus();return;}if(b.dataset.chapter){chapterPage=Number(b.dataset.chapter);renderCollection();return;}if(b.dataset.pref){const k=b.dataset.pref;data.preferences[k]=!data.preferences[k];save();render();paintDialog();if(k==='sound')tone(false);return;}if(b.dataset.arm!==undefined){const i=Number(b.dataset.arm),bb=beam(level(),state(level(),run()).marks,run().selected);announce(i===4?'自身只计1格':`${['北','东','南','西'][i]}臂贡献${bb.arms[i].length}格`);return;}if(b.dataset.action)handle(b.dataset.action);});
document.addEventListener('keydown',ev=>{if(dialog){if(ev.key==='Escape'){ev.preventDefault();closeDialog();return;}if(ev.key==='Tab'){const elements=Array.from($('.sheet').querySelectorAll('button:not(:disabled)'));const first=elements[0],last=elements[elements.length-1];if(ev.shiftKey&&(document.activeElement===first||document.activeElement===$('.sheet'))){ev.preventDefault();last.focus();}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first.focus();}}return;}const target=ev.target.closest('[data-cell]');if(page!=='play'||!target)return;const i=Number(target.dataset.cell),l=level(),d={ArrowUp:-l.width,ArrowDown:l.width,ArrowLeft:-1,ArrowRight:1};if(d[ev.key]!==undefined){ev.preventDefault();let j=i+d[ev.key];if(j>=0&&j<l.width*l.height&&!(ev.key==='ArrowLeft'&&i%l.width===0)&&!(ev.key==='ArrowRight'&&i%l.width===l.width-1))$('#cell-'+j).focus();return;}const key=ev.key.toLowerCase();if(['b','w','delete','backspace',' '].includes(key)){ev.preventDefault();actCell(i,key==='b'?'black':key==='w'?'white':key===' '?(ev.shiftKey?'reverse':'cycle'):'erase');}});
let hold=null,holdTimer=null;document.addEventListener('pointerdown',ev=>{const b=ev.target.closest('[data-cell]');if(!b||dialog||!clueAt(level(),Number(b.dataset.cell)))return;hold={x:ev.clientX,y:ev.clientY,i:Number(b.dataset.cell),active:false};holdTimer=setTimeout(()=>{if(!hold)return;hold.active=true;preview=hold.i;renderPlay();announce('临时预览四向光臂，松开返回');},300);});
function endHold(){clearTimeout(holdTimer);if(hold&&hold.active){preview=null;suppressCell=hold.i;renderPlay();setTimeout(()=>suppressCell=null,500);}hold=null;}
document.addEventListener('pointermove',ev=>{if(hold&&(Math.abs(ev.clientX-hold.x)>8||Math.abs(ev.clientY-hold.y)>8))endHold();});document.addEventListener('pointerup',endHold);document.addEventListener('pointercancel',endHold);document.addEventListener('scroll',()=>{if(hold)endHold();},true);function adaptText(){document.body.classList.toggle('large-text',parseFloat(getComputedStyle(document.documentElement).fontSize)>=24);}
new MutationObserver(adaptText).observe(document.documentElement,{attributes:true,attributeFilter:['style']});
window.addEventListener('resize',()=>{adaptText();if(page==='play')renderPlay();});adaptText();
let audio=null;function tone(success){if(!data.preferences.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!audio)audio=new AC();if(audio.state==='suspended')audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.frequency.value=success?700:340;gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);osc.start();osc.stop(audio.currentTime+.14);}catch(e){announce('声音不可用，所有测绘反馈仍以文字呈现');}}
async function reloadSaved(){if(busy)return;busy=true;try{const saved=await store.read();data=restore(LEVELS,saved);readBlocked=false;render();await save();announce('已恢复旧存档');}catch(e){readBlocked=true;await save();}finally{busy=false;}}
async function boot(){store=await backend(window);let saved=null;try{saved=await store.read();}catch(e){readBlocked=true;announce('存档读取失败；本页暂不覆盖旧记录。');}data=restore(LEVELS,saved);render();await save();if(!data.seenTutorial)openDialog('tutorial');}boot();
