export const UNKNOWN=-1; export const WHITE=0; export const BLACK=1;
export const RULE_VERSION='range-1';
export function clueAt(l,i){const c=l.clues.find(c=>c[0]===i);return c?c[1]:0;}
export function initial(l){return {marks:Array.from({length:l.width*l.height},(_,i)=>clueAt(l,i)?WHITE:UNKNOWN),moves:0};}
export function adjacent(l,i){const x=i%l.width,y=Math.floor(i/l.width),a=[];if(y)a.push(i-l.width);if(x<l.width-1)a.push(i+1);if(y<l.height-1)a.push(i+l.width);if(x)a.push(i-1);return a;}
export function beam(l,marks,i){if(!clueAt(l,i))return null;const x=i%l.width,y=Math.floor(i/l.width);const arms=[[0,-1],[1,0],[0,1],[-1,0]].map(d=>{const cells=[];let xx=x+d[0],yy=y+d[1];while(xx>=0&&xx<l.width&&yy>=0&&yy<l.height){const p=yy*l.width+xx;if(marks[p]===BLACK)break;cells.push(p);xx+=d[0];yy+=d[1];}return cells;});return {arms,cells:[i].concat(...arms),count:1+arms.reduce((s,a)=>s+a.length,0),target:clueAt(l,i)};}
export function evaluate(l,s){const m=s.marks,n=l.width*l.height;if(!Array.isArray(m)||m.length!==n||m.some((v,i)=>![-1,0,1].includes(v)||(clueAt(l,i)&&v!==WHITE)))return {complete:false,invalid:true,readings:[],pairs:[],groups:[]};const pairs=[];m.forEach((v,i)=>{if(v===BLACK)adjacent(l,i).filter(j=>j>i&&m[j]===BLACK).forEach(j=>pairs.push([i,j]));});const groups=[],seen=new Set();for(let i=0;i<n;i++){if(m[i]===BLACK||seen.has(i))continue;const q=[i];seen.add(i);for(let k=0;k<q.length;k++)adjacent(l,q[k]).forEach(j=>{if(m[j]!==BLACK&&!seen.has(j)){seen.add(j);q.push(j);}});groups.push(q);}const readings=l.clues.map(c=>Object.assign({cell:c[0]},beam(l,m,c[0])));return {complete:readings.every(b=>b.count===b.target)&&!pairs.length&&groups.length===1,readings,pairs,groups,invalid:false};}
export function setMark(l,s,cell,mark){if(!Number.isInteger(cell)||cell<0||cell>=s.marks.length||![-1,0,1].includes(mark)||clueAt(l,cell)||s.marks[cell]===mark)return null;const marks=s.marks.slice(),old=marks[cell];marks[cell]=mark;return {marks,moves:s.moves+((old===BLACK||mark===BLACK)?1:0)};}
export function replay(l,actions){if(!Array.isArray(actions)||actions.length>4096)return null;let s=initial(l);for(const a of actions){if(!a||!Number.isInteger(a.cell)||![-1,0,1].includes(a.mark)||!Number.isInteger(a.selected)||a.selected<0||a.selected>=s.marks.length||!clueAt(l,a.selected))return null;const next=setMark(l,s,a.cell,a.mark);if(!next)return null;s=next;}return s;}
export function validateLevel(l){return l&&Number.isInteger(l.width)&&l.width>=5&&l.width<=6&&Number.isInteger(l.height)&&l.height>=5&&l.height<=6&&Array.isArray(l.clues)&&l.clues.length>=3&&new Set(l.clues.map(c=>c[0])).size===l.clues.length&&l.clues.every(c=>Number.isInteger(c[0])&&c[0]>=0&&c[0]<l.width*l.height&&Number.isInteger(c[1])&&c[1]>=2&&c[1]<=l.width+l.height-1);}
