import {initial,replay,setMark,evaluate,clueAt,RULE_VERSION} from './core.mjs';
export const GAME='sunlit-courtyard-survey';
export const KEY='mini-polish:'+GAME+':v1:save';
export const TUTORIAL='courtyard-guide-1';
function uid(){return 'run-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,12);}
const safe=s=>typeof s==='string'&&/^[a-z0-9-]{4,100}$/.test(s);
export function newRun(l){return {id:uid(),clueHash:l.clueHash,generatorVersion:l.generatorVersion,seed:l.seed,actions:[],selected:l.clues[0][0],hintLevel:0,views:[],completed:false};}
export function fresh(levels){return {version:RULE_VERSION,current:levels[0].id,runs:{},evidence:[],seenTutorial:false,preferences:{sound:false,quiet:false,guide:true},outbox:[],claims:[],xp:0};}
function validRun(l,r){return r&&safe(r.id)&&r.clueHash===l.clueHash&&r.generatorVersion===l.generatorVersion&&r.seed===l.seed&&Array.isArray(r.actions)&&replay(l,r.actions)&&Number.isInteger(r.selected)&&r.selected>=0&&r.selected<l.width*l.height&&clueAt(l,r.selected)&&Number.isInteger(r.hintLevel)&&r.hintLevel>=0&&r.hintLevel<=3;}
export function restore(levels,input){const d=fresh(levels);if(!input||input.version!==RULE_VERSION)return d;d.current=levels.some(l=>l.id===input.current)?input.current:d.current;d.seenTutorial=input.tutorialVersion===TUTORIAL;d.tutorialVersion=d.seenTutorial?TUTORIAL:null;if(input.preferences){['sound','quiet','guide'].forEach(k=>{if(typeof input.preferences[k]==='boolean')d.preferences[k]=input.preferences[k];});}
 levels.forEach(l=>{const r=input.runs&&Object.prototype.hasOwnProperty.call(input.runs,l.id)?input.runs[l.id]:null;if(validRun(l,r)){d.runs[l.id]={id:r.id,clueHash:l.clueHash,generatorVersion:l.generatorVersion,seed:l.seed,actions:r.actions.map(a=>({cell:a.cell,mark:a.mark,selected:a.selected})),selected:r.selected,hintLevel:r.hintLevel,views:Array.isArray(r.views)?r.views.filter(i=>Number.isInteger(i)&&clueAt(l,i)).slice(0,4096):[],completed:evaluate(l,replay(l,r.actions)).complete};}});
 const ids=new Set();if(Array.isArray(input.evidence))input.evidence.forEach(e=>{const l=levels.find(l=>l.id===e.levelId);if(!l||!validRun(l,e.run)||!evaluate(l,replay(l,e.run.actions)).complete||ids.has(e.run.id))return;ids.add(e.run.id);const prior=d.evidence.filter(p=>p.levelId===l.id);if(prior.length&&e.run.hintLevel>=Math.min(...prior.map(p=>p.run.hintLevel)))return;d.evidence.push({levelId:l.id,generatorVersion:l.generatorVersion,seed:l.seed,clueHash:l.clueHash,run:JSON.parse(JSON.stringify(e.run))});});
 rebuild(levels,d);const pending=new Set(Array.isArray(input.outbox)?input.outbox.map(e=>e.completionId):[]);d.outbox=d.evidence.filter(e=>pending.has(GAME+':'+e.levelId+':'+e.run.id)).map(e=>payload(e));return d;}
export function state(l,r){return replay(l,r.actions)||initial(l);}
export function ensure(l,d){if(!d.runs[l.id])d.runs[l.id]=newRun(l);return d.runs[l.id];}
export function mark(l,d,cell,value){let r=ensure(l,d),s=state(l,r);if(r.actions.length>=4096)return false;const next=setMark(l,s,cell,value);if(!next)return false;if(r.completed&&(s.marks[cell]===1||value===1)){r=Object.assign({},r,{id:uid(),actions:r.actions.slice(),completed:false});d.runs[l.id]=r;}r.actions.push({cell,mark:value,selected:r.selected});r.completed=evaluate(l,next).complete;return true;}
export function undo(l,d){let r=ensure(l,d);if(!r.actions.length)return false;const old=state(l,r),a=r.actions[r.actions.length-1];if(r.completed&&(old.marks[a.cell]===1||state(l,{actions:r.actions.slice(0,-1)}).marks[a.cell]===1)){r=Object.assign({},r,{id:uid(),actions:r.actions.slice(),completed:false});d.runs[l.id]=r;}r.actions.pop();r.selected=a.selected;r.completed=evaluate(l,state(l,r)).complete;return true;}
export function restart(l,d){d.runs[l.id]=newRun(l);}
export function payload(e){return {gameId:GAME,levelId:e.levelId,generatorVersion:e.generatorVersion,seed:e.seed,clueHash:e.clueHash,ruleVersion:RULE_VERSION,completionId:GAME+':'+e.levelId+':'+e.run.id,runId:e.run.id,hintLevel:e.run.hintLevel,rewardClaimId:GAME+':first:'+e.levelId};}
function rebuild(levels,d){const done=new Set(d.evidence.map(e=>e.levelId));d.claims=[...done].map(id=>GAME+':first:'+id);for(let ch=1;ch<=6;ch++)if(levels.filter(l=>l.chapter===ch).every(l=>done.has(l.id)))d.claims.push(GAME+':chapter:'+ch);d.xp=done.size*10;}
export function settle(levels,l,d){const r=ensure(l,d);if(!evaluate(l,state(l,r)).complete)return null;r.completed=true;if(d.evidence.some(e=>e.run.id===r.id))return null;const prior=progress(d,l.id);if(prior.length&&r.hintLevel>=Math.min(...prior.map(e=>e.run.hintLevel)))return null;const e={levelId:l.id,generatorVersion:l.generatorVersion,seed:l.seed,clueHash:l.clueHash,run:JSON.parse(JSON.stringify(r))};d.evidence.push(e);rebuild(levels,d);const event=payload(e);d.outbox.push(event);return event;}
export function progress(d,id){return d.evidence.filter(e=>e.levelId===id);}
export function hint(l,r,level){const s=state(l,r);const t=l.logic.find(t=>t.mark===1?s.marks[t.cell]!==1:s.marks[t.cell]!==0);if(!t)return null;const idx=l.logic.indexOf(t),xy=i=>`${Math.floor(i/l.width)+1}行${i%l.width+1}列`,where=xy(t.cell),source=t.reason.source,sourceText=source===undefined?'':xy(source);let reason='';if(t.reason.type==='reading')reason=`${sourceText}的数字为${clueAt(l,source)}。把四臂所有可行长度分配逐一对照，剩下${t.reason.possibilities}种，都要求${where}${t.mark?'放遮屏':'保持白地'}。`;if(t.reason.type==='spacing')reason=`已推得${sourceText}必须放遮屏，${where}与它共边，所以必须白。`;if(t.reason.type==='bridge')reason=`${where}是连接已确定白格的必经桥。若放遮屏，白地会分成无法正交相通的区域，所以必须白。`;
 const premises=l.logic.slice(0,idx).filter(p=>p.mark===1?s.marks[p.cell]!==1:s.marks[p.cell]===1).map(p=>xy(p.cell)+(p.mark?'屏':'白')).slice(-8);
 return {cell:t.cell,mark:t.mark,source,level,text:level===1?(source===undefined?'先检查全局白路：角点相触不算连通。':`先查看${sourceText}的${t.reason.type==='spacing'?'遮屏四邻':'四臂读数'}，再对照已确定白地。`):reason,premises,originalOnly:true};}
