import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { LEVEL, SIZE, TUTORIAL, cagePossible, cageSatisfied, countSolutions, createState, evaluate, isComplete, normalizeState, setCell, stateFromValues, tutorialSvg, undo } from "./logic.mjs";

let checks = 0;
const check = (condition, message) => { assert.ok(condition, message); checks += 1; };
const here = path.dirname(fileURLToPath(import.meta.url));

check(SIZE === 4, "fixed mobile board is 4×4");
check(LEVEL.cages.length === 8 && new Set(LEVEL.cages.flatMap((cage) => cage.cells)).size === 16, "arithmetic cages partition every cell once");
check(new Set(LEVEL.cages.map((cage) => cage.op)).size === 4, "fixture includes add, multiply, subtract and divide cages");
check(countSolutions(LEVEL, 2) === 1, "independent Latin/cage backtracker proves the fixed board has one solution");

let state = createState();
check(!isComplete(state) && !evaluate(LEVEL, state).complete, "empty but conflict-free board never wins");
state = setCell(state, 0, 1);
check(state.moves === 1 && state.values[0] === 1 && evaluate(LEVEL, state).errors.length === 0, "tutorial fill:0:1 is a legal conflict-free operation");
check(cagePossible(LEVEL.cages[0], state.values), "partial tutorial cage can still reach its target");
const changed = setCell(state, 0, 4);
check(evaluate(LEVEL, changed).errors.some((entry) => entry.type === "cage"), "impossible partial arithmetic cage is reported");
check(undo(state).values[0] === 0 && undo(state).moves === 0, "undo restores both board and move count");
const solved = stateFromValues(LEVEL.solution, 15);
check(isComplete(solved) && LEVEL.cages.every((cage) => cageSatisfied(cage, solved.values)), "fixed solution satisfies all Latin and arithmetic rules");
check(!isComplete(stateFromValues([...LEVEL.solution.slice(0, 15), 0], 14)), "one blank cell cannot claim completion");
check(normalizeState({ values: Array(16).fill(9), moves: 0 }) === null, "corrupt persisted values are rejected so the kit creates only this game's fresh state");
check(TUTORIAL.actionState.values[0] === 1 && isComplete(TUTORIAL.solved), "three tutorial states are regenerated by the rule engine");
for (const [state, stage] of [[TUTORIAL.initial, "elements"], [TUTORIAL.actionState, "action"], [TUTORIAL.solved, "complete"]]) {
  const svg = tutorialSvg(state, stage);
  check(svg.includes('<svg') && svg.includes('data-tutorial-game="quantum-apothecary"') && svg.includes(`data-stage="${stage}"`), `${stage} runtime SVG is self-contained`);
}
check(tutorialSvg(TUTORIAL.actionState, "action").includes('data-action="fill:0:1"'), "runtime action SVG names engine action");
check(tutorialSvg(TUTORIAL.solved, "complete").includes('data-complete="true"'), "runtime goal SVG records true completion");

const [html, app, css] = await Promise.all(["index.html", "app.mjs", "styles.css"].map((name) => readFile(path.join(here, name), "utf8")));
check(html.includes('data-realm="quantum-apothecary"') && html.includes('href="../../"'), "entry retains V4 realm identity and return path");
check(html.includes('../../shared/realm-ui.css') && html.includes('../../shared/game-kit.css') && html.includes('../../shared/realm-ui.mjs'), "entry includes frozen V4 shared contracts");
check(app.includes("mountPuzzle") && app.includes("tutorialSvg"), "app uses kit and rule-derived SVG tutorial cards");
check(css.includes("min-height: 44px") && css.includes("@media (max-width: 480px)"), "touch controls and narrow-phone layout meet baseline");

console.log(`Quantum Apothecary: ${checks} assertions passed.`);
