import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {oracle,canonical} from '../scripts/oracle.mjs';
const ctx=vm.createContext({});for(const f of ['engine','storage','levels','view','tutorial'])vm.runInContext(fs.readFileSync(`src/${f}.js`,'utf8'),ctx);const E=ctx.LoomEngine,S=ctx.LoomStorage,levels=ctx.LoomLevels,p=levels[0],plain=v=>JSON.parse(JSON.stringify(v));const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};};function finish(s,p){const sol=oracle(p.givens,p.n).solutions[0];p.givens.forEach((v,i)=>{if(v===-1)s.events.push([i,sol[i]]);});return s;}
test('all 72 puzzles unique under independent second-solution row search, no 16-way isomorphs',()=>{assert.equal(levels.length,72);const keys=new Set();for(const p of levels){const result=oracle(p.givens,p.n);assert.equal(result.solutions.length,1,p.id);assert(E.analyze(result.solutions[0],p.n).complete);const key=p.n+canonical(p.givens,p.n);assert(!keys.has(key),p.id);keys.add(key);let a=E.fresh(p),steps=0;while(a.includes(-1)){const h=E.deduction(a,p.n);assert(h,p.id);a=E.move(p,a,h.i,h.v);assert(a);steps++;assert(steps<37);}assert(E.analyze(a,p.n).complete);}});
test('engine and oracle agree on all 4x4 complete binary boards, including duplicate rows',()=>{let valid=0;for(let bits=0;bits<65536;bits++){const a=Array.from({length:16},(_,i)=>(bits>>i)&1);const actual=E.analyze(a,4).complete,expected=oracle(a,4,1).solutions.length===1;assert.equal(actual,expected,'bits '+bits);if(actual)valid++;}assert(valid>0);assert(E.analyze([0,0,1,1,0,0,1,1,1,1,0,0,1,1,0,0],4).complete);});
test('atomic invalid moves, immutable givens, conflicts, incomplete and replay',()=>{const a=E.fresh(p),fixed=p.givens.findIndex(v=>v!==-1),empty=p.givens.indexOf(-1),before=JSON.stringify(a);for(const [i,v] of [[fixed,1-p.givens[fixed]],[-1,1],[16,0],[empty,2],[empty,-1]])assert.equal(E.move(p,a,i,v),null);assert.equal(JSON.stringify(a),before);assert(!E.analyze(a,4).complete);assert(!E.analyze(Array(16).fill(1),4).valid);assert.equal(E.replay(p,[[fixed,0]]),null);assert.equal(E.replay(p,[[empty,0],[empty,0]]),null);const b=E.move(p,a,empty,0);assert.equal(b[empty],0);assert.deepEqual(plain(E.replay(p,[[empty,0]])),plain(b));});
test('tutorial SVG truth chain from same immutable puzzle and real action',()=>{const t=ctx.LoomTutorial;assert.equal(t.puzzle.id,'daynight-scroll-tutorial-v1');assert.deepEqual(plain(E.move(t.puzzle,t.states[0],t.hint.i,t.hint.v)),plain(t.states[1]));assert(E.analyze(t.states[1],4).valid);assert(E.analyze(t.states[2],4).complete);assert.equal(oracle(t.states[0],4).solutions.length,1);for(let i=0;i<3;i++){const svg=fs.readFileSync(`dist/xhs/assets/tutorial-${i}.svg`,'utf8');assert(svg.includes('viewBox="0 0 256 256"'));assert(svg.includes('data-cells="'+t.states[i].join(',')+'"'));assert.equal((svg.match(/data-cell=/g)||[]).length,16);}});
test('reload replays sessions and rewards, corruption never accepts completion flags',()=>{const store=memory(),data=S.blank(),s=S.session(p,'chapter','');data.sessions[p.id]=s;assert(S.save(store,data));assert.equal(S.load(store,levels).sessions[p.id].events.length,0);const forged=plain(data);forged.completed[p.id]=plain(s);assert.equal(Object.keys(S.normalize(forged,levels).completed).length,0);forged.sessions[p.id].events=[[999,1]];assert.equal(Object.keys(S.normalize(forged,levels).sessions).length,0);store.setItem(S.KEY,'{bad');store.setItem('another-game','keep');assert.equal(Object.keys(S.load(store,levels).sessions).length,0);assert.equal(store.getItem('another-game'),'keep');});
test('completion persisted before host, retry stable, replay/restart no duplicate claim',()=>{const store=memory(),data=S.blank(),s=finish(S.session(p,'chapter',''),p);data.sessions[p.id]=s;assert(S.settle(data,s,p,store).persisted);const payload=plain(data.outbox[0]);S.settle(data,s,p,store);S.settle(data,finish(S.session(p,'chapter',''),p),p,store);assert.equal(Object.keys(data.completed).length,1);assert.equal(data.outbox.length,1);S.flush(data,store,()=>{assert.equal(JSON.parse(store.getItem(S.KEY)).outbox.length,1);throw Error('host offline');});assert.deepEqual(plain(data.outbox[0]),payload);const restored=S.load(store,levels);assert.equal(Object.keys(restored.completed).length,1);S.flush(restored,store,x=>{assert.equal(x.completionId,payload.completionId);return true;});assert.equal(restored.outbox.length,0);});
test('storage failure preserves playable victory without premature host call',()=>{const fail={setItem(){throw Error('quota');}},data=S.blank(),s=finish(S.session(p,'chapter',''),p);assert(S.settle(data,s,p,fail).complete);assert.equal(S.settle(data,s,p,fail).persisted,false);S.flush(data,fail,()=>{assert.fail('must persist first');});});
test('daily seed stable and distinct claim; hint conflict does not change cells',()=>{assert.equal(E.daily('2026-09-13',72),E.daily('2026-09-13',72));for(let i=1;i<31;i++){const x=E.daily('2026-09-'+String(i).padStart(2,'0'),72);assert(x>=0&&x<72);}const a=Array(16).fill(0),before=JSON.stringify(a);assert.equal(E.hint(a,4).i,undefined);assert.equal(JSON.stringify(a),before);assert.equal(S.claim(S.session(p,'daily','2026-09-13')),'daily:2026-09-13');});
test('chapter introductions and within-chapter progression match verified deduction traces',()=>{const report=JSON.parse(fs.readFileSync('release/level-proof.json'));for(let ch=1;ch<=6;ch++){const group=report.levels.slice((ch-1)*12,ch*12);assert(group[0].logicSteps<group[11].logicSteps);for(const x of group.slice(0,2)){if(ch===1)assert(x.trace.every(h=>h.kind==='triple'));if(ch===2){assert.equal(x.trace[0].kind,'sandwich');assert(x.trace.every(h=>h.kind!=='balance'));}if(ch===3)assert.equal(x.trace[0].kind,'balance');}}});
