import fs from 'node:fs';import vm from 'node:vm';import {shapes,solve,boundary,canonical} from './oracle.mjs';
vm.runInThisContext(fs.readFileSync(new URL('../core.js',import.meta.url),'utf8'));const C=globalThis.HoneyCore;
let seed=7112026;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function tile(n,k){const all=shapes(n,k),by=Array.from({length:n*n},()=>[]);all.forEach(s=>s.cells.forEach(i=>by[i].push(s)));const full=(1n<<BigInt(n*n))-1n;let nodes=0;function search(used,path){if(++nodes>10000)return null;if(used===full)return path;let opts=null;for(let i=0;i<by.length;i++)if(!(used&(1n<<BigInt(i)))){const a=by[i].filter(s=>!(used&s.mask));if(!a.length)return null;if(!opts||a.length<opts.length)opts=a;if(a.length===1)break;}for(const s of shuffle(opts)){const v=search(used|s.mask,path.concat([s.cells]));if(v)return v;}return null;}return search(0n,[]);}
const chapterNames=['蜜田初巡','篱边留门','四格一家','花带新田','六篱长坡','丰收巡界'];const names=['第一张田契','角上的两道篱','共享的短篱','两格的约定','花影小径','北坡留门','转角的土块','田边木尺','四处花香','初巡归来','已足的数字','留一扇门','墙边相传','奶油纸签','并排小田','轻雨田径','短篱之间','逐格对照','蜜色日光','留门札记','满田不再扩','不凭角相接','折向花带','绕过一片花','四格同契','围而不碎','花田回廊','一处窄口','纸上田形','四格归家','五格的新田','花带初展','长形土田','纸边压花','五步花径','细长的田契','南坡折角','曲折仍相连','完整一块田','新田巡毕','六格长坡','精确的边向','长坡开口','篱桩两端','容量木尺','北田折线','六格同纹','坡上小门','连通的花影','长坡田契','丰收的起点','数与形相合','山坡的缺口','完整的界线','长坡上的六块田','绕行的小田','最后的通路','花带交织','季末巡田','一庄蜜香'];
function logical(l){let s=C.fresh(l),trace=[];const sets=shapes(l.n,l.k).filter(g=>g.cells.every((i,j)=>l.clues[i]===null||l.clues[i]===g.counts[j]));while(!C.solved(l,s)){let a=C.deduction(l,s);if(!a){const candidates=sets.filter(g=>C.edges(l).every(key=>{const [u,v]=C.adjacent(l,key),inside=g.cells.includes(u),other=g.cells.includes(v);return s.edges[key]===1?!(inside&&other):s.edges[key]===2?inside===other:true;}));for(let i=0;i<l.n*l.n&&!a;i++){const domain=candidates.filter(g=>g.cells.includes(i));if(!domain.length)break;for(let d=0;d<4&&!a;d++){const key=C.side(l,i,d);if(!key||s.edges[key]!==0)continue;const [u,v]=C.adjacent(l,key),j=u===i?v:u,values=domain.map(g=>g.cells.includes(j));if(values.every(v=>v===values[0]))a={key,value:values[0]?2:1,cell:i,type:'region-domain',reason:'把数字与每区 '+l.k+' 格一起核对，这格所有可行连通田形都要求此边'+(values[0]?'无墙。':'立篱。')};}}}if(!a)break;s=C.set(l,s,a.key,a.value);trace.push(a);}return {state:s,trace,complete:C.solved(l,s)};}
const levels=[],proofs=[],seen=new Set(),seenPartition=new Set();for(let ch=0;ch<6;ch++){const n=ch<3?4:ch===3?5:6,k=n;let attempts=0,got=0;const chapterPartitions=new Set();while(got<10&&attempts++<20000){const before=seed,p=tile(n,k);if(!p)continue;const pk=canonical(n,p);if(chapterPartitions.has(pk))continue;const solution=boundary(n,p),stub={n,k,clues:Array(n*n).fill(null)},state={edges:solution,moves:0};let clues=stub.clues.map((_,i)=>C.count(stub,state,i));let l={n,k,clues};let proof=solve(l);if(proof.truncated||proof.solutions.length!==1||!logical(l).complete)continue;
const removeTarget=ch===0?Math.floor(got/4):ch===1?3+Math.floor(got/3):ch===2?6+Math.floor(got/4):ch===3?3+Math.floor(got/2):ch===4?5+Math.floor(got/2):10+Math.floor(got/2);let removed=0;for(const i of shuffle(Array.from({length:n*n},(_,i)=>i))){if(removed>=removeTarget)break;const old=clues[i];clues[i]=null;const q=solve(l);if(!q.truncated&&q.solutions.length===1&&logical(l).complete)removed++;else clues[i]=old;}
const canon=canonical(n,p,clues);if(seen.has(canon))continue;const idx=levels.length;const logic=logical(l);proof=solve(l);l={id:'hf-'+String(idx+1).padStart(2,'0'),chapter:ch+1,name:names[idx],n,k,clues:clues.slice(),solution,seed:before,generatorVersion:'hf-gen-1',focus:ch<2?'数字与共享边':ch===2?'容量与折角连通':ch===3?'五格连通区':ch===4?'六格与精确选边':'数字、容量与连通综合',hintTrace:logic.trace};levels.push(l);proofs.push({id:l.id,solutions:1,exhaustive:proof.exhaustive,nodes:proof.nodes,candidates:proof.candidates,logicSteps:logic.trace.length,strategies:logic.trace.reduce((o,a)=>(o[a.type]=(o[a.type]||0)+1,o),{}),clues:clues.filter(v=>v!==null).length,canonical:canon,partitionCanonical:pk,seed:before});seen.add(canon);seenPartition.add(pk);chapterPartitions.add(pk);got++;console.log(l.id,n,proof.nodes,removed,logic.trace.length);}
if(got!==10)throw Error('insufficient chapter '+ch+' got '+got);}
fs.writeFileSync(new URL('../levels.js',import.meta.url),'(function(root){root.HoneyLevels='+JSON.stringify(levels)+';root.HoneyChapters='+JSON.stringify(chapterNames)+';})(typeof window!=="undefined"?window:globalThis);\n');fs.writeFileSync(new URL('../release/level-proofs.json',import.meta.url),JSON.stringify({method:'independent connected-K-set exact cover; exhaustive search for second solution; no reference solution input',levels:proofs},null,2));
