import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';import {server} from './serve.mjs';import {LEVELS} from '../src/levels.mjs';
const host=await server(0);const port=host.address().port;const url='http://127.0.0.1:'+port;const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const reports=[],errors=[],external=[];
async function shot(page,options){await page.waitForFunction(()=>Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0));await page.screenshot(options);}
const key='mini-polish:dream-isle-hotel:v1:save';
async function layout(page,label){const m=await page.evaluate(()=>{const all=Array.from(document.querySelectorAll('button')).filter(b=>b.getBoundingClientRect().width&& !b.closest('[hidden]'));return {width:innerWidth,scroll:document.documentElement.scrollWidth,small:all.filter(b=>{const r=b.getBoundingClientRect();return r.width<43.9||r.height<43.9;}).map(b=>({text:b.textContent,label:b.getAttribute('aria-label'),w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height})),modalOverflow:document.querySelector('.dialog')?document.querySelector('.dialog').scrollWidth>document.querySelector('.dialog').clientWidth:false};});assert.ok(m.scroll<=m.width,label+' horizontal overflow');assert.deepEqual(m.small,[],label+' small targets');assert.equal(m.modalOverflow,false);reports.push({label,viewport:m.width,status:'PASS'});}
async function clickRoom(page,p,r){await page.locator('[data-cell="'+(r.y*p.n+r.x)+'"]').click();await page.locator('[data-cell="'+((r.y+r.h-1)*p.n+r.x+r.w-1)+'"]').click();await page.locator('[data-action="confirm"]').click();}
try{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith(url))external.push(r.url());});await page.goto(url);await layout(page,'home');await shot(page,{path:'release/home-mobile.png',fullPage:true});
 await page.locator('[data-action="continue"]').click();await page.locator('.tutorial-img').waitFor();await layout(page,'first tutorial');await shot(page,{path:'release/tutorial-mobile.png'});await page.locator('[data-action="close"]').click();await page.locator('[data-action="tutorial"]').click();await page.locator('[data-action="tutorial-next"]').click();await page.locator('[data-action="tutorial-next"]').click();await page.locator('[data-action="tutorial-next"]').click();assert.equal(await page.locator('#modal').isVisible(),false);
 const p=LEVELS[0],r=p.answer[0];await clickRoom(page,p,r);assert.equal(await page.locator('#board-image [data-room]').count(),1);await shot(page,{path:'release/gameplay-mobile.png'});
 await page.reload();await page.locator('[data-action="continue"]').click();assert.equal(await page.locator('#board-image [data-room]').count(),1);
 await page.locator('[data-action="undo"]').click();assert.equal(await page.locator('#board-image [data-room]').count(),0);
 await clickRoom(page,p,r);await page.locator('[data-cell="'+(r.y*p.n+r.x)+'"]').click();await page.locator('[data-action="remove"]').click();assert.equal(await page.locator('#board-image [data-room]').count(),0);
 await page.locator('[data-action="undo"]').click();assert.equal(await page.locator('#board-image [data-room]').count(),1);
 for(const room of p.answer.slice(1))await clickRoom(page,p,room);
 await page.locator('.win').waitFor();await shot(page,{path:'release/completion-mobile.png'});const saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);assert.equal(Object.keys(saved.records).length,1);assert.equal(saved.outbox.length,1);
 await page.locator('[data-action="close"]').click();await page.locator('[data-action="restart"]').click();await page.locator('[data-action="restart-yes"]').click();for(const room of p.answer)await clickRoom(page,p,room);assert.equal(await page.evaluate(k=>Object.keys(JSON.parse(localStorage.getItem(k)).records).length,key),1);assert.equal(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).outbox.length,key),1);
 await page.locator('[data-action="win-back"]').click();await page.locator('[data-level="'+LEVELS[59].id+'"]').count();await page.locator('[data-action="home"]').click();await page.locator('[data-chapter="5"]').click();await page.locator('[data-level="'+LEVELS[59].id+'"]').click();
 for(const width of [320,349,350,351,390,479,480,481,759,760,761,1280]){await page.setViewportSize({width,height:width===390?844:720});await page.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');});await layout(page,'max board safe area '+width);await shot(page,{path:'release/qa-board-'+width+'.png',fullPage:true});await page.locator('[data-action="tutorial"]').click();await layout(page,'tutorial safe area '+width);await page.keyboard.press('Tab');await page.keyboard.press('Escape');assert.equal(await page.locator('#modal').isVisible(),false);assert.equal(await page.evaluate(()=>document.activeElement.textContent),'玩法');}
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.locator('[data-action="hint"]').click();await page.locator('[data-action="hint-apply"]').click();assert.equal(await page.locator('#board-image [data-room]').count(),1);await page.locator('[data-action="note"]').click();await page.locator('[data-cell="0"]').focus();await page.keyboard.press('Enter');await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await page.locator('[data-action="confirm"]').click();assert.equal(await page.locator('.note').count(),1);
 await page.locator('[data-action="back"]').click();await page.locator('[data-action="home"]').click();await page.locator('[data-action="daily"]').click();assert.ok((await page.locator('.play-head').textContent()).includes('今日房型'));
 await page.locator('[data-action="back"]').click();await page.locator('[data-action="home"]').click();await page.locator('[data-action="collection"]').click();await layout(page,'collection');
 // Actual pointer drag, cancelled preview, invalid placement, and denied storage.
 await page.locator('[data-action="home"]').click();await page.locator('[data-chapter="0"]').click();await page.locator('[data-level="'+LEVELS[1].id+'"]').click();
 const dragRoom=LEVELS[1].answer.find(r=>r.w*r.h>1),da=await page.locator('[data-cell="'+(dragRoom.y*LEVELS[1].n+dragRoom.x)+'"]').boundingBox(),db=await page.locator('[data-cell="'+((dragRoom.y+dragRoom.h-1)*LEVELS[1].n+dragRoom.x+dragRoom.w-1)+'"]').boundingBox();
 await page.mouse.move(da.x+da.width/2,da.y+da.height/2);await page.mouse.down();await page.mouse.move(db.x+db.width/2,db.y+db.height/2,{steps:5});await page.mouse.up();assert.equal(await page.locator('[data-preview]').count(),1);await page.locator('[data-action="cancel"]').click();assert.equal(await page.locator('[data-preview]').count(),0);
 await page.locator('[data-cell="0"]').click();await page.locator('[data-cell="'+(LEVELS[1].n*LEVELS[1].n-1)+'"]').click();await page.locator('[data-action="confirm"]').click();assert.equal(await page.locator('#board-image [data-room]').count(),0);assert.ok((await page.locator('#message').textContent()).length>0);
 const denied=await browser.newContext({viewport:{width:320,height:720}});await denied.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('test quota');};});const dp=await denied.newPage();dp.on('pageerror',e=>errors.push(e.message));await dp.goto(url);assert.equal(await dp.locator('.save-warning').count(),1);await dp.locator('[data-action="continue"]').click();await dp.locator('[data-action="close"]').click();for(const room of p.answer)await clickRoom(dp,p,room);assert.equal(await dp.locator('.win').count(),1);assert.equal(await dp.locator('.win .save-warning').count(),1);await denied.close();
 await page.evaluate(k=>localStorage.setItem(k,'{broken'),key);await page.reload();assert.ok((await page.locator('.pill').textContent()).includes('0 / 60'));await page.locator('[data-action="continue"]').click();assert.equal(await page.locator('#board-image [data-room]').count(),0);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);writeFileSync('release/browser-qa.json',JSON.stringify({status:'PASS',browser:await browser.version(),viewports:[320,349,350,351,390,479,480,481,759,760,761,1280],safeArea:{top:44,bottom:34},reports,errors,externalRequests:external,flows:['first tutorial','skip/reopen/complete','place/remove/undo','refresh replay','win/repeat dedupe','hint confirm','keyboard notes','daily','collection','reduced motion','drag/cancel','illegal atomic placement','storage denied still playable','corrupt storage fallback'],limits:['Desktop Chromium emulation only','No actual iOS/Android/Chrome61/XHS container']},null,2));console.log('Browser QA passed:',reports.length,'layout cases and interaction flows.');
}finally{await browser.close();await new Promise(r=>host.close(r));}
