(function(S){
'use strict';
const $=id=>document.getElementById(id),levels=S.levels;
let data=S.fresh(),p=levels[0],state=S.blank(),selected=0,core=0,store,queue=Promise.resolve(),focusBefore=null,closeAction=null,modalOpen=false,chapterTab=0;
function message(t,success){$('message').textContent=t;$('message').className='message'+(success?' success':'');}
function snapshot(){return JSON.parse(JSON.stringify(data));}
function persist(){const saved=snapshot();queue=queue.then(async()=>{const ok=await store.write(saved);$('saveStatus').textContent=ok?'已保存 · 随时离开，下次继续':'暂时无法保存，请保持页面打开；稍后操作会重试。';return ok;}).catch(()=>false);return queue;}
async function settle(){if(!S.evaluate(p,state).complete)return;const session=data.sessions[p.id];const first=S.complete(data,p,state,session);render();message(first?'这片星园开花了。已收入图鉴 ✧':'这片星园再次开花了 ✧',true);const ok=await persist();if(ok){const host=window.starbudHost&&window.starbudHost.onComplete;if(typeof host==='function'){await S.flush(data,async()=>persist(),e=>host(e));}}}
function remember(){data.sessions[p.id].actions=state.actions;persist();}
function start(index){if(modalOpen)closeModal();data.current=index;p=levels[index];let session=data.sessions[p.id];if(!session){session={runId:S.uid(),actions:[],hints:0};data.sessions[p.id]=session;}state=S.replay(p,session.actions);selected=0;core=0;fillSelects();render();message(S.evaluate(p,state).complete?'这片星园已完成，可重玩或前往下一关。':'先选一格，再按上、下、左、右画边。');persist();}
function fillSelects(){['row','col'].forEach(id=>{$(id).innerHTML=Array.from({length:id==='row'?p.h:p.w},(_,i)=>'<option value="'+i+'">'+(i+1)+'</option>').join('');});$('core').innerHTML=p.cores.map((c,i)=>'<option value="'+i+'">'+(i+1)+'号 · '+(c.x%2&&c.y%2?'格心':(c.x%2===0&&c.y%2===0?'角点':'边心'))+'</option>').join('');}
function edgeFor(dir){const r=Math.floor(selected/p.w),c=selected%p.w;const target=dir==='up'?(r?selected-p.w:-1):dir==='down'?(r<p.h-1?selected+p.w:-1):dir==='left'?(c?selected-1:-1):(c<p.w-1?selected+1:-1);return target<0?null:S.key(selected,target);}
function render(){const ev=S.evaluate(p,state),count=Object.keys(data.completed).length;$('board').innerHTML=S.render(p,state,{interactive:true,selected,core});$('chapterLabel').textContent='第'+p.chapter+'章 · '+S.chapters[p.chapter-1];$('levelMeta').textContent=String(data.current+1).padStart(2,'0')+' / 60 · '+p.stage;$('levelTitle').textContent=p.title;$('lesson').textContent=p.lesson;$('regionStatus').textContent=ev.validCount+' / '+p.cores.length+' 片花园已成形';$('sizeLabel').textContent=p.w+' × '+p.h;$('collectionCount').textContent=count+' / 60';$('meterFill').style.width=count/60*100+'%';$('favorite').setAttribute('aria-pressed',String(data.favorites.includes(p.id)));$('favorite').textContent=data.favorites.includes(p.id)?'♥':'♡';$('undo').disabled=!state.actions.length;$('next').textContent=data.current===59?'星园图鉴 ✧':'下一关 →';$('row').value=Math.floor(selected/p.w);$('col').value=selected%p.w;$('core').value=core;document.querySelectorAll('[data-dir]').forEach(b=>{const id=edgeFor(b.dataset.dir),e=S.edges(p).find(e=>e.id===id);b.disabled=!e||!e.legal;b.classList.toggle('on',state.walls.includes(id));});document.body.classList.toggle('reduced',data.reduced);}
function move(action){if(S.evaluate(p,state).complete){message('这一局已完成，重开后可以再画。');return;}const next=S.act(p,state,action);if(next===state){message('这里不能这样标记：星核周围不能切开，笔记也不能落到星核上。');return;}state=next;remember();render();if(S.evaluate(p,state).complete)settle();else message(action.type==='note'?'已更新成对笔记；笔记不参与通关。':'边界已更新。每一园需连通、恰含一核并旋转对称。');}
function modal(title,html,buttons,onClose){if(!modalOpen)focusBefore=document.activeElement;modalOpen=true;closeAction=onClose||null;$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modalBody').scrollTop=0;$('modalActions').innerHTML='';(buttons||[]).forEach(o=>{const b=document.createElement('button');b.textContent=o.text;if(o.primary)b.className='primary';b.addEventListener('click',o.action);$('modalActions').appendChild(b);});$('overlay').hidden=false;document.body.classList.add('locked');$('closeModal').focus();}
function closeModal(){if(!modalOpen)return;modalOpen=false;$('overlay').hidden=true;document.body.classList.remove('locked');const cb=closeAction;closeAction=null;if(cb)cb();if(focusBefore&&document.contains(focusBefore))focusBefore.focus();}
function tutorial(step){const descriptions=['花园必须完整铺满棋盘，每片只含一颗星核。星核可能落在格心、边心或角点。','先选左上格，再点“右”边。这是一次真实画边：浅绿粗线是边界，细网格不是。','完成后，每片花园都正交连通，并绕自己的星核旋转 180° 后重合。点号笔记永远不算正式边界。'];const states=S.tutorialStates();modal('三步，认识一座星园','<p class="step-label">FIELD GUIDE / 0'+(step+1)+'</p><div class="tutorial-picture">'+S.render(S.tutorial,states[step],{selected:step===1?0:undefined})+'</div><p class="tutorial-copy">'+descriptions[step]+'</p>',[{text:'跳过',action:closeModal},{text:step<2?'下一张 →':'进入花园',primary:true,action:()=>step<2?tutorial(step+1):closeModal()}],()=>{data.tutorial=S.TUTORIAL;persist();});}
function chapters(ch){chapterTab=ch;const done=Object.keys(data.completed).length;modal('花园地图','<p>已开花 '+done+' / 60 · 每章十关，全部可自由选择</p><div class="chapter-tabs">'+S.chapters.map((c,i)=>'<button data-chapter="'+i+'" class="'+(i===ch?'active':'')+'">'+(i+1)+' · '+c+'</button>').join('')+'</div><div class="level-grid">'+levels.slice(ch*10,ch*10+10).map((l,i)=>'<button data-level="'+(ch*10+i)+'" class="'+(data.completed[l.id]?'done':'')+'">'+(data.completed[l.id]?'✧ ':String(ch*10+i+1).padStart(2,'0'))+'<small>'+l.title+'</small></button>').join('')+'</div><p class="small">前 2 关认识概念 · 中 6 关组合 · 后 2 关综合</p>',[{text:'每日星圃',action:daily},{text:'星园图鉴',action:collection},{text:'设置',action:settings}]);$('modalBody').querySelectorAll('[data-chapter]').forEach(b=>b.addEventListener('click',()=>chapters(Number(b.dataset.chapter))));$('modalBody').querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>start(Number(b.dataset.level))));}
function daily(){const d=new Date(),day=Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/86400000);start(day%levels.length);message('每日星圃 · 按设备本地日期从 60 关循环选取，与主线共享进度。');}
function collection(){modal('星园图鉴','<p>已开花 '+Object.keys(data.completed).length+' / 60 · 星花来自真实通关</p><div class="collection-grid">'+levels.map((l,i)=>'<div class="collection-item '+(data.completed[l.id]?'':'locked')+'"><svg viewBox="0 0 80 80" aria-hidden="true">'+S.flower(40,40,22,S.palette[(l.chapter-1)%6],null)+'</svg><button data-visit="'+i+'">'+(i+1)+(data.favorites.includes(l.id)?' ♥':'')+'</button></div>').join('')+'</div>',[{text:'回到花园',primary:true,action:closeModal}]);$('modalBody').querySelectorAll('[data-visit]').forEach(b=>b.addEventListener('click',()=>start(Number(b.dataset.visit))));}
function hint(){if(S.evaluate(p,state).complete){message('所有花园都已满足规则。',true);return;}const i=selected,j=S.mirror(p,i,p.cores[core]);const body='<p>观察 '+(core+1)+' 号星核：所选第 '+(Math.floor(i/p.w)+1)+' 行、第 '+(i%p.w+1)+' 列，'+(j>=0?'旋转半圈对应第 '+(Math.floor(j/p.w)+1)+' 行、第 '+(j%p.w+1)+' 列。':'旋转半圈会落到棋盘外，因此不能归属这颗星核。')+'</p><p>同一花园的格子要成对出现，并通过上下左右连回星核；仅斜角接触不算连通。</p><p class="small">仍卡住时，可查看唯一解中的一条边。答案提示会记入本局提示次数，不扣分。</p>';modal('先看看另一半',body,[{text:'继续思考',action:closeModal},{text:'查看一条答案边',primary:true,action:()=>{const edge=S.edges(p).find(e=>e.legal&&state.walls.includes(e.id)!==p.solution.includes(e.id));if(!edge){closeModal();return;}selected=edge.a;data.sessions[p.id].hints++;persist();render();const r=Math.floor(edge.a/p.w)+1,c=edge.a%p.w+1,dir=edge.b-edge.a===1?'右':'下';modal('一条经过验证的答案边','<p>第 <strong>'+r+'</strong> 行、第 <strong>'+c+'</strong> 列的<strong>'+dir+'边</strong>，应当'+(p.solution.includes(edge.id)?'画上边界':'擦掉边界')+'。</p><p class="small">这是依据已验证唯一解给出的答案提示。观察修改后，星核归属、对称与连通能否同时成立。</p>',[{text:'自己来画',action:closeModal},{text:'应用这条边',primary:true,action:()=>{closeModal();move({type:'wall',id:edge.id});}}]);}}]);}
function settings(){modal('温室手记','<p><button id="reduce">'+(data.reduced?'开启装饰动态':'减少动态')+'</button> <button id="guideAgain">重看三步教程</button></p><h3>一片花园的三个条件</h3><ol class="rule-list"><li>上下左右连成一片，完整覆盖棋盘。</li><li>恰好一颗星核；边心两格和角点四格必须同属一园。</li><li>以星核旋转半圈，形状重合；区内不能留悬空的边线。</li></ol><p>点击选格，按四个选边按钮切换边界。键盘方向键移动选格，Shift + 方向键画边；Z 撤销。归属笔记仅辅助观察。</p><h3>规则与制作</h3><p>原型：Simon Tatham 谜题集 Galaxies（180° 对称分区）。参考本项目星云孵化场规则，独立重写引擎、题库与界面，AI 辅助开发。MIT 许可。</p><p>关卡 60 道、6 章；每道均经独立搜索验证唯一解。每日题按本地日期循环。没有计时或最少步排名。</p><h3>关于存档</h3><p>进度仅保存在本设备，可因清理缓存或环境变化丢失。存档错误时只恢复可验证的部分。提示计数随当前会话保存；重开新一局。</p><details><summary>完整许可与声明</summary><pre class="license-text"></pre></details>',[{text:'回到花园',primary:true,action:closeModal}]);$('reduce').addEventListener('click',()=>{data.reduced=!data.reduced;render();persist();settings();});$('guideAgain').addEventListener('click',()=>tutorial(0));$('modalBody').querySelector('.license-text').textContent=S.license||'MIT License';}
async function init(){store=await S.adapter(window);const raw=await store.read();data=S.restore(raw,levels);$('greenhouse').innerHTML='<svg viewBox="0 0 300 210"><g fill="none" stroke="#719d88" stroke-width="1"><path d="M40 190V75L150 12 260 75V190ZM40 75H260M150 12V190M95 44V190M205 44V190M40 115H260M40 155H260" opacity=".45"/><path d="M10 193H290M75 190Q45 140 75 115Q105 148 75 190M225 190Q195 130 225 105Q255 145 225 190"/></g>'+S.flower(150,102,30,'#d5c389',null)+S.flower(105,158,15,'#9de5c2',null)+S.flower(203,143,18,'#9de5c2',null)+'<path d="M150 135V191M105 176V191M203 164V191" stroke="#719d88"/><circle cx="30" cy="30" r="2" fill="#d5c389"/><circle cx="266" cy="37" r="1.5" fill="#d5c389"/></svg>';
 $('board').addEventListener('click',e=>{const cell=e.target.getAttribute('data-cell');if(cell!==null){selected=Number(cell);render();}});$('board').addEventListener('keydown',e=>{const dirs={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};if(dirs[e.key]){e.preventDefault();const dir=dirs[e.key],id=edgeFor(dir);if(e.shiftKey){if(id)move({type:'wall',id});}else if(id){const pair=id.split(':').map(Number);selected=pair[0]===selected?pair[1]:pair[0];render();}}if(e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click();}});
 document.querySelectorAll('[data-dir]').forEach(b=>b.addEventListener('click',()=>{const id=edgeFor(b.dataset.dir);if(id)move({type:'wall',id});}));['row','col'].forEach(id=>$(id).addEventListener('change',()=>{selected=Number($('row').value)*p.w+Number($('col').value);render();}));$('core').addEventListener('change',()=>{core=Number($('core').value);render();});$('note').addEventListener('click',()=>move({type:'note',cell:selected,core}));$('undo').addEventListener('click',()=>{state=S.undo(p,state);remember();render();message('已撤销上一步，边界和笔记一起恢复。');});$('restart').addEventListener('click',()=>modal('重新培育这一局？','<p>本局边界、笔记和提示次数将重置，已经获得的图鉴星花会保留。</p>',[{text:'继续这一局',action:closeModal},{text:'重新开始',primary:true,action:()=>{delete data.sessions[p.id];start(data.current);}}]));$('next').addEventListener('click',()=>data.current<59?start(data.current+1):collection());$('hint').addEventListener('click',hint);$('help').addEventListener('click',()=>tutorial(0));$('settings').addEventListener('click',settings);$('chapters').addEventListener('click',()=>chapters(p.chapter-1));$('collection').addEventListener('click',collection);$('daily').addEventListener('click',daily);$('favorite').addEventListener('click',()=>{const i=data.favorites.indexOf(p.id);if(i<0)data.favorites.push(p.id);else data.favorites.splice(i,1);persist();render();});$('closeModal').addEventListener('click',closeModal);$('overlay').addEventListener('click',e=>{if(e.target===$('overlay'))closeModal();});document.addEventListener('keydown',e=>{if(!modalOpen)return;if(e.key==='Escape'){e.preventDefault();closeModal();}if(e.key==='Tab'){const nodes=Array.from($('modal').querySelectorAll('button,select,summary,[tabindex="0"]')).filter(el=>!el.disabled);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 start(data.current);if(!data.tutorial)tutorial(0);if(Object.keys(data.outbox).length&&window.starbudHost&&typeof window.starbudHost.onComplete==='function')S.flush(data,async()=>persist(),e=>window.starbudHost.onComplete(e));
}
init().catch(()=>{$('saveStatus').textContent='暂时无法读取花园存档。为保护进度，请稍后重新打开。';});
})(Starbud);
