const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const levels=require('../src/levels.js').levels,E=require('../src/engine.js'),root=path.resolve(__dirname,'..');process.chdir(root);
const errors=[],external=[],checks=[];
const server=http.createServer((req,res)=>{let pathname=decodeURIComponent(req.url.split('?')[0]);if(pathname==='/')pathname='/index.html';const file=path.join(root,'dist/xhs',pathname);if(!file.startsWith(path.join(root,'dist/xhs'))||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.html':'text/html'})[path.extname(file)]||'application/octet-stream');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'none'; object-src 'none'");res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port,b=await chromium.launch({channel:'chrome',headless:true});try{const context=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,hasTouch:true});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(url))external.push(r.url());});await p.goto(url);await p.getByText('跳过',{exact:true}).click();await p.locator('#help').click();assert.equal(await p.locator('body').evaluate(e=>getComputedStyle(e).overflow),'hidden');await p.locator('#modal').screenshot({path:'release/tutorial-1.png'});await p.getByText('下一张 →',{exact:true}).click();assert.equal(await p.locator('.tutorial-picture [data-wall]').count(),1);await p.locator('#modal').screenshot({path:'release/tutorial-2.png'});await p.getByText('下一张 →',{exact:true}).click();assert.equal(await p.locator('.tutorial-picture svg').getAttribute('data-complete'),'true');await p.locator('#modal').screenshot({path:'release/tutorial-3.png'});await p.getByText('进入花园',{exact:true}).click();assert.equal(await p.evaluate(()=>document.activeElement.id),'help');checks.push('tutorial initial/action/win, skip, scroll lock and focus restore');
 await p.locator('#help').click();await p.keyboard.press('Escape');assert(await p.locator('#overlay').isHidden());
 for(const [width,height]of [[320,720],[390,844],[1280,720],[359,720],[360,720],[361,720],[899,900],[900,900],[901,900]]){await p.setViewportSize({width,height});const sizes=await p.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,actionBottom:document.querySelector('.action-bar').getBoundingClientRect().bottom}));assert(sizes.scroll<=sizes.width,'overflow '+width);if(width===320||width===390)assert(sizes.actionBottom<=height,'actions below viewport '+width+' '+sizes.actionBottom);for(const btn of await p.locator('.edge-buttons button').all()){const box=await btn.boundingBox();assert(box.height>=44&&box.width>=44);}if([320,390,1280].includes(width))await p.screenshot({path:'release/viewport-'+width+'.png',fullPage:true});}checks.push('9 viewport/breakpoint checks and 44px edge buttons');
 await p.setViewportSize({width:390,height:844});await p.locator('#board [data-cell="0"]').tap();await p.locator('[data-dir="right"]').tap();assert.equal(await p.locator('#board [data-wall]').count(),1);await p.screenshot({path:'release/phone-one-move.png',fullPage:true});await p.locator('#undo').click();assert.equal(await p.locator('#board [data-wall]').count(),0);await p.locator('#board').focus();await p.keyboard.press('Shift+ArrowRight');assert.equal(await p.locator('#board [data-wall]').count(),1);await p.reload();await p.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('已保存'));assert.equal(await p.locator('#board [data-wall]').count(),1);await p.locator('#undo').click();checks.push('real touch/keyboard wall, undo and refresh restore');
 for(const id of levels[0].solution){const [a,c]=id.split(':').map(Number);await p.locator('#row').selectOption({value:String(Math.floor(a/5))});await p.locator('#col').selectOption({value:String(a%5)});await p.locator('[data-dir="'+(c-a===1?'right':'down')+'"]').click();}await p.waitForFunction(()=>document.querySelector('#message').textContent.includes('开花'));assert.equal(await p.locator('#board svg').getAttribute('data-complete'),'true');await p.waitForFunction(()=>JSON.parse(localStorage.getItem('mini-polish:starbud-garden:v1:garden')).completed['sg-01']);await p.screenshot({path:'release/phone-complete.png',fullPage:true});await p.reload();await p.waitForFunction(()=>document.querySelector('#board svg').getAttribute('data-complete')==='true');assert.equal(await p.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('mini-polish:starbud-garden:v1:garden')).completed).length),1);await p.locator('#restart').click();await p.getByText('重新开始',{exact:true}).click();assert.equal(await p.locator('#board [data-wall]').count(),0);assert.equal(await p.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('mini-polish:starbud-garden:v1:garden')).completed).length),1);checks.push('full level solved using only UI controls, completion reload and reward retained on restart');
 await p.locator('#hint').click();await p.getByText('查看一条答案边',{exact:true}).click();await p.getByText('应用这条边',{exact:true}).click();assert.equal(await p.locator('#board [data-wall]').count(),1);await p.locator('#favorite').click();assert.equal(await p.locator('#favorite').getAttribute('aria-pressed'),'true');await p.locator('#chapters').click();await p.getByText('星园图鉴',{exact:true}).last().click();assert.equal(await p.locator('.collection-item:not(.locked)').count(),1);await p.screenshot({path:'release/collection.png',fullPage:true});await p.locator('#closeModal').click();
 await p.locator('#chapters').click();await p.locator('[data-chapter="5"]').click();await p.locator('[data-level="59"]').click();await p.locator('#notes summary').click();await p.locator('#core').selectOption({value:'0'});await p.locator('#row').selectOption({value:'6'});await p.locator('#col').selectOption({value:'6'});assert.equal(await p.locator('#board svg').getAttribute('data-level'),'sg-60');await p.screenshot({path:'release/phone-final-chapter.png',fullPage:true});await p.locator('#notes summary').click();await p.setViewportSize({width:320,height:720});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=320));await p.screenshot({path:'release/320-final-chapter.png',fullPage:true});checks.push('answer hint, favorite, collection and maximum 7x7 board');
 await p.locator('#chapters').click();await p.getByText('设置',{exact:true}).click();await p.locator('#reduce').click();assert(await p.locator('body').evaluate(e=>e.classList.contains('reduced')));await p.locator('#modalBody').evaluate(e=>e.scrollTop=e.scrollHeight);await p.locator('#guideAgain').click();assert.equal(await p.locator('#modalBody').evaluate(e=>e.scrollTop),0);await p.locator('#closeModal').click();await p.locator('#chapters').click();await p.getByText('每日星圃',{exact:true}).last().click();assert((await p.locator('#message').innerText()).includes('60 关循环'));checks.push('mobile settings, reduced motion, modal scrolling and finite daily rotation');

 for(const index of [20,30,59]){const level=levels[index];await p.locator('#chapters').click();await p.locator('[data-chapter="'+Math.floor(index/10)+'"]').click();await p.locator('[data-level="'+index+'"]').click();const drawn=await p.locator('#board [data-wall]').evaluateAll(a=>a.map(e=>e.dataset.wall));for(const id of level.solution.filter(id=>!drawn.includes(id))){const[a,c]=id.split(':').map(Number);await p.locator('#row').selectOption({value:String(Math.floor(a/level.w))});await p.locator('#col').selectOption({value:String(a%level.w)});await p.locator('[data-dir="'+(c-a===1?'right':'down')+'"]').click();}assert.equal(await p.locator('#board svg').getAttribute('data-complete'),'true');await p.screenshot({path:'release/complete-'+level.id+'.png',fullPage:true});}checks.push('edge-core, vertex-core and final mixed 7x7 representatives solved through UI');
 const broken=await b.newContext();await broken.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('quota');};});const bp=await broken.newPage();await bp.goto(url);await bp.getByText('跳过',{exact:true}).click();await bp.waitForFunction(()=>document.querySelector('#saveStatus').textContent.includes('无法保存'));await bp.locator('[data-dir="right"]').click();assert.equal(await bp.locator('#board [data-wall]').count(),1);await broken.close();checks.push('storage write failure stays playable with warning');
 const native=await b.newContext();await native.addInitScript(()=>{window.nativeCalls=[];window.xhs={launchOptions:{miniToolEnv:{buildVersion:9462004}},miniTool:{getStorage:async()=>({data:null}),setStorage:async o=>window.nativeCalls.push(o)}};});const np=await native.newPage();await np.goto(url);await np.getByText('跳过',{exact:true}).click();await np.locator('[data-dir="right"]').click();await np.waitForFunction(()=>window.nativeCalls.some(c=>c.data.sessions['sg-01'].actions.length===1));assert.equal(await np.evaluate(()=>localStorage.length),0);await native.close();checks.push('native Storage API used on supported client (mocked)');
 // Render native SVG icon, preserving vector source and recording output.
 const icon=await context.newPage();await icon.setViewportSize({width:512,height:512});await icon.goto(url+'/icon.svg');await icon.locator('svg').screenshot({path:'release/icon.png',scale:'css'});await icon.close();
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync('release/browser-qa.json',JSON.stringify({date:new Date().toISOString(),browser:await b.version(),checks,errors,external,physicalDevices:'not tested',platformContainer:'separate publication preview'},null,2));console.log(JSON.stringify({checks,errors,external},null,2));}finally{await b.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
