import {createRequire} from 'node:module';import fs from 'node:fs';import {prove,canonical} from './oracle.mjs';
const require=createRequire(import.meta.url),E=require('../src/engine.js');
const chapterNames=['星核落点','成对扩展','边心双生','角点四象','狭口连通','综合星园'];
const lessons=['每一片花园只留一颗星核','多长出一格，对面也要长一格','边上的星核，两侧属于同一片','角点星核周围四格不能分开','转弯之后，花园也必须连在一起','把对称、星核和连通一起考虑'];
function random(seed){return ()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return (seed>>>0)/4294967296;};}
function construct(seed,ch){const r=random(seed),w=ch===5?6:ch===6?7:5,p={w,h:w,cores:[]},owners=Array(w*w).fill(-1);
 const centers=[];for(let y=1;y<2*w;y++)for(let x=1;x<2*w;x++)if(ch<3?x%2&&y%2:ch===3?x%2||y%2:true)centers.push({x,y});
 function add(c){const a=E.support(p,c);if(a.some(i=>owners[i]>=0))return false;const k=p.cores.length;p.cores.push(c);a.forEach(i=>owners[i]=k);return true;}
 for(let attempt=0;attempt<6;attempt++)add(centers[Math.floor(r()*centers.length)]);
 function expand(){let changes=0;for(let loop=0;loop<35;loop++){const order=p.cores.map((_,i)=>i).sort(()=>r()-.5);for(const k of order){const c=p.cores[k],front=[];owners.forEach((v,i)=>{if(v===k)E.adjacent(p,i).forEach(j=>{const o=E.mirror(p,j,c);if(owners[j]<0&&o>=0&&owners[o]<0&&(E.adjacent(p,o).some(a=>owners[a]===k)||E.adjacent(p,o).includes(j)))front.push(j);});});if(front.length&&r()<.85){let i=front[Math.floor(r()*front.length)],j=E.mirror(p,i,c);owners[i]=owners[j]=k;changes++;}}}return changes;}
 expand();for(let i=0;i<owners.length;i++)if(owners[i]<0){add({x:2*(i%w)+1,y:2*Math.floor(i/w)+1});expand();}
 return {p,owners};}
function metrics(p,owners){let nonrect=0,bottleneck=0,maxArea=0;for(let k=0;k<p.cores.length;k++){const cells=owners.map((o,i)=>o===k?i:-1).filter(i=>i>=0);maxArea=Math.max(maxArea,cells.length);const xs=cells.map(i=>i%p.w),ys=cells.map(i=>Math.floor(i/p.w));if((Math.max(...xs)-Math.min(...xs)+1)*(Math.max(...ys)-Math.min(...ys)+1)>cells.length)nonrect++;if(cells.length>=5){for(const remove of cells){const pool=new Set(cells.filter(i=>i!==remove)),queue=[pool.values().next().value],seen=new Set(queue);for(const i of queue)E.adjacent(p,i).forEach(j=>{if(pool.has(j)&&!seen.has(j)){seen.add(j);queue.push(j);}});if(seen.size<pool.size){bottleneck++;break;}}}}
 return {nonrect,bottleneck,maxArea,cell:p.cores.filter(c=>c.x%2&&c.y%2).length,edge:p.cores.filter(c=>(c.x%2)!==(c.y%2)).length,vertex:p.cores.filter(c=>!((c.x%2)||(c.y%2))).length};}
const chosen=[],keys=new Set();let attempts=0;
for(let ch=1;ch<=6;ch++){const pool=[];for(let offset=0;offset<10000&&pool.length<35;offset++){const seed=ch*100000+offset+71;attempts++;const {p,owners}=construct(seed,ch),m=metrics(p,owners);if(p.cores.length>p.w*p.h*.55||p.cores.length<4)continue;if(ch===1&&(m.nonrect>1||m.maxArea>9))continue;if(ch===2&&m.nonrect<1)continue;if(ch===3&&m.edge<2)continue;if(ch===4&&m.vertex<1)continue;if(ch===5&&(m.bottleneck<2||m.nonrect<2))continue;if(ch===6&&(!m.vertex||!m.edge||m.nonrect<2))continue;const key=canonical(p);if(keys.has(key))continue;const proof=prove(p);if(!proof.unique)continue;const solution=E.solutionWalls(p,proof.solutions[0]);if(!E.evaluate(p,{walls:solution,notes:{}}).complete)throw Error('oracle disagreement');keys.add(key);pool.push(Object.assign(p,{seed,solution,metrics:m,proof:{method:'connected symmetric regions + exact cover, limit 2',count:1,exhausted:true,regions:proof.enumerated,nodes:proof.nodes,branches:proof.branches,depth:proof.maxDepth},score:proof.branches*10+proof.enumerated+m.nonrect*8+m.maxArea}));}
 if(pool.length<10)throw Error('not enough '+ch+' '+pool.length);pool.sort((a,b)=>a.score-b.score);const picks=Array.from({length:10},(_,i)=>pool[Math.floor(i*(pool.length-1)/9)]);picks.forEach((p,i)=>{p.id='sg-'+String((ch-1)*10+i+1).padStart(2,'0');p.chapter=ch;p.title=['露光','初叶','银蕨','月苔','蓝铃','风芽','星穗','夜藤','流萤','花冠'][i];p.lesson=lessons[ch-1];p.stage=i<2?'认识':i<8?'组合':'综合';chosen.push(p);});console.log('chapter',ch,'pool',pool.length,'scores',picks.map(p=>p.score).join(','));}
fs.writeFileSync('src/levels.js','var Starbud = typeof Starbud === "undefined" ? {} : Starbud;\nStarbud.chapters = '+JSON.stringify(chapterNames)+';\nStarbud.levels = '+JSON.stringify(chosen)+';\nif(typeof module!=="undefined")module.exports=Starbud;\n');fs.writeFileSync('release/puzzle-proof.json',JSON.stringify({generator:'symmetric-growth-v1',attempts,count:chosen.length,levels:chosen.map(p=>({id:p.id,seed:p.seed,metrics:p.metrics,proof:p.proof}))},null,2));
