from pathlib import Path
import json,hashlib,datetime,zoneinfo,zipfile
root=Path(__file__).resolve().parents[1];archive=root/'dist/lantern-spirit-market-xhs.zip'
with zipfile.ZipFile(archive) as z:assert z.testzip() is None and 'index.html' in z.namelist() and len(z.namelist())==9
artifacts=[]
for rel in ['dist/lantern-spirit-market-xhs.zip','release/cover.png','assets/icon.svg','release/browser-report.json','release/edge-report.json','release/core-test.log','release/clean-build-report.json']:
 p=root/rel;artifacts.append({'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
sourcehashes={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in (root/'dist/xhs').iterdir()}
report={'slug':'lantern-spirit-market','title':'灯灵夜归市','updatedAt':datetime.datetime.now(zoneinfo.ZoneInfo('Asia/Shanghai')).isoformat(),'status':'local_complete_candidate_pending_container_validation','source':{'worktree':str(root.parent.parent),'directory':str(root),'branch':'codex/lantern-spirit-market','baseCommit':'55cdddb75cf57c17baee80bac4121bd3be1687c6','original':'games/night-market-spirits','rule':'Same Game','originalLogicSha256':'5520a02b30850b17de90d796c3e37ec19e5a057bdb88ac17f6fd940e27044569','license':'MIT'},'targetLevelCount':60,'verifiedLevelCount':60,'chapters':['灯笼巷','落伞街','回家路','借一盏光','五色终钟','整街归灯'],'features':['maximal-group preview then confirm','stable gravity then left compaction animation','60 independently replayed clear witnesses','proven traps and unequal-score late routes','shared-engine three-state tutorial','hint/undo/restart','replayed saves and first-claim dedup','native Storage preference and serialized fallback','five original silhouettes','48px precise group cards and fixed mobile tools'],'checks':{'logic':'11/11 passed','smallBoardEnumeration':729,'clearWitnesses':60,'trapProofs':'chapters3–6 independent exhaustive DFS','browserMatrix':'320x720,390x844,1280x720 with restrictive CSP','breakpoints':'449/450/451 and799/800/801,44/34px safe areas','allBoardsRendered':60,'es2017':'Acorn8.18 parse passed','packageAudit':'9 files,0 warnings,CRC valid','cleanBuild':'passed,byte-identical ZIP','visualQA':'actual Chrome screenshots reviewed','repositoryGlobalTests':'not run; unrelated baseline games unchanged'},'runtimeHashes':sourcehashes,'artifacts':artifacts,'publication':{'github':'not_pushed','xhsTool':'not_uploaded_or_submitted','xhsNote':'local_draft_not_published','automation':'not_created'},'limitations':['official platform simulator not tested','iOS/Android physical scan container not tested','real touch and Chrome61/WebView61 not tested','real performance not measured','online specification DNS timeout; cache name1.7.0 but metadata1.6.0'],'usage':{'status':'unavailable','actualTokens':None,'cost':None,'reason':'No available task-specific official usage interface; no estimates substituted','imagegenCalls':0},'documents':['README.md','RULES.md','QA.md','ART.md','THIRD_PARTY_NOTICES.md','release/NOTE-DRAFT.md']}
(root/'DELIVERY.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print('DELIVERY updated:',archive.stat().st_size,'ZIP bytes')
