import {createRequire} from 'node:module';import {writeFileSync} from 'node:fs';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';const require=createRequire(import.meta.url),{chromium}=require('playwright'),root=fileURLToPath(new URL('../',import.meta.url));const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});await page.goto('http://127.0.0.1:4180');async function active(level,path=[]){await page.evaluate(({level,path})=>{const d=window.LanternStorage.fresh();d.tutorial=1;d.active={level:level,path:path,runId:'edge-qa'};localStorage.setItem(window.LanternStorage.key,JSON.stringify(d));},{level,path});await page.reload();await page.getByRole('button',{name:path.length?'继续这一摊':'去收最后一摊'}).click();}
await active(20);const anchor=await page.evaluate(()=>window.LanternLevels[20].tags.provenLosingFirstMoves[0]);await page.locator('[data-group="'+anchor.join()+'"]').click();await page.evaluate(()=>document.querySelector('[data-action="confirm"]').click());await page.evaluate(()=>document.querySelector('[data-action="confirm"]').click());await page.waitForTimeout(650);assert.ok((await page.locator('.stats').innerText()).endsWith('1'));await page.getByRole('button',{name:'撤销',exact:true}).click();await page.locator('[data-group="'+anchor.join()+'"]').click();await page.getByRole('button',{name:'送他们回家'}).click();await page.getByRole('button',{name:'重开',exact:true}).click();await page.waitForTimeout(650);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(window.LanternStorage.key)).active.path.length),0);
// Keyboard preview, confirm, escape.
await page.locator('.cell').first().focus();await page.keyboard.press('ArrowRight');const focused=await page.evaluate(()=>document.activeElement.dataset.col);assert.equal(focused,'1');await page.keyboard.press('Enter');assert.equal(await page.locator('[data-action="confirm"]').count(),1);await page.keyboard.press('Escape');assert.equal(await page.locator('[data-action="confirm"]').count(),0);
// Reach a real stuck position by following legal groups after a proven losing first move.
await active(20);await page.locator('[data-group="'+anchor.join()+'"]').click();await page.getByRole('button',{name:'送他们回家'}).click();await page.waitForTimeout(650);let moves=0;while(await page.locator('.group-card').count()&&moves++<40){await page.locator('.group-card').first().click();await page.getByRole('button',{name:'送他们回家'}).click();await page.waitForTimeout(650);}assert.ok((await page.locator('#preview').innerText()).includes('落单'));await page.screenshot({path:root+'release/stuck-390.png',fullPage:true});await page.getByRole('button',{name:'撤销',exact:true}).click();assert.ok(await page.locator('.group-card').count());
// Fixed tutorial states rendered by real app.
await page.getByRole('button',{name:'玩法图解'}).click();for(let i=0;i<3;i++){await page.screenshot({path:root+'release/tutorial-'+(i+1)+'.png'});await page.getByRole('button',{name:i===2?'看完，去收摊':'下一张'}).click();}
const layouts=[];for(const width of [320,390,449,450,451,799,800,801,1280]){await page.setViewportSize({width,height:844});await page.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');});await active(59);const geometry=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,tools:document.querySelector('.tools').getBoundingClientRect().toJSON()}));assert.ok(geometry.scroll<=geometry.width);if(width<=800){assert.ok(geometry.tools.bottom<=844);assert.ok(geometry.tools.y>=0);}layouts.push({width,geometry});}
// Render all 60 actual initial boards as separate real screenshots for chapter QA.
await page.setViewportSize({width:390,height:844});for(let i=0;i<60;i++){await active(i);assert.equal(await page.locator('.cell').count(),await page.evaluate(i=>window.LanternLevels[i].board.flat().length,i));if([0,10,20,30,40,50].includes(i))await page.screenshot({path:root+'release/chapter-'+(Math.floor(i/10)+1)+'.png',fullPage:true});}
console.log(errors);assert.equal(errors.length,0);writeFileSync(root+'release/edge-report.json',JSON.stringify({layouts,errors,checks:['double-confirm one move','restart cancels pending animation','keyboard arrow/enter/escape','real stuck and undo','tutorial screenshots','44/34px injected safe areas','all 60 initial boards render'],browser:await browser.version()},null,2));await browser.close();console.log('Edge, breakpoint, safety-area and 60-board checks passed');
