import '../core.js';
import {writeFileSync} from 'node:fs';
const C=globalThis.LanternCore;let seed=74213;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
const specs=[[4,5,3],[5,6,3],[6,6,4],[7,6,4],[7,8,5],[7,8,5]],chapters=['灯笼巷','落伞街','回家路','借一盏光','五色终钟','整街归灯'];
function canonical(b){const map=new Map();return b.flat().map(v=>{if(!map.has(v))map.set(v,map.size);return map.get(v);}).join('');}
const levels=[],seen=new Set();
for(let ch=0;ch<6;ch++){let attempts=0;while(levels.length<(ch+1)*10){attempts++;const [w,h,k]=specs[ch];let b=Array.from({length:h},()=>Array(w).fill(0));for(let r=0;r<h;r++)for(let c=0;c<w;c++){const a=rand();b[r][c]=a<0.28&&r?b[r-1][c]:a<0.54&&c?b[r][c-1]:Math.floor(rand()*k);}const key=w+'x'+h+canonical(b);if(seen.has(key)||new Set(b.flat()).size!==k)continue;const sol=C.solve(b,12000);if(!sol.path)continue;let state=C.initial({board:b}),ref=0,bridge=0,two=0;for(const p of sol.path){const pr=C.preview(state,...p);if(pr.group.length===2)two++;const oldmax=Math.max(...C.groups(state.board).map(g=>g.length));state=C.move(state,...p);ref=state.score;const ng=C.groups(state.board);if(ng.length&&Math.max(...ng.map(g=>g.length))>oldmax)bridge++;}const gs=C.groups(b);const losing=gs.filter(g=>{const n=C.stages(b,g).board;const res=C.solve(n,3000);return !res.path&&res.exhaustive;});if(ch>=2&&(!bridge||!losing.length))continue;if(ch===0&&levels.length===0&&!two)continue;let alternate=null;for(const g of gs){if(g[0].join()==sol.path[0].join())continue;const start=C.move(C.initial({board:b}),...g[0]);const tail=C.solve(start.board,5000);if(tail.path){const path=[g[0]].concat(tail.path),s=C.replay({board:b},path);if(s.score!==ref){alternate={path:path,score:s.score};break;}}}if(ch===5&&!alternate)continue;seen.add(key);levels.push({id:levels.length+1,chapter:ch,title:chapters[ch]+' · '+String(levels.length%10+1).padStart(2,'0'),board:b,path:sol.path,referenceScore:ref,alternate:alternate,tags:{initialGroups:gs.length,twoGroups:two,bridges:bridge,provenLosingFirstMoves:losing.map(g=>g[0]),nodes:sol.nodes},lesson:['两盏也能回家：合法的两只得0分。','先下落，再向左收拢；不会自动连消。','留一条路，让落单的灯灵与同伴汇合。','小群先走，可能换来更大的同行队伍。','五种剪影，先保清盘，再试更高分。','有不同得分的清盘路线，参考分不是最优分。'][ch]});console.log('level',levels.length,'attempt',attempts,'nodes',sol.nodes);}}
writeFileSync(new URL('../levels.js',import.meta.url),'/* deterministic curated search candidates; see level-review.json */\n(function(r){r.LanternLevels='+JSON.stringify(levels)+';})(typeof window===\'undefined\'?globalThis:window);\n');
writeFileSync(new URL('../level-review.json',import.meta.url),JSON.stringify({seed:74213,method:'correlated random rectangular boards, bounded DFS, canonical color dedup; chapters 3–6 require growth bridge and independently exhaustive losing branch; chapter 6 requires two unequal verified scores',levels:levels.map(l=>({id:l.id,tags:l.tags,reference:l.referenceScore,alternate:l.alternate&&l.alternate.score}))},null,2));
