import {LEVELS,CHAPTERS} from './levels.mjs';
import {fresh,analyze,replay} from './engine.mjs';
import {SAVE_KEY,TUTORIAL_KEY,loadSave,persist,newSession,changeSession,undoSession,finish,flush,dayStamp,dailyIndex} from './session.mjs';
import {boardMarkup,tutorialStates} from './render.mjs';
import {getHint} from './hints.mjs';
const app=document.getElementById('app'),modalRoot=document.getElementById('modal-root');
let storage;try{storage=window.localStorage;}catch(e){storage={getItem:()=>null,setItem:()=>{throw Error('storage unavailable');}};}
const save=loadSave(storage,LEVELS);let view='home',chapter=1,selected=-1,warning=false,modal=null,previousFocus=null,flushing=false;
const LESSONS=['遮去重号，留下一张清晰书页。','黑格上下左右不能相邻，对角可以。','遮黑前看看：白纸还能沿边走到一起吗？','同时看看横行与竖列，留白会带来新的线索。','去重、间距与连通，要一起考虑。','把学过的线索串起来，找回完整藏书。'];
const BOOKS=['重影笺','留白记','连山册','暗线录','月下集','全卷藏'];
function button(action,text,cls='',extra=''){return '<button type="button" data-action="'+action+'" class="'+cls+'" '+extra+'>'+text+'</button>';}
function activePuzzle(){return LEVELS.find(p=>save.session&&p.id===save.session.levelId);}
function count(c){return LEVELS.filter(p=>(!c||p.chapter===c)&&save.records[p.id]).length;}
function independent(){return LEVELS.filter(p=>save.records[p.id]&&save.records[p.id].hints===0).length;}
function remember(){warning=!persist(storage,save);}
function warningHtml(){return warning?'<p class="save-warning" role="alert">当前无法保存进度。你仍可游玩，但关闭页面可能丢失本局；奖励暂不向宿主投递。</p>':'';}
function flushHost(){if(flushing)return;const host=window.moonshadeHost;if(!host||typeof host.onComplete!=='function')return;flushing=true;flush(save,storage,e=>host.onComplete(e)).then(()=>{flushing=false;},()=>{flushing=false;});}
function home(){return '<div class="shell"><header class="topline"><div class="brand"><img src="./assets/icon.svg" alt="">月影书斋</div>'+button('tutorial','玩法','tiny')+'</header><section class="hero"><div class="hero-copy"><div class="eyebrow">THE MOONSHADE ARCHIVE</div><h1>把月光<br>留在纸上</h1><p>遮去重复印记，<br>让留下的书页连成一片。</p><div class="quote">一盏灯 · 一页纸 · 一道谜</div></div><img class="hero-art" src="./assets/study.svg" alt="月光穿过圆拱书窗，照亮桌上的藏书"></section>'+warningHtml()+'<div class="level-meta"><span>已清印 '+count()+' / 60 页</span><span>独立完成 '+independent()+' 页</span></div><div class="progress"><span style="width:'+(count()/60*100)+'%"></span></div><div class="home-actions">'+button('continue',save.session?'继续清印':'翻开第一页','primary')+button('daily','每日清印')+'</div><div class="section-label"><h2>六卷藏书</h2>'+button('library','我的书架','tiny')+'</div><div class="home-grid">'+CHAPTERS.map((name,i)=>'<button class="chapter" data-action="chapter" data-chapter="'+(i+1)+'"><span class="number">0'+(i+1)+'</span><div class="eyebrow">卷 '+['一','二','三','四','五','六'][i]+'</div><h3>'+name+'</h3><span class="rule-name">'+['行列去重 · 4×4','黑格间距 · 4×4','白域连通 · 4×4','双向线索 · 5×5','联合推演 · 5×5','综合清印 · 6×6'][i]+'</span><div class="progress"><span style="width:'+(count(i+1)*10)+'%"></span></div><span class="muted">'+count(i+1)+' / 10 页'+(count(i+1)===10?' · 已收卷':'')+'</span></button>').join('')+'</div><footer class="footer">60道固定谜题 · 无计时压力 · 可随时撤销<br>每日题按本地日期从这60题轮换，每60天循环<br>'+button('about','规则来源与说明','tiny')+'</footer></div>';}
function chapterPage(){return '<div class="shell play-shell"><div class="play-top">'+button('home','← 书斋','tiny')+'<span class="eyebrow">卷 0'+chapter+'</span>'+button('tutorial','玩法','tiny')+'</div><img class="chapter-art" src="./assets/study.svg" alt="月下书斋"><h1 style="font-size:30px;letter-spacing:4px">'+CHAPTERS[chapter-1]+'</h1><p class="chapter-intro">'+LESSONS[chapter-1]+'<br>前2页入门，中6页组合，末2页综合。可自由选页。</p><div class="level-grid">'+LEVELS.filter(p=>p.chapter===chapter).map((p,i)=>'<button class="level-btn '+(save.records[p.id]?'done':'')+'" data-action="level" data-id="'+p.id+'">'+String((chapter-1)*10+i+1).padStart(2,'0')+'<small>'+(save.records[p.id]?(save.records[p.id].hints===0?'独立 ✓':'提示 ✓'):p.stage)+'</small></button>').join('')+'</div><p class="muted">完成本卷10页后，收藏《'+BOOKS[chapter-1]+'》。<br>圈注是笔记，不需要把白格全部圈出。</p></div>';}
function play(){const p=activePuzzle(),s=replay(p,save.session.log),a=analyze(p,s),ordinal=LEVELS.indexOf(p)+1;let win='';
 if(a.complete){const result=finish(save,p,storage);warning=!result.persisted;flushHost();win='<section class="win" role="status"><div class="eyebrow">PAGE RESTORED</div><h3>这一页，月光通透</h3><p>'+(save.session.hints===0?'独立完成':'使用提示完成 · '+save.session.hints+' 次辅助')+'，三条规则全部满足。'+(count(p.chapter)===10?'《'+BOOKS[p.chapter-1]+'》已收入书架。':'')+'</p>'+button('next',save.session.mode==='daily'?'回到书架':ordinal===60?'回到藏书':'翻开下一页','primary')+'</section>';}
 const stateText=a.complete?'✓ 书页已清印':a.touching.length?'! 黑格相邻：请恢复其中一格':a.disconnected.length?'! 白纸断开：请为白格留一条路':a.duplicates.length?'还有重号，慢慢找出该遮去的印记':'继续检查书页';
 return '<div class="shell play-shell"><div class="play-top">'+button('home','← 书斋','tiny')+'<div class="center"><div class="eyebrow">'+(save.session.mode==='daily'?'每日清印 · '+save.session.date:'卷 0'+p.chapter+' · '+p.stage)+'</div><h2>'+p.chapterName+'</h2></div>'+button('tutorial','玩法','tiny')+'</div><div class="level-meta"><span>第 '+String(ordinal).padStart(2,'0')+' 页 / 60</span><span>'+p.n+' × '+p.n+' · '+s.moves+' 次落笔</span></div><p class="lesson">'+LESSONS[p.chapter-1]+'</p>'+warningHtml()+'<div class="paper">'+boardMarkup(p,s,selected)+'</div><div class="rule-bar"><span class="'+(!a.duplicates.length?'ok':'')+'">'+(!a.duplicates.length?'✓':'○')+' 行列无重号</span><span class="'+(!a.touching.length?'ok':'bad')+'">'+(!a.touching.length?'✓':'!')+' 黑格不相邻</span><span class="'+(!a.disconnected.length&&a.whiteCount?'ok':'bad')+'">'+(!a.disconnected.length&&a.whiteCount?'✓':'!')+' 白域相连</span></div><p class="status" aria-live="polite">'+stateText+'</p><div class="selection">'+(selected<0?'先选一格，再决定遮黑或保留':('第 '+(Math.floor(selected/p.n)+1)+' 行 · 第 '+(selected%p.n+1)+' 列 · 印记 '+p.cells[selected]))+'</div><div class="actions">'+button('black','╳ 遮黑','primary',selected<0?'disabled':'')+button('circle','○ 圈注','',selected<0?'disabled':'')+button('white','恢复白格','',selected<0?'disabled':'')+'</div><div class="secondary-actions">'+button('undo','↶ 撤销','',s.moves===0?'disabled':'')+button('restart','重开本页')+button('hint','一点提示')+'</div><div class="quick-row">'+button('quick','快捷循环 '+(save.quick?'开启 ✓':'关闭'),'', 'aria-pressed="'+save.quick+'"')+'<span class="muted">'+(save.session.hints?'本局已使用提示':'圈注不影响通关')+'</span></div>'+win+'<p class="shortcuts">选格后：B 遮黑 / C 圈注 / W 恢复 / Z 撤销</p></div>';}
function library(){return '<div class="shell play-shell"><div class="play-top">'+button('home','← 书斋','tiny')+'<h2>我的书架</h2><span class="eyebrow">'+CHAPTERS.filter((x,i)=>count(i+1)===10).length+' / 6</span></div><div class="collection-picture"><div class="reveal-scene"><img src="./assets/study.svg" alt="月影书斋画卷，完成每章后揭开一部分">'+CHAPTERS.map((name,i)=>count(i+1)===10?'':'<div class="reveal-strip" style="left:'+(i*100/6)+'%;width:'+(100/6)+'%"><span>'+['壹','贰','叁','肆','伍','陆'][i]+'</span></div>').join('')+'</div><p>'+ (count()===60?'六卷齐，满室月光。':'每清印一卷，就为书架添一本藏书。')+'</p></div>'+BOOKS.map((name,i)=>'<div class="library-card '+(count(i+1)===10?'earned':'')+'"><div class="spine">'+['壹','贰','叁','肆','伍','陆'][i]+'</div><div><h3>《'+name+'》'+(count(i+1)===10?' ✓':'')+'</h3><p>'+CHAPTERS[i]+' · '+count(i+1)+' / 10 页<br>'+(count(i+1)===10?'已收藏，可随时重读。':'完成本卷后收入书架。')+'</p></div></div>').join('')+'<p class="footer">总计 '+count()+' 页，独立完成 '+independent()+' 页。<br>重复清印不会重复领取藏书。</p></div>';}
function render(){const y=window.scrollY;app.innerHTML=view==='play'?play():view==='chapter'?chapterPage():view==='library'?library():home();window.scrollTo(0,y);}
function go(next){view=next;render();window.scrollTo(0,0);}
function start(p,mode='campaign',date=''){save.session=newSession(p,mode,date);selected=-1;remember();go('play');}
function apply(mode){const p=activePuzzle();save.session=changeSession(p,save.session,selected,mode);remember();render();const el=app.querySelector('[data-cell="'+selected+'"]');if(el)el.focus({preventScroll:true});}
function closeModal(){if(!modal)return;const closing=modal;modal=null;modalRoot.innerHTML='';document.body.style.overflow='';app.removeAttribute('aria-hidden');if(closing.tutorial){try{storage.setItem(TUTORIAL_KEY,'seen');}catch(e){}}if(previousFocus&&document.contains(previousFocus))previousFocus.focus({preventScroll:true});else{const fallback=app.querySelector('button');if(fallback)fallback.focus({preventScroll:true});}}
function showModal(html,config){if(!modal)previousFocus=document.activeElement;modal=config||{};modalRoot.innerHTML='<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title">'+html+'</section></div>';document.body.style.overflow='hidden';app.setAttribute('aria-hidden','true');modalRoot.querySelector('button').focus();}
function tutorial(step=0){const p=LEVELS[0],card=tutorialStates(p)[step];showModal('<div class="modal-head"><span class="eyebrow">清印入门 · '+(step+1)+' / 3</span>'+button('close','跳过','tiny')+'</div><h2 id="modal-title">'+card.title+'</h2><div class="paper">'+boardMarkup(p,card.state,card.index===undefined?-1:card.index,false)+'</div><p>'+card.text+'</p><div class="step-dots">'+[0,1,2].map(i=>i===step?'●':'○').join(' ')+'</div><div class="modal-actions">'+(step?button('tutorial-prev','上一张'):'')+button(step===2?'close':'tutorial-next',step===2?'开始清印':'下一张','primary')+'</div>',{tutorial:true,step});}
function hint(){const p=activePuzzle(),s=replay(p,save.session.log);if(analyze(p,s).complete){showModal('<h2 id="modal-title">书页已清印</h2><p>三条规则已满足，可以翻到下一页。</p>'+button('close','知道了','primary'));return;}
 const h=getHint(p,s);save.session.hints++;remember();render();showModal('<div class="eyebrow">'+(h.kind||'推理提示')+'</div><h2 id="modal-title" style="margin-top:12px">给思路留一盏灯</h2>'+(h.index===undefined?'':'<div class="hint-coord">第 '+(Math.floor(h.index/p.n)+1)+' 行，第 '+(h.index%p.n+1)+' 列</div>')+'<p>'+h.text+'</p><p class="muted">查看解释已记为一次辅助；是否落笔由你决定。撤销不清除提示记录。</p><div class="modal-actions">'+button('close','自己再想想')+(h.index===undefined?'':button('apply-hint',h.mode===1?'按提示遮黑':'恢复这格','primary'))+'</div>',{hint:h});}
function handle(action,el){if(action==='close'){closeModal();return;}if(action==='tutorial-next'||action==='tutorial-prev'){tutorial(modal.step+(action==='tutorial-next'?1:-1));return;}if(action==='apply-hint'){const h=modal.hint;closeModal();selected=h.index;apply(h.mode);return;}if(action==='confirm-restart'){closeModal();const s=save.session;start(activePuzzle(),s.mode,s.date);return;}
 if(action==='home'){go('home');return;}if(action==='tutorial'){tutorial();return;}if(action==='chapter'){chapter=Number(el.dataset.chapter);go('chapter');return;}if(action==='level'){start(LEVELS.find(p=>p.id===el.dataset.id));return;}if(action==='library'){go('library');return;}
 if(action==='continue'){if(save.session){selected=-1;go('play');}else start(LEVELS.find(p=>!save.records[p.id])||LEVELS[0]);return;}if(action==='daily'){const d=new Date(),p=LEVELS[dailyIndex(d)];if(save.session&&save.session.mode==='daily'&&save.session.date===dayStamp(d)){go('play');}else start(p,'daily',dayStamp(d));return;}
 if(action==='about'){showModal('<h2 id="modal-title">一页纸的规则</h2><p>① 每行、每列剩余白格数字不重复。<br>② 黑格不能上下左右相邻。<br>③ 所有白格沿边连成非空的一片。</p><p>圈注只是笔记；无需把所有白格圈出。黑格数量不是评分目标。提示和独立完成分开记录。</p><p>规则原型：Hitori，参考 Simon Tatham 的 Singles。参考项目：Ten Realms Arcade「影印净化室」，MIT 许可。主题、实现、关卡及矢量插画由 AI 辅助制作。</p><p>60道固定唯一解题。每日题按本地日期轮换，60天循环，可能与主线重复。进度仅保存在当前设备；清理应用数据会丢失进度。</p><div class="modal-actions">'+button('close','回到书斋','primary')+'</div>');return;}
 if(view!=='play')return;
 if(action==='black')apply(1);if(action==='circle')apply(2);if(action==='white')apply(0);
 if(action==='undo'){save.session=undoSession(save.session);remember();render();}
 if(action==='quick'){save.quick=!save.quick;remember();render();}
 if(action==='restart')showModal('<h2 id="modal-title">重新翻开这一页？</h2><p>将清除本局落笔与提示计数，已获得的藏书与完成记录会保留。</p><div class="modal-actions">'+button('close','继续这局')+button('confirm-restart','重开本页','primary')+'</div>');
 if(action==='hint')hint();
 if(action==='next'){const i=LEVELS.indexOf(activePuzzle());if(save.session.mode==='daily'||i===59)go('library');else start(LEVELS[i+1]);}
}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el||el.disabled)return;if(el.dataset.cell!==undefined&&!modal){selected=Number(el.dataset.cell);if(save.quick){const p=activePuzzle(),s=replay(p,save.session.log);apply((s.modes[selected]+1)%3);}else{render();const target=app.querySelector('[data-cell="'+selected+'"]');if(target)target.focus({preventScroll:true});}return;}if(el.dataset.action)handle(el.dataset.action,el);});
document.addEventListener('keydown',e=>{if(modal){if(e.key==='Escape'){e.preventDefault();closeModal();return;}if(e.key==='Tab'){const focusable=Array.from(modalRoot.querySelectorAll('button:not(:disabled)'));const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(view!=='play')return;const p=activePuzzle();const dirs={ArrowLeft:-1,ArrowRight:1,ArrowUp:-p.n,ArrowDown:p.n};if(dirs[e.key]!==undefined){e.preventDefault();selected=Math.max(0,Math.min(p.cells.length-1,(selected<0?0:selected)+dirs[e.key]));render();app.querySelector('[data-cell="'+selected+'"]').focus({preventScroll:true});}if(!e.ctrlKey&&!e.metaKey){const k=e.key.toLowerCase();if(k==='z'){e.preventDefault();handle('undo');}else if(selected>=0&&['b','c','w'].includes(k)){e.preventDefault();apply({b:1,c:2,w:0}[k]);}}});
render();flushHost();let seen=false;try{seen=storage.getItem(TUTORIAL_KEY)==='seen';}catch(e){}if(!seen)tutorial();
