import fs from 'node:fs';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);let chromium;
try{({chromium}=require('playwright'));}catch(e){({chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'));}
const browser=await chromium.launch({channel:'chrome',headless:true});
const base=process.env.GAME_URL||'http://127.0.0.1:4187';const root=new URL('../',import.meta.url);
const data=JSON.parse(fs.readFileSync(new URL('data/campaign.json',root))),prefix='mini-polish:stardew-formulas:v1:',errors=[],requests=[];
fs.mkdirSync(new URL('release/screenshots/',root),{recursive:true});
const ctx=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push(r.url()));
await page.goto(base);await page.locator('#modal').waitFor({state:'visible'});
await page.screenshot({path:fileURLToPath(new URL('release/screenshots/tutorial-1.png',root))});
assert.equal(await page.locator('.tutorial-board .cell').count(),9);
await page.locator('#tutorial-next').click();await page.screenshot({path:fileURLToPath(new URL('release/screenshots/tutorial-2.png',root))});
assert.equal(await page.locator('.tutorial-board [data-value="'+data.levels[0].answer[0]+'"]').count(),1);
await page.locator('#tutorial-next').click();assert.equal(await page.locator('.tutorial-board').getAttribute('data-complete'),'true');await page.screenshot({path:fileURLToPath(new URL('release/screenshots/tutorial-3.png',root))});await page.locator('#tutorial-next').click();
assert.equal(await page.locator('#modal').isVisible(),false);
// Real tap and keyboard interactions, notes, undo, clearing and persistence.
await page.locator('#board [data-cell="0"]').tap();await page.locator('#note').tap();await page.locator('[data-number="2"]').tap();assert.equal(await page.locator('#board [data-cell="0"] .notes').textContent(),'2');await page.locator('#undo').tap();assert.equal(await page.locator('#board [data-cell="0"] .notes').textContent(),'');await page.locator('#note').tap();
await page.locator('[data-number="1"]').tap();await page.reload();assert.equal(await page.locator('#board [data-cell="0"]').getAttribute('data-value'),'1');await page.keyboard.press('Backspace');assert.equal(await page.locator('#board [data-cell="0"]').getAttribute('data-value'),'0');await page.keyboard.press('5');assert.equal(await page.locator('#board [data-cell="0"]').getAttribute('data-value'),'0');
await page.locator('#help').click();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'help');await page.locator('#help').click();await page.locator('#skip').click();assert.equal(await page.locator('#modal').isVisible(),false);
await page.locator('#hint').click();assert.match(await page.locator('#message').textContent(),/可选/);
async function select(index){await page.locator('#chapters').click();await page.locator('[data-chapter="'+Math.floor(index/10)+'"]').click();await page.locator('[data-level-index="'+index+'"]').click();}
// Three representative puzzles, all input through actual UI.
for(const index of [0,30,59]){await select(index);for(let i=0;i<data.levels[index].answer.length;i++){await page.locator('#board [data-cell="'+i+'"]').click();await page.locator('[data-number="'+data.levels[index].answer[i]+'"]').click();}assert.ok(await page.locator('#win').isVisible());await page.screenshot({path:fileURLToPath(new URL('release/screenshots/solved-'+(index+1)+'.png',root))});await page.reload();assert.ok(await page.locator('#win').isVisible());}
assert.equal(await page.locator('#progress').textContent(),'3/60');
await select(0);await page.locator('#restart').click();await page.locator('#confirm-restart').click();for(let i=0;i<9;i++){await page.locator('#board [data-cell="'+i+'"]').click();await page.keyboard.press(String(data.levels[0].answer[i]));}assert.equal(await page.locator('#progress').textContent(),'3/60');
await select(0);await page.locator('#restart').click();await page.locator('#confirm-restart').click();
const metrics=[];
for(const width of [320,359,360,361,390,619,620,621,899,900,901,1099,1100,1101,1280]){
 await page.setViewportSize({width,height:width===390?844:720});
 const info=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,cells:Array.from(document.querySelectorAll('#board .cell')).map(b=>{const r=b.getBoundingClientRect();return {w:r.width,h:r.height};})}));assert.ok(info.scroll<=info.client,'horizontal overflow at '+width);assert.ok(info.cells.every(c=>c.w>=44&&c.h>=44),'touch target at '+width);metrics.push(info);
 if([320,390,1280].includes(width))await page.screenshot({path:fileURLToPath(new URL('release/screenshots/play-'+width+'.png',root)),fullPage:true});
}
// Dense 5x5, longest candidates; modal scrolling, safe area, reduced motion.
await page.setViewportSize({width:320,height:720});await select(59);await page.locator('#restart').click();await page.locator('#confirm-restart').click();await page.locator('#note').click();for(let i=0;i<25;i++){await page.locator('#board [data-cell="'+i+'"]').click();for(let n=1;n<=5;n++)await page.keyboard.press(String(n));}
assert.ok((await page.locator('#board .cell').first().boundingBox()).width>=44);await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','24px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');});await page.screenshot({path:fileURLToPath(new URL('release/screenshots/stress-320.png',root)),fullPage:true});
await page.locator('#help').click();await page.evaluate(()=>document.querySelector('.dialog').scrollTop=500);await page.locator('#tutorial-next').click();assert.equal(await page.locator('.dialog').evaluate(e=>e.scrollTop),0);await page.keyboard.press('Escape');
await page.locator('#daily').click();assert.match(await page.locator('#message').textContent(),/60 道题循环/);
// Corrupted/forged saves cannot grant completion or delete another game's storage.
const corrupt=await browser.newContext();await corrupt.addInitScript(({prefix})=>{localStorage.setItem('unrelated-game','keep');localStorage.setItem(prefix+'save',JSON.stringify({version:1,active:999,sessions:{},completed:{'sf-01':{runId:'run-forged',events:[],complete:true}},ack:['forged']}));localStorage.setItem(prefix+'stardew-formulas-tutorial-v1','seen');},{prefix});const cp=await corrupt.newPage();cp.on('pageerror',e=>errors.push(String(e)));await cp.goto(base);assert.equal(await cp.locator('#progress').textContent(),'0/60');assert.equal(await cp.evaluate(()=>localStorage.getItem('unrelated-game')),'keep');await corrupt.close();
// A failed persistent write must block host delivery, while local play stays usable.
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('quota');};window.hostCalls=[];window.stardewCompletionHost=e=>{window.hostCalls.push(e);return e.rewardClaimId;};});const bp=await blocked.newPage();bp.on('pageerror',e=>errors.push(String(e)));await bp.goto(base);await bp.locator('#skip').click();for(let i=0;i<9;i++){await bp.locator('#board [data-cell="'+i+'"]').click();await bp.keyboard.press(String(data.levels[0].answer[i]));}assert.ok(await bp.locator('#win').isVisible());assert.match(await bp.locator('#save-state').textContent(),/保存失败/);assert.equal(await bp.evaluate(()=>window.hostCalls.length),0);await blocked.close();
// Host rejection followed by explicit readiness retries the identical payload.
const hosted=await browser.newContext();await hosted.addInitScript(()=>{window.hostCalls=[];window.stardewCompletionHost=e=>{window.hostCalls.push(e);throw Error('host offline');};});const hp=await hosted.newPage();hp.on('pageerror',e=>errors.push(String(e)));await hp.goto(base);await hp.locator('#skip').click();for(let i=0;i<9;i++){await hp.locator('#board [data-cell="'+i+'"]').click();await hp.keyboard.press(String(data.levels[0].answer[i]));}assert.equal(await hp.evaluate(()=>window.hostCalls.length),1);await hp.evaluate(()=>{window.stardewCompletionHost=e=>{window.hostCalls.push(e);return e.rewardClaimId;};window.dispatchEvent(new Event('stardew-host-ready'));});await hp.waitForFunction(()=>window.hostCalls.length===2);const payloads=await hp.evaluate(()=>window.hostCalls);assert.deepEqual(payloads[0],payloads[1]);await hp.evaluate(()=>window.dispatchEvent(new Event('stardew-host-ready')));assert.equal(await hp.evaluate(()=>window.hostCalls.length),2);await hosted.close();
assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith(base)));
fs.writeFileSync(new URL('release/browser-report.json',root),JSON.stringify({browser:await browser.version(),metrics,requests:Array.from(new Set(requests)),errors,representativeLevels:[1,31,60],realDevice:false},null,2));await browser.close();console.log('Browser interaction and responsive checks passed');
