import fs from 'node:fs';
import {solve,canonical} from './oracle.mjs';
import {validateLevel,evaluate,createState,apply} from '../src/engine.js';
const chapters=['加法初配','乘法组合','差值配方','整除配方','交叉排除','星露合成'];
let seed=260920;function rand(n){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return Math.floor(seed/4294967296*n);}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=rand(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function candidate(n,ch,slot){
 const startSeed=seed;const rows=shuffle(Array.from({length:n},(_,i)=>i)),cols=shuffle(Array.from({length:n},(_,i)=>i)),digits=shuffle(Array.from({length:n},(_,i)=>i+1));
 const values=rows.reduce((a,r)=>a.concat(cols.map(c=>digits[(r+c)%n])),[]);
 const left=new Set(Array.from({length:n*n},(_,i)=>i)),cages=[];
 while(left.size){let cells=[Array.from(left)[rand(left.size)]];left.delete(cells[0]);const target=2+rand(ch>=4?3:2);
  while(cells.length<target){const opts=Array.from(left).filter(i=>cells.some(j=>Math.abs(Math.floor(i/n)-Math.floor(j/n))+Math.abs(i%n-j%n)===1));if(!opts.length)break;const i=opts[rand(opts.length)];cells.push(i);left.delete(i);}
  cells.sort((a,b)=>a-b);let ops=ch===0?['+']:ch===1?['+','*']:['+','*'];
  if(cells.length===1)ops=['='];
  if(cells.length===2){if(ch>=2)ops.push('-');if(ch>=3&&Math.max(...cells.map(i=>values[i]))%Math.min(...cells.map(i=>values[i]))===0)ops.push('/');}
  const op=ops[rand(ops.length)],v=cells.map(i=>values[i]);
  const t=op==='='?v[0]:op==='+'?v.reduce((a,b)=>a+b,0):op==='*'?v.reduce((a,b)=>a*b,1):op==='-'?Math.abs(v[0]-v[1]):Math.max(...v)/Math.min(...v);
  cages.push({cells,op,target:t});
 }
 return {n,cages,seed:startSeed};
}
const levels=[],used=new Set();
for(let ch=0;ch<6;ch++){
 const pool=[];let attempts=0;
 while(pool.length<36&&attempts<20000){const slot=Math.floor(pool.length/3);const n=ch===0&&pool.length<3?3:ch===5&&slot>=8?5:4;attempts++;
  const p=candidate(n,ch,slot),key=canonical(p,true);
  if(used.has(key)||p.cages.filter(c=>c.op==='=').length>2)continue;
  const required=['+','*','-','/'][ch];if(required&&!p.cages.some(c=>c.op===required))continue;
  if(ch>=4&&new Set(p.cages.map(c=>c.op)).size<3)continue;
  if(!validateLevel(p))throw Error('Invalid generator');
  const proof=solve(p);if(proof.count!==1||!proof.exhausted)continue;
  // Reserve geometry+operator classes, a stronger filter than exact target comparison.
  used.add(key);pool.push(Object.assign(p,{proof:{solutions:1,exhausted:true,nodes:proof.nodes,branches:proof.branches,maxDepth:proof.maxDepth,candidateTotal:proof.initialCandidates.reduce((a,b)=>a+b,0)},answer:proof.solutions[0]}));
 }
 if(pool.length<10)throw Error('Insufficient unique levels chapter '+ch+' '+pool.length);
 pool.sort((a,b)=>a.n-b.n||a.proof.maxDepth-b.proof.maxDepth||a.proof.branches-b.proof.branches||a.proof.candidateTotal-b.proof.candidateTotal);
 const spread=(a,n)=>Array.from({length:n},(_,i)=>a[Math.floor(i*(a.length-1)/(n-1))]);
 const selected=ch===0?pool.filter(p=>p.n===3).concat(spread(pool.filter(p=>p.n===4),7)):ch===5?spread(pool.filter(p=>p.n===4),8).concat(spread(pool.filter(p=>p.n===5),2)):spread(pool,10);
 selected.forEach((p,i)=>{p.id='sf-'+String(ch*10+i+1).padStart(2,'0');p.chapter=ch;p.stage=i<2?'概念':i<8?'组合':'综合';p.generatorVersion=1;p.difficulty=p.proof.maxDepth>2?'深入推演':p.proof.branches?'交叉排除':'逐格推理';levels.push(p);});
 console.log(chapters[ch],selected.map(p=>p.n+'×'+p.n+'/'+p.proof.branches).join(' '),'attempts',attempts);
}
for(const p of levels){let s=createState(p);p.answer.forEach((v,i)=>s=apply(p,s,{type:'fill',cell:i,value:v}));if(!evaluate(p,s).complete)throw Error('Oracle mismatch');}
const data={version:1,generatorVersion:1,chapters,levels};
fs.writeFileSync(new URL('../data/campaign.json',import.meta.url),JSON.stringify(data,null,2)+'\n');
const runtime=Object.assign({},data,{levels:data.levels.map(p=>{const q=Object.assign({},p);delete q.answer;return q;})});
const tutorial={id:'stardew-formulas-tutorial-v1',levelId:levels[0].id,action:{type:'fill',cell:0,value:levels[0].answer[0]},answer:levels[0].answer};
fs.writeFileSync(new URL('../src/campaign.js',import.meta.url),'// Generated by scripts/generate.mjs; versioned runtime data.\nexport const CAMPAIGN='+JSON.stringify(runtime)+';\nexport const TUTORIAL='+JSON.stringify(tutorial)+';\n');
console.log('60 levels independently proved, geometry/operator classes distinct');
