import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const require=createRequire(import.meta.url);
const R=require('../src/rules.js'),L=require('../src/levels.js'),V=require('../src/render.js');
const assets=path.join(root,'assets');
const level=L.levels[0];
const initial=R.blank(level);
const filledIndex=level.rows.join('').indexOf('#');
const action=R.apply(level,initial,filledIndex,1);
const complete=level.rows.join('').split('').map(c=>c==='#'?1:2);
if(!R.complete(level,complete))throw new Error('Tutorial completion does not satisfy rules');
[initial,action,complete].forEach((grid,i)=>fs.writeFileSync(path.join(assets,`tutorial-${i}.svg`),V.boardImage(level,grid,i===1?filledIndex:-1)));
fs.writeFileSync(path.join(assets,'tutorial-truth.json'),JSON.stringify({levelId:level.id,states:[initial,action,complete],action:{index:filledIndex,value:1},completed:true},null,2));
const license=fs.readFileSync(path.join(root,'LICENSE'),'utf8');
fs.writeFileSync(path.join(assets,'license.json'),JSON.stringify({license:'MIT',notice:license,source:'Ten Realms Arcade / v2/games/mist-photo-studio',sourceCommit:'374d2eee951c8f6aa0bbc829e9cceaa127596b7c',rules:'https://www.chiark.greenend.org.uk/~sgtatham/puzzles/doc/pattern.html',originalAssets:'Mistwood Album contributors, 2026'},null,2));
const dist=path.join(root,'dist'),out=path.join(dist,'xhs');
fs.mkdirSync(dist,{recursive:true});
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
fs.cpSync(assets,path.join(out,'assets'),{recursive:true});
fs.copyFileSync(path.join(root,'styles.css'),path.join(out,'styles.css'));
let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
html=html.replace(/  <script src="\.\/src\/[^\"]+"><\/script>\n/g,'');
html=html.replace('</body>','  <script src="./app.js"></script>\n</body>');
fs.writeFileSync(path.join(out,'index.html'),html);
const scripts=['rules','levels','store','render','app'].map(name=>fs.readFileSync(path.join(root,'src',name+'.js'),'utf8'));
fs.writeFileSync(path.join(out,'app.js'),scripts.join('\n;\n'));
const zip=path.join(dist,'mistwood-album-xhs.zip');
fs.rmSync(zip,{force:true});
execFileSync('zip',['-q','-r',zip,'.'],{cwd:out});
const {audit}=await import('./zip-audit.mjs');
const result=audit(out,zip);
fs.writeFileSync(path.join(root,'release','zip-audit.json'),JSON.stringify(result,null,2));
console.log(`Built ${out}\nZIP ${zip} (${fs.statSync(zip).size} bytes)\nAudit: ${result.checks.length} checks passed`);
