import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import vm from 'node:vm';import {execFileSync} from 'node:child_process';
const ctx={};vm.runInNewContext(process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'],ctx);const acorn=ctx.acorn;
const out=path.resolve('dist/xhs'),zip=path.resolve('dist/cinnabar-terraces-xhs-candidate.zip'),listing=execFileSync('unzip',['-Z1',zip],{encoding:'utf8'}).trim().split('\n'),files=listing.filter(x=>!x.endsWith('/'));assert.ok(listing.includes('index.html'));assert.equal(files.filter(x=>x.endsWith('.html')).length,1);
let total=0;for(const file of files){assert.ok(/\.(html|css|js|svg|json|png|jpg|webp)$/.test(file));assert.ok(!file.includes('..')&&!file.startsWith('/')&&!file.includes('node_modules'));const text=fs.readFileSync(path.join(out,file),'utf8');total+=Buffer.byteLength(text);if(file.endsWith('.js')){acorn.parse(text,{ecmaVersion:2017,sourceType:'script'});assert.ok(!/\b(fetch|XMLHttpRequest|WebSocket|EventSource|Worker|SharedWorker|eval)\s*\(|new\s+Function|serviceWorker|WebAssembly|localStorage\.clear|\.replaceAll\(|\.at\(|structuredClone|Object\.hasOwn/.test(text),file);}if(file.endsWith('.svg'))execFileSync('xmllint',['--noout',path.join(out,file)]);}
const html=fs.readFileSync(path.join(out,'index.html'),'utf8');assert.ok(!/type=["']module|\son\w+=|javascript:|<iframe|<object|<base|http-equiv=["']Content-Security-Policy/.test(html));for(const m of html.matchAll(/(?:src|href)="([^"]+)"/g)){assert.ok(m[1].startsWith('./'));assert.ok(fs.existsSync(path.resolve(out,m[1])));}assert.ok(!/<script[^>]*>[\s\S]*?\S[\s\S]*?<\/script>/.test(html.replace(/<script[^>]*src=[^>]*><\/script>/g,'')));
const css=fs.readFileSync(path.join(out,'style.css'),'utf8');assert.ok(!/(?:^|[;{}])\s*gap:|aspect-ratio:|clamp\(|:has\(|\binset:|\bdvh\b|\bsubgrid\b/.test(css));assert.ok(css.includes('grid-gap:'));for(const m of css.matchAll(/url\(['"]?([^)'"\s]+)/g)){assert.ok(m[1].startsWith('./'));assert.ok(fs.existsSync(path.resolve(out,m[1])));}
assert.ok(fs.statSync(zip).size<2*1024*1024);const crc=execFileSync('unzip',['-t',zip],{encoding:'utf8'});const licenses=JSON.parse(fs.readFileSync(path.join(out,'licenses.json'),'utf8'));assert.ok(licenses.license.includes('Permission is hereby granted'));assert.ok(licenses.notices.includes('James Harvey'));
const official=['dist/xhs',zip].map(p=>execFileSync(process.execPath,['platform/minitool-zip-builder/scripts/audit_artifact.mjs',p],{encoding:'utf8'}));
const report={status:'LOCAL_CANDIDATE_AUDIT_PASSED',zipBytes:fs.statSync(zip).size,uncompressedBytes:total,fileCount:files.length,ES2017Parse:true,crc:crc.includes('No errors detected'),localReferences:true,SVGXML:true,licenses:true,officialOutput:official,platformReady:false,limitations:['online spec DNS timed out','no official simulator','no physical iOS/Android','no actual Chrome61 runtime']};fs.writeFileSync('release/package-audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
