import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const runtime=process.env.TERRACE_NODE_MODULES||'node_modules';const {chromium}=require(path.join(runtime,'playwright'));const L=require('../levels.js').levels;
const out=path.resolve('dist/xhs'),release=path.resolve('release'),mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json'};
const server=http.createServer((req,res)=>{let file=path.resolve(out,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(out+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end('missing');return;}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Content-Security-Policy':"default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'; worker-src 'none'"});res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,executablePath:process.env.TERRACE_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const report={artifact:'dist/xhs (exact ZIP contents)',csp:'restricted headers; no script-inline/eval/network',viewports:[],errors:[],externalRequests:[],checks:[],screenshots:[]};
async function snap(p,name,full=true){await p.screenshot({path:path.join(release,name+'.png'),fullPage:full && !(await p.locator('.modal').count())});report.screenshots.push(name+'.png');}
async function noOverflow(p){const d=await p.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:document.documentElement.clientWidth}));assert.ok(d.scroll<=d.width,JSON.stringify(d));}
async function click(p,action){const scope=await p.locator('.modal').count()?p.locator('#modal-root'):p;await scope.locator('[data-action="'+action+'"]').first().click();}
async function saved(p){await p.waitForTimeout(40);return p.evaluate(()=>JSON.parse(localStorage.getItem('mini-polish:cinnabar-terraces:v1:save')));}
try{
for(const [width,height] of [[320,720],[390,844],[1280,720]]){
 const touch=width<500,context=await browser.newContext({viewport:{width,height},hasTouch:touch,deviceScaleFactor:1});const p=await context.newPage();p.on('pageerror',e=>report.errors.push(String(e)));p.on('request',req=>{if(!req.url().startsWith(url))report.externalRequests.push(req.url());});await p.goto(url);await p.locator('.tutorial-art').waitFor();
 await noOverflow(p);await snap(p,'tutorial-one-'+width);await click(p,'tutorial-next');await snap(p,'tutorial-two-'+width);await click(p,'tutorial-next');await snap(p,'tutorial-three-'+width);assert.ok(await p.locator('[data-stage="complete"][data-complete="true"]').count());await click(p,'tutorial-next');assert.equal(await p.locator('.modal').count(),0);assert.equal(await p.locator('body.modal-open').count(),0);
 await click(p,'home');await snap(p,'home-'+width);await click(p,'chapters');await noOverflow(p);assert.equal(await p.locator('.level-button').count(),60);await snap(p,'chapters-'+width);await p.locator('[data-action="level"][data-id="ct-41"]').click();await noOverflow(p);await snap(p,'game-'+width);
 const targets=await p.locator('.digit-key,.cell-key,.row-key').evaluateAll(bs=>bs.map(b=>{const r=b.getBoundingClientRect();return {class:b.className,width:r.width,height:r.height};}));for(const t of targets){assert.ok(t.width>=44&&t.height>=44,JSON.stringify(t));if(width===320&&/digit-key|cell-key/.test(t.class))assert.ok(t.width>=87.9&&t.height>=48,JSON.stringify(t));}
 // Touch uses the actual row and cell selection panel; no DOM state injection.
 async function act(locator){if(touch)await locator.tap();else await locator.click();}
 await act(p.locator('[data-action="row"][data-row="5"]'));await act(p.locator('[data-action="cell"][data-cell="35"]'));let before=(await saved(p)).current;assert.equal(before.selected,35);assert.equal(before.state.values[35],0);
 await click(p,'mode');await act(p.locator('[data-action="digit"][data-value="6"]'));assert.deepEqual((await saved(p)).current.state.notes[35],[6]);assert.equal((await saved(p)).current.state.values[35],0);await click(p,'undo');assert.deepEqual((await saved(p)).current.state.notes[35],[]);await click(p,'mode');
 const l=L[40];await act(p.locator('[data-action="digit"][data-value="'+l.solution[35]+'"]'));assert.equal((await saved(p)).current.state.values[35],l.solution[35]);await click(p,'undo');await click(p,'relations');await p.locator('[data-action="relation-locate"]').last().click();assert.equal(await p.locator('.modal').count(),0);
 await click(p,'candidates');await snap(p,'maximum-notes-'+width);await click(p,'undo');await click(p,'hint');await click(p,'hint-more');await click(p,'hint-more');await snap(p,'hint-'+width);await click(p,'hint-apply');let state=(await saved(p)).current.state;assert.equal(state.values.filter(Boolean).length,1);
 const run=(await saved(p)).current.runId;await p.reload();await p.locator('[data-action="continue"]').waitFor();await click(p,'continue');assert.equal((await saved(p)).current.runId,run);assert.equal((await saved(p)).current.state.values.filter(Boolean).length,1);
 for(let r=0;r<6;r++)for(let c=0;c<6;c++){await act(p.locator('[data-action="row"][data-row="'+r+'"]'));await act(p.locator('[data-action="cell"][data-cell="'+(r*6+c)+'"]'));await act(p.locator('[data-action="digit"][data-value="'+l.solution[r*6+c]+'"]'));}
 await p.locator('.result-landscape').waitFor();await noOverflow(p);await snap(p,'complete-'+width);let s=await saved(p);assert.equal(Object.keys(s.completed).length,1);assert.equal(s.outbox.length,1);assert.deepEqual(s.current.state.values,l.solution);
 await click(p,'review-proof');assert.ok(await p.locator('.proof-list li').count()>40);await click(p,'result');await click(p,'collection-modal');await snap(p,'collection-'+width);assert.equal(await p.locator('.brick.earned').count(),1);
 await click(p,'home');await click(p,'continue');await click(p,'restart');await click(p,'restart-confirm');assert.equal((await saved(p)).current.state.values.filter(Boolean).length,0);assert.equal(Object.keys((await saved(p)).completed).length,1);
 await click(p,'hint');await click(p,'solution-confirm');await click(p,'solution');await p.locator('.result-landscape').waitFor();assert.ok((await saved(p)).current.practice);assert.equal((await saved(p)).outbox.length,1);await click(p,'close');await snap(p,'practice-'+width);await click(p,'home');await click(p,'tutorial');
 // Focus trap and internal scroll reset; game progress remains intact.
 await p.locator('[data-action="tutorial-next"]').click();await p.locator('.modal-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);await p.locator('[data-action="tutorial-next"]').click();assert.equal(await p.locator('.modal-scroll').evaluate(el=>el.scrollTop),0);await p.keyboard.press('Escape');assert.equal(await p.locator('.modal').count(),0);assert.equal(await p.locator('body.modal-open').count(),0);
 report.viewports.push({width,height,touchInput:touch,overflow:false,controls:targets,fullSolve:'ct-41 via '+(touch?'touch panel':'mouse panel'),saveResume:true,completionDedup:true,practice:true});await context.close();
}
// Desktop keyboard path, reward transport retry and persisted-before-send assertions.
const context=await browser.newContext({viewport:{width:1280,height:720}});await context.addInitScript(()=>{window.rewardCalls=[];window.hostPersistedChecks=[];window.TerraceHost={claimReward:async p=>{const stored=JSON.parse(localStorage.getItem('mini-polish:cinnabar-terraces:v1:save'));window.hostPersistedChecks.push(!!stored.completed[p.levelId]&&stored.outbox.some(q=>q.rewardClaimId===p.rewardClaimId));window.rewardCalls.push(p);if(window.rewardCalls.length===1)throw Error('simulated host failure');return true;}};});const p=await context.newPage();p.on('pageerror',e=>report.errors.push(String(e)));await p.goto(url);await p.locator('.tutorial-art').waitFor();await click(p,'tutorial-prev');
const first=L[0];for(let c=0;c<16;c++){await p.locator('.board button[data-cell="'+c+'"]').click();await p.keyboard.press(String(first.solution[c]));}await p.locator('.result-landscape').waitFor();await p.waitForTimeout(100);assert.equal((await saved(p)).outbox.length,1);await p.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await p.waitForTimeout(100);assert.equal((await saved(p)).outbox.length,0);assert.equal((await p.evaluate(()=>window.rewardCalls)).length,2);assert.ok((await p.evaluate(()=>window.hostPersistedChecks)).every(Boolean));await click(p,'close');await click(p,'result');await click(p,'close');assert.equal((await p.evaluate(()=>window.rewardCalls)).length,2);report.checks.push('desktop keyboard full solve, host failure/retry same ID, persistent ledger before host');
// Corrupt active save, keep earned brick, reject forged completion.
await p.addInitScript(()=>{const key='mini-polish:cinnabar-terraces:v1:save',s=JSON.parse(localStorage.getItem(key));s.current.state.values[0]=999;s.completed['ct-02']={completed:true};localStorage.setItem(key,JSON.stringify(s));localStorage.setItem('other-game-save','keep');});await p.reload();await p.locator('[data-action="continue"]').waitFor();const repaired=await saved(p);assert.equal(Object.keys(repaired.completed).length,1);assert.equal(repaired.current.state.values.filter(Boolean).length,0);assert.equal(await p.evaluate(()=>localStorage.getItem('other-game-save')),'keep');report.checks.push('corrupt current reset, earned ledger revalidated, forged completion rejected, other game preserved');await context.close();
// Storage unavailable is playable, cannot emit a host reward.
const bad=await browser.newContext({viewport:{width:320,height:720},hasTouch:true});await bad.addInitScript(()=>{Object.defineProperty(window,'localStorage',{value:{getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}}});window.hostCount=0;window.TerraceHost={claimReward:async()=>{window.hostCount++;return true;}};});const bp=await bad.newPage();await bp.goto(url);await bp.locator('.tutorial-art').waitFor();await click(bp,'tutorial-prev');assert.ok(await bp.locator('#save-warning').isVisible());for(let c=0;c<16;c++){await bp.locator('.board button[data-cell="'+c+'"]').tap();await bp.locator('[data-action="digit"][data-value="'+first.solution[c]+'"]').tap();}await bp.locator('.result-landscape').waitFor();assert.equal(await bp.evaluate(()=>window.hostCount),0);await snap(bp,'storage-unavailable-320');await bad.close();report.checks.push('storage-blocked path remains playable and never delivers unpersisted reward');
// Critical breakpoints ±1px, large text, safe-area simulation, reduced motion and landscape.
for(const width of [358,359,360,798,799,800,1149,1150,1151]){const c=await browser.newContext({viewport:{width,height:720}});const p=await c.newPage();await p.goto(url);await p.locator('.tutorial-art').waitFor();await click(p,'tutorial-prev');await click(p,'chapters');await p.locator('[data-id="ct-60"]').click();await noOverflow(p);await snap(p,'breakpoint-'+width);await c.close();}
const safe=await browser.newContext({viewport:{width:320,height:720},reducedMotion:'reduce',hasTouch:true});const sp=await safe.newPage();await sp.goto(url);await sp.locator('.tutorial-art').waitFor();await click(sp,'tutorial-prev');await sp.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');});await click(sp,'chapters');await sp.locator('[data-id="ct-60"]').click();await sp.evaluate(()=>{document.body.style.fontSize='20px';});await noOverflow(sp);await snap(sp,'safe-area-large-text-320');await click(sp,'tutorial');await snap(sp,'safe-area-modal-320');await click(sp,'close');await sp.setViewportSize({width:720,height:320});await noOverflow(sp);await snap(sp,'landscape-720');await safe.close();report.checks.push('breakpoints ±1px, 44/34px safe area, reduced motion, large body text, landscape');
const teaching=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});const tp=await teaching.newPage();await tp.goto(url);await tp.locator('.tutorial-art').waitFor();await click(tp,'tutorial-prev');
for(const id of ['ct-06','ct-27','ct-56']){await click(tp,'chapters');await tp.locator('[data-action="level"][data-id="'+id+'"]').click();await noOverflow(tp);await snap(tp,'representative-'+id+'-390');const l=L.find(x=>x.id===id),rendered=await tp.locator('.board .relation').evaluateAll(es=>es.map(e=>({a:Number(e.getAttribute('data-a')),b:Number(e.getAttribute('data-b')),sign:e.getAttribute('data-sign'),glyph:e.textContent})));assert.equal(rendered.length,l.relations.length);for(const e of rendered)assert.equal(e.glyph,e.b-e.a===l.n?(e.sign==='<'?'∧':'∨'):e.sign);await click(tp,'hint');await click(tp,'hint-more');await click(tp,'hint-more');await snap(tp,'representative-'+id+'-hint');await click(tp,'close');}
await click(tp,'tutorial');for(const n of [5,6]){await tp.locator('[data-action="tutorial-size"][data-n="'+n+'"]').click();await click(tp,'tutorial-next');await snap(tp,'tutorial-'+n+'-action-390');await click(tp,'tutorial-next');await snap(tp,'tutorial-'+n+'-complete-390');assert.equal(await tp.locator('.tutorial-art [data-cell]').count(),n*n);}await click(tp,'close');await teaching.close();report.checks.push('ct-06 vertical direction, ct-27 five-length chain, ct-56 branching; 5/6 tutorial true-state cards');
assert.deepEqual(report.errors,[]);assert.deepEqual(report.externalRequests,[]);report.status='BROWSER_SIMULATION_PASSED';fs.writeFileSync(path.join(release,'browser-report.json'),JSON.stringify(report,null,2));console.log('Browser simulation passed; '+report.screenshots.length+' screenshots; no page errors or external requests.');
}catch(e){report.status='FAILED';report.failure=String(e.stack);fs.writeFileSync(path.join(release,'browser-report.json'),JSON.stringify(report,null,2));throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
