import {AREAS,SKINS,createWorld,freshRun,freshSave,validateSave,radius,collect,tasks,settle,SpatialGrid,moveAndCollect} from './core.mjs';
import {View} from './view.mjs';
const $=id=>document.getElementById(id),KEY='rolling-town:v1';let save;try{save=validateSave(JSON.parse(localStorage.getItem(KEY)));}catch{save=freshSave();}let storageOK=true,view,run,world,grid,playing=false,home=true,paused=false,last=0,writeAt=0,target=null,toastTimer,nearAt=0,velocity={x:0,z:0},input={x:0,y:0},keys=new Set(),pointer=null,origin=null,ac=null,firstFrame=true;
const icons=['◉','●','▰','▣','✎','◉','☕','▤','♧','◷','♧','⌂'];
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));}catch{if(storageOK){storageOK=false;toast('本机存档不可用，本次仍可继续游玩');}}}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300);}
function sound(n=0){if(!save.sound)return;try{if(!ac)ac=new(window.AudioContext||window.webkitAudioContext)();if(ac.state==='suspended')ac.resume();const o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.setValueAtTime(520+n*80,ac.currentTime);o.frequency.exponentialRampToValueAtTime(820+n*80,ac.currentTime+.09);g.gain.setValueAtTime(.035,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.2);o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+.21);}catch{}}
function resetInput(){keys.clear();pointer=null;input={x:0,y:0};velocity={x:0,z:0};$('knob').style.transform='translate(0,0)';}
function screen(html){resetInput();$('panel').innerHTML=html;$('panel').classList.toggle('modal',html.includes('class="sheet"'));}
function sheet(title,body,back='home'){screen(`<div class="sheet"><button class="close" data-action="${back}" aria-label="关闭">×</button><span class="eyebrow">ROLLING TOWN · 小小收藏家</span><h2>${title}</h2>${body}</div>`);}
function homeScreen(){playing=false;paused=false;home=true;save.run=run&& !run.finished&&!homeWasDemo?run:save.run;persist();$('hud').hidden=$('hint').hidden=$('controls').hidden=true;const current=save.run?save.run.area:Math.min(save.unlocked,2);screen(`<div class="home"><div class="brand">A LITTLE WORLD TO COLLECT</div><h1>滚滚小镇</h1><p class="tagline">把小日子，滚成大世界</p><div class="edition"><span class="pill">3D 滚动收集</span><span class="pill">不用赶时间</span></div><div class="home-bottom"><div class="chapter"><div><small>CHAPTER 0${current+1} · ${save.book.length} / 36 收藏</small><h3>${AREAS[current].name}</h3></div><span class="stamp">✺</span></div><button class="primary" data-action="start">${save.run?'继续我的小旅程':'开始滚动'} <span>↗</span></button><div class="home-nav"><button data-action="areas">小镇地图</button><button data-action="book">收藏图鉴</button><button data-action="skins">球心衣橱</button><button data-action="settings">设置</button></div></div><div class="home-foot">一颗小球 · 三段旅程 · 无数小惊喜</div></div>`);}
let homeWasDemo=true;
function initWorld(r){run=r;world=createWorld(r.area,r.seed);grid=new SpatialGrid(world);view.build(r.area,world);view.restore(run);view.setSkin(save.skin);target=null;}
function start(area,mode='story',resume=false){const r=resume&&save.run?save.run:freshRun(area,mode,1234);initWorld(r);nearAt=0;writeAt=0;goalShown=false;homeWasDemo=false;home=false;playing=true;paused=false;save.run=run;screen('');$('hud').hidden=$('hint').hidden=$('controls').hidden=false;persist();updateHud();sound();}
function areasScreen(){sheet('每一站，都长大一点',`<p>沿着书桌、庭院和街区，一路收集生活里的小美好。</p>${AREAS.map((a,i)=>`<button class="area-card" data-action="area" data-value="${i}" ${i>save.unlocked?'disabled':''}><b>0${i+1}</b><span><strong>${a.name} ${i>save.unlocked?'· 未解锁':''}</strong><small>${i>save.unlocked?'完成前一区域的尺寸目标':a.subtitle} · ${'✦'.repeat(save.stars[i])}${'✧'.repeat(3-save.stars[i])}</small></span></button>`).join('')}${save.unlocked===3?'<button class="secondary" data-action="free">自由收集 · 奶油街区</button><button class="secondary" data-action="challenge">3 分钟挑战 · 阳光书桌</button>':''}<p class="note">进入另一场探索会替换当前旅程；已获得的图鉴与外观保留。</p>`);}
function bookScreen(){sheet('生活的小小博物馆',`<p>已经遇见 ${save.book.length} / 36 种小美好。首次收集即可点亮，并解锁新的球心配色。</p>${AREAS.map((a,i)=>`<div class="eyebrow">0${i+1} / ${a.name}</div><div class="grid">${a.names.map((n,j)=>`<div class="card ${save.book.includes(i*12+j)?'':'locked'}"><span class="emoji">${save.book.includes(i*12+j)?icons[j]:'?'}</span>${save.book.includes(i*12+j)?n:'尚未遇见'}<small>${save.book.includes(i*12+j)?'已收藏':'探索 '+a.name}</small></div>`).join('')}</div>`).join('')}`);}
function skinsScreen(){sheet('今天，是什么颜色？',`<p>每一种新发现，都会让旅程多一点颜色。</p><div class="grid">${SKINS.map((s,i)=>`<button class="card ${i===save.skin?'selected':''}" data-action="skin" data-value="${i}" ${save.book.length<s[2]?'disabled':''}><div class="skin" style="background:${s[1]}"></div>${s[0]}<small>${i===save.skin?'正在使用':save.book.length>=s[2]?'轻点换装':`收藏 ${s[2]} 种解锁`}</small></button>`).join('')}</div>`);}
function settingsScreen(){sheet('慢慢玩，刚刚好',`<div class="row">收集音效<button data-action="sound">${save.sound?'已开启':'已关闭'}</button></div><div class="row">减弱动态效果<button data-action="reduced">${save.reduced?'已开启':'已关闭'}</button></div><button class="secondary" data-action="tutorial">重新体验互动引导</button><p>下半屏摇杆控制移动，松手停下。比你小的物件会黏上球面，带着你一起长大。金色标记是隐藏收藏。</p><p class="note">原创美术与音效 · Three.js MIT<br>玩法灵感来自《块魂》（Katamari Damacy），非官方作品。进度仅保存在当前浏览器。</p>`);}
function pauseScreen(){paused=true;sheet('把这个午后暂停一下',`<p>${AREAS[run.area].name} · 已收集 ${run.collected.length} 件</p><button class="primary" data-action="resume">继续滚动 ↗</button><button class="secondary" data-action="result">查看本程收获</button><button class="secondary" data-action="home">保存并回到小镇</button>`,'resume');}
function resultScreen(){paused=true;const done=settle(save,run,world);persist();const count=done.filter(Boolean).length;sheet(done[0]?'小小的你，装下了大世界':'每一份收集，都算数',`<p>${AREAS[run.area].name} · ${run.mode==='challenge'?'3 分钟挑战': '本程收藏'}</p><div class="stat">${(radius(run.volume)*AREAS[run.area].scale).toFixed(1)} <small style="font-size:20px">${AREAS[run.area].unit}</small></div><p>${run.collected.length} 件小物 · 图鉴 ${save.book.length}/36 · ${'✦'.repeat(count)}${'✧'.repeat(3-count)}</p>${['达到区域目标尺寸','收集至少 150 件物品','找到全部 4 件金色收藏'].map((t,i)=>`<div class="task">${t}<span>${done[i]?'已完成 ✓':'继续探索'}</span></div>`).join('')}${run.finished?'': '<button class="secondary" data-action="resume">继续搜集这一站</button>'}${done[0]&&run.area<2?'<button class="primary" style="margin-top:16px" data-action="next">去下一站 ↗</button>':'<button class="primary" style="margin-top:16px" data-action="home">收好回忆，回到小镇</button>'}` ,run.finished?'home':'resume');}
$('panel').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,n=Number(b.dataset.value);switch(a){case'home':homeScreen();break;case'start':start(save.run?save.run.area:Math.min(2,save.unlocked),'story',!!save.run);break;case'areas':areasScreen();break;case'area':start(n);break;case'book':bookScreen();break;case'skins':skinsScreen();break;case'skin':save.skin=n;persist();view.setSkin(n);skinsScreen();break;case'settings':settingsScreen();break;case'sound':save.sound=!save.sound;persist();settingsScreen();break;case'reduced':save.reduced=!save.reduced;persist();settingsScreen();break;case'tutorial':save.tutorial=0;start(0);break;case'resume':if(run.finished){homeScreen();break;}paused=false;resetInput();screen('');break;case'result':resultScreen();break;case'next':start(run.area+1);break;case'free':start(2,'free');break;case'challenge':start(0,'challenge');break;}});
$('pause').onclick=pauseScreen;$('finish').onclick=resultScreen;$('skip').onclick=()=>{save.tutorial=5;persist();updateHud();};$('recenter').onclick=()=>{view.focus.set(run.x,radius(run.volume),run.z);toast('镜头已回到小球身边');};
const stick=$('stick');stick.addEventListener('pointerdown',e=>{if(!playing||paused||pointer!==null)return;pointer=e.pointerId;const b=stick.getBoundingClientRect();origin={x:b.left+b.width/2,y:b.top+b.height/2};stick.setPointerCapture(pointer);moveStick(e);sound(0);});function moveStick(e){if(e.pointerId!==pointer)return;e.preventDefault();const x=e.clientX-origin.x,y=e.clientY-origin.y,len=Math.hypot(x,y),factor=len>40?40/len:1;input.x=x*factor/40;input.y=y*factor/40;$('knob').style.transform=`translate(${input.x*32}px,${input.y*32}px)`;}stick.addEventListener('pointermove',moveStick);for(const event of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(event,e=>{if(e.pointerId===pointer)resetInput();});window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)&&playing&&!paused){e.preventDefault();keys.add(e.key);}if(e.key==='Escape'&&playing&&!run.finished)paused?($('panel').innerHTML='',paused=false):pauseScreen();});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>{resetInput();if(playing&&!paused)pauseScreen();});document.addEventListener('visibilitychange',()=>{if(document.hidden){resetInput();if(playing&&!paused)pauseScreen();persist();}});window.addEventListener('pagehide',persist);window.addEventListener('resize',resetInput);
let bumpedAt=0,goalShown=false;
function update(dt){run.elapsed+=dt;let ix=input.x+(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),iy=input.y+(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);const length=Math.hypot(ix,iy);if(length>1){ix/=length;iy/=length;}const r=radius(run.volume),speed=3.2+r*.85;const desiredX=(ix*.847+iy*.53)*speed,desiredZ=(-ix*.53+iy*.847)*speed,lerp=1-Math.exp(-dt*12);velocity.x+=(desiredX-velocity.x)*lerp;velocity.z+=(desiredZ-velocity.z)*lerp;const prevX=run.x,prevZ=run.z;let nx=run.x+velocity.x*dt,nz=run.z+velocity.z*dt;const result=moveAndCollect(run,world,grid,velocity.x*dt,velocity.z*dt);for(const o of result.collected){view.attach(o.id,r);if(!save.book.includes(o.key)){save.book.push(o.key);toast(`新发现 · ${AREAS[run.area].names[o.type]}  ${save.book.length}/36`);}else if(o.rare)toast('找到了金色收藏 ✦');sound(o.tier);if(save.tutorial===1)save.tutorial=2;persist();}if(result.blocked.length){const o=result.blocked[0];if(run.elapsed-bumpedAt>3){toast(`还差一点：长到 ${(o.need*AREAS[run.area].scale).toFixed(1)} ${AREAS[run.area].unit} 就能收集`);bumpedAt=run.elapsed;}if(save.tutorial===2)save.tutorial=3;}if(save.tutorial===0&&run.travel>1.2)save.tutorial=1;if(save.tutorial===2&&run.collected.length>=8)save.tutorial=3;if(save.tutorial===3&&radius(run.volume)>=1.38)save.tutorial=4;if(save.tutorial===4&&run.collected.some(id=>world[id].tier>0)){save.tutorial=5;persist();toast('学会啦！整个小镇都在等你探索');}if(run.elapsed-nearAt>.3){nearAt=run.elapsed;target=world.filter(o=>!run.collected.includes(o.id)&&o.need<=radius(run.volume)).sort((a,b)=>Math.hypot(a.x-run.x,a.z-run.z)-Math.hypot(b.x-run.x,b.z-run.z))[0];updateHud();}if(run.mode==='challenge'&&run.elapsed>=180){run.finished=true;save.run=null;resultScreen();}if(run.collected.length===world.length&&!run.finished){run.finished=true;save.run=null;resultScreen();}if(run.elapsed-writeAt>3){writeAt=run.elapsed;persist();}}
function updateHud(){const a=AREAS[run.area],r=radius(run.volume),done=r>=a.goal;$('areaLabel').textContent=`0${run.area+1} / ${a.name}`;$('diameter').textContent=(r*a.scale).toFixed(1);$('unit').textContent=a.unit;$('growth').style.width=`${Math.min(100,(r-1)/(a.goal-1)*100)}%`;$('goalLabel').textContent=done?'区域目标达成 · 还可以继续探索':`下一站目标 ${(a.goal*a.scale).toFixed(1)} ${a.unit}`;$('counter').textContent=run.mode==='challenge'?`${Math.max(0,180-Math.floor(run.elapsed))} 秒 · ${run.collected.length} 件`:`${run.collected.length} / ${world.length} 件`;$('finish').hidden=!done;if(done&&!goalShown){goalShown=true;toast('长大啦！新的区域已经触手可及');}if(!done)goalShown=false;const tutorial=['轻推下方摇杆，让小球动起来','靠近小物件，把它们黏到球上','更大的物件还推不动，先收集周围小物','继续收集，让小球长到 '+(a.scale*1.38).toFixed(1)+' '+a.unit,'现在试试收集更大的物件'];$('skip').hidden=save.tutorial>=5;$('hintTitle').textContent=save.tutorial<5?`小小练习 ${save.tutorial+1} / 5`:'下一份小惊喜';if(save.tutorial<5)$('hintText').textContent=tutorial[save.tutorial];else if(target){const dx=target.x-run.x,dz=target.z-run.z,sx=dx*.847-dz*.53,sy=dx*.53+dz*.847;const arrows=['→','↘','↓','↙','←','↖','↑','↗'];const direction=arrows[(Math.round(Math.atan2(sy,sx)/(Math.PI/4))+8)%8];$('hintText').textContent=`${direction} ${a.names[target.type]} · ${Math.hypot(dx,dz)<r+2?'就在身边':'沿着方向，慢慢靠近'}`;}else $('hintText').textContent='这一站的小美好，都被你收好啦';}
function loop(t){const dt=Math.min(.05,(t-last)/1000||.016);last=t;if(playing&&!paused)update(dt);if(view&&run){view.update(run,dt,home,save.reduced,target);if(firstFrame){view.camera.position.set(9,18,15);firstFrame=false;}}requestAnimationFrame(loop);}
try{view=new View($('scene'));initWorld(freshRun(0));run.volume=2.1;for(const id of [0,1,2,3,4,5,6,7,8,9])view.attach(id,radius(run.volume));homeScreen();requestAnimationFrame(loop);}catch(e){$('fatal').hidden=false;$('fatal').textContent='这个设备暂时无法启动 3D 场景。请更新小红书或浏览器后重试。';console.error(e);}
