export const AREAS = [
 {name:'阳光书桌',subtitle:'从一颗纽扣，开始收集世界',unit:'cm',scale:5,color:0xe9c7a2,start:1,goal:3.25,names:['纽扣','糖豆','橡皮','积木','铅笔','线团','茶杯','小书','玩具鸭','闹钟','小盆栽','音乐盒']},
 {name:'午后庭院',subtitle:'把整个午后，滚进怀里',unit:'cm',scale:30,color:0xadc5a0,start:1,goal:3.25,names:['草莓','小石头','蘑菇','小花','苹果','小铲子','花盆','皮球','喷水壶','小木凳','玩具车','野餐篮']},
 {name:'奶油街区',subtitle:'曾经仰望的街景，现在触手可及',unit:'m',scale:1.8,color:0xb5ccd1,start:1,goal:3.25,names:['甜甜圈','牛奶盒','路锥','邮包','路灯','树篱','长椅','自行车','贩卖机','小汽车','面包屋','钟楼']}
];
export const SKINS=[['蜜桃汽水','#ed987f',0],['薄荷奶糖','#89bdad',6],['柠檬布丁','#e9c762',12],['蓝莓苏打','#99accf',20],['草莓奶昔','#d995ad',28],['星光收藏家','#b4a0d0',36]];
export function rng(seed){let n=seed>>>0;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
export function createWorld(area=0,seed=1234){const rand=rng(seed+area*157),objects=[];let id=0;for(let tier=0;tier<4;tier++){for(let j=0;j<54;j++){const type=tier*3+j%3;let x,z;if(tier===0&&j<12){x=(j%3-1)*1.3;z=-2.3-Math.floor(j/3)*1.5;}else{const band=tier===0?Math.floor((j-12)/14):Math.floor(j/18);const rad=(tier===0?3.2:tier===1?8.7:tier===2?13.6:18.4)+band*(tier===3?.9:1.5)+(rand()-.5)*.5;const angle=(j%(tier===0?14:18))/(tier===0?14:18)*Math.PI*2+band*.27+(rand()-.5)*.12;x=Math.cos(angle)*rad;z=Math.sin(angle)*rad;}objects.push({id:id++,type,key:area*12+type,x,z,tier,need:[.88,1.38,2,2.7][tier],size:[.3,.48,.72,1.05][tier],volume:[.047,.13,.32,.63][tier],rare:j===53,angle:rand()*Math.PI*2});}}return objects;}
export function radius(volume){return Math.cbrt(volume);}
export function freshRun(area=0,mode='story',seed=1234){return{area,mode,seed,x:0,z:1,volume:1,collected:[],elapsed:0,travel:0,finished:false};}
export function collect(run,obj){if(run.finished||run.collected.includes(obj.id)||radius(run.volume)+1e-8<obj.need)return false;run.collected.push(obj.id);run.volume+=obj.volume;return true;}
export function tasks(run,world){return[radius(run.volume)>=AREAS[run.area].goal,run.collected.length>=150,world.filter(o=>o.rare&&run.collected.includes(o.id)).length===4];}
export function freshSave(){return{version:1,unlocked:0,book:[],stars:[0,0,0],skin:0,tutorial:0,sound:true,reduced:false,run:null,best:[0,0,0],challengeBest:0};}
export function settle(save,run,world){const done=tasks(run,world);const count=done.filter(Boolean).length;save.stars[run.area]=Math.max(save.stars[run.area],count);save.best[run.area]=Math.max(save.best[run.area],radius(run.volume));if(done[0])save.unlocked=Math.min(3,Math.max(save.unlocked,run.area+1));if(run.mode==='challenge')save.challengeBest=Math.max(save.challengeBest,run.collected.length);return done;}
export function validateSave(raw){try{if(!raw||raw.version!==1)return freshSave();const s=freshSave();s.unlocked=Math.max(0,Math.min(3,Number(raw.unlocked)||0));s.book=[...new Set((raw.book||[]).filter(x=>Number.isInteger(x)&&x>=0&&x<36))];s.stars=s.stars.map((_,i)=>Math.max(0,Math.min(3,Number(raw.stars?.[i])||0)));s.best=s.best.map((_,i)=>Math.max(0,Number(raw.best?.[i])||0));s.skin=Number.isInteger(raw.skin)&&SKINS[raw.skin]&&s.book.length>=SKINS[raw.skin][2]?raw.skin:0;s.tutorial=Math.min(5,Math.max(0,Number(raw.tutorial)||0));s.sound=raw.sound!==false;s.reduced=!!raw.reduced;s.challengeBest=Math.max(0,Number(raw.challengeBest)||0);if(raw.run&&Number.isInteger(raw.run.area)&&raw.run.area>=0&&raw.run.area<=Math.min(2,s.unlocked)&&['story','free','challenge'].includes(raw.run.mode)){const r=freshRun(raw.run.area,raw.run.mode,Number(raw.run.seed)||1234);const world=createWorld(r.area,r.seed);for(const id of raw.run.collected||[]){const obj=world.find(o=>o.id===id);if(!obj||!collect(r,obj))return s;}for(const k of ['x','z'])r[k]=Number.isFinite(raw.run[k])?Math.max(-22,Math.min(22,raw.run[k])):0;r.elapsed=Math.max(0,Number(raw.run.elapsed)||0);r.travel=Math.max(0,Number(raw.run.travel)||0);s.run=r;}return s;}catch{return freshSave();}}
export class SpatialGrid{constructor(objects,cell=4){this.cell=cell;this.map=new Map();for(const o of objects){const k=this.key(o.x,o.z);if(!this.map.has(k))this.map.set(k,[]);this.map.get(k).push(o);}}key(x,z){return`${Math.floor(x/this.cell)},${Math.floor(z/this.cell)}`;}near(x,z,r){const out=[];for(let a=Math.floor((x-r)/this.cell);a<=Math.floor((x+r)/this.cell);a++)for(let b=Math.floor((z-r)/this.cell);b<=Math.floor((z+r)/this.cell);b++)out.push(...(this.map.get(`${a},${b}`)||[]));return out;}}
export function moveAndCollect(run,world,grid,dx,dz){const r=radius(run.volume),oldX=run.x,oldZ=run.z;let nx=run.x+dx,nz=run.z+dz;const collected=[],blocked=[];const candidates=grid.near(nx,nz,r+2);for(let pass=0;pass<3;pass++)for(const o of candidates){if(run.collected.includes(o.id))continue;const vx=nx-o.x,vz=nz-o.z,dist=Math.hypot(vx,vz),contact=r+o.size*.42;if(dist>contact)continue;if(collect(run,o)){collected.push(o);}else{const penetration=contact-dist;if(dist>.001){nx+=vx/dist*penetration;nz+=vz/dist*penetration;}else nx+=contact;if(pass===0)blocked.push(o);}}run.x=Math.max(-22+r*.25,Math.min(22-r*.25,nx));run.z=Math.max(-22+r*.25,Math.min(22-r*.25,nz));run.travel+=Math.hypot(run.x-oldX,run.z-oldZ);return{collected,blocked};}
