/* Original Mosaic implementation. 0 undecided, 1 counting tile, 2 backing tile. */
const Tessera = (() => {
 const neighbours=(l,i)=>{if(!Number.isInteger(i)||i<0||i>=l.width*l.height)return [];const a=[],y=Math.floor(i/l.width),x=i%l.width;for(let r=Math.max(0,y-1);r<=Math.min(l.height-1,y+1);r++)for(let c=Math.max(0,x-1);c<=Math.min(l.width-1,x+1);c++)a.push(r*l.width+c);return a;};
 function evaluate(l,b){if(!Array.isArray(b)||b.length!==l.width*l.height||b.some(v=>![0,1,2].includes(v)))return {valid:false,complete:false};const clues=[];l.clues.forEach((target,i)=>{if(target===null)return;const area=neighbours(l,i),black=area.filter(j=>b[j]===1).length,empty=area.filter(j=>b[j]===0).length;clues.push({index:i,target,area,black,empty,impossible:black>target||black+empty<target,settled:black===target&&empty===0});});const empty=b.filter(v=>v===0).length;return {valid:true,empty,clues,complete:empty===0&&clues.every(c=>c.black===c.target)};}
 function move(l,b,i,tool){const e=evaluate(l,b);if(!e.valid||e.complete||!Number.isInteger(i)||i<0||i>=b.length||!['black','white','clear'].includes(tool))return null;const n=tool==='clear'?0:(b[i]+(tool==='black'?1:2))%3;if(n===b[i])return null;const a=b.slice();a[i]=n;return a;}
 function replay(l,history){if(!Array.isArray(history)||history.length>4096)return null;let b=Array(l.width*l.height).fill(0);for(const m of history){if(!m)return null;b=move(l,b,m.index,m.tool);if(!b)return null;}return b;}
 function deduction(l,b,subset=true){const e=evaluate(l,b),bad=e.clues.find(c=>c.impossible);if(bad)return {conflict:true,clue:bad.index,text:'这个数字已不可能满足，请撤销或改片。'};const cs=e.clues.map(c=>({index:c.index,vars:c.area.filter(i=>b[i]===0),need:c.target-c.black})).filter(c=>c.vars.length);for(const c of cs)if(c.need===0||c.need===c.vars.length)return {index:c.vars[0],value:c.need===0?2:1,clue:c.index,kind:'direct',text:`目标还需 ${c.need} 枚彩片，未定 ${c.vars.length} 格；这些格全部${c.need===0?'是底片':'是彩片'}。`};if(subset)for(const a of cs)for(const c of cs){if(a===c||a.vars.length>=c.vars.length||!a.vars.every(i=>c.vars.includes(i)))continue;const diff=c.vars.filter(i=>!a.vars.includes(i)),n=c.need-a.need;if(n===0||n===diff.length)return {index:diff[0],value:n===0?2:1,clue:c.index,other:a.index,kind:'subset',common:a.vars.slice(),difference:diff.slice(),remainingA:c.need,remainingB:a.need,text:`A 的未定 ${c.vars.length} 格还需 ${c.need} 枚彩片；B 的公共 ${a.vars.length} 格还需 ${a.need} 枚。相减 ${c.need} − ${a.need} = ${n}，余下 ${diff.length} 格全部${n===0?'是底片':'是彩片'}。`};}return null;}
 return {neighbours,evaluate,move,replay,deduction};
})();
if(typeof module!=='undefined')module.exports=Tessera;
