import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {satisfied,validateLevel,createState,apply,undo,evaluate,replay,candidates,hint} from '../src/engine.js';
import {solve,canonical} from '../scripts/oracle.mjs';
import {fresh,restore,newRun,record,settle,flush,outbox,dailyIndex} from '../src/session.js';
const data=JSON.parse(fs.readFileSync(new URL('../data/campaign.json',import.meta.url))),levels=data.levels;
const solved=l=>replay(l,l.answer.map((value,cell)=>({type:'fill',cell,value})));
test('60 validated unique puzzles, six chapters, distinct geometry/operator classes',()=>{assert.equal(levels.length,60);assert.equal(new Set(levels.map(l=>canonical(l,true))).size,60);for(let ch=0;ch<6;ch++){const group=levels.filter(l=>l.chapter===ch);assert.equal(group.length,10);assert.deepEqual(group.map(l=>l.stage),['概念','概念',...Array(6).fill('组合'),'综合','综合']);}for(const l of levels){assert.ok(validateLevel(l));const proof=solve(l);assert.equal(proof.count,1,l.id);assert.ok(proof.exhausted);assert.deepEqual(proof.solutions[0],l.answer);assert.ok(evaluate(l,solved(l)).complete);}});
test('arithmetic boundaries, integer division, same cage repeated digits',()=>{assert.ok(satisfied({cells:[0,1],op:'-',target:2},[1,3]));assert.ok(satisfied({cells:[0,1],op:'/',target:2},[4,2]));assert.ok(!satisfied({cells:[0,1],op:'/',target:1},[3,2]));assert.ok(!satisfied({cells:[0,1],op:'/',target:0},[0,2]));assert.ok(satisfied({cells:[0,4],op:'+',target:2},[1,0,0,0,1]));const p={n:3,cages:[{cells:[0,1,4],op:'+',target:4},{cells:[2,5],op:'+',target:5},{cells:[3,6],op:'+',target:5},{cells:[7,8],op:'+',target:4}]};const v=[1,2,3,3,1,2,2,3,1];assert.ok(evaluate(p,{values:v}).complete);assert.ok(solve(p).count>0);});
test('oracle detects multiple solutions and unsatisfiable constraints independently',()=>{const p={n:3,cages:[{cells:[0,1,2,3,4,5,6,7,8],op:'+',target:18}]};assert.equal(solve(p).count,2);p.cages[0].target=1;assert.equal(solve(p).count,0);});
test('empty, full wrong, malformed boards never complete',()=>{for(const l of levels){assert.ok(!evaluate(l,createState(l)).complete);assert.ok(!evaluate(l,{values:Array(l.n*l.n).fill(1)}).complete);assert.ok(!evaluate(l,{values:l.answer.slice(1)}).complete);assert.ok(!evaluate(l,{values:l.answer.map(()=>NaN)}).complete);}});
test('illegal input atomic no-op; note undo restores entire state; notes cannot win',()=>{const l=levels[0],s=createState(l);for(const a of [{type:'fill',cell:-1,value:1},{type:'fill',cell:0,value:4},{type:'x',cell:0,value:1},{type:'note',cell:0,value:0}])assert.equal(apply(l,s,a),s);const n=apply(l,s,{type:'note',cell:0,value:2});assert.deepEqual(undo(n),s);const f=apply(l,n,{type:'fill',cell:0,value:1});assert.equal(f.notes[0],0);assert.deepEqual(undo(f),n);assert.equal(apply(l,f,{type:'note',cell:0,value:2}),f);assert.ok(!evaluate(l,n).complete);assert.equal(replay(l,[{type:'undo'}]),null);});
test('candidate hints preserve true solution and never mutate',()=>{for(const l of levels){const s=createState(l),snapshot=JSON.stringify(s);for(let i=0;i<s.values.length;i++)assert.ok(candidates(l,s,i).includes(l.answer[i]));assert.ok(hint(l,s).text);assert.equal(JSON.stringify(s),snapshot);}});
test('restore replays history and ignores forged win flags, claims and corrupted data',()=>{const l=levels[0],d=fresh(),r=newRun();let s=createState(l);l.answer.forEach((value,cell)=>s=record(l,r,s,{type:'fill',cell,value}));d.sessions[l.id]=r;settle(d,l,r,s);const round=restore(JSON.stringify(d),levels);assert.deepEqual(round,d);assert.equal(Object.keys(restore('{bad',levels).completed).length,0);assert.equal(Object.keys(restore({version:1,completed:{[l.id]:{runId:r.runId,events:[],complete:true}}},levels).completed).length,0);const forged=JSON.parse(JSON.stringify(d));forged.completed[l.id].events[0].value=100;forged.ack=['forged'];assert.equal(Object.keys(restore(forged,levels).completed).length,0);assert.deepEqual(restore(forged,levels).ack,[]);});
test('settlement first-only, persistence precedes host, failed retries retain IDs',async()=>{const l=levels[0],d=fresh(),r=newRun();let s=createState(l);l.answer.forEach((value,cell)=>s=record(l,r,s,{type:'fill',cell,value}));assert.ok(settle(d,l,r,s));assert.ok(!settle(d,l,newRun(),s));const payload=outbox(d)[0],calls=[];await flush(d,()=>{calls.push('persist');return true;},e=>{calls.push(e);throw Error('offline');});assert.equal(calls[0],'persist');assert.deepEqual(outbox(d)[0],payload);await flush(d,()=>true,e=>e.rewardClaimId);assert.equal(outbox(d).length,0);const before=calls.length;await flush(d,()=>false,()=>calls.push('unexpected'));assert.equal(calls.length,before);});
test('daily rotates at Beijing midnight and cycles every sixty days',()=>{const a=new Date('2026-09-20T15:59:59Z'),b=new Date('2026-09-20T16:00:00Z');assert.equal(dailyIndex(b,60),(dailyIndex(a,60)+1)%60);assert.equal(dailyIndex(b,60),dailyIndex(new Date(b.getTime()+60*86400000),60));});
test('tutorial states follow the production action path and independent oracle',()=>{const l=levels[0],s=createState(l),one=apply(l,s,{type:'fill',cell:0,value:l.answer[0]});assert.equal(one.values.filter(Boolean).length,1);assert.ok(!evaluate(l,s).complete);assert.ok(!evaluate(l,one).complete);assert.ok(evaluate(l,solved(l)).complete);});
test('independent exhaustive Latin-square enumeration agrees for every 3x3 board',()=>{
 const permutations=[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]],latins=[];
 for(const a of permutations)for(const b of permutations)for(const c of permutations)if(a.every((v,j)=>v!==b[j]&&v!==c[j]&&b[j]!==c[j]))latins.push(a.concat(b,c));assert.equal(latins.length,12);
 for(const l of levels.filter(l=>l.n===3)){
  const matches=latins.filter(v=>l.cages.every(c=>{const a=c.cells.map(i=>v[i]);return c.op==='='?a[0]===c.target:c.op==='+'?a.reduce((x,y)=>x+y,0)===c.target:c.op==='*'?a.reduce((x,y)=>x*y,1)===c.target:c.op==='-'?Math.abs(a[0]-a[1])===c.target:Math.max(...a)===Math.min(...a)*c.target;}));assert.equal(matches.length,1);assert.deepEqual(matches[0],solve(l).solutions[0]);
 }
});
test('bad level structures rejected; full conflicts remain editable and undoable',()=>{const l=levels[0];assert.ok(!validateLevel({n:3,cages:[{cells:[0,0],op:'+',target:3}]}));assert.ok(!validateLevel({n:3,cages:[{cells:[0,4],op:'-',target:2}]}));const s=solved(l),bad=apply(l,s,{type:'fill',cell:0,value:s.values[1]});assert.ok(!evaluate(l,bad).complete);assert.deepEqual(undo(bad),s);});
test('ack persistence failure retries the same payload and discards unverified acknowledgments',async()=>{const l=levels[0],d=fresh(),r=newRun();let s=createState(l);l.answer.forEach((value,cell)=>s=record(l,r,s,{type:'fill',cell,value}));settle(d,l,r,s);let writes=0;const first=outbox(d)[0];await flush(d,()=>++writes===1,e=>e.rewardClaimId);assert.deepEqual(outbox(d)[0],first);const seen=[];await flush(d,()=>true,e=>{seen.push(e);return e.rewardClaimId;});assert.deepEqual(seen,[first]);assert.equal(outbox(d).length,0);});
