import {createRequire} from 'node:module';import {writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
import {LEVELS} from '../src/levels.mjs';import {SAVE_KEY,TUTORIAL_KEY,newSession,changeSession,finish,loadSave} from '../src/session.mjs';
const require=createRequire(import.meta.url);let chromium;try{({chromium}=require('playwright'));}catch(e){({chromium}=require(process.env.PLAYWRIGHT_PATH||(process.env.HOME||'')+'/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const browser=await chromium.launch({channel:'chrome',headless:true});const report={checks:[],layouts:[],errors:[],externalRequests:[],engine:browser.version(),boundary:'desktop Chrome responsive simulation; not physical phones'};
const origin='http://127.0.0.1:4197';
function track(page){page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin))report.externalRequests.push(r.url());});}
async function noOverflow(p){assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);}
try{
 for(const width of [320,359,360,390,599,600,601,1280]){const context=await browser.newContext({viewport:{width,height:width===390?844:720},hasTouch:width<600,isMobile:width<600,reducedMotion:'reduce'});const page=await context.newPage();track(page);
 await page.addInitScript(()=>{document.addEventListener('DOMContentLoaded',()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');});});
 await page.goto(origin);assert.equal(await page.getByRole('dialog').count(),1);await noOverflow(page);
 for(let step=0;step<3;step++){assert.equal(await page.locator('.modal .cell').count(),16);if(width===320)await page.screenshot({path:'release/tutorial-'+step+'-320.png'});await page.getByRole('button',{name:step===2?'开始清印':'下一张',exact:true}).click();}
 assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await page.evaluate(()=>document.body.style.overflow),'');await noOverflow(page);
 await page.getByRole('button',{name:/卷 六/}).click();await page.locator('[data-id="ma-v1-60"]').click();await noOverflow(page);
 const cells=await page.locator('.cell').evaluateAll(es=>es.map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right})));
 assert.ok(cells.every(b=>b.width>=44&&b.height>=44&&b.left>=0&&b.right<=width),JSON.stringify({width,cells:cells[0]}));
 await page.locator('[data-cell="0"]').click();await page.getByRole('button',{name:'○ 圈注',exact:true}).click();assert.ok(await page.locator('[data-cell="0"]').evaluate(e=>e.classList.contains('marked')));
 await page.getByRole('button',{name:'↶ 撤销',exact:true}).click();assert.ok(await page.locator('[data-cell="0"]').evaluate(e=>e.classList.contains('white')));
 await page.getByRole('button',{name:'一点提示',exact:true}).click();await noOverflow(page);if(width===320)await page.screenshot({path:'release/hint-320.png'});await page.getByRole('button',{name:'自己再想想',exact:true}).click();
 await page.getByRole('button',{name:'玩法',exact:true}).click();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'玩法');
 if([320,390,1280].includes(width))await page.screenshot({path:'release/play-6x6-'+width+'.png',fullPage:true});
 report.layouts.push({width,height:width===390?844:720,safeAreaTop:44,safeAreaBottom:34,minCellWidth:Math.min(...cells.map(x=>x.width)),noHorizontalOverflow:true});await context.close();}
 report.checks.push('8 viewport/breakpoint widths; safe areas 44/34; 6x6 targets >=44px; tutorial/hint fit; reduced motion; modal focus restore');
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage();track(page);await page.goto(origin);await page.getByRole('button',{name:'跳过',exact:true}).click();await page.screenshot({path:'release/home-390.png',fullPage:true});
 await page.getByRole('button',{name:'翻开第一页',exact:true}).click();await page.locator('[data-cell="0"]').tap();await page.getByRole('button',{name:'○ 圈注',exact:true}).tap();await page.reload();await page.getByRole('button',{name:'继续清印',exact:true}).click();assert.ok(await page.locator('[data-cell="0"]').evaluate(e=>e.classList.contains('marked')));await page.getByRole('button',{name:'↶ 撤销',exact:true}).click();
 await page.locator('[data-cell="0"]').click();await page.keyboard.press('c');assert.ok(await page.locator('[data-cell="0"]').evaluate(e=>e.classList.contains('marked')));await page.keyboard.press('z');
 await page.getByRole('button',{name:'重开本页',exact:true}).click();await page.getByRole('button',{name:'继续这局',exact:true}).click();await page.screenshot({path:'release/play-390.png'});
 for(let i=0;i<16;i++)if(LEVELS[0].solution[i]){await page.locator('[data-cell="'+i+'"]').tap();await page.getByRole('button',{name:'╳ 遮黑',exact:true}).tap();}
 assert.equal(await page.locator('.win').count(),1);await page.screenshot({path:'release/completed-390.png',fullPage:true});let saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),SAVE_KEY);assert.equal(Object.keys(saved.records).length,1);assert.equal(saved.outbox.length,1);const completionId=saved.outbox[0].session.runId;
 await page.reload();await page.getByRole('button',{name:'继续清印',exact:true}).click();saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),SAVE_KEY);assert.equal(saved.outbox.length,1);assert.equal(saved.outbox[0].session.runId,completionId);
 await page.getByRole('button',{name:'重开本页',exact:true}).click();await page.getByRole('button',{name:'重开本页',exact:true}).last().click();assert.equal(await page.locator('.black').count(),0);
 for(let i=0;i<16;i++)if(LEVELS[0].solution[i]){await page.locator('[data-cell="'+i+'"]').click();await page.keyboard.press('b');}
 saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),SAVE_KEY);assert.equal(saved.outbox.length,1);report.checks.push('touch + keyboard complete; reload replay; undo/restart; same-run and replay reward deduplication');
 await page.getByRole('button',{name:'← 书斋',exact:true}).click();await page.getByRole('button',{name:'每日清印',exact:true}).click();assert.match(await page.locator('.play-top').innerText(),/每日清印/);await page.getByRole('button',{name:'一点提示',exact:true}).click();await page.getByRole('button',{name:/按提示遮黑|恢复这格/}).click();saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),SAVE_KEY);assert.equal(saved.session.hints,1);
 // Verified fixtures for maximum collection layout, not a claim of manual sixty-level play.
 const data={};const memory={getItem:k=>data[k]||null,setItem:(k,v)=>data[k]=v};const all=loadSave(memory,LEVELS);for(const p of LEVELS){let s=newSession(p);p.solution.forEach((v,i)=>{if(v)s=changeSession(p,s,i,1);});all.session=s;finish(all,p,memory);}await page.evaluate(([key,value])=>localStorage.setItem(key,value),[SAVE_KEY,JSON.stringify(all)]);await page.reload();await page.getByRole('button',{name:'我的书架',exact:true}).click();assert.equal(await page.locator('.library-card.earned').count(),6);await noOverflow(page);await page.screenshot({path:'release/collection-full-390.png',fullPage:true});report.checks.push('daily/hint flow; all six collections layout using validated completion fixtures');
 await page.evaluate(key=>localStorage.setItem(key,'{bad'),SAVE_KEY);await page.reload();assert.equal(await page.getByRole('dialog').count(),0);assert.match(await page.locator('body').innerText(),/已清印 0 \/ 60/);report.checks.push('corrupt save recovers without wiping tutorial preference');
 await context.close();
 const blocked=await browser.newContext({viewport:{width:320,height:720}});const bp=await blocked.newPage();track(bp);await bp.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('quota');};});await bp.goto(origin);await bp.getByRole('button',{name:'跳过',exact:true}).click();await bp.getByRole('button',{name:'翻开第一页',exact:true}).click();assert.equal(await bp.locator('.save-warning').count(),1);await blocked.close();report.checks.push('storage failure remains playable and visibly reported');
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.externalRequests,[]);report.status='PASS';
} catch(e){report.status='FAIL';report.failure=e.stack;throw e;}finally{writeFileSync('release/browser-qa.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
