(function(){'use strict';
var E=Astral,L=ASTRAL_LEVELS,key='mini-polish:astral-turn-gallery:v1:',tutorial='astral-turn-gallery-tutorial-v1',screen=document.getElementById('screen'),overlay=document.getElementById('overlay'),dialog=document.getElementById('dialog'),db,level,s,zone=0,busy=false,view='home',chapter=1,lastFocus,step=0,hintData=null,storageOK=true;
var chapters=['启开星窗','回到原位','交错回廊','守住一角','星序穿行','穹顶复位'],artifacts=['星窗罗盘','逆行齿轮','双环仪','角星徽章','黄道仪','穹顶星球'],symbols=['✧','◈','◎','✦','☼','✺'];
function read(k){try{return localStorage.getItem(key+k);}catch(e){storageOK=false;return null;}}
function write(k,v){try{localStorage.setItem(key+k,v);return true;}catch(e){storageOK=false;return false;}}
db=E.load(read('save'),L);
function save(){db.current=s||db.current;return write('save',JSON.stringify(db));}
function deliver(){if(!storageOK||typeof window.astralCompletionHost!=='function')return;db.outbox=db.outbox.filter(function(e){try{return window.astralCompletionHost(e)!==true;}catch(err){return true;}});save();}
function button(label,action,cls,extra){return '<button data-action="'+action+'" class="'+(cls||'')+'" '+(extra||'')+'>'+label+'</button>';}
function boardHTML(b,z,interactive){var p=Math.floor(z/3)*4+z%3,sel=[p,p+1,p+4,p+5];return '<div class="board" role="group" aria-label="星仪排列：'+b.join('、')+'">'+b.map(function(n,i){return '<div class="tile '+(n===i+1?'correct ':'')+(sel.includes(i)?'selected':'')+'" data-cell="'+i+'">'+n+'</div>';}).join('')+(interactive?'<div class="window-overlay">'+Array.from({length:9},function(_,i){return button('<span>'+(i+1)+'</span>','zone-'+i,'window-dot','aria-label="'+(Math.floor(i/3)+1)+'行 '+(i%3+1)+'列" aria-pressed="'+(z===i)+'" style="left:calc('+(i%3+1)*25+'% + '+((i%3-1)*1.5)+'px);top:calc('+(Math.floor(i/3)+1)*25+'% + '+((Math.floor(i/3)-1)*1.5)+'px)"');}).join('')+'</div>':'')+'</div>';}
function count(ch){return L.filter(function(l){return (!ch||l.chapter===ch)&&db.proofs[l.id];}).length;}
function notice(){return storageOK?'':'<p class="notice" role="status">本机存储不可用，本次进度无法保留。</p>';}
function home(){view='home';screen.innerHTML='<section class="hero"><div class="ornament">✧</div><small>机械天文馆 · 星序修复计划</small><h2>只转四格，重整星河</h2><p>相邻四枚星仪，每一次旋转都彼此牵动。</p>'+button(db.current?'继续校准':'开启第一扇星窗','continue','primary')+'<p class="notice">已修复 '+count()+' / 60 · 六段回廊</p></section><div class="actions">'+button('每日校准','daily')+button('机械藏品 · '+chapters.filter(function(_,i){return count(i+1)===10;}).length,'collection')+'</div><div class="section-head row"><h3>探索回廊</h3><small>06 CHAPTERS</small></div><div class="chapters">'+chapters.map(function(n,i){return button('<b>CHAPTER 0'+(i+1)+'</b><h3>'+n+'</h3><span>'+count(i+1)+' / 10 已归位</span><div class="chapter-progress"><i style="width:'+count(i+1)*10+'%"></i></div>','chapter-'+(i+1),'chapter');}).join('')+'</div>'+notice();}
function map(ch){view='map';chapter=ch;screen.innerHTML='<div class="row">'+button('‹ 回廊','home')+'<small>CHAPTER 0'+ch+'</small></div><div class="section-head"><h2>'+chapters[ch-1]+'</h2><p class="muted">'+L[(ch-1)*10].lesson+'</p></div><div class="levels">'+L.filter(function(l){return l.chapter===ch;}).map(function(l){var p=db.proofs[l.id];return button(String((l.chapter-1)*10+l.index).padStart(2,'0')+'<br><small>'+(p?(p.assisted?'辅助 ✓':'独立 ✓'):'待校准')+'</small>','level-'+l.id,p?'done':'');}).join('')+'</div><p class="muted">每关都可自由挑战。完整修复本章十扇星窗，即可收藏「'+artifacts[ch-1]+'」。</p>'+notice();}
function start(l,mode,resume){level=l;s=resume||E.session(l,'r-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,9),mode);zone=0;hintData=null;save();play();}
function play(){view='play';var b=E.board(level,s),done=E.won(b),aligned=b.filter(function(n,i){return n===i+1;}).length,best=db.proofs[level.id];screen.innerHTML='<div class="row">'+button('‹ 选关','back-map')+'<small>'+(s.mode==='daily'?'每日校准 · ':'')+String((level.chapter-1)*10+level.index).padStart(2,'0')+' / 60</small></div><div class="section-head"><small>CHAPTER 0'+level.chapter+'</small><h2>'+level.title+'</h2></div><div class="play-layout"><section><div class="instrument"><div class="dial-top">✦ ASTROLABE ✦</div>'+boardHTML(b,zone,!done)+'<div class="board-caption">金色框：当前旋转窗口 · 角点：已归位</div></div><div class="stats"><span><strong>'+s.history.length+'</strong>步</span><span><strong>'+aligned+'</strong>/ 16 归位</span><span>'+(s.assisted?'辅助校准':'独立校准')+'</span></div><p class="notice">参考回放 '+level.reference+' 步'+(level.metrics.exactShortest?' · 已证明最短 '+level.metrics.exactShortest+' 步':'（不代表最短）')+(best?' · 个人记录 '+best.history.length+' 步'+(best.assisted?'（辅助）':'（独立）'):'')+'</p></section><section class="controls"><h3>点交点选窗，再旋转四枚星仪</h3><div class="actions turns">'+button('↶ 逆时针','ccw','',done?'disabled':'')+button('顺时针 ↷','cw','primary',done?'disabled':'')+'</div><div class="actions">'+button('撤销','undo','',s.history.length?'':'disabled')+button('重开','restart')+button('提示','hint','',done?'disabled':'')+'</div><p class="notice">'+level.lesson+'。键盘：1–9 选窗，← / → 旋转，Z 撤销。</p><div id="hint-area"></div>'+(done?'<div class="success" role="status"><h3>✺ 穹顶已点亮</h3><p>16 枚星仪全部归位 · '+(s.assisted?'本次使用了辅助':'本次独立完成')+'</p>'+button('下一扇星窗','next','primary')+'</div>':'')+'</section></div>'+notice();if(hintData)showHint();}
function rotate(dir){if(busy||view!=='play'||E.won(E.board(level,s)))return;var move=[zone,dir],p=Math.floor(zone/3)*4+zone%3,ring=[p,p+1,p+5,p+4],nodes=screen.querySelectorAll('.tile');busy=true;
if(!E.apply(level,s,move)){busy=false;return;}hintData=null;var reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduced){ring.forEach(function(c,i){var n=nodes[c],to=nodes[ring[(i+dir+4)%4]],a=n.getBoundingClientRect(),b=to.getBoundingClientRect();n.classList.add('moving');n.style.transform='translate('+(b.left-a.left)+'px,'+(b.top-a.top)+'px)';});}
setTimeout(function(){if(E.won(E.board(level,s)))E.completion(level,s,db);save();busy=false;play();deliver();},reduced?0:260);}
function showHint(){var h=hintData;if(!h)return;document.getElementById('hint-area').innerHTML='<div class="hint"><p>'+(h.kind==='undo'?'当前盘面偏离参考路线。建议先撤销最后一步，逐步返回可解释的参考状态；不会偷偷重置棋盘。':'当前盘面在已验证的参考路线中。选择第 '+(Math.floor(h.move[0]/3)+1)+' 行、第 '+(h.move[0]%3+1)+' 列窗口，'+(h.move[1]===1?'顺时针':'逆时针')+'旋转一次。四枚星仪会循环移动。')+'</p>'+button(h.kind==='undo'?'采用：撤销一步':'采用这一步','use-hint','primary')+'</div>';}
function collection(){view='collection';screen.innerHTML=button('‹ 回廊','home')+'<div class="section-head"><h2>机械藏品室</h2><p class="muted">修复整章，留下属于你的天文馆纪念。</p></div>'+artifacts.map(function(n,i){var unlocked=count(i+1)===10;return '<section class="collection"><span class="artifact">'+(unlocked?symbols[i]:'◇')+'</span><h3>'+n+'</h3><p class="muted">'+(unlocked?'已收藏 · '+chapters[i]+'全部归位':chapters[i]+' · '+count(i+1)+'/10，完成本章后收藏')+'</p></section>';}).join('');}
var tut=L[9],tutBoards=[tut.board,E.rotate(tut.board,tut.solution[0]),E.replay(tut.board,tut.solution)];
function openTutorial(){if(busy)return;lastFocus=document.activeElement;step=0;overlay.hidden=false;document.body.classList.add('modal');tutorialCard();}
function tutorialCard(){var m=tut.solution[0];dialog.innerHTML='<div class="step">星仪入门 · '+(step+1)+' / 3</div><h2 id="dialog-title">'+['看懂一扇星窗','四枚一起转动','让星序重新归位'][step]+'</h2>'+boardHTML(tutBoards[step],step===2?-20:m[0])+'<p>'+['这是一道真实三步题。数字最终按从左到右、从上到下排列为 1–16。金框圈住相邻的四枚星仪。','同一道题已执行一次'+(m[1]===1?'顺时针':'逆时针')+'旋转。四枚数字沿窗口中心转动90°，其他数字不动。','完整回放三步后，每个数字回到目标位置。可以撤销、重开，或先阅读提示，再决定是否采用。'][step]+'</p><div class="actions">'+button('跳过 / 关闭','close-tutorial')+button(step===2?'开始校准':'下一张','tutorial-next','primary')+'</div><p class="rule">规则原型：Simon Tatham 的 Twiddle。主题与界面为独立设计，AI 辅助开发。无空格滑动，无任意交换。每日题按本地日期从60关循环选取。</p>';dialog.scrollTop=0;dialog.focus();}
function closeTutorial(){overlay.hidden=true;document.body.classList.remove('modal');write(tutorial,'seen');if(lastFocus&&document.contains(lastFocus))lastFocus.focus();else document.getElementById('help').focus();}
function action(a){if(a==='close-tutorial'){closeTutorial();return;}if(a==='tutorial-next'){if(step<2){step++;tutorialCard();}else closeTutorial();return;}if(busy||!overlay.hidden)return;
if(a==='home')home();else if(a==='collection')collection();else if(a.indexOf('chapter-')===0)map(Number(a.slice(8)));else if(a.indexOf('level-')===0)start(L.find(function(l){return l.id===a.slice(6);}),'campaign');else if(a==='continue'){var r=db.current,l=r&&L.find(function(v){return v.id===r.levelId;});start(l||L[0],r?r.mode:'campaign',r||null);}else if(a==='daily'){var d=new Date(),n=Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/86400000);start(L[((n%60)+60)%60],'daily');}else if(view==='play'){
if(a==='back-map')map(level.chapter);else if(a.indexOf('zone-')===0){zone=Number(a.slice(5));play();}else if(a==='cw'||a==='ccw')rotate(a==='cw'?1:-1);else if(a==='undo'){s.history.pop();hintData=null;save();play();}else if(a==='restart')start(level,s.mode);else if(a==='hint'){hintData=E.hint(level,s);showHint();}else if(a==='use-hint'&&hintData){s.assisted=true;var h=hintData;hintData=null;if(h.kind==='undo'){s.history.pop();save();play();}else{zone=h.move[0];play();rotate(h.move[1]);}}else if(a==='next')start(L[(L.indexOf(level)+1)%60],s.mode);}}
document.addEventListener('click',function(e){var b=e.target.closest('button[data-action]');if(b&&!b.disabled)action(b.getAttribute('data-action'));});document.getElementById('help').addEventListener('click',openTutorial);
document.addEventListener('keydown',function(e){if(!overlay.hidden){if(e.key==='Escape')closeTutorial();if(e.key==='Tab'){var bs=dialog.querySelectorAll('button'),first=bs[0],last=bs[bs.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===dialog)){e.preventDefault();first.focus();}}return;}if(view!=='play'||busy)return;if(/^[1-9]$/.test(e.key)){zone=Number(e.key)-1;play();}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();rotate(e.key==='ArrowRight'?1:-1);}else if(e.key.toLowerCase()==='z')action('undo');});home();if(!read(tutorial))openTutorial();deliver();
}());
