import {LEVELS,CHAPTERS} from './levels.mjs';
import {initial,change,inspect,pathState,tileName,TILES,DIRS,neighbor} from './engine.mjs';
import {boardSvg,rail,tutorialStates} from './render.mjs';
import {createStorage} from './storage.mjs';
import {TUTORIAL,blank,normalize,newRun,perform,undo,complete,flush,daily} from './session.mjs';
const app=document.getElementById('app'),modalRoot=document.getElementById('modal-root');
const lessons=['从 A 出发，认识轨道格配额。','直轨与弯轨接头必须互相连通。','数字 0 和已满行列，是留白的依据。','在狭窄山口中，寻找唯一可行的接头。','每段铁轨都要连入主线，别留下副环。','把配额、接头与整条路线一起考虑。'];
const souvenirs=['雪松站牌','风湾邮亭','雾凇信号灯','山口高架桥','极夜观景车','晨光终点站'];
let data=blank(),storage,page='home',p=LEVELS[0],run,key,selected=-1,modal=null,opener=null,animation=0,saveWarning='',saveQueue=Promise.resolve(),toastTimer;
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.style.display='none';},3600);}
function host(payload){if(window.RealmArcade&&typeof window.RealmArcade.reportCompletion==='function')return window.RealmArcade.reportCompletion(payload);return false;}
// Queue saves without parallel native writes. Host delivery is retried with a stable ID.
function save(){const snapshot=JSON.parse(JSON.stringify(data)),before=snapshot.outbox.map(e=>e.completionId);saveQueue=saveQueue.then(async()=>{const ok=await flush(snapshot,storage,host);if(ok){const pending=snapshot.outbox.map(e=>e.completionId);const acknowledged=before.filter(id=>!pending.includes(id));data.outbox=data.outbox.filter(e=>!acknowledged.includes(e.completionId));saveWarning='';}else{saveWarning='进度暂未保存，请保持本页打开，稍后重试保存。';toast('保存失败，进度暂留本页');}return ok;}).catch(()=>{saveWarning='进度暂未保存，请重试。';return false;});return saveQueue;}
function warning(){return saveWarning?`<div class="save-warning">${saveWarning} <button class="secondary" data-action="save">重试保存</button></div>`:'';}
function mast(active){return `<header class="masthead"><div class="brand"><img src="./assets/icon.svg" alt="">霜野铁道<small></small></div><nav class="nav" aria-label="主导航"><button data-action="home" class="${active==='home'?'active':''}">线路</button><button data-action="collection" class="${active==='collection'?'active':''}">收藏</button><button data-action="tutorial">玩法</button></nav></header>`;}
function footer(){return '<footer class="footer"><span>FROSTFIELD RAILWAY · 慢慢铺轨，好好到站</span><button data-action="about">规则来源与作品说明</button></footer>';}
function renderHome(){page='home';animation++;const c=data.chapter,count=Object.keys(data.records).length,d=daily(LEVELS),current=LEVELS.find(q=>q.id===data.selected)||LEVELS[0];
 app.innerHTML=`<main class="app-shell">${mast('home')}${warning()}<section class="hero" aria-label="雪原铁道风景"><div class="hero-copy"><div class="eyebrow">A QUIET JOURNEY THROUGH THE SNOW</div><h1>霜野铁道</h1><p>行列数字，是雪地里的路标。<br>铺好一条铁路，让暖灯列车驶向黎明。</p><button class="primary" data-action="continue">${count?'继续旅程':'从第一站出发'} <span aria-hidden="true">→</span></button></div><div class="hero-ticket">旅程手账　${String(count).padStart(2,'0')} / 60<br>6 段旅程 · 不限时推理</div></section><div class="section-head"><h2>雪原线路图</h2><small>每一格，都有去向</small></div><div class="map-layout"><section><div class="chapter-tabs" role="group" aria-label="章节">${CHAPTERS.map((name,i)=>`<button class="chapter-tab ${i===c?'active':''}" data-action="chapter" data-value="${i}" aria-pressed="${i===c}"><span class="number">STATION 0${i+1} · ${LEVELS.filter(q=>q.chapter===i&&data.records[q.id]).length}/10</span>${name}</button>`).join('')}</div><div class="station-board"><h3>${CHAPTERS[c]}</h3><p>${lessons[c]}<br>前 2 关学会新概念，之后逐步组合。</p><div class="level-grid">${LEVELS.filter(q=>q.chapter===c).map(q=>{const num=Number(q.id.slice(3)),r=data.records[q.id];return `<button class="level ${r?'done':''} ${q.id===current.id?'current':''}" data-action="level" data-value="${q.id}" aria-label="第${num}关，${r?r.assisted?'提示完成':'独立完成':'未完成'}">${String(num).padStart(2,'0')}<small>${r?r.assisted?'已通车 · 提示':'✓ 已通车':q.phase}</small></button>`;}).join('')}</div></div></section><aside class="sidebar"><div><img src="./assets/station-1.svg" alt="雪原木屋与站牌"><h3>今日车次</h3><p>${d.date} · 从已验证的 60 关中每日选一题，60 天轮换。随时来，没有断签惩罚。</p></div><button class="daily-button" data-action="daily">搭上今日列车 →</button></aside></div>${footer()}</main>`;
}
function start(level,mode='main',dailyKey){animation++;p=level;key=dailyKey||p.id;run=data.sessions[key];if(!run||run.levelId!==p.id)run=data.sessions[key]=newRun(p,mode);const goal=pathState(p,p.path);selected=p.path.find(i=>!p.givens.some(g=>g[0]===i)&&run.board.masks[i]!==goal.masks[i]);if(selected===undefined)selected=0;data.selected=p.id;data.chapter=p.chapter;page='game';save();renderGame();window.scrollTo(0,0);}
function renderGame(){page='game';const check=inspect(p,run.board),num=Number(p.id.slice(3));
 app.innerHTML=`<main class="app-shell game-shell"><header class="game-header"><button class="back" data-action="home">← 线路图</button><button class="back" data-action="tutorial">玩法说明</button></header>${warning()}<div class="section-head"><div><div class="chapter-label">STATION 0${p.chapter+1} · ${run.mode==='daily'?'今日车次':p.phase}</div><h1 class="game-title">${CHAPTERS[p.chapter]}</h1></div><small>${String(num).padStart(2,'0')} / 60</small></div><div class="game-layout"><div><section class="board-wrap" aria-label="铺轨区"><div class="board-meta"><span>SNOWFIELD LINE · ${p.n} × ${p.n}</span><span>行列数字 = 轨道格数</span></div><div id="board">${boardSvg(p,run.board,selected)}</div><div class="board-legend"><span>● 铆钉：固定轨片</span><span>◇ 候选</span><span>× 排除</span></div></section><div class="live-status ${check.status}" role="status" aria-live="polite">${check.status==='won'?'✓ ':check.status==='conflict'?'! ':''}${check.message}</div>${check.status==='won'?`<section class="success-card"><h3>这一路，终于亮起暖灯</h3><p>${run.hints?'在提示帮助下到站':'独立推理 · 顺利到站'}。${run.mode==='daily'?'今日车票已收入手账。':'此关已计入车站收藏。'}<br>可回看路线，也可以继续下一站。</p><button class="primary" data-action="next">${num===60||run.mode==='daily'?'回到线路图':'下一段旅程 →'}</button><button class="secondary" data-action="train">再看一次列车通行</button></section>`:''}</div><aside class="control-panel"><div class="control-heading">铺轨工具</div><div class="selection-name">${selected>=0?`${Math.floor(selected/p.n)+1} 行 ${selected%p.n+1} 列`:'先点选一格'}</div><p class="selection-help">先点格子，再选接头方向。<br>相邻接头会同步；金色圆点表示尚未接齐。</p><div class="tile-grid" role="group" aria-label="选择轨片">${TILES.map((m,i)=>`<button class="tile-option" data-action="tile" data-value="${m}" aria-label="${tileName(m)}轨片，快捷键${i+1}" ${check.status==='won'?'disabled':''}><svg viewBox="0 0 64 64" aria-hidden="true">${rail(m)}</svg><span>${tileName(m)}</span></button>`).join('')}</div><div class="edit-tools"><button data-action="erase" ${check.status==='won'?'disabled':''}>擦除</button><button data-action="candidate" ${check.status==='won'?'disabled':''}>◇ 候选</button><button data-action="exclude" ${check.status==='won'?'disabled':''}>× 排除</button></div><div class="utility-tools"><button class="secondary" data-action="undo" ${!run.history.length||run.settled?'disabled':''}>↶ 撤销</button><button class="secondary" data-action="restart">重开</button></div><button class="hint-button" data-action="hint" ${check.status==='won'?'disabled':''}>站长提示 · 先看思路</button><div class="game-note"><strong>${lessons[p.chapter]}</strong>上方数字看列，右侧数字看行。所有铁轨都属于同一条 A→B 路线。空格不必全标 ×。<br>方向键选格，数字 1–6 选轨片，Z 撤销。</div></aside></div>${footer()}</main>`;
}
function renderCollection(){page='collection';animation++;app.innerHTML=`<main class="app-shell">${mast('collection')}${warning()}<div class="section-head"><div><div class="eyebrow muted">POSTCARDS FROM THE RAILWAY</div><h2>把沿途风景，留在手账</h2></div></div><p class="selection-help">每完成一章的 10 条线路，收藏一处雪原风景。提示完成同样计入收藏。</p><div class="collection-grid">${CHAPTERS.map((name,c)=>{const k=LEVELS.filter(q=>q.chapter===c&&data.records[q.id]).length;return `<article class="collect-card ${k<10?'locked':''}"><img src="./assets/station-${c+1}.svg" alt="${souvenirs[c]}风景插画，${k===10?'已收藏':'待解锁'}"><div class="chapter-label">POSTCARD 0${c+1}</div><h3>${souvenirs[c]}</h3><div class="progress-track"><span style="width:${k*10}%"></span></div><p>${name} · ${k}/10<br>${k===10?'✓ 已收藏这段旅程':'完成本章全部线路，即可收藏'}</p><button class="secondary" data-action="visit" data-value="${c}">前往这一站</button></article>`;}).join('')}</div>${footer()}</main>`;}
function rerender(){if(page==='game')renderGame();else if(page==='collection')renderCollection();else renderHome();}
function focusCell(){const el=app.querySelector(`[data-cell="${selected}"]`);if(el)el.focus();}
function selectCell(i,focus=false){selected=i;const board=document.getElementById('board');board.innerHTML=boardSvg(p,run.board,selected);const label=app.querySelector('.selection-name');if(label)label.textContent=`${Math.floor(i/p.n)+1} 行 ${i%p.n+1} 列`;if(focus)focusCell();}
function act(value,kind='tile'){if(selected<0){toast('先在棋盘上点选一格');return;}const result=perform(p,run,selected,value,kind);if(!result.ok){toast(result.reason);return;}animation++;const event=complete(data,p,run,LEVELS,key);save();renderGame();focusCell();if(event)animateTrain();}
function showModal(content,state){if(!modal){opener=document.activeElement;document.body.classList.add('modal-open');app.setAttribute('aria-hidden','true');}modal=state;modalRoot.innerHTML=`<div class="modal-overlay"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" tabindex="-1">${content}</section></div>`;const panel=modalRoot.querySelector('.modal');panel.scrollTop=0;panel.focus();}
function closeModal(){if(modal&&modal.type==='tutorial'){data.tutorial=TUTORIAL;save();}modal=null;modalRoot.innerHTML='';document.body.classList.remove('modal-open');app.removeAttribute('aria-hidden');if(opener&&document.contains(opener))opener.focus();else{const b=app.querySelector('button');if(b)b.focus();}}
function top(title){return `<div class="modal-top"><h2 id="modal-title">${title}</h2><button class="modal-close" data-action="close" aria-label="关闭">×</button></div>`;}
function tutorial(index=0){const tp=LEVELS[0],t=tutorialStates(tp),titles=['数字，是雪地路标','一块轨片，两个接头','只有一条完整铁路'],copy=[`A 从左侧进入，B 从下方离开。上方数字是每列的轨道格数，右侧数字是每行的轨道格数。带铆钉的轨片是固定线索。`,`点第 ${Math.floor(t.action.cell/tp.n)+1} 行、第 ${t.action.cell%tp.n+1} 列，再选「${tileName(t.action.mask)}」。相邻接头会一起连接，金色圆点表示还要继续铺轨。`,`每个轨道格恰好有两个接头，配额全部满足，且所有铁轨连成 A→B 的一条路线。不能分叉，也不能留下独立闭环。空白格不用全部标 ×。`];
 showModal(`${top(titles[index])}<div class="steps">使用真实第 01 关 · ${index+1} / 3</div><div class="modal-board">${boardSvg(tp,t.states[index],index===1?t.action.cell:-1,false)}</div><p>${copy[index]}</p><div class="modal-actions"><button class="secondary" data-action="close">${index===2?'关闭':'跳过教程'}</button><button class="primary" data-action="tutorial-next">${index===2?'我会了，去铺轨':'下一张 →'}</button></div>`,{type:'tutorial',index});}
function hintIntro(){showModal(`${top('听听站长怎么说')}<div class="hint-fact">${lessons[p.chapter]}<br>先看 0 配额与已满的行列，再观察固定轨片伸出的接头。</div><p>数字满足后，还要检查整条路线是否从 A 接到了 B。轨道旁的金色圆点可以帮你找到尚未接齐的位置。</p><div class="modal-actions"><button class="secondary" data-action="close">自己再想想</button><button class="primary" data-action="hint-reveal">看具体一格</button></div><p class="muted">查看具体一格后，本局会记录为「提示完成」。</p>`,{type:'hint'});}
function hintReveal(){run.hints++;save();const goal=pathState(p,p.path),off=[];let chosen;
 for(let i=0;i<p.n*p.n;i++)if(run.board.masks[i]!==goal.masks[i]&&!p.givens.some(g=>g[0]===i))off.push(i);
 off.sort((a,b)=>((run.board.masks[b]&~goal.masks[b])?1:0)-((run.board.masks[a]&~goal.masks[a])?1:0));
 for(const i of off){const result=change(p,run.board,i,goal.masks[i]);if(result.ok){chosen={cell:i,value:goal.masks[i]};break;}}
 if(!chosen){showModal(`${top('先整理当前线路')}<p>现有轨道互相牵制，暂时不能直接补上一块。请撤销最近几步，再从配额较小的行列继续。</p><button class="primary" data-action="close">回到棋盘</button>`,{type:'hint'});return;}
 const i=chosen.cell,row=Math.floor(i/p.n),col=i%p.n;let fact;
 if(!p.rows[row]||!p.cols[col])fact='这一行或这一列配额是 0，因此这里必须留空。';
 else if(run.board.masks[i]&~goal.masks[i])fact='这格的现有接头与完整 A→B 路线不一致。综合配额和固定轨片，它需要调整。';
 else fact=`第 ${row+1} 行需要 ${p.rows[row]} 个轨道格，第 ${col+1} 列需要 ${p.cols[col]} 个。结合固定接头和全线连通，这格在已验证的唯一线路中是「${tileName(chosen.value)}」。`;
 showModal(`${top('这一格，可以确定')}<div class="steps">第 ${row+1} 行 · 第 ${col+1} 列</div><div class="hint-preview"><svg viewBox="0 0 64 64" aria-label="${tileName(chosen.value)}">${chosen.value?rail(chosen.value):'<text x="32" y="42" text-anchor="middle" fill="#607f70" font-size="30">×</text>'}</svg></div><div class="hint-fact">${fact}</div><p>综合提示参考已独立验证的唯一解。你可以只看解释，也可以放入这一块。</p><div class="modal-actions"><button class="secondary" data-action="close">我自己来</button><button class="primary" data-action="hint-apply">使用这一步</button></div>`,{type:'hint',chosen});}
function animateTrain(){const check=inspect(p,run.board);if(check.status!=='won')return;const svg=app.querySelector('.board-svg'),marker=svg&&svg.querySelector('.train-marker');if(!marker)return;const token=++animation,path=check.path;let d=`M-4 ${p.entry*64+32}`;
 for(let k=0;k<path.length;k++){const i=path[k],x=i%p.n*64+32,y=Math.floor(i/p.n)*64+32;const next=path[k+1],dx=k===path.length-1?0:(next%p.n-i%p.n),dy=k===path.length-1?1:(Math.floor(next/p.n)-Math.floor(i/p.n));d+=` Q${x} ${y} ${x+dx*32} ${y+dy*32}`;}
 const track=document.createElementNS('http://www.w3.org/2000/svg','path');track.setAttribute('d',d);track.setAttribute('fill','none');track.setAttribute('stroke','none');svg.appendChild(track);const len=track.getTotalLength(),duration=path.length*180,startTime=performance.now(),reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 marker.style.display='block';function frame(t){if(token!==animation||!document.contains(svg))return;const ratio=reduced?1:Math.min(1,(t-startTime)/duration),point=track.getPointAtLength(len*ratio),ahead=track.getPointAtLength(Math.min(len,len*ratio+1)),angle=Math.atan2(ahead.y-point.y,ahead.x-point.x)*180/Math.PI;marker.setAttribute('transform',`translate(${point.x} ${point.y}) rotate(${angle})`);if(ratio<1)requestAnimationFrame(frame);else{track.remove();}}
 requestAnimationFrame(frame);
}
function about(){showModal(`${top('关于这趟旅程')}<p>霜野铁道 · 1.0.0<br>60 道主线题，6 个章节。每日车次来自这 60 道题，按北京时间轮换。完成记录和收藏保存在当前设备。</p><p>规则基于 Simon Tatham 谜题集的 Tracks；参考本项目「极地蒸汽列车」。底层规则不声明原创。代码、主题图形与文案使用 AI 辅助制作。</p><p>每题经独立搜索验证唯一线路，不限制铺轨顺序。主线不计时。具体提示会标记为提示完成，仍可获得章节收藏。</p><p>MIT License · Copyright 2026 Ten Realms Arcade contributors。完整许可随发行源码提供。</p><button class="primary" data-action="close">继续旅程</button>`,{type:'about'});}
document.addEventListener('click',e=>{
 const cell=e.target.closest&&e.target.closest('[data-cell]');if(cell&&page==='game'&&!modal){selectCell(Number(cell.getAttribute('data-cell')));return;}
 const button=e.target.closest&&e.target.closest('[data-action]');if(!button||button.disabled)return;const action=button.dataset.action,value=button.dataset.value;
 if(action==='close'){closeModal();return;}
 if(action==='tutorial-next'){const i=modal.index;if(i===2)closeModal();else tutorial(i+1);return;}
 if(action==='hint-reveal'){hintReveal();return;}if(action==='hint-apply'){const choice=modal.chosen;closeModal();selected=choice.cell;act(choice.value);return;}
 if(action==='restart-yes'){closeModal();animation++;run=data.sessions[key]=newRun(p,run.mode);save();renderGame();return;}
 if(modal)return;
 if(action==='home'){renderHome();window.scrollTo(0,0);}else if(action==='collection'){renderCollection();window.scrollTo(0,0);}else if(action==='chapter'){data.chapter=Number(value);save();renderHome();}else if(action==='visit'){data.chapter=Number(value);renderHome();}else if(action==='level')start(LEVELS.find(q=>q.id===value));else if(action==='continue')start(LEVELS.find(q=>q.id===data.selected)||LEVELS[0]);else if(action==='daily'){const d=daily(LEVELS);start(d.level,'daily',d.key);}else if(action==='tutorial')tutorial();else if(action==='about')about();else if(action==='tile')act(Number(value));else if(action==='erase')act(0);else if(action==='candidate')act(run.board.notes[selected]===1?0:1,'note');else if(action==='exclude')act(run.board.notes[selected]===2?0:2,'note');else if(action==='undo'){if(undo(run)){animation++;save();renderGame();focusCell();}}else if(action==='restart')showModal(`${top('重新铺这条线路？')}<p>会清空本局轨道和笔记，已经获得的通关记录与收藏会保留。</p><div class="modal-actions"><button class="secondary" data-action="close">继续这局</button><button class="primary" data-action="restart-yes">重新开始</button></div>`,{type:'restart'});else if(action==='hint')hintIntro();else if(action==='next'){const index=LEVELS.indexOf(p);if(index===59||run.mode==='daily')renderHome();else start(LEVELS[index+1]);}else if(action==='train')animateTrain();else if(action==='save')save().then(()=>rerender());
});
document.addEventListener('keydown',e=>{
 if(modal){if(e.key==='Escape'){e.preventDefault();closeModal();}else if(e.key==='Tab'){const items=Array.from(modalRoot.querySelectorAll('button:not(:disabled),[tabindex="0"]'));if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===modalRoot.querySelector('.modal'))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===modalRoot.querySelector('.modal'))){e.preventDefault();first.focus();}}return;}
 if(page!=='game'||e.ctrlKey||e.metaKey||e.altKey)return;
 if(e.target.closest('[data-cell]')&&['Enter',' '].includes(e.key)){e.preventDefault();const tile=app.querySelector('.tile-option');if(tile)tile.focus();return;}
 if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();let row=Math.floor(selected/p.n),col=selected%p.n;row=Math.max(0,Math.min(p.n-1,row+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)));col=Math.max(0,Math.min(p.n-1,col+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0)));selectCell(row*p.n+col,true);}else if(/^[1-6]$/.test(e.key)){e.preventDefault();act(TILES[Number(e.key)-1]);}else if(e.key.toLowerCase()==='z'){if(undo(run)){save();renderGame();focusCell();}}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();act(0);}
});
(async()=>{storage=await createStorage(window);try{data=normalize(await storage.read(),LEVELS);}catch(e){saveWarning=e.message;}renderHome();if(data.tutorial!==TUTORIAL)tutorial();await save();})().catch(()=>{app.innerHTML='<main class="app-shell"><h1>车站暂未打开</h1><p>请关闭后重新打开小工具。</p></main>';});
