import {DIRS,inspect,pop,tileName,initial,pathState,change} from './engine.mjs';
export function trackPath(mask,size=64){const c=size/2,points={1:[c,0],2:[size,c],4:[c,size],8:[0,c]},bits=DIRS.filter(d=>mask&d.bit).map(d=>d.bit);if(!bits.length)return '';const a=points[bits[0]],b=bits.length>1?points[bits[1]]:[c,c];return `M${a[0]} ${a[1]} Q${c} ${c} ${b[0]} ${b[1]}`;}
export function rail(mask,size=64){if(!mask)return '';const d=trackPath(mask,size);return `<path d="${d}" class="sleepers"/><path d="${d}" class="steel"/><path d="${d}" class="rail-center"/>`+(pop(mask)===1?`<circle cx="${size/2}" cy="${size/2}" r="4" class="end-port"/>`:'');}
export function boardSvg(p,state,selected=-1,interactive=true){const n=p.n,v=n*64,check=inspect(p,state),fixed=new Set(p.givens.map(g=>g[0]));let body='';
 for(let i=0;i<n*n;i++){const x=i%n*64,y=Math.floor(i/n)*64,m=state.masks[i],note=state.notes[i];const label=`第${Math.floor(i/n)+1}行第${i%n+1}列，${fixed.has(i)?'固定 ':''}${m?tileName(m)+'轨道':note===1?'候选':note===2?'排除':'空白'}`;
 body+=`<g transform="translate(${x} ${y})" class="cell ${fixed.has(i)?'fixed':''} ${selected===i?'selected':''} ${check.conflicts.includes(i)?'conflict':''}" ${interactive?`data-cell="${i}" role="button" tabindex="${selected===i||selected<0&&i===0?0:-1}" aria-label="${label}" aria-pressed="${selected===i}"`:`aria-label="${label}"`}><rect class="cell-bg" x="1" y="1" width="62" height="62" rx="9"/>${rail(m)}${fixed.has(i)?'<circle class="rivet" cx="10" cy="10" r="2.5"/><circle class="rivet" cx="54" cy="54" r="2.5"/>':''}${note===1?'<path class="pencil" d="M32 23 L41 32 L32 41 L23 32 Z"/>':note===2?'<path class="pencil" d="M25 25 L39 39 M39 25 L25 39"/>':''}</g>`;}
 for(let k=0;k<n;k++){const r=check.rows[k],c=check.cols[k];body+=`<g class="quota ${c>p.cols[k]?'over':c===p.cols[k]?'satisfied':''}"><text x="${k*64+32}" y="-12">${p.cols[k]}</text>${c===p.cols[k]?`<path d="M${k*64+21} -5 h22"/>`:''}</g><g class="quota ${r>p.rows[k]?'over':r===p.rows[k]?'satisfied':''}"><text x="${v+16}" y="${k*64+38}">${p.rows[k]}</text>${r===p.rows[k]?`<path d="M${v+7} ${k*64+44} h18"/>`:''}</g>`;}
 body+=`<g class="station-label"><rect x="-26" y="${p.entry*64+20}" width="24" height="24" rx="7"/><text x="-14" y="${p.entry*64+37}">A</text><rect x="${p.exit*64+20}" y="${v+2}" width="24" height="24" rx="7"/><text x="${p.exit*64+32}" y="${v+19}">B</text></g>`;
 return `<svg class="board-svg" xmlns="http://www.w3.org/2000/svg" viewBox="-28 -28 ${v+56} ${v+56}" ${interactive?'role="group"':'role="img"'} aria-label="${n}乘${n}铁路棋盘；上方是列配额，右侧是行配额" data-level="${p.id}" data-status="${check.status}">${body}<g class="train-marker" style="display:none"><rect x="-11" y="-8" width="22" height="16" rx="5"/><rect x="-5" y="-5" width="9" height="10" rx="2"/></g></svg>`;
}
export function tutorialStates(p){const start=initial(p),goal=pathState(p,p.path);let mid=null,action=null;for(const i of p.path){const result=change(p,start,i,goal.masks[i]);if(result.ok){mid=result.state;action={cell:i,mask:goal.masks[i]};break;}}if(!mid||inspect(p,goal).status!=='won')throw Error('Invalid tutorial');return {states:[start,mid,goal],action};}
