import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {solve,boundary,canonical,shapes} from '../scripts/oracle.mjs';
for(const p of ['core.js','levels.js','session.js','view.js'])vm.runInThisContext(fs.readFileSync(new URL('../'+p,import.meta.url),'utf8'));const C=globalThis.HoneyCore,S=globalThis.HoneySession,V=globalThis.HoneyView,L=globalThis.HoneyLevels;let assertions=0;function check(v,msg){assert(v,msg);assertions++;}const report=[];
check(L.length===60,'60 levels');check(new Set(L.map(l=>l.id)).size===60);const keys=new Set();for(const l of L){const p=solve({n:l.n,k:l.k,clues:l.clues});check(!p.truncated&&p.exhaustive&&p.solutions.length===1,l.id+' unique exhaustive');const oracle=boundary(l.n,p.solutions[0]);check(JSON.stringify(oracle)===JSON.stringify(l.solution),'independent matches '+l.id);check(C.solved(l,{edges:oracle,moves:0}));check(!C.solved(l,C.fresh(l)));check(!C.set(l,C.fresh(l),'h:0:0',1));check(!C.set(l,C.fresh(l),C.edges(l)[0],3));check(C.normalize(l,{edges:oracle,moves:0}));const wallOnly={edges:Object.assign({},oracle),moves:0};C.edges(l).forEach(k=>{if(wallOnly.edges[k]===2)wallOnly.edges[k]=0;});check(C.solved(l,wallOnly),'unknown is traversable');const canon=canonical(l.n,p.solutions[0],l.clues);check(!keys.has(canon),'D4 puzzle duplicate');keys.add(canon);let s=C.fresh(l);for(const a of l.hintTrace){check(oracle[a.key]===a.value,'hint fact');const next=C.set(l,s,a.key,a.value);check(next!==null);s=next;}check(C.solved(l,s),'no-guess inference chain');var b=S.blank(L);b.current=S.run(l);b.current.state=wallOnly;const first=S.claim(l,b);check(first!==null);check(S.claim(l,b)===null);const restored=S.restore(L,JSON.parse(JSON.stringify(b)));check(restored.ledger[l.id].claimId===first.claimId);check(S.claim(l,restored)===null);const forged=JSON.parse(JSON.stringify(b));forged.ledger[l.id].proof=C.fresh(l);check(!S.restore(L,forged).ledger[l.id],'reject fabricated completion');const corrupt=JSON.parse(JSON.stringify(b));corrupt.current.state.edges={'bad':1};check(S.restore(L,corrupt).ledger[l.id],'preserve valid ledger with corrupt run');b.current=S.run(l);b.current.state=wallOnly;b.current.practice=true;b.ledger={};check(S.claim(l,b)===null,'practice no reward');report.push({id:l.id,nodes:p.nodes,unique:true,logicSteps:l.hintTrace.length});}
for(let ch=1;ch<=6;ch++){check(L.filter(l=>l.chapter===ch).length===10);const ps=L.filter(l=>l.chapter===ch).map(l=>canonical(l.n,solve(l).solutions[0]));check(new Set(ps).size===10,'no repeated partition within chapter');}
const l=L[0],r=S.run(l),key=C.edges(l)[0],initial=JSON.stringify(r.state);check(S.edit(l,r,key,1));check(S.undo(r));check(JSON.stringify(r.state)===initial);check(S.redo(r));check(r.state.edges[key]===1);check(!S.edit(l,r,key,1));check(!C.normalize(l,{edges:r.state.edges,moves:-1}));
const quad={n:4,k:4,clues:Array(16).fill(null)},part=[[0,1,4,5],[2,3,6,7],[8,9,12,13],[10,11,14,15]],e=boundary(4,part);e['v:0:1']=1;const stray={edges:e,moves:1};quad.clues=quad.clues.map((_,i)=>C.count(quad,stray,i));const a=C.analyze(quad,stray);check(a.errors.length===0&&a.sizes&&a.stray.length===1,'stray exact counterexample');check(!C.solved(quad,stray),'reject stray with all clues and sizes correct');
const big={n:4,k:4,clues:Array(16).fill(null)},blank=C.fresh(big);big.clues=big.clues.map((_,i)=>C.count(big,blank,i));check(C.analyze(big,blank).errors.length===0&&!C.solved(big,blank),'all clues correct not enough');
const zero={n:3,k:9,clues:Array(9).fill(null)},z=C.fresh(zero);zero.clues[4]=0;check(C.solved(zero,z),'zero distinct null');const zBad=C.set(zero,z,'h:1:1',1);check(!C.solved(zero,zBad));zero.clues[4]=null;check(C.analyze(zero,zBad).errors.length===0&&C.analyze(zero,zBad).stray.length===1);check(C.side(l,0,0)===null&&C.side(l,0,3)===null,'outer immutable');check(C.side(l,0,1)===C.side(l,1,3),'shared edge');
const by=Array.from({length:16},()=>[]);shapes(4,4).forEach(s=>s.cells.forEach(i=>by[i].push(s)));let covers=0;function walk(used,p){if(used===65535n){const x={n:4,k:4,clues:Array(16).fill(null)},s={edges:boundary(4,p),moves:0};x.clues=x.clues.map((_,i)=>C.count(x,s,i));check(C.solved(x,s));covers++;return;}let i=0;while(used&(1n<<BigInt(i)))i++;for(const shape of by[i])if(!(used&shape.mask))walk(used|shape.mask,p.concat([shape.cells]));}walk(0n,[]);check(covers===117);
const meta=JSON.parse(fs.readFileSync(new URL('../release/tutorial-metadata.json',import.meta.url)));check(meta.levelId===l.id&&meta.seed===l.seed);check(!C.solved(l,meta.states[0])&&C.solved(l,meta.states[2]));check(JSON.stringify(C.set(l,meta.states[0],meta.action.key,meta.action.value))===JSON.stringify(meta.states[1]));for(let i=0;i<3;i++){const expected=V.board(l,meta.states[i],{cell:i===1?meta.action.cell:undefined,edge:i===1?meta.action.key:null,caption:'真实教程第'+(i+1)+'图'});check(fs.readFileSync(new URL('../assets/tutorial-'+(i+1)+'.svg',import.meta.url),'utf8')===expected,'tutorial renderer exact');}
let saved=null;const fake={localStorage:{getItem:()=>saved,setItem:(k,v)=>saved=v}},st=S.store(fake);await st.init();const storedData=S.blank(L);await st.save(storedData);check(S.restore(L,JSON.parse(saved)).current.level===l.id);fake.localStorage.setItem=()=>{throw Error('quota');};check(await st.save(storedData)===false,'failed persistence visible');const calls=[];const native={xhs:{launchOptions:{miniToolEnv:{buildVersion:9462004}},miniTool:{getStorage:async()=>({data:null}),setStorage:async x=>calls.push(x)}},localStorage:{getItem:()=>{throw Error('should not use');}}};const ns=S.store(native);await ns.init();await Promise.all([ns.save(storedData),ns.save(Object.assign({},storedData,{tutorial:1}))]);check(calls.length===2&&JSON.parse(calls[1].data).tutorial===1,'native storage and serialized writes');
fs.writeFileSync(new URL('../release/rules-report.json',import.meta.url),JSON.stringify({assertions,completeTilings4x4:covers,levels:report,checks:['outer count','null/zero','stray wall','local-only false positives','unknown/clear equivalence','history','corrupt state/ledger','practice','reward IDs','local and native storage','no-guess traces','tutorial exact renderer']},null,2));console.log('PASS '+assertions+' assertions; 60 exhaustive unique proofs; '+covers+' 4x4 tilings');
