import { mountPuzzle } from "../../shared/game-kit.mjs";
import { LEVEL, SIZE, TUTORIAL, createState, evaluate, isComplete, normalizeState, positionOf, relationSatisfied, setCell, tutorialSvg, undo, verticalGlyph } from "./logic.mjs";

let selected = 0;
const massGlyph = ["", "○", "◔", "◑", "●"];
const tutorialCards = () => [
  { tag: "01 · 阶梯元素", title: "读懂高低刻印", svg: tutorialSvg(TUTORIAL.initial, "elements"), body: "在每格安放 1–4 阶位。每行、每列不可重复；两格之间的刻印规定高低，例如 < 表示左/上格必须比右/下格小。", bullets: ["竖向刻印的尖端指向较小值，开口朝向较大值。", "没有刻印的相邻格不附加“相邻数”规则；只遵守显示的大小关系。"] },
  { tag: "02 · 一次真实安放", title: "放下最轻的 1 阶石", svg: tutorialSvg(TUTORIAL.actionState, "action"), body: "真实操作 fill:0:1 将第 1 行第 1 列放为 1。它不会在行列重复，也符合该格向下的 < 刻印：下格最终会更大。", bullets: ["点选一格，再点底部 1–4 阶石；方向键和数字键同样可用。", "错误关系会给两端亮红边，仍可清除或撤销。"] },
  { tag: "03 · 阶庭平衡", title: "让拉丁方与刻印同时成立", svg: tutorialSvg(TUTORIAL.solved, "complete"), body: "填满棋盘后，所有行、列和十道高低刻印都要准确成立，整座阶梯庭才会恢复平衡。", bullets: ["本通关图来自固定关卡的真实解，独立搜索证实该显示关系下只有一个解。", "建议步数是 16 次安放；奖励只按稳定的完成编号结算一次。"] },
];
function markSelection(grid) { grid.querySelectorAll("[data-cell]").forEach((node) => node.classList.toggle("is-selected", Number(node.dataset.cell) === selected)); }
function moveFocus(grid, cell, dx, dy) { const point = positionOf(cell); const row = Math.max(0, Math.min(SIZE - 1, point.row + dy)); const column = Math.max(0, Math.min(SIZE - 1, point.column + dx)); selected = row * SIZE + column; markSelection(grid); grid.querySelector(`[data-cell="${selected}"]`)?.focus(); }
function edgePosition(relation) { const a = positionOf(relation.a); const b = positionOf(relation.b); return a.row === b.row ? { horizontal: true, left: `${(Math.min(a.column, b.column) + 1) * 25}%`, top: `${(a.row + .5) * 25}%`, glyph: relation.sign } : { horizontal: false, left: `${(a.column + .5) * 25}%`, top: `${(Math.min(a.row, b.row) + 1) * 25}%`, glyph: verticalGlyph(relation) }; }
function renderBoard({ board, state, commit, toast }) {
  const result = evaluate(LEVEL, state); const conflicts = new Set(result.invalidCells); const stage = document.createElement("div"); stage.className = "terrace-stage"; const grid = document.createElement("div"); grid.className = "terrace-grid"; grid.setAttribute("role", "grid"); grid.setAttribute("aria-label", "天平阶梯庭棋盘");
  const place = (value) => { const next = setCell(state, selected, value); if (next === state) { toast("这一步没有改变阶位"); return; } commit(next, value ? `已安放 ${value} 阶石` : "已收回所选阶石"); };
  for (let cell = 0; cell < SIZE * SIZE; cell += 1) { const point = positionOf(cell); const value = state.values[cell]; const button = document.createElement("button"); button.type = "button"; button.className = "terrace-cell"; button.dataset.cell = String(cell); if (selected === cell) button.classList.add("is-selected"); if (conflicts.has(cell)) button.classList.add("is-conflict"); button.innerHTML = `<i aria-hidden="true">${value ? massGlyph[value] : "·"}</i><b>${value || ""}</b>`; button.setAttribute("aria-label", `第 ${point.row + 1} 行第 ${point.column + 1} 列，${value ? `${value} 阶` : "空白"}`); button.addEventListener("click", () => { selected = cell; markSelection(grid); toast(`已选中第 ${point.row + 1} 行第 ${point.column + 1} 列`); }); button.addEventListener("keydown", (event) => { const direction = { ArrowUp: [0, -1], ArrowRight: [1, 0], ArrowDown: [0, 1], ArrowLeft: [-1, 0] }[event.key]; if (direction) { event.preventDefault(); moveFocus(grid, cell, ...direction); return; } if (/^[1-4]$/.test(event.key)) { event.preventDefault(); selected = cell; place(Number(event.key)); return; } if (["Backspace", "Delete", "0", " "].includes(event.key)) { event.preventDefault(); selected = cell; place(0); } }); grid.append(button); }
  for (const relation of LEVEL.relations) { const position = edgePosition(relation); const mark = document.createElement("span"); mark.className = `terrace-relation ${position.horizontal ? "is-horizontal" : "is-vertical"}`; mark.style.left = position.left; mark.style.top = position.top; mark.textContent = position.glyph; mark.setAttribute("aria-label", `第 ${relation.a + 1} 格 ${relation.sign} 第 ${relation.b + 1} 格`); if (state.values[relation.a] && state.values[relation.b] && relationSatisfied(relation, state.values)) mark.classList.add("is-met"); grid.append(mark); }
  stage.append(grid); const controls = document.createElement("div"); controls.className = "terrace-controls"; for (let value = 1; value <= SIZE; value += 1) { const button = document.createElement("button"); button.type = "button"; button.className = "mass-button"; button.innerHTML = `<i aria-hidden="true">${massGlyph[value]}</i><b>${value}</b>`; button.setAttribute("aria-label", `向所选格安放 ${value} 阶石`); button.addEventListener("click", () => place(value)); controls.append(button); } const clear = document.createElement("button"); clear.type = "button"; clear.className = "terrace-utility"; clear.textContent = "收回"; clear.addEventListener("click", () => place(0)); controls.append(clear); const undoButton = document.createElement("button"); undoButton.type = "button"; undoButton.className = "terrace-utility"; undoButton.textContent = "撤销"; undoButton.addEventListener("click", () => { const next = undo(state); if (next === state) { toast("还没有可撤销的安放"); return; } commit(next, "已撤销上一枚阶石"); }); controls.append(undoButton); board.className = "terrace-board"; board.append(stage, controls);
}
mountPuzzle({
  slug: "balance-terrace", title: "天平阶梯庭", eyebrow: "REALM 09 · BALANCE TERRACE", summary: "沿着高低刻印排布阶石；局部的大小关系会牵动整座四阶庭院。", accent: "#b7df82", levelId: LEVEL.id, tier: 2, par: 16,
  rules: [{ title: "行列各异", copy: "每行、每列都要各有 1、2、3、4 阶石一次。" }, { title: "遵循刻印", copy: "显示的 < 与 > 规定相邻两格真实的高低关系。" }, { title: "没有暗规", copy: "未显示刻印的相邻格不需要连续，只遵守拉丁方。" }], freshState: createState, normalizeState, isComplete, tutorialCards, renderBoard,
  statusFor(state, completed) { const result = evaluate(LEVEL, state); if (completed || result.complete) return { title: "阶庭已平衡", copy: "所有阶石与高低刻印完全吻合。", help: "可重新安放，或重看真实三卡教程。" }; if (result.errors.length) return { title: "平衡仍有偏差", copy: "红色格涉及重复阶石或反向的高低刻印。", help: "可直接改写、收回或撤销；没有额外惩罚。" }; return { title: "铺设高低阶位", copy: `还有 ${state.values.filter((value) => !value).length} 格待安放。`, help: "竖向刻印的尖端指向小值；焦点可用方向键移动。" }; },
});
document.querySelector("#victory-title").textContent = "阶庭重归平衡";
export { TUTORIAL };
