import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { LEVEL, SIZE, TUTORIAL, countSolutions, createState, evaluate, isComplete, normalizeState, relationSatisfied, setCell, stateFromValues, tutorialSvg, undo, verticalGlyph } from "./logic.mjs";

let checks = 0; const check = (value, message) => { assert.ok(value, message); checks += 1; }; const here = path.dirname(fileURLToPath(import.meta.url));
check(SIZE === 4 && LEVEL.relations.length === 10, "fixture has a 4×4 Latin grid and its ten explicit relations");
check(LEVEL.relations.every((relation) => Math.abs(relation.a - relation.b) === 1 || Math.abs(relation.a - relation.b) === SIZE), "every inequality connects orthogonal neighbours");
check(LEVEL.relations.every((relation) => relationSatisfied(relation, LEVEL.solution)), "fixture solution satisfies each displayed sign");
check(countSolutions(LEVEL, 2) === 1, "independent Futoshiki solver finds no second solution");
const initial = createState(); check(!isComplete(initial), "empty Latin grid cannot prematurely clear");
const action = setCell(initial, 0, 1); check(action.moves === 1 && action.values[0] === 1 && evaluate(LEVEL, action).errors.length === 0, "tutorial fill:0:1 is conflict free and respects its partial relation");
const duplicate = setCell(action, 1, 1); check(evaluate(LEVEL, duplicate).errors.some((entry) => entry.type === "row"), "repeated row tier is caught");
let inverse = setCell(initial, 0, 4); inverse = setCell(inverse, 4, 1); check(evaluate(LEVEL, inverse).errors.some((entry) => entry.type === "relation"), "reversed displayed inequality is caught");
check(verticalGlyph(LEVEL.relations.find((relation) => Math.abs(relation.a - relation.b) === SIZE)) === "∧", "vertical glyph points toward the smaller upper value");
check(undo(action).moves === 0 && undo(action).values[0] === 0, "undo restores real preceding terrace state");
const solved = stateFromValues(LEVEL.solution, 16); check(isComplete(solved), "completed fixture satisfies Latin and all relations");
check(!isComplete(stateFromValues([...LEVEL.solution.slice(0, 15), 0], 15)), "one empty terrace cannot win");
check(normalizeState({ values: Array(16).fill(8), moves: 0 }) === null, "corrupt local state is rejected so the kit creates only this game's fresh session");
check(TUTORIAL.actionState.values[0] === 1 && isComplete(TUTORIAL.solved), "tutorial state chain is generated by same logic module");
for (const [state, stage] of [[TUTORIAL.initial, "elements"], [TUTORIAL.actionState, "action"], [TUTORIAL.solved, "complete"]]) { const svg = tutorialSvg(state, stage); check(svg.includes('<svg') && svg.includes('data-tutorial-game="balance-terrace"') && svg.includes(`data-stage="${stage}"`), `${stage} runtime SVG is self-contained`); }
check(tutorialSvg(TUTORIAL.actionState, "action").includes('data-action="fill:0:1"'), "runtime action art records engine input"); check(tutorialSvg(TUTORIAL.solved, "complete").includes('data-complete="true"'), "runtime goal art records completed state");
const [html, app, css] = await Promise.all(["index.html", "app.mjs", "styles.css"].map((name) => readFile(path.join(here, name), "utf8")));
check(html.includes('data-realm="balance-terrace"') && html.includes('href="../../"'), "entry retains V4 realm isolation and return link");
check(html.includes('../../shared/realm-ui.css') && html.includes('../../shared/game-kit.css') && html.includes('../../shared/realm-ui.mjs'), "entry loads the frozen V4 shared resources");
check(app.includes("mountPuzzle") && app.includes("tutorialSvg"), "app uses game kit and true runtime SVG tutorial card");
check(css.includes("min-height: 44px") && css.includes("@media (max-width: 480px)"), "all narrow-screen controls retain touch baseline");
console.log(`Balance Terrace: ${checks} assertions passed.`);
