import {platformStorage} from './platform-storage.mjs';
import {rect,inside,equal,reason,solved,replay,hint} from './engine.mjs';
import {LEVELS,TUTORIAL,BANK_VERSION} from './levels.mjs';
import {boardSVG,hotelSVG} from './renderer.mjs';
import {STORE_KEY,TUTORIAL_KEY,load,persist,flush,runId,dailyKey,dailyIndex,sessionKey,settle} from './storage.mjs';
const CHAPTERS=['入住登记','窗边小屋','拐角走廊','整层规划','群岛连住','月下满房'];
const LESSONS=['读懂数字，安排第一间房','一样的面积，不一样的长宽','从边缘寻找房间的归属','让相邻房间各就各位','在更大的楼层里逐步排除','留一盏灯，迎接最后的旅客'];
const DECOR=['海风台灯','窗边绿植','藤编靠椅','木质书架','群岛挂画','月光床幔'];
const ICONS=['☀','♧','▱','▤','▧','☾'];
const app=document.getElementById('app'),modal=document.getElementById('modal');
let storage;try{storage=window.localStorage;}catch(e){storage={getItem:()=>null,setItem:()=>{throw Error('storage unavailable');}};}
let busy=false;
let data=null,view='home',chapter=0,puzzle=null,session=null,state=null,start=null,preview=null,notes=[],noteMode=false,message='',previousFocus=null,closeAction=null,tutorialStep=0,saveOK=true;
async function save(){busy=true;saveOK=persist(storage,data);if(saveOK&&storage.drain)saveOK=await storage.drain();if(saveOK){flush(storage,data,window.dreamIsleHost);if(storage.drain)saveOK=await storage.drain();}busy=false;}
function done(p){return !!data.records[sessionKey(p.id,'chapter')];}
function count(ch){return LEVELS.filter(p=>p.chapter===ch&&done(p)).length;}
function header(){return '<header class="top"><div class="brand"><img class="brand-icon" src="./assets/icon.png" alt="">梦屿旅舍</div><span class="eyebrow">DREAM ISLE HOTEL</span><button class="quiet" data-action="collection">陈设集</button></header>';}
function render(){
 let content='';
 if(view==='home')content='<section class="hero"><div class="hero-copy"><span class="eyebrow">海风来信 · 第一本入住簿</span><h1>把小小的日子<br>一间间安放。</h1><p>数字是房间的面积。划出矩形，<br>给海岛上的每位旅客，留一个位置。</p><button class="primary" data-action="continue">'+(Object.keys(data.records).length?'继续安排客房':'从第一间房开始')+' ↗</button></div><div class="hero-art">'+hotelSVG()+'</div></section><div class="section-title"><h2>岛屿入住簿</h2><span class="pill">'+LEVELS.filter(done).length+' / 60 间心事</span></div><div class="chapter-grid">'+CHAPTERS.map((name,i)=>'<button class="chapter-card" data-chapter="'+i+'"><span class="number">CHAPTER 0'+(i+1)+'</span><h3>'+name+'</h3><p>'+LESSONS[i]+'</p><div class="progress"><i style="width:'+count(i)*10+'%"></i></div><p>'+count(i)+' / 10 已完成</p></button>').join('')+'</div><footer class="foot"><span>不用赶路，也没有倒计时。<br>60 道固定题 · 每日一间房</span><div><button class="quiet" data-action="daily">今日房型 ↗</button><button class="quiet" data-action="rules">规则与来源</button></div></footer>';
 if(view==='chapter')content='<div class="page-head"><button data-action="home" aria-label="返回首页">←</button><div><span class="eyebrow">CHAPTER 0'+(chapter+1)+'</span><h1>'+CHAPTERS[chapter]+'</h1><p class="subtle">'+LESSONS[chapter]+' · '+count(chapter)+'/10</p></div></div><div class="level-grid">'+LEVELS.filter(p=>p.chapter===chapter).map((p,i)=>'<button class="level-card" data-level="'+p.id+'"><strong>'+String(i+1).padStart(2,'0')+(done(p)?' ✓':'')+'</strong><span>'+p.lesson+' · '+p.n+' × '+p.n+'</span></button>').join('')+'</div><p class="subtle">完成本章，收藏「'+DECOR[chapter]+'」。全部关卡可自由进入。</p>';
 if(view==='play')content='<div class="play-head"><button data-action="back">← 入住簿</button><div><p class="subtle">'+(session.mode==='chapter'?'第 '+(puzzle.chapter+1)+' 章 · '+puzzle.lesson:'今日房型 · '+session.mode.split(':')[1])+'</p><h1>'+CHAPTERS[puzzle.chapter]+' · '+puzzle.id.slice(-2)+'</h1></div><button class="quiet" data-action="tutorial">玩法</button></div><div class="play-layout"><section class="floor-wrap"><div class="roof-label"><span>ISLE '+String(puzzle.chapter+1).padStart(2,'0')+' / 客房平面</span><span>'+puzzle.n+' × '+puzzle.n+'</span></div><div class="board" id="board"><div class="board-image" id="board-image"></div><div class="notes" id="notes"></div><div class="cell-layer" id="cells" style="grid-template-columns:repeat('+puzzle.n+',1fr);grid-template-rows:repeat('+puzzle.n+',1fr)">'+Array.from({length:puzzle.n*puzzle.n},(_,i)=>{const x=i%puzzle.n,y=Math.floor(i/puzzle.n),c=puzzle.clues.find(c=>c.x===x&&c.y===y);return '<button class="cell" data-cell="'+i+'" aria-label="第'+(y+1)+'行第'+(x+1)+'列'+(c?'，数字'+c.v:'，空格')+'"></button>';}).join('')+'</div></div><p class="board-counter" id="counter"></p></section><aside class="side-panel"><span class="eyebrow">YOUR LITTLE RETREAT</span><h2>为一段旅途<br>划出归处。</h2><p class="instructions">点选两个对角格，确认房间。<br>每间一个数字，面积与它相等。</p><div class="selection" id="selection" aria-live="polite"></div><div class="actions"><button class="primary" id="confirm" data-action="confirm">确认房间</button><button data-action="cancel">取消选择</button></div><div class="tools"><button data-action="undo">撤销</button><button data-action="remove">清除房间</button><button data-action="hint">提示</button></div><div class="tools"><button data-action="note" id="note-mode">候选笔记</button><button data-action="restart">重开本题</button><button data-action="rules">规则</button></div><p class="toast" id="message" role="status"></p></aside></div>';
 if(view==='collection')content='<div class="page-head"><button data-action="home" aria-label="返回首页">←</button><div><span class="eyebrow">SOUVENIRS FROM THE ISLE</span><h1>旅舍陈设集</h1><p class="subtle">每住满一章，给旅舍添一件小物。</p></div></div><div class="collection">'+DECOR.map((d,i)=>'<div class="collect-item '+(count(i)<10?'locked':'')+'"><span class="motif" aria-hidden="true">'+ICONS[i]+'</span><h3>'+d+'</h3><p>'+(count(i)===10?'已收藏 ✓':'第 '+(i+1)+' 章 · '+count(i)+'/10')+'</p></div>').join('')+'</div><p class="subtle">独立解题徽章：'+Object.values(data.records).filter(s=>{const p=LEVELS.find(p=>p.id===s.levelId);return !replay(p,s.actions).helped;}).length+' 枚。提示不影响章节收藏；无提示完成可获得徽章。</p>';
 app.innerHTML='<main class="shell '+(view==='play'?'play-shell':'')+'">'+header()+(!saveOK?'<p class="save-warning">本地存储不可用，本次进度暂未保存。请恢复存储后重新打开。</p>':'')+content+'</main>';
 if(view==='play'){draw();bindBoard();}
}
function draw(){document.getElementById('board-image').innerHTML=boardSVG(puzzle,state.rooms,preview);document.getElementById('counter').textContent='已安排 '+state.rooms.length+' / '+puzzle.clues.length+' 间房 · '+state.rooms.reduce((s,r)=>s+r.w*r.h,0)+' / '+puzzle.n*puzzle.n+' 格';document.getElementById('selection').innerHTML=preview?'<strong>'+preview.w+' × '+preview.h+' = '+preview.w*preview.h+'</strong>　'+(noteMode?'候选，不计入通关':'待确认'):(start?'已选起点，再点对角格。':'点选两个对角格，安排一间房。');document.getElementById('confirm').disabled=!preview||solved(puzzle,state.rooms);document.getElementById('confirm').textContent=noteMode?'记下候选':'确认房间';document.getElementById('note-mode').className=noteMode?'mode-active':'';document.getElementById('note-mode').setAttribute('aria-pressed',String(noteMode));document.getElementById('message').textContent=message;document.getElementById('message').hidden=!message;document.getElementById('notes').innerHTML=notes.map(r=>'<div class="note" style="left:'+r.x/puzzle.n*100+'%;top:'+r.y/puzzle.n*100+'%;width:'+r.w/puzzle.n*100+'%;height:'+r.h/puzzle.n*100+'%"></div>').join('');document.querySelector('[data-action="undo"]').disabled=!state.history.length||solved(puzzle,state.rooms);}
async function begin(p,mode){puzzle=p;chapter=p.chapter;const key=sessionKey(p.id,mode);session=data.sessions[key]||{levelId:p.id,mode,runId:runId(),actions:[]};data.sessions[key]=session;state=replay(p,session.actions);start=preview=null;notes=[];noteMode=false;message='';view='play';if(solved(p,state.rooms))settle(data,session,p,new Date().toISOString());await save();render();let seen=false;try{seen=storage.getItem(TUTORIAL_KEY)==='seen';}catch(e){}if(!seen)showTutorial();else if(solved(p,state.rooms))showWin();}
async function act(a){if(session.actions.length>=3990){message='这局记录已满，请重开本题。';draw();return;}const actions=session.actions.concat([a]),next=replay(puzzle,actions);if(!next){message='这一步没有改变房间。';draw();return;}session.actions=actions;state=next;start=preview=null;message='';if(solved(puzzle,state.rooms))settle(data,session,puzzle,new Date().toISOString());await save();render();if(solved(puzzle,state.rooms))showWin();}
function choose(point){if(busy)return;if(solved(puzzle,state.rooms))return;if(!start||preview){start=point;preview=null;}else{preview=rect(start,point);}message='';draw();}
function bindBoard(){const cells=document.getElementById('cells');let down=null,moved=false;function point(e){const b=cells.getBoundingClientRect();const x=Math.floor((e.clientX-b.left)/b.width*puzzle.n),y=Math.floor((e.clientY-b.top)/b.height*puzzle.n);return x>=0&&x<puzzle.n&&y>=0&&y<puzzle.n?{x,y}:null;}
 cells.addEventListener('pointerdown',e=>{if(busy||e.button!==0||solved(puzzle,state.rooms))return;down=point(e);moved=false;if(cells.setPointerCapture)cells.setPointerCapture(e.pointerId);});
 cells.addEventListener('pointermove',e=>{if(!down)return;const p=point(e);if(p&&(p.x!==down.x||p.y!==down.y)){moved=true;preview=rect(down,p);start=down;draw();}});
 cells.addEventListener('pointerup',e=>{if(!down)return;const p=point(e);if(p){if(moved){start=down;preview=rect(down,p);draw();}else choose(p);}down=null;});
 cells.addEventListener('pointercancel',()=>{down=null;start=preview=null;draw();});
 cells.addEventListener('click',e=>{if(e.detail===0&&e.target.dataset.cell!==undefined){const i=Number(e.target.dataset.cell);choose({x:i%puzzle.n,y:Math.floor(i/puzzle.n)});}});
 cells.addEventListener('keydown',e=>{const i=Number(e.target.dataset.cell);if(!Number.isInteger(i))return;let j=i;if(e.key==='ArrowRight')j=Math.min(puzzle.n*puzzle.n-1,i+1);else if(e.key==='ArrowLeft')j=Math.max(0,i-1);else if(e.key==='ArrowDown')j=Math.min(puzzle.n*puzzle.n-1,i+puzzle.n);else if(e.key==='ArrowUp')j=Math.max(0,i-puzzle.n);else return;e.preventDefault();cells.children[j].focus();});}
function openDialog(html,onClose){previousFocus=document.activeElement;closeAction=onClose||null;modal.innerHTML='<section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title">'+html+'</section>';modal.hidden=false;document.body.style.overflow='hidden';const firstButton=modal.querySelector('button');if(firstButton)firstButton.focus();}
function closeDialog(){modal.hidden=true;document.body.style.overflow='';if(previousFocus&&document.contains(previousFocus))previousFocus.focus();else{const b=app.querySelector('button');if(b)b.focus();}const fn=closeAction;closeAction=null;if(fn)fn();}
function showTutorial(){tutorialStep=0;openDialog('',()=>{try{storage.setItem(TUTORIAL_KEY,'seen');}catch(e){} });tutorialCard();}
function tutorialCard(){const titles=['一个数字，一间房','点两个角，再确认','每一格都有了归处'];const texts=['房间必须是矩形，而且恰好含一个数字。数字 3 就需要 3 格面积。','图中这间房由两个对角格确定，确认后才会入住。虚线候选笔记不算正式房间。','这是同一题的真实完成状态：每间面积正确、互不重叠，整层没有空格。'];modal.querySelector('.dialog').innerHTML='<div class="dialog-top"><span class="eyebrow">入住指南 · '+(tutorialStep+1)+' / 3</span><button class="quiet" data-action="close">跳过</button></div><h2 id="dialog-title">'+titles[tutorialStep]+'</h2><img class="tutorial-img" src="./assets/tutorial-'+tutorialStep+'.svg" alt="'+texts[tutorialStep]+'"><p>'+texts[tutorialStep]+'</p><div class="dots">'+[0,1,2].map(i=>'<i class="'+(i===tutorialStep?'on':'')+'"></i>').join('')+'</div><div class="actions">'+(tutorialStep?'<button data-action="tutorial-prev">上一张</button>':'')+'<button class="primary" data-action="tutorial-next">'+(tutorialStep===2?'去安排客房':'下一张')+'</button></div>';modal.querySelector('.dialog').scrollTop=0;modal.querySelector('[data-action="tutorial-next"]').focus();}
function showWin(){const all=count(puzzle.chapter)===10;openDialog('<div class="win"><div class="win-icon" aria-hidden="true">☾</div><span class="eyebrow">ALL GUESTS CHECKED IN</span><h2 id="dialog-title">今晚，满房了。</h2><p>每一位旅客，都有了自己的小天地。</p><img class="tutorial-img" src="./assets/hotel.svg" alt="海岛旅舍"><p>'+(state.helped?'已完成 · 提示辅助':'独立解题徽章 ✓')+(all?'<br>本章陈设「'+DECOR[puzzle.chapter]+'」已收藏。':'<br>本章已完成 '+count(puzzle.chapter)+' / 10 关。')+'</p>'+(!saveOK?'<p class="save-warning">本局已完成，但存储失败，尚未保存。</p>':'')+'<div class="actions"><button data-action="win-back">返回入住簿</button><button class="primary" data-action="next-level">'+(session.mode==='chapter'?'下一间房':'回到首页')+'</button></div><button class="quiet" data-action="close">查看房间</button></div>');}
function rules(){openDialog('<div class="dialog-top"><span class="eyebrow">HOUSE RULES</span><button class="quiet" data-action="close">关闭</button></div><h2 id="dialog-title">一间间，刚刚好。</h2><p>① 每个矩形房间恰好包含一个数字。<br>② 长 × 宽 = 数字。<br>③ 房间不能重叠，铺满整层才通关。</p><p class="sources">点两个对角格（同一格点两次可选 1×1），或拖动，再确认。要清房，先点房内一格，再按「清除房间」。撤销可恢复上一步。候选笔记仅本局临时辅助；再次确认同一候选可移除。提示会标记本局为辅助解题，不影响章节收藏。无提示重开完成可补获独立徽章。</p><p class="sources">60 道固定唯一解题目。每日房型由本地日期与题库版本决定，跨日后从首页重新进入。进度保存在当前小工具的本地存储中。</p><p class="sources">规则：Rect / Shikaku。参考 Simon Tatham’s Portable Puzzle Collection（MIT）。<br>www.chiark.greenend.org.uk/~sgtatham/puzzles/<br>基线：55cdddb75cf57c17baee80bac4121bd3be1687c6。主题、界面与 SVG 素材由本项目设计，AI 辅助开发。版本 1.0.0。</p>');}
async function dispatch(action){
 if(action==='close'){closeDialog();return;}
 if(action==='tutorial-next'){if(tutorialStep===2)closeDialog();else{tutorialStep++;tutorialCard();}return;}
 if(action==='tutorial-prev'){tutorialStep--;tutorialCard();return;}
 if(action==='home'){view='home';render();}
 if(action==='collection'){view='collection';render();}
 if(action==='continue'){await begin(LEVELS.find(p=>!done(p))||LEVELS[0],'chapter');}
 if(action==='daily'){const date=dailyKey(new Date());await begin(LEVELS[dailyIndex(date,BANK_VERSION,LEVELS.length)],'daily:'+date+':'+BANK_VERSION);}
 if(action==='back'||action==='win-back'){if(!modal.hidden)closeDialog();view='chapter';render();}
 if(action==='tutorial')showTutorial();
 if(action==='rules')rules();
 if(action==='cancel'){start=preview=null;message='';draw();}
 if(action==='note'){noteMode=!noteMode;draw();}
 if(action==='confirm'&&preview){if(noteMode){const at=notes.findIndex(r=>equal(r,preview));if(at>=0)notes.splice(at,1);else if(notes.length<30)notes.push(preview);start=preview=null;message='候选笔记仅作参考，不计入通关。';draw();}else{const why=reason(puzzle,state.rooms,preview);if(why){message=why;draw();}else await act({type:'place',r:preview});}}
 if(action==='remove'){if(solved(puzzle,state.rooms))return;const r=start&&state.rooms.find(r=>inside(r,start));if(r)await act({type:'remove',r});else{message='先点一下已有房间，再清除。';draw();}}
 if(action==='undo'&&state.history.length&&!solved(puzzle,state.rooms))await act({type:'undo'});
 if(action==='restart')openDialog('<h2 id="dialog-title">重新安排这一层？</h2><p>本局房间与临时笔记将清空，已获得的章节进度与收藏会保留。</p><div class="actions"><button data-action="close">继续本局</button><button class="primary" data-action="restart-yes">确认重开</button></div>');
 if(action==='restart-yes'){closeDialog();const mode=session.mode;delete data.sessions[sessionKey(puzzle.id,mode)];await begin(puzzle,mode);}
 if(action==='hint'&&!solved(puzzle,state.rooms)){await act({type:'hint'});const advice=hint(puzzle,state.rooms);openDialog('<h2 id="dialog-title">看看这间房</h2><p>'+advice.text+'</p><p class="sources">本局已标记为提示辅助。确认后才会放置房间。</p><div class="actions"><button data-action="close">我再想想</button>'+(advice.r?'<button class="primary" data-action="hint-apply">确认落房</button>':'')+'</div>');}
 if(action==='hint-apply'){const advice=hint(puzzle,state.rooms);closeDialog();if(advice.r)await act({type:'place',r:advice.r});}
 if(action==='next-level'){closeDialog();const i=LEVELS.indexOf(puzzle);if(session.mode!=='chapter'||i===59){view='home';render();}else await begin(LEVELS[i+1],'chapter');}
}
async function clicks(e){if(busy)return;const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.action)await dispatch(b.dataset.action);if(b.dataset.chapter!==undefined){chapter=Number(b.dataset.chapter);view='chapter';render();}if(b.dataset.level)await begin(LEVELS.find(p=>p.id===b.dataset.level),'chapter');}
app.addEventListener('click',clicks);modal.addEventListener('click',clicks);document.addEventListener('keydown',e=>{if(modal.hidden)return;if(e.key==='Escape'){e.preventDefault();closeDialog();}if(e.key==='Tab'){const bs=Array.from(modal.querySelectorAll('button:not(:disabled)'));const first=bs[0],last=bs[bs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
async function boot(){storage=await platformStorage(window.xhs,storage,[STORE_KEY,TUTORIAL_KEY]);data=load(storage,LEVELS);await save();render();}
boot();
