import fs from 'node:fs';import vm from 'node:vm';
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../src/engine.js',import.meta.url),'utf8'),ctx);const E=ctx.Astral;
let seed=20260922;function rand(n){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return Math.floor(seed/4294967296*n);}
const key=b=>b.join(',');
function canonical(b){let ks=[];for(let flip=0;flip<2;flip++)for(let turn=0;turn<4;turn++){let f=i=>{let r=i>>2,c=i%4;if(flip)c=3-c;for(let t=0;t<turn;t++)[r,c]=[c,3-r];return r*4+c;};let x=[];b.forEach((v,i)=>x[f(i)]=f(v-1)+1);ks.push(key(x));}return ks.sort()[0];}
const shallow=new Map([[key(E.goal),0]]);let frontier=[E.goal];for(let d=1;d<=3;d++){let next=[];for(const b of frontier)for(let z=0;z<9;z++)for(const dir of [-1,1]){const n=E.rotate(b,[z,dir]),k=key(n);if(!shallow.has(k)){shallow.set(k,d);next.push(n);}}frontier=next;}
function metrics(b){let misplaced=b.filter((v,i)=>v!==i+1).length, distance=b.reduce((s,v,i)=>s+Math.abs((v-1)%4-i%4)+Math.abs(Math.floor((v-1)/4)-Math.floor(i/4)),0),seen=new Set,cycles=[];for(let i=0;i<16;i++){if(seen.has(i))continue;let j=i,n=0;while(!seen.has(j)){seen.add(j);n++;j=b[j]-1;}if(n>1)cycles.push(n);}return {aligned:16-misplaced,cycles:cycles.sort((a,b)=>b-a),lowerBound:Math.max(Math.ceil(misplaced/4),Math.ceil(distance/4)),exactShortest:shallow.get(key(b))||null,searchStates:shallow.size,searchDepth:3};}
const names=['启开星窗','回到原位','交错回廊','守住一角','星序穿行','穹顶复位'];const lessons=['认出窗口，分清顺逆','逆转一步，理解四转复原','相邻窗口会改变彼此','选择顺序，守住已归位的一角','沿多个窗口整理错位循环','综合规划，完成穹顶校准'];let levels=[],used=new Set;
for(let ch=0;ch<6;ch++)for(let j=0;j<10;j++){let chosen;for(let attempt=0;attempt<10000;attempt++){let len=ch===0?(j===0?1:j<4?2:3):[0,4,5,6,8,10][ch]+Math.floor(j/4),moves=[],b=E.goal,last=-1;
for(let t=0;t<len;t++){let zones=ch===2?[0,1,3,4]:ch===3?[0,1,3,4,5]:[0,1,2,3,4,5,6,7,8];let z=zones[rand(zones.length)];while(z===last)z=zones[rand(zones.length)];last=z;let m=[z,rand(2)?1:-1];moves.push(m);b=E.rotate(b,m);}const k=canonical(b),met=metrics(b);if(used.has(k)||E.won(b)||(ch>1&&met.lowerBound<ch-1))continue;used.add(k);chosen={id:'astral-'+String(levels.length+1).padStart(2,'0'),chapter:ch+1,index:j+1,title:names[ch],lesson:lessons[ch],seed,generatorVersion:1,board:b,scramble:moves,solution:E.reverse(moves),reference:len,metrics:met};break;}if(!chosen)throw Error('Insufficient distinct levels');levels.push(chosen);}
fs.writeFileSync(new URL('../src/levels.js',import.meta.url),'var ASTRAL_LEVELS = '+JSON.stringify(levels)+';\n');fs.writeFileSync(new URL('../release/level-proof.json',import.meta.url),JSON.stringify({seed:20260922,count:60,canonicalUnique:used.size,shallowBFSStates:shallow.size,levels:levels.map(l=>({id:l.id,...l.metrics,reference:l.reference}))},null,2));console.log('Generated',levels.length,'D4-distinct levels. Complete BFS depth 3:',shallow.size);
