const {test}=require('node:test'),assert=require('node:assert/strict'),H=require('../core.js'),{solve,model}=require('../tools/oracle.cjs'),{LEVELS}=require('../levels.js'),vm=require('node:vm'),fs=require('node:fs');
function mapSolution(p,o){let es=H.graph(p);return es.map(e=>o.solutions[0][o.edges.findIndex(f=>f.includes(e[0])&&f.includes(e[1]))]);}
for(const p of LEVELS)test(p.id+' exhaustive independent uniqueness and legal replay',()=>{let o=solve(p);assert.equal(o.unique,true);assert.equal(o.exhaustive,true);assert.deepEqual(mapSolution(p,o),p.solution);assert.deepEqual(H.graph(p).map(e=>e.slice().sort((a,b)=>a-b).join('-')).sort(),model(p).es.map(e=>e.join('-')).sort());let s=H.empty(p);p.solution.forEach((n,k)=>{if(n){let r=H.move(p,s,k,n);assert(r.ok);s=r.state;}});assert(H.inspect(p,s).complete);assert(H.valid(p,s));});
test('representative lessons really exhibit double, connectivity and cycle',()=>{assert.equal(LEVELS[0].ports.length,5);assert(LEVELS[0].solution.includes(2));let p=LEVELS[30];assert.equal(p.ports.length,12);assert.equal(solve(p,{ignoreConnectivity:true}).count,2);assert(solve(p).unique);p=LEVELS[50];assert.equal(p.ports.length,20);assert(p.metrics.cycleRank>=1);assert(p.metrics.crossingPairs>=1);});
test('no skipping middle port; endpoint sharing; cycle allowed; overfull allowed',()=>{let p={size:3,ports:[{x:0,y:0,n:2},{x:1,y:0,n:3},{x:2,y:0,n:1}]};assert.deepEqual(H.graph(p),[[0,1],[1,2]]);let s=H.empty(p);s=H.move(p,s,0,2).state;s=H.move(p,s,1,1).state;assert(H.inspect(p,s).complete);let r=H.move(p,s,1,2);assert(r.ok);assert(!H.inspect(p,r.state).complete);p={size:3,ports:[{x:0,y:0,n:2},{x:2,y:0,n:2},{x:0,y:2,n:2},{x:2,y:2,n:2}]};s=H.empty(p);s.lines=[1,1,1,1];assert(H.inspect(p,s).complete);});
test('full disconnected components do not win',()=>{let p={size:4,ports:[{x:0,y:0,n:1},{x:1,y:0,n:1},{x:2,y:0,n:1},{x:3,y:0,n:1}]},s=H.empty(p);s.lines=[1,0,1];assert.equal(H.inspect(p,s).exact,4);assert.equal(H.inspect(p,s).groups.length,2);assert(!H.inspect(p,s).complete);});
test('crossing atomic rejection; notes never block crossing route; checked invalidation',()=>{let p={size:5,ports:[{x:0,y:2,n:1},{x:4,y:2,n:1},{x:2,y:0,n:1},{x:2,y:4,n:1}]},s=H.empty(p);assert(H.cross(p,...H.graph(p)));let before=H.clone(s);assert(!H.move(p,s,9,1).ok);assert.deepEqual(s,before);s=H.note(p,s,0).state;let r=H.move(p,s,1,1);assert(r.ok);assert(r.state.marks.includes(0));let snap=H.clone(r.state);assert(!H.move(p,r.state,0,1).ok);assert.deepEqual(r.state,snap);r=H.check(p,r.state,2);assert(r.ok);r=H.move(p,r.state,1,2);assert(r.ok);assert(!r.state.checked.includes(2));});
test('strict state validation rejects tampering',()=>{let p=LEVELS[0],s=H.empty(p);for(let patch of [{lines:[3]},{marks:[999]},{checked:[0]},{marks:[0,0]},{lines:s.lines.map(()=>-1)}])assert(!H.valid(p,Object.assign({},s,patch)));});
function brute(p){let es=model(p).es,counts=es.map(()=>0),found=[];function dfs(k){if(k===es.length){let ds=p.ports.map(()=>0),adj=p.ports.map(()=>[]);es.forEach((e,i)=>{e.forEach(j=>ds[j]+=counts[i]);if(counts[i]){adj[e[0]].push(e[1]);adj[e[1]].push(e[0]);}});if(ds.some((d,i)=>d!==p.ports[i].n))return;let seen=new Set([0]),q=[0];for(let i=0;i<q.length;i++)for(let t of adj[q[i]])if(!seen.has(t)){seen.add(t);q.push(t);}if(seen.size!==p.ports.length)return;let m=model(p);for(let i=0;i<es.length;i++)if(counts[i]&&m.conflicts[i].some(j=>counts[j]))return;found.push(counts.slice());return;}for(let n=0;n<=2;n++){counts[k]=n;dfs(k+1);}}dfs(0);return found;}
test('domain oracle agrees with raw 3^E enumeration on 30 small fixtures',()=>{for(let t=0;t<30;t++){let p={size:3,ports:[{x:0,y:0,n:1+t%4},{x:2,y:0,n:1+Math.floor(t/4)%4},{x:0,y:2,n:1+Math.floor(t/3)%4},{x:2,y:2,n:1+Math.floor(t/5)%4}]},b=brute(p),o=solve(p);assert.equal(o.count,Math.min(2,b.length));assert.equal(o.unique,b.length===1);}});
function storageContext(extra={}){let c=Object.assign({Harbor:H,Promise,Number,Set,JSON,module:{exports:{}},localStorage:{setItem(){},getItem(){return null;}},window:{}},extra);vm.createContext(c);vm.runInContext(fs.readFileSync(require.resolve('../storage.js'),'utf8'),c);return c;}
test('completion and reward dedupe; restore recomputes actual winner',()=>{let S=storageContext().HarborStore,save=S.fresh(),p=LEVELS[0],s={runId:'run1',hints:0,state:H.empty(p)};assert(!S.claim(save,p,s));s.state.lines=p.solution.slice();assert(S.claim(save,p,s));assert(!S.claim(save,p,s));s.runId='run2';assert(!S.claim(save,p,s));assert.equal(Object.keys(save.completed).length,1);assert.equal(save.outbox.length,1);let tamper=S.fresh();tamper.completed[p.id]={state:H.empty(p),runId:'fake',noHint:true};tamper.claims['first:'+p.id]=true;let restored=S.validate(tamper,LEVELS);assert.equal(Object.keys(restored.completed).length,0);assert.equal(Object.keys(restored.claims).length,0);assert.equal(Object.keys(S.validate(save,LEVELS).completed).length,1);});
test('native 9.46+ storage preference, fallback and failures',async()=>{let calls=[],data=null,c=storageContext({window:{xhs:{launchOptions:{miniToolEnv:{buildVersion:9462004}},miniTool:{async getStorage(x){calls.push('get');return {data};},async setStorage(x){calls.push('set');data=x.data;}}}},localStorage:{getItem(){throw Error('must not use web');},setItem(){throw Error('must not use web');}}});assert((await c.HarborStore.read()).ok);assert(await c.HarborStore.write({a:1}));assert.deepEqual(calls,['get','set']);c=storageContext({localStorage:{getItem(){throw Error('denied');},setItem(){throw Error('quota');}}});assert.equal((await c.HarborStore.read()).ok,false);assert.equal(await c.HarborStore.write({}),false);});
test('damaged histories rejected without deleting valid collection',()=>{let S=storageContext().HarborStore,save=S.fresh(),p=LEVELS[0];save.session={level:0,runId:'r',state:H.empty(p),history:[{lines:[99],marks:[],checked:[]}],hints:0};assert.equal(S.validate(save,LEVELS).session,null);});
