import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const ctx=vm.createContext({});for(const f of ['engine','levels','store'])vm.runInContext(fs.readFileSync('src/'+f+'.js','utf8'),ctx);const E=ctx.City,L=ctx.CityLevels,S=ctx.CityStore;const plain=x=>JSON.parse(JSON.stringify(x));
// Independent cell-by-cell Latin search; visibility uses prefix maxima, no engine functions.
function oracle(p){const n=p.n,b=Array(n*n).fill(0),answers=[];let nodes=0;const count=a=>a.filter((v,i)=>i===0||v>Math.max.apply(null,a.slice(0,i))).length;
function check(a,c){return !c||count(a)===c;}function rec(i){nodes++;if(answers.length>=2)return;if(i===n*n){answers.push(b.slice());return;}const r=Math.floor(i/n),c=i%n;for(let v=1;v<=n;v++){if(p.givens[i]&&p.givens[i]!==v)continue;let ok=true;for(let j=0;j<c;j++)if(b[r*n+j]===v)ok=false;for(let j=0;j<r;j++)if(b[j*n+c]===v)ok=false;if(!ok)continue;b[i]=v;if(c===n-1){const row=b.slice(r*n,(r+1)*n);if(!check(row,p.clues.left[r])||!check(row.slice().reverse(),p.clues.right[r]))continue;}if(r===n-1){const col=Array.from({length:n},(_,j)=>b[j*n+c]);if(!check(col,p.clues.top[c])||!check(col.slice().reverse(),p.clues.bottom[c]))continue;}rec(i+1);}b[i]=0;}rec(0);return {answers,nodes};}
test('60 independently unique puzzles, valid declared solutions',()=>{assert.equal(L.length,60);for(const p of L){const result=oracle(p);assert.equal(result.answers.length,1,p.id);assert.deepEqual(result.answers[0],plain(p.solution),p.id);assert.equal(E.evaluate(p,{values:p.solution}).complete,true);}});
test('direction mapping and visible count',()=>{const p={n:3},b=[3,1,2,1,2,3,2,3,1];assert.deepEqual(plain(E.line(p,b,'bottom',1)),[3,2,1]);assert.deepEqual(plain(E.line(p,b,'right',0)),[2,1,3]);assert.equal(E.visible([2,1,3]),2);assert.equal(E.visible([3,2,1]),1);assert.equal(E.visible([1,2,3]),3);});
test('illegal moves atomic, notes isolated, undo by replay',()=>{const p=L.find(p=>p.givens.some(Boolean));let s=E.initial(p);assert.equal(E.evaluate(p,s).complete,false);const fixed=p.givens.findIndex(Boolean),i=p.givens.findIndex(v=>!v);for(const a of [{type:'set',i:fixed,v:1},{type:'set',i:-1,v:1},{type:'set',i,v:9},{type:'bogus',i,v:1}])assert.equal(E.move(p,s,a),s);const a={type:'note',i,v:1},t=E.move(p,s,a);assert.equal(t.values[i],0);assert.equal(t.notes[i],2);assert.deepEqual(plain(E.replay(p,[])),plain(s));assert.deepEqual(plain(E.replay(p,[a])),plain(t));assert.throws(()=>E.replay(p,[{type:'set',i:fixed,v:1}]));});
test('completion rejects duplicate and wrong given/clue; missing clues unconstrained',()=>{const p=L[0],b=p.solution.slice();b[0]=b[1];assert.equal(E.evaluate(p,{values:b}).complete,false);const q=plain(p);q.givens.fill(0);q.clues.top[0]=q.clues.top[0]===1?2:1;assert.equal(E.evaluate(q,{values:q.solution}).complete,false);Object.values(q.clues).forEach(a=>a.fill(0));assert.equal(E.evaluate(q,{values:q.solution}).complete,true);});
test('tutorial same puzzle initial, legal action, exact completion',()=>{const t=JSON.parse(fs.readFileSync('release/tutorial-truth.json'));assert.deepEqual(plain(E.initial(t.puzzle).values),t.states[0]);assert.deepEqual(plain(E.move(t.puzzle,E.initial(t.puzzle),t.action).values),t.states[1]);assert.equal(E.evaluate(t.puzzle,{values:t.states[2]}).complete,true);assert.equal(oracle(t.puzzle).answers.length,1);for(let i=0;i<3;i++){const svg=fs.readFileSync('assets/tutorial-'+i+'.svg','utf8');assert.equal((svg.match(/data-cell=/g)||[]).length,9);t.states[i].forEach((v,j)=>assert.ok(svg.includes('data-cell="'+j+'" data-value="'+v+'"')));}});
test('storage restoration, corrupt histories, outbox retry, reward dedup',()=>{const p=L[0],actions=[];p.solution.forEach((v,i)=>{if(!p.givens[i])actions.push({type:'set',i,v});});const session={runId:'test-run',actions,hints:0,mode:'chapter'},d=S.empty();d.sessions[p.id]=session;const payload=S.settle(d,p,session,'2026-09-13T00:00:00Z');assert.equal(payload.rewardClaims.length,2);assert.equal(S.settle(d,p,session,'now'),null);assert.equal(S.settle(d,p,Object.assign({},session,{runId:'second'}),'now'),null);const mem={text:null,getItem(){return this.text;},setItem(k,v){this.text=v;}};S.save(mem,d);const restored=S.load(mem,L);assert.equal(restored.claims.length,2);assert.equal(restored.sessions[p.id].actions.length,actions.length);let calls=0;S.deliver(mem,d,()=>{calls++;throw Error('offline');});assert.equal(d.outbox.length,1);S.deliver(mem,d,x=>{calls++;assert.equal(x.completionId,payload.completionId);return true;});assert.equal(calls,2);assert.equal(d.outbox.length,0);mem.text='{';assert.equal(Object.keys(S.load(mem,L).records).length,0);const bad=plain(restored);bad.sessions[p.id].actions=[{type:'set',i:-1,v:8}];bad.records[p.id].actions=[];mem.text=JSON.stringify(bad);assert.equal(Object.keys(S.load(mem,L).records).length,0);assert.equal(Object.keys(S.load(mem,L).sessions).length,0);});
test('no delivery before persistence, deterministic daily',()=>{const d=S.empty();d.outbox=[{}];let calls=0;S.deliver({setItem(){throw Error('quota');}},d,()=>calls++);assert.equal(calls,0);assert.equal(E.daily('2026-09-13',60),E.daily('2026-09-13',60));});
test('no rotational or mirror duplicate puzzle; six chapters ten levels',()=>{const keys=new Set();for(const p of L){const n=p.n+2,a=Array.from({length:n},()=>Array(n).fill(0));for(let r=0;r<p.n;r++)for(let c=0;c<p.n;c++)a[r+1][c+1]=p.givens[r*p.n+c];for(let i=0;i<p.n;i++){a[0][i+1]=p.clues.top[i];a[n-1][i+1]=p.clues.bottom[i];a[i+1][0]=p.clues.left[i];a[i+1][n-1]=p.clues.right[i];}let b=a;const variants=[];for(let k=0;k<4;k++){variants.push(JSON.stringify(b));variants.push(JSON.stringify(b.map(row=>row.slice().reverse())));b=b.map((row,r)=>row.map((_,c)=>b[n-1-c][r]));}const key=variants.sort()[0];assert.ok(!keys.has(key),p.id);keys.add(key);}for(let c=0;c<6;c++)assert.equal(L.filter(p=>p.chapter===c).length,10);});
test('daily session isolation and both pending reward events survive independent upgrade',()=>{const p=L[0],actions=[];p.solution.forEach((v,i)=>{if(!p.givens[i])actions.push({type:'set',i,v});});const d=S.empty(),hinted={actions,hints:1,runId:'hinted',mode:'chapter'},independent={actions,hints:0,runId:'independent',mode:'daily'};d.sessions[p.id]=hinted;d.sessions['daily:2026-09-13:'+p.id]=independent;S.settle(d,p,hinted,'2026-09-13T00:00:00Z');S.settle(d,p,independent,'2026-09-13T00:01:00Z');const restored=S.load({getItem:()=>JSON.stringify(d)},L);assert.equal(restored.outbox.length,2);assert.equal(restored.sessions[p.id].runId,'hinted');assert.equal(restored.sessions['daily:2026-09-13:'+p.id].runId,'independent');assert.equal(restored.records[p.id].hints,0);});
test('recover interrupted settlement once, without rewarding unfinished sessions',()=>{const p=L[0],actions=[];p.solution.forEach((v,i)=>{if(!p.givens[i])actions.push({type:'set',i,v});});const d=S.empty();d.sessions[p.id]={actions,hints:0,runId:'interrupted',mode:'chapter'};d.sessions[L[1].id]={actions:[],hints:0,runId:'incomplete',mode:'chapter'};assert.equal(S.recover(d,L,'2026-09-13T01:00:00Z'),1);assert.equal(d.claims.length,2);assert.equal(d.outbox[0].runId,'interrupted');assert.equal(S.recover(d,L,'2026-09-13T01:01:00Z'),0);assert.equal(d.outbox.length,1);});
test('host mutation cannot alter durable pending payload or bypass acknowledgement',()=>{const d=S.empty();d.outbox=[{completionId:'original',rewardClaims:['first:test']}];const mem={setItem(){}};S.deliver(mem,d,p=>{p.completionId='mutated';p.rewardClaims.length=0;return false;});assert.equal(d.outbox[0].completionId,'original');assert.equal(d.outbox[0].rewardClaims.length,1);S.deliver(mem,d,p=>{p.completionId='changed';return true;});assert.equal(d.outbox.length,0);});
