import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {parse} from 'acorn';import {createHash} from 'node:crypto';
const root='dist/xhs',files=[];function walk(dir){for(const f of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,f.name);if(f.isDirectory())walk(full);else files.push(full);}}walk(root);
const js=fs.readFileSync(root+'/app.js','utf8'),html=fs.readFileSync(root+'/index.html','utf8'),css=fs.readFileSync(root+'/style.css','utf8');parse(js,{ecmaVersion:2017,sourceType:'script'});
const prohibited=[/\bfetch\s*\(/,/XMLHttpRequest/,/\b(?:WebSocket|EventSource|Worker|SharedWorker|RTCPeerConnection)\s*\(/,/serviceWorker/,/\beval\s*\(/,/new\s+Function/,/WebAssembly/,/navigator\.(?:clipboard|geolocation|bluetooth|usb|hid|serial|credentials|locks)/,/window\.(?:open|prompt)\s*\(/,/localStorage\.clear/,/\.at\s*\(/,/\.replaceAll\s*\(/,/structuredClone\s*\(/,/Object\.(?:hasOwn|fromEntries)\s*\(/];for(const rule of prohibited)assert(!rule.test(js),'Forbidden runtime: '+rule);
assert(!/type=["']module|\son[a-z]+\s*=|javascript:|<iframe|<object|<base|http-equiv=["']Content-Security/i.test(html));for(const s of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)){assert(/src=/.test(s[1]));assert.equal(s[2].trim(),'');}
for(const code of [html,css]){for(const m of code.matchAll(/(?:src|href)=["']([^"']+)["']|url\(['"]?([^)'"\s]+)['"]?\)/g)){const ref=m[1]||m[2];assert(ref.startsWith('./'),'nonrelative asset '+ref);assert(fs.existsSync(path.join(root,ref)),ref);}}
const allowed=/\.(html|css|js|png|jpg|jpeg|gif|webp|svg|woff|woff2|json)$/;assert(files.every(f=>allowed.test(f)));assert.equal(files.filter(f=>f.endsWith('.html')).length,1);assert(fs.existsSync(root+'/index.html'));assert(js.includes('Permission is hereby granted'));
const zip='dist/frostfield-railway-xhs.zip';const listing=execFileSync('unzip',['-Z1',zip],{encoding:'utf8'}).trim().split('\n');assert(listing.includes('index.html'));assert(listing.every(f=>!f.startsWith('/')&&!f.includes('..')&&!/node_modules|\.map$/.test(f)));execFileSync('unzip',['-t',zip]);assert(fs.statSync(zip).size<2*1024*1024);
execFileSync('python3',['-c',`import xml.etree.ElementTree as E,glob\nfor p in glob.glob('dist/xhs/assets/*.svg'): E.parse(p)\n`]);
const report={passed:true,checks:['ES2017 classic-script parse','Chrome 61 runtime API scan','All local references exist','No external resource or prohibited API','Exactly one HTML at ZIP root','All file suffixes allowed','ZIP CRC passed','SVG XML parsed','MIT notice included'],zipBytes:fs.statSync(zip).size,uncompressedBytes:files.reduce((s,f)=>s+fs.statSync(f).size,0),sha256:createHash('sha256').update(fs.readFileSync(zip)).digest('hex'),files:files.map(f=>({path:f.slice(root.length+1),bytes:fs.statSync(f).size}))};fs.writeFileSync('release/audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
