import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {LEVELS} from '../src/levels.mjs';import {initial,pathState,change,inspect,TILES} from '../src/engine.mjs';import {blank,newRun,complete,TUTORIAL} from '../src/session.mjs';import {PREFIX} from '../src/storage.mjs';
const require=createRequire(import.meta.url);let playwright;try{playwright=require('playwright');}catch(e){playwright=require(process.env.PLAYWRIGHT_MODULE||'playwright');}
const browser=await playwright.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1}),page=await context.newPage(),errors=[],external=[],report=[];
const url=process.env.GAME_URL||'http://127.0.0.1:4194/';
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(url))external.push(r.url());});
const click=action=>page.locator(`[data-action="${action}"]`).first().click();
async function read(){return page.evaluate(key=>JSON.parse(localStorage.getItem(key)),PREFIX+'profile');}
async function loadLevel(p){if(await page.locator('[data-action="home"]').count())await click('home');await page.locator(`[data-action="chapter"][data-value="${p.chapter}"]`).click();await page.locator(`[data-action="level"][data-value="${p.id}"]`).click();}
async function playSolution(p){const goal=pathState(p,p.path);for(const i of p.path){if(p.givens.some(g=>g[0]===i))continue;const data=await read(),current=data.sessions[p.id].board;if(current.masks[i]===goal.masks[i])continue;await page.locator(`[data-cell="${i}"]`).click();await page.locator(`[data-action="tile"][data-value="${goal.masks[i]}"]`).click();}assert.equal(await page.locator('.board-svg').getAttribute('data-status'),'won',p.id);}
try{
 await page.goto(url);await page.locator('[role="dialog"]').waitFor();assert.equal(await page.locator('[role="dialog"] .board-svg').getAttribute('data-status'),'unfinished');await page.screenshot({path:'release/tutorial-mobile.png'});
 await click('close');assert.equal(await page.locator('[role="dialog"]').count(),0);assert.equal((await read()).tutorial,TUTORIAL);await page.screenshot({path:'release/home-mobile.png',fullPage:true});
 await click('tutorial');for(let i=0;i<2;i++)await click('tutorial-next');assert.equal(await page.locator('[role="dialog"] .board-svg').getAttribute('data-status'),'won');await page.screenshot({path:'release/tutorial-complete.png'});await click('tutorial-next');assert.equal(await page.evaluate(()=>document.activeElement.dataset.action),'tutorial');report.push('First tutorial, skip, reopen, three truth states and restored focus');
 await click('continue');const p=LEVELS[0];let saved=await read();const fixed=p.givens[0][0];await page.locator(`[data-cell="${fixed}"]`).click();await click('erase');assert.deepEqual((await read()).sessions[p.id].board,saved.sessions[p.id].board);
 const goal=pathState(p,p.path);let move;for(let i=0;i<p.n*p.n&&!move;i++)for(const m of TILES){const r=change(p,saved.sessions[p.id].board,i,m);if(r.ok&&inspect(p,r.state).status!=='won'){move={i,m};break;}}assert(move);await page.locator(`[data-cell="${move.i}"]`).click();await page.locator(`[data-action="tile"][data-value="${move.m}"]`).click();assert.equal((await read()).sessions[p.id].board.moves,1);await click('undo');assert.deepEqual((await read()).sessions[p.id].board,saved.sessions[p.id].board);
 const empty=saved.sessions[p.id].board.masks.findIndex(x=>!x);await page.locator(`[data-cell="${empty}"]`).click();await click('candidate');assert.equal((await read()).sessions[p.id].board.notes[empty],1);await click('exclude');assert.equal((await read()).sessions[p.id].board.notes[empty],2);await click('undo');await click('undo');
 await click('restart');await click('restart-yes');assert.equal((await read()).sessions[p.id].history.length,0);await page.screenshot({path:'release/game-mobile.png',fullPage:true});
 await playSolution(p);let data=await read();assert(data.records[p.id]);const claims=data.claims.slice();await page.screenshot({path:'release/completion-mobile.png',fullPage:true});await page.reload();await click('continue');assert.equal(await page.locator('.board-svg').getAttribute('data-status'),'won');assert.deepEqual((await read()).claims,claims);await click('restart');await click('restart-yes');await playSolution(p);assert.deepEqual((await read()).claims,claims);report.push('Real clicks: fixed tile no-op, shared edges, candidates, exclude, undo/restart, win and refresh/replay reward dedup');
 await loadLevel(LEVELS[30]);await click('hint');await click('hint-reveal');assert.equal((await read()).sessions[LEVELS[30].id].hints,1);await click('hint-apply');await playSolution(LEVELS[30]);assert((await read()).records[LEVELS[30].id].assisted);report.push('Specific hint records assistance; apply and finish a middle chapter');
 await loadLevel(LEVELS[59]);
 const sizes=[[320,720],[359,720],[360,720],[361,720],[390,844],[759,844],[760,844],[761,844],[1280,720]];
 for(const [width,height]of sizes){await page.setViewportSize({width,height});await page.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');});const layout=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth,cell:document.querySelector('[data-cell]').getBoundingClientRect().width,buttons:Array.from(document.querySelectorAll('.tile-option,.edit-tools button,.back,.hint-button')).map(b=>({w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height}))}));assert(layout.scroll<=width,JSON.stringify(layout));assert(layout.cell>=43.99,`cell ${width}: ${layout.cell}`);assert(layout.buttons.every(b=>b.w>=43.99&&b.h>=43.99),`buttons ${width}: `+JSON.stringify(layout));await click('tutorial');assert.equal(await page.evaluate(()=>getComputedStyle(document.body).overflow),'hidden');await page.keyboard.press('Tab');for(let t=0;t<7;t++)await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>!!document.activeElement.closest('[role="dialog"]')),true);await page.keyboard.press('Escape');report.push(`Viewport ${width}×${height}, safe area 44/34, no horizontal overflow, targets >=44, modal trap`);if(width===320)await page.screenshot({path:'release/game-320.png',fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{document.documentElement.style.removeProperty('--safe-area-inset-top');document.documentElement.style.removeProperty('--safe-area-inset-bottom');});await playSolution(LEVELS[59]);await page.screenshot({path:'release/final-level-complete.png',fullPage:true});report.push('Last 6×6 puzzle completed through real buttons with reduced motion');
 await click('home');await click('collection');await page.screenshot({path:'release/collection-mobile.png',fullPage:true});
 // Maximal collection fixture is validated by the same completion routine; never mislabel as manual play.
 const max=blank();max.tutorial=TUTORIAL;for(const q of LEVELS){const r=newRun(q);r.board=pathState(q,q.path);max.sessions[q.id]=r;complete(max,q,r,LEVELS,q.id);}await page.evaluate(({key,value})=>localStorage.setItem(key,JSON.stringify(value)),{key:PREFIX+'profile',value:max});await page.reload();await click('collection');assert.equal(await page.locator('.collect-card.locked').count(),0);await page.screenshot({path:'release/collection-all-fixture.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);report.push('Maximum 60-completion/6-collection fixture renders without overflow');
 await page.setViewportSize({width:1280,height:720});await click('home');await page.screenshot({path:'release/home-desktop.png',fullPage:true});
 // Separate simulated native host with asynchronous storage, no browser persistence allowed.
 const nativeCtx=await browser.newContext();await nativeCtx.addInitScript(()=>{let store={};window.xhs={launchOptions:{miniToolEnv:{buildVersion:9462004}},miniTool:{getStorage:async o=>({data:store[o.key]}),setStorage:async o=>{store[o.key]=JSON.parse(JSON.stringify(o.data));},getStorageInfo:async()=>({keys:Object.keys(store)})}};window.__nativeStore=store;});const np=await nativeCtx.newPage();await np.goto(url);await np.locator('[data-action="close"]').first().click();await np.locator('[data-action="continue"]').click();assert(await np.evaluate(key=>!!window.__nativeStore[key].sessions['fr-001'],PREFIX+'profile'));await nativeCtx.close();report.push('Native storage bridge mock on client 9.46.2');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);report.push('No page exceptions or external runtime requests under restricted CSP');
 fs.writeFileSync('release/browser-report.json',JSON.stringify({passed:true,browser:await browser.version(),environment:'Headless desktop Chrome; responsive simulations, not physical devices',checks:report,errors,external},null,2));console.log(report.join('\n'));
}finally{await browser.close();}
