(function(){
'use strict';
var C=window.ScarletCore,L=window.ScarletLevels,R=window.ScarletRenderer,S=window.ScarletSession,D=window.ScarletStorage;
var main=document.getElementById('main'),modal=document.getElementById('modal'),content=document.getElementById('modal-content'),actions=document.getElementById('modal-actions');
var doc=S.fresh(),repo,state=null,index=0,view='home',selected=null,drag=null,busy=false,only=false,guide=null,lastFocus=null,scrollBefore=0,tutorialRead=false,tutorialStep=0,audio=null,clockStart=0,galleryChapter=0,ledgerFailed=false,tutorialFailed=false;
var chapters=['初签','双缘','回环','交契','星罗','归缘'];
function esc(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');}
function button(action,text,extra){return '<button data-action="'+action+'" '+(extra||'')+'>'+text+'</button>';}
function runId(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,12);}
function count(){return Object.keys(doc.collection).length;}
function msg(text){var e=document.getElementById('message');if(e)e.textContent=text;}
function saved(ok,key){if(key==='tutorial')tutorialFailed=!ok;else ledgerFailed=!ok;var e=document.getElementById('save-status');e.textContent=ledgerFailed?'本次未能保存。请保持页面打开，使用“重试保存”；关闭后可能丢失进度。':tutorialFailed?'教程阅读状态未保存，下次可能再次提示。':'';if(ledgerFailed||tutorialFailed){var b=document.createElement('button');b.textContent='重试保存';b.setAttribute('data-action','save');e.appendChild(b);}}
function sound(kind){if(doc.muted)return;try{var Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;if(!audio)audio=new Audio();if(audio.state==='suspended')audio.resume();var o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type=kind==='win'?'sine':'triangle';o.frequency.setValueAtTime(kind==='win'?520:kind==='knot'?160:340,t);o.frequency.exponentialRampToValueAtTime(kind==='win'?780:kind==='knot'?100:220,t+.12);g.gain.setValueAtTime(.025,t);g.gain.exponentialRampToValueAtTime(.0001,t+.22);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.24);}catch(e){}}
function elapsed(){return (state&&state.elapsedMs||0)+(clockStart?Date.now()-clockStart:0);}
function snapshotClock(){if(state){state.elapsedMs=elapsed();clockStart=C.solved(state.points,L[index].edges)?0:Date.now();}}
function formatTime(ms){var secs=Math.floor(ms/1000);return Math.floor(secs/60)+'分'+String(secs%60).padStart(2,'0')+'秒';}
async function persist(){if(!repo)return false;var ok=await repo.write('ledger',doc);saved(ok);if(ok&&doc.outbox.length&&typeof window.ScarletRewardHost==='function'){var result=await D.flush(doc,repo,window.ScarletRewardHost,function(){return doc;});Object.keys(result.doc.claims).forEach(function(id){if(result.doc.claims[id].delivered&&doc.claims[id])doc=S.acknowledge(doc,id);});ok=result.ok;if(ok)ok=await repo.write('ledger',doc);saved(ok);}return ok;}
function closeModal(){if(modal.hidden)return;modal.hidden=true;document.body.style.overflow='';if(lastFocus&&document.contains(lastFocus))lastFocus.focus();else main.focus();window.scrollTo(0,scrollBefore);}
function openModal(title,html,controls){if(modal.hidden){lastFocus=document.activeElement;scrollBefore=window.scrollY;}document.getElementById('modal-title').textContent=title;content.innerHTML=html;actions.innerHTML=controls||button('close','知道了','class="primary"');modal.hidden=false;document.body.style.overflow='hidden';content.scrollTop=0;document.getElementById('close-modal').focus();}
function leave(){if(state){snapshotClock();doc.sessions[L[index].id]=C.clone(state);persist();}}
function home(){leave();closeModal();view='home';state=null;clockStart=0;selected=null;main.innerHTML='<section class="home"><div class="hall"><div class="hall-copy"><p class="eyebrow">缘簿四十八封 · 结线师的馆</p><h1>红线绮梦馆</h1><p class="subtitle">一枚纸签，一段缘。<br>慢慢整理，任红线各归其位。</p></div></div><div class="home-panel"><p class="progress">已归档 '+count()+' / 48 封缘签</p><p class="muted">六册缘簿 · 挪动签印 · 解开所有线结</p>'+button('continue',count()?'继续整理':'整理第一封缘签','class="primary"')+'<div class="home-nav">'+button('chapters','六册缘簿','class="quiet"')+button('collection','缘签图鉴','class="quiet"')+button('tutorial','玩法三图','class="quiet"')+'</div></div><div class="intro-note"><div class="seal-clerk" aria-hidden="true">缘</div><p class="muted">不必寻找唯一摆法。<br>所有不共端点的朱线互不接触，就是你的答案。</p></div></section>';window.scrollTo(0,0);}
function books(collection){leave();closeModal();view=collection?'collection':'chapters';state=null;clockStart=0;var html='<section class="page"><div class="page-heading"><div><p class="eyebrow">缘簿 · '+count()+' / 48</p><h1>'+(collection?'缘签图鉴':'六册缘簿')+'</h1></div>'+button('home','馆门','class="quiet"')+'</div><p class="muted">'+(collection?'收录真实完成图。每一封缘签只收一次，图中的点位是你的个人摆法。':'每册两封引导、四封迁移、两封综合。可自由选关，慢慢学会整理。')+'</p><div class="books">';
if(collection){html+='<div class="archive-tabs">';chapters.forEach(function(name,ch){html+=button('archive-chapter',(ch+1)+' · '+name,'data-index="'+ch+'" '+(galleryChapter===ch?'class="primary"':''));});html+='</div>';}
chapters.forEach(function(name,ch){if(collection&&ch!==galleryChapter)return;var ls=L.filter(function(l){return l.chapter===ch+1;}),done=ls.filter(function(l){return !!doc.collection[l.id];}).length;html+='<section class="book"><div class="book-title"><strong>'+String(ch+1).padStart(2,'0')+' · '+name+'</strong><span>'+done+' / 8 封</span></div><p class="goal">'+esc(ls[0].goal)+'</p><div class="signatures">';ls.forEach(function(l,j){var i=L.indexOf(l),record=doc.collection[l.id];html+='<button class="signature '+(record?'done ':'')+(i===doc.current?'current':'')+'" data-action="'+(collection?'inspect':'level')+'" data-index="'+i+'" '+(collection&&!record?'disabled':'')+'><span class="num">'+String(i+1).padStart(2,'0')+'</span>'+esc(collection?name+'缘签':l.role)+'<span class="state">'+(record?'已归档':i===doc.current?'正在整理':'尚未归档')+'</span>'+(collection?R.svg(l,record?record.session.points:l.witness,{width:350,height:400}):'')+'</button>';});html+='</div></section>';});html+='</div></section>';main.innerHTML=html;window.scrollTo(0,0);}
function start(i,newRun){closeModal();view='game';index=i;doc.current=i;selected=null;only=false;guide=null;state=!newRun&&doc.sessions[L[i].id]?C.clone(doc.sessions[L[i].id]):C.create(L[i],runId());clockStart=C.solved(state.points,L[i].edges)?0:Date.now();doc.sessions[L[i].id]=C.clone(state);busy=true;renderGame();window.scrollTo(0,0);persist().then(function(){busy=false;});if(!tutorialRead&&i===0)showTutorial(0);}
function renderGame(){var level=L[index],n=C.pairs(state.points,level.edges).length,win=n===0;
main.innerHTML='<section class="desk"><div class="board-column"><div class="game-heading"><div><p class="eyebrow">第'+level.chapter+'册 · '+chapters[level.chapter-1]+'</p><h1>'+esc(level.name)+'</h1></div><span class="folio">'+String(index+1).padStart(2,'0')+' / 48</span></div><div class="counter"><span>交叉边对 <strong id="cross-count">'+n+'</strong></span><span id="moves">'+state.history.length+' 次移动</span></div><div id="board" class="board" tabindex="0" role="group" aria-label="结线案面，选签后可用方向键微调"></div><div class="tools">'+button('undo','撤销',state.history.length?'':'disabled')+button('hint','提示')+button('pick','选点')+button('restart','重开')+'</div><div id="selection" class="selection"></div><p id="message" class="message" role="status">'+(win?'所有线结已解开。仍可撤销，保留你自己的摆法。':'拖动纸签，所有相连朱线会一起移动。菱形标记表示线结。')+'</p><div id="win" '+(win?'':'hidden')+' class="win"><span class="stamp">归档</span><h2>这一封，各归其缘</h2><p id="win-record">'+state.history.length+' 次移动 · '+formatTime(state.elapsedMs||0)+'</p><p class="muted">'+(doc.collection[level.id]?'缘签已收录，复玩不重复领取。':'已完成；正在保存这封缘签。')+'</p>'+button('next',index===47?'回看六册缘簿':'整理下一封','class="primary"')+'</div></div><aside class="desk-note"><span class="chapter-tab">'+chapters[level.chapter-1]+' · '+level.role+'</span><h2>挪一枚印，<br>看一段缘。</h2><p>'+esc(level.goal)+'</p><div class="principle"><p>让 <b>所有不共端点的边</b> 互不接触。</p><p class="muted">X 交叉、T 接触、共线重叠都算线结。同一个签印上的共同端点不算。</p></div><p class="muted">选点后，用方向键微调；按住 Shift 更细。密集处会列出签号，避免选错。</p><p class="muted">个人记录：<span id="time">'+formatTime(elapsed())+'</span> · 不设倒计时</p><div class="row">'+button('chapters','六册缘簿')+button('collection','缘签图鉴')+button('tutorial','重看教程')+'</div></aside></section>';
renderBoard();renderSelection();bindBoard();}
function displayPoints(){if(!drag)return state.points;var ps=C.clone(state.points);ps.forEach(function(p){if(p.id===drag.id){p.x=drag.x;p.y=drag.y;}});return ps;}
function size(){var b=document.getElementById('board');return {width:b.clientWidth,height:b.clientHeight};}
function renderBoard(){var board=document.getElementById('board');if(!board)return;var sz=size(),ps=displayPoints(),level=L[index],html=R.svg(level,ps,{width:sz.width,height:sz.height,selected:selected,onlySelected:only});ps.forEach(function(p){var connected=level.edges.filter(function(e){return e.includes(p.id);}).map(function(e){return (e[0]===p.id?e[1]:e[0])+1;});html+='<button class="node-hit" data-node="'+p.id+'" aria-label="签印'+(p.id+1)+'，连接签'+connected.join('、')+'" style="left:'+(18+p.x*(sz.width-36))+'px;top:'+(20+p.y*(sz.height-40))+'px">'+(p.id+1)+'</button>';});if(guide){html+='<span aria-hidden="true" style="position:absolute;left:'+(18+guide.x*(sz.width-36)-16)+'px;top:'+(20+guide.y*(sz.height-40)-16)+'px;width:32px;height:32px;border:2px dashed #2e6e66;border-radius:50%;pointer-events:none"></span>';}board.innerHTML=html;document.getElementById('cross-count').textContent=C.pairs(ps,level.edges).length;}
function renderSelection(){var el=document.getElementById('selection');el.innerHTML='<div class="selection-head"><p>'+(selected===null?'先选一枚签印，再精确微调':'当前选择：签印 '+(selected+1))+'</p>'+button('pick','换签','class="small"')+'</div><div class="direction-pad" aria-label="方向微调">'+button('nudge','←','data-dx="-1" data-dy="0" aria-label="向左微调" '+(selected===null?'disabled':''))+button('nudge','↑','data-dx="0" data-dy="-1" aria-label="向上微调" '+(selected===null?'disabled':''))+button('nudge','↓','data-dx="0" data-dy="1" aria-label="向下微调" '+(selected===null?'disabled':''))+button('nudge','→','data-dx="1" data-dy="0" aria-label="向右微调" '+(selected===null?'disabled':''))+'</div><label class="check"><input id="only" type="checkbox" '+(only?'checked':'')+(selected===null?' disabled':'')+'>仅看所选连线（总交叉数始终保留）</label>';document.getElementById('only').addEventListener('change',function(e){only=e.target.checked;renderBoard();});}
function select(id){selected=id;guide=null;renderBoard();renderSelection();var b=document.getElementById('board');b.focus();msg('已选签印 '+(id+1)+'。拖动它或使用方向微调。');}
function picker(ids){var level=L[index],ps=state.points,candidates=ids||ps.map(function(p){return p.id;});var html='<p class="muted">'+(ids?'此处有多个命中区。请先确认签号，再移动。':'签号常驻在纸签上。选择后可用方向微调，不必拖动。')+'</p><div class="pick-preview">'+R.svg(level,ps,{width:320,height:140,selected:selected})+'</div>';candidates.forEach(function(id){var others=level.edges.filter(function(e){return e.includes(id);}).map(function(e){return (e[0]===id?e[1]:e[0])+1;});html+='<button class="pick-row" data-action="select" data-id="'+id+'"><span>签印 '+(id+1)+'</span><small>连接 '+others.join(' · ')+'</small></button>';});openModal('选择一枚签印',html);}
function mapPoint(e){var b=document.getElementById('board'),r=b.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left-18)/(r.width-36))),y:Math.max(0,Math.min(1,(e.clientY-r.top-20)/(r.height-40)))};}
function down(e){if(busy||!modal.hidden||drag)return;if(e.button!==undefined&&e.button!==0)return;var b=document.getElementById('board'),r=b.getBoundingClientRect(),ps=state.points;var hits=ps.filter(function(p){return Math.hypot(r.left+18+p.x*(r.width-36)-e.clientX,r.top+20+p.y*(r.height-40)-e.clientY)<=22;}).map(function(p){return p.id;});if(hits.length>1){e.preventDefault();picker(hits);return;}if(!hits.length)return;e.preventDefault();selected=hits[0];var p=ps.filter(function(p){return p.id===selected;})[0];drag={id:selected,x:p.x,y:p.y,pointer:e.pointerId,startX:e.clientX,startY:e.clientY,offsetX:e.clientX-(r.left+18+p.x*(r.width-36)),offsetY:e.clientY-(r.top+20+p.y*(r.height-40)),moved:false};if(b.setPointerCapture&&e.pointerId!==undefined){try{b.setPointerCapture(e.pointerId);}catch(err){}}renderBoard();renderSelection();}
function move(e){if(!drag||(e.pointerId!==undefined&&drag.pointer!==undefined&&e.pointerId!==drag.pointer))return;e.preventDefault();if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<2&&!drag.moved)return;drag.moved=true;var p=mapPoint({clientX:e.clientX-drag.offsetX,clientY:e.clientY-drag.offsetY});drag.x=p.x;drag.y=p.y;renderBoard();}
function cancel(){if(!drag)return;drag=null;renderBoard();msg('手势已取消，签印回到原位，未计步。');}
function up(e){if(!drag||(e.pointerId!==undefined&&drag.pointer!==undefined&&e.pointerId!==drag.pointer))return;var d=drag;drag=null;if(d.moved)apply(C.move(state,d.id,d.x,d.y));else{renderBoard();msg('已选签印 '+(selected+1)+'，未移动。');}}
function bindBoard(){var b=document.getElementById('board');if(window.PointerEvent){b.addEventListener('pointerdown',down);b.addEventListener('pointermove',move);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',cancel);b.addEventListener('lostpointercapture',cancel);}else{b.addEventListener('mousedown',down);b.addEventListener('touchstart',function(e){if(e.touches.length!==1){cancel();return;}var t=e.touches[0];down({clientX:t.clientX,clientY:t.clientY,preventDefault:function(){e.preventDefault();}});},{passive:false});b.addEventListener('touchmove',function(e){if(e.touches.length!==1){cancel();return;}var t=e.touches[0];move({clientX:t.clientX,clientY:t.clientY,preventDefault:function(){e.preventDefault();}});},{passive:false});b.addEventListener('touchend',function(e){e.preventDefault();up({});});b.addEventListener('touchcancel',cancel);}
b.addEventListener('keydown',function(e){var delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta){e.preventDefault();nudge(delta[0],delta[1],e.shiftKey ? .005 : .02);}if(e.key==='Escape')cancel();});}
if(!window.PointerEvent){window.addEventListener('mousemove',move);window.addEventListener('mouseup',up);}
async function apply(next){if(busy||next===state)return;busy=true;var was=C.solved(state.points,L[index].edges),old=C.pairs(state.points,L[index].edges).length;next.elapsedMs=elapsed();state=next;guide=null;var won=C.solved(state.points,L[index].edges);clockStart=won?0:Date.now();doc=S.settle(doc,L[index],state);renderGame();sound(won&&!was?'win':C.pairs(state.points,L[index].edges).length>old?'knot':'paper');await persist();busy=false;}
function nudge(dx,dy,step){if(selected===null||busy)return;var p=state.points.filter(function(v){return v.id===selected;})[0];apply(C.move(state,selected,Math.max(0,Math.min(1,Math.round((p.x+dx*(step||.02))*1000000)/1000000)),Math.max(0,Math.min(1,Math.round((p.y+dy*(step||.02))*1000000)/1000000))));}
function showTutorial(step){tutorialStep=step;var titles=['认出线结','挪一枚纸签','各归其缘'],files=['initial','one','complete'],text=['签号是点，朱线是边。两条不共端点的直线交叉，中央会出现菱形。现在有 1 对交叉。','同一题，把签 1 从左上移到左侧中部。与它相连的朱线一起改变；仍有 1 对交叉。一次拖动只在松手后计一步。','再把签 4 移到右上方的空处。正式判定为 0 对交叉，就完成了。T 接触与共线重叠也算线结。'];openModal('玩法 · '+titles[step],'<p class="tutorial-num">'+(step+1)+' / 3 · 同一封缘签</p><img class="tutorial-img" src="./assets/tutorial-'+files[step]+'.svg" alt="第一封缘签真实'+titles[step]+'状态，'+(step===2?'0':'1')+'对交叉"><p>'+text[step]+'</p><p class="muted">也可点击“选点”，再用方向微调。没有唯一或最优摆法的要求。</p>',button('tutorial-skip','跳过','class="quiet"')+button(step===2?'tutorial-finish':'tutorial-next',step===2?'看完，开始整理':'下一张','class="primary"'));}
function hint(){if(busy)return;var level=L[index],pairs=C.pairs(state.points,level.edges);if(!pairs.length){msg('这一封已经归档，可以回看自己的布局。');return;}state.hintsUsed++;doc.sessions[level.id]=C.clone(state);busy=true;persist().then(function(){busy=false;});var stage=(state.hintsUsed-1)%3,html,controls;
if(stage===0){var p=pairs[0],a=level.edges[p[0]],b=level.edges[p[1]];html='<p>先检查签 '+(a[0]+1)+'—'+(a[1]+1)+' 与签 '+(b[0]+1)+'—'+(b[1]+1)+' 两条朱线。它们没有共同端点，却发生了接触。</p><p class="muted">移动任何一端都会同时改变该签上的其他线，先看影响范围。</p>';}else if(stage===1){var ids=level.topology.articulations;html='<p>'+esc(level.goal)+'</p><p>'+(ids.length?'签 '+ids.map(function(i){return i+1;}).join('、')+' 连接着不同图块。先用“仅看所选连线”检查它们，再分片安排空位。':'这页没有单一关节点。先从一个回环的外轮廓开始，给内部连接留空位。')+'</p>';}else{guide=level.witness.filter(function(p){var cur=state.points.filter(function(v){return v.id===p.id;})[0];return Math.hypot(p.x-cur.x,p.y-cur.y)>.001;})[0];if(!guide)return;selected=guide.id;renderBoard();renderSelection();html='<p>参考摆法：把签 '+(guide.id+1)+' 移到案面上的虚线圆框。</p><p class="muted">这是经过验证的一份完整布局中的落点，不是必选位置，也不保证这一步就减少交叉。你可以换一种摆法。</p>';controls=button('close','自己试试')+button('hint-apply','试放此签','class="primary"');}openModal('结线提示 · '+(stage+1)+'/3',html,controls);}
document.addEventListener('click',function(e){var node=e.target.closest('.node-hit');if(node&&e.detail===0){select(Number(node.getAttribute('data-node')));return;}var el=e.target.closest('[data-action]');if(!el)return;var action=el.getAttribute('data-action');if(busy&&['home','continue','chapters','collection','level','next','restart','nudge','undo','hint','hint-apply'].includes(action))return;
if(action==='home')home();else if(action==='continue')start(doc.current,false);else if(action==='chapters')books(false);else if(action==='collection')books(true);else if(action==='archive-chapter'){galleryChapter=Number(el.getAttribute('data-index'));books(true);}else if(action==='level')start(Number(el.getAttribute('data-index')),false);else if(action==='next'){if(index===47)books(false);else start(index+1,false);}else if(action==='close')closeModal();else if(action==='tutorial')showTutorial(0);else if(action==='tutorial-next')showTutorial(tutorialStep+1);else if(action==='tutorial-skip'||action==='tutorial-finish'){tutorialRead=true;repo.write('tutorial',{version:1}).then(function(ok){saved(ok,'tutorial');});closeModal();}else if(action==='pick')picker();else if(action==='select'){var id=Number(el.getAttribute('data-id'));closeModal();select(id);}else if(action==='nudge')nudge(Number(el.getAttribute('data-dx')),Number(el.getAttribute('data-dy')));else if(action==='undo')apply(C.undo(state));else if(action==='restart')openModal('重新整理这一封？','<p>本局点位、移动次数和提示次数会重新开始；已经收录的缘签不会重复领取。</p>',button('close','保留这一局')+button('restart-confirm','重新开始','class="primary"'));else if(action==='restart-confirm'){if(!busy)start(index,true);}else if(action==='hint')hint();else if(action==='hint-apply'){var g=guide;closeModal();if(g)apply(C.move(state,g.id,g.x,g.y));}else if(action==='save'){if(tutorialRead)repo.write('tutorial',{version:1}).then(function(ok){saved(ok,'tutorial');});persist();}else if(action==='inspect'){var i=Number(el.getAttribute('data-index')),rec=doc.collection[L[i].id];openModal('缘签 · '+L[i].name,'<div class="collected-view">'+R.svg(L[i],rec.session.points,{width:350,height:400})+'</div><p class="gallery-caption">个人摆法 · 0 对交叉 · '+rec.session.history.length+' 次移动 · '+formatTime(rec.session.elapsedMs||0)+'</p>',button('close','收好')+button('level','再整理一遍','data-index="'+i+'" class="primary"'));}else if(action==='source')openModal('规则与来源','<p>这是 Untangle：移动签印，让所有没有共同逻辑端点的直线边互不相交。</p><p>X 交叉、T 接触、共线重叠、不同签号的端点重合都算相交。同 ID 的共端点边对豁免。胜利依据正式提交点位的几何判定；撤销胜利仍然可用。</p><p class="muted">交叉数是边对数，不是不同交点的数量。没有额外的最小间距规则；贴线时可以用方向微调拉开。提示不扣缘签，没有唯一解或最少步数承诺。</p><p class="source-list">规则参考：Simon Tatham’s Portable Puzzle Collection、ebnbin/puzzles（MIT）。来源《月老红线事务所》；本作重新设计主题、关卡、界面与原创代码素材。馆景插画由 OpenAI ImageGen 辅助生成，玩法和教程来自真实规则状态。</p><p class="muted">仅使用本工具私有本地存档。清理缓存或卸载可能导致进度丢失；未联网收集玩法数据。</p>');});
document.getElementById('home-link').addEventListener('click',function(){if(!busy)home();});document.getElementById('sound').addEventListener('click',function(){if(busy)return;doc.muted=!doc.muted;this.textContent=doc.muted?'静音':'声音';this.setAttribute('aria-label',doc.muted?'开启声音':'关闭声音');sound('paper');persist();});document.getElementById('close-modal').addEventListener('click',closeModal);
document.addEventListener('keydown',function(e){if(modal.hidden)return;if(e.key==='Escape'){e.preventDefault();closeModal();}if(e.key==='Tab'){var all=Array.prototype.slice.call(modal.querySelectorAll('button:not([disabled]),input:not([disabled])'));if(!all.length)return;var first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('resize',function(){if(view==='game'){cancel();renderBoard();}});document.addEventListener('visibilitychange',function(){if(state&&!busy){snapshotClock();if(document.hidden)clockStart=0;else if(!C.solved(state.points,L[index].edges))clockStart=Date.now();doc.sessions[L[index].id]=C.clone(state);persist();}});setInterval(function(){var el=document.getElementById('time');if(el&&state)el.textContent=formatTime(elapsed());},1000);
(async function(){repo=D.repository(await D.adapter(window));var result=await repo.read('ledger');doc=S.restore(L,result.value);var tr=await repo.read('tutorial');tutorialRead=!!(tr.value&&tr.value.version===1);document.getElementById('sound').textContent=doc.muted?'静音':'声音';home();if(!result.ok)saved(false);if(doc.outbox.length)await persist();})();
}());
