import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve,extname} from 'node:path';
import {LEVELS} from '../levels.mjs';
import {STORE_KEY,TUTORIAL_KEY} from '../session.mjs';
import {logicTrace} from '../logic.mjs';
const require=createRequire(import.meta.url),{chromium}=require(resolve(process.env.PORCELAIN_NODE_MODULES||'node_modules','playwright'));
const base=fileURLToPath(new URL('..',import.meta.url)),root=resolve(base,'dist/xhs'),screens=resolve(base,'release/screenshots');mkdirSync(screens,{recursive:true});
const CSP="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'none'; worker-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'";
const server=createServer((req,res)=>{try{let path=decodeURIComponent(req.url.split('?')[0]);if(path==='/')path='/index.html';const target=resolve(root,'.'+path);if(!target.startsWith(root+'/'))throw Error('path');const data=readFileSync(target);res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json'}[extname(target)]||'application/octet-stream','Content-Security-Policy':CSP});res.end(data);}catch(e){res.writeHead(404);res.end('missing');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,channel:'chrome'});const failures=[],results=[],external=[];
async function context(width,height,opts={}){const c=await browser.newContext(Object.assign({viewport:{width,height},deviceScaleFactor:1},opts));const page=await c.newPage();page.on('pageerror',e=>failures.push(e.message));page.on('request',r=>{if(!r.url().startsWith(url))external.push(r.url());});return {c,page};}
async function ready(page){await page.goto(url);await page.locator('#app[aria-busy="false"]').waitFor();}
async function click(page,action){await page.locator('[data-action="'+action+'"]').first().click();}
async function stored(page){return page.evaluate(key=>JSON.parse(localStorage.getItem(key)),STORE_KEY);}
async function waitCursor(page,cursor){await page.waitForFunction(({key,cursor})=>JSON.parse(localStorage.getItem(key)).current.cursor===cursor,{key:STORE_KEY,cursor});}
async function selectLevel(page,n){if(await page.locator('[data-action="home"]').count())await click(page,'home');await click(page,'chapters');await page.locator('[data-chapter="'+LEVELS[n-1].chapter+'"]').click();await page.locator('[data-level="'+LEVELS[n-1].id+'"]').click();if(n===21)await click(page,'ring-done');await page.locator('[data-cell="0"]').waitFor();}
async function directCell(page,i,v){await page.locator('[data-tool]').filter({hasText:v==='\\'?'╲':'╱'}).first().click();await page.locator('[data-cell="'+i+'"]').click();}
async function fit(page,label,minCell){const m=await page.evaluate(()=>{const d=document.documentElement;const cells=Array.from(document.querySelectorAll('[data-cell]')).map(n=>n.getBoundingClientRect());return {scrollWidth:d.scrollWidth,width:d.clientWidth,minCell:cells.length?Math.min(...cells.map(b=>b.width)):null,minHeight:cells.length?Math.min(...cells.map(b=>b.height)):null,modalOverflow:Array.from(document.querySelectorAll('.modal')).some(n=>n.scrollWidth>n.clientWidth)};});assert.ok(m.scrollWidth<=m.width,label+' horizontal '+JSON.stringify(m));if(minCell)assert.ok(m.minCell>=44&&m.minHeight>=44,label+' targets '+JSON.stringify(m));assert.ok(!m.modalOverflow,label+' modal overflow');results.push({label,metrics:m});}
try{
 // First launch, all 3 real tutorial frames, skip/reopen/focus, home and full desktop session.
 const {c,page}=await context(1280,720);await ready(page);await fit(page,'desktop first tutorial');await page.screenshot({path:resolve(screens,'tutorial-01-desktop.png')});
 await click(page,'tutorial-next');await page.screenshot({path:resolve(screens,'tutorial-02-desktop.png')});await click(page,'tutorial-next');await page.screenshot({path:resolve(screens,'tutorial-03-desktop.png')});await click(page,'tutorial-next');await page.screenshot({path:resolve(screens,'home-desktop.png')});await click(page,'continue');await fit(page,'desktop play',true);
 // Tapping close to a digit enters inspection and cannot install a wrong cell.
 const cornerBox=await page.locator('[data-cell="0"]').boundingBox();await page.mouse.click(cornerBox.x+2,cornerBox.y+2);assert.equal((await stored(page)).current.cursor,0);assert.ok((await page.locator('.board-caption').innerText()).includes('检查模式'));await click(page,'install');
 // No-op, inspect, note, undo/redo, keyboard, drag cancellation, save/refresh.
 await directCell(page,0,LEVELS[0].solution[0]);let s=await stored(page);assert.equal(s.current.cursor,1);await directCell(page,0,LEVELS[0].solution[0]);assert.equal((await stored(page)).current.cursor,1);
 await page.locator('[data-corner="0"]').click();await page.locator('[data-cell="1"]').click();assert.equal((await stored(page)).current.cursor,1);await click(page,'install');
 await click(page,'pencil');await directCell(page,1,'/');await waitCursor(page,2);assert.equal((await stored(page)).current.actions[1].kind,'note');await click(page,'undo');await waitCursor(page,1);await click(page,'redo');await waitCursor(page,2);await click(page,'install');
 await page.locator('[data-cell="2"]').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Backslash');await waitCursor(page,3);await page.keyboard.press('Control+z');await waitCursor(page,2);await page.keyboard.press('Control+Shift+z');await waitCursor(page,3);
 const box=await page.locator('[data-cell="4"]').boundingBox(),before=(await stored(page)).current.cursor;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+12,box.y+box.height/2);await page.mouse.up();assert.equal((await stored(page)).current.cursor,before);
 await page.reload();await page.locator('#app[aria-busy="false"]').waitFor();await click(page,'continue');assert.equal((await stored(page)).current.cursor,before);
 await click(page,'restart');await click(page,'close');assert.equal((await stored(page)).current.cursor,before);await click(page,'restart');await click(page,'restart-confirm');await waitCursor(page,0);
 // Finish with actual actions, stable reward, undo completion/re-completion and replay new run.
 for(let i=0;i<LEVELS[0].solution.length;i++)await directCell(page,i,LEVELS[0].solution[i]);await page.locator('.win-banner').waitFor();await page.screenshot({path:resolve(screens,'complete-desktop.png')});
 let completed=await stored(page);assert.equal(Object.keys(completed.records).length,1);assert.equal(completed.outbox.length,1);assert.equal(completed.outbox[0].claimIds.length,2);const completionId=completed.current.completedId;
 await click(page,'undo');assert.equal(await page.locator('.win-banner').count(),0);await click(page,'redo');assert.equal((await stored(page)).current.completedId,completionId);assert.equal((await stored(page)).outbox.length,1);
 await click(page,'result');await page.screenshot({path:resolve(screens,'result-desktop.png')});await click(page,'collection');await page.screenshot({path:resolve(screens,'collection-desktop.png')});
 await selectLevel(page,1);await click(page,'restart');await click(page,'restart-confirm');for(let i=0;i<LEVELS[0].solution.length;i++)await directCell(page,i,LEVELS[0].solution[i]);assert.equal((await stored(page)).outbox.length,1);
 // Three explicit hint stages and current-state proof, no baked answer placement.
 await selectLevel(page,24);await click(page,'hint');await click(page,'hint-explain');await page.screenshot({path:resolve(screens,'hint-desktop.png')});await click(page,'hint-confirm');await click(page,'hint-apply');assert.equal((await stored(page)).current.hints,1);assert.equal((await stored(page)).current.cursor,1);
 await click(page,'manual');await page.keyboard.press('Escape');assert.equal(await page.locator('.modal').count(),0);await click(page,'ring');await click(page,'ring-toggle');assert.equal(await page.locator('.modal svg [stroke-dasharray]').count()>0,true);await page.screenshot({path:resolve(screens,'loop-practice-desktop.png')});await click(page,'ring-toggle');await click(page,'ring-done');
 // Hint exposing real long path, reached by actual deduction steps on 57.
 await selectLevel(page,57);const trace=logicTrace(LEVELS[56],false).steps,stop=trace.findIndex(d=>d.type==='loop'&&d.path.length>=6);assert.ok(stop>=0);
 for(const d of trace.slice(0,stop))await directCell(page,d.i,d.value);await click(page,'hint');await click(page,'hint-explain');await page.screenshot({path:resolve(screens,'long-path-desktop.png')});await fit(page,'desktop long-path');await click(page,'close');
 // Clearly labeled optional cycle; choosing a direction returns to direct mode.
 await click(page,'restart');await click(page,'restart-confirm');await click(page,'home');await click(page,'settings');await click(page,'cycle');await click(page,'close');await click(page,'continue');await page.locator('[data-cell="0"]').click();await waitCursor(page,1);await page.locator('[data-cell="0"]').click();await waitCursor(page,2);assert.equal((await stored(page)).current.actions[1].value,'/');await directCell(page,1,'/');assert.equal((await stored(page)).settings.cycle,false);
 // Pending event host retry retains same payload, once ack persisted removes; ready repeat remains quiet.
 await page.evaluate(()=>{window.received=[];window.PorcelainHost={complete:async e=>{window.received.push(e);return false;}};window.dispatchEvent(new Event('porcelain-host-ready'));});await page.waitForFunction(()=>window.received.length===1);assert.equal((await stored(page)).outbox.length,1);
 await page.evaluate(()=>{window.PorcelainHost.complete=async e=>{window.received.push(e);return true;};window.dispatchEvent(new Event('porcelain-host-ready'));});await page.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).outbox.length===0,STORE_KEY);const events=await page.evaluate(()=>window.received);assert.equal(events[0].completionId,events[1].completionId);assert.deepEqual(events[0],events[1]);
 await page.evaluate(()=>window.dispatchEvent(new Event('porcelain-host-ready')));await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>window.received.length),2);
 results.push({label:'desktop interactions, reward and host retry',passed:true});await c.close();
 // Touch and keyboard focus sizes, largest board, every breakpoint adjacent, landscape.
 for(const [width,height] of [[320,720],[359,720],[360,720],[390,844],[759,720],[760,720],[761,720],[844,390],[1280,720]]){
  const {c,page}=await context(width,height,{hasTouch:width<800,isMobile:width<500});await ready(page);await click(page,'tutorial-skip');await fit(page,width+' home');
  if(width===390)await page.screenshot({path:resolve(screens,'home-390.png'),fullPage:true});await click(page,'chapters');if(width===390)await page.screenshot({path:resolve(screens,'chapters-390.png'),fullPage:true});await page.locator('[data-chapter="6"]').click();await page.locator('[data-level="porcelain-60"]').click();await fit(page,width+' largest board',true);
  if(width===320||width===390)await page.screenshot({path:resolve(screens,'play-'+width+'.png'),fullPage:true});
  await page.locator('[data-tool="/"]').click();const b=page.locator('[data-cell="41"]');if(width<500)await b.tap();else await b.click();await waitCursor(page,1);await page.locator('[data-corner="3"]').click();assert.equal((await stored(page)).current.cursor,1);await click(page,'install');await click(page,'undo');await waitCursor(page,0);
  await click(page,'hint');await fit(page,width+' hint');await click(page,'close');await click(page,'manual');await fit(page,width+' tutorial');await click(page,'tutorial-next');await click(page,'tutorial-next');if(width===390)await page.screenshot({path:resolve(screens,'tutorial-390.png')});await click(page,'tutorial-next');
  await page.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');});await fit(page,width+' safe area',true);
  await c.close();
 }
 // Reduced motion and 200% text: explicit physical CSS resizing all base text.
 const zoom=await context(390,844,{reducedMotion:'reduce'});await ready(zoom.page);await click(zoom.page,'tutorial-skip');await selectLevel(zoom.page,60);await zoom.page.addStyleTag({content:'button,p,small,h1,h2,h3,.small,.eyebrow,.status,.board-caption{font-size:200%!important}'});await fit(zoom.page,'200% text, reduced motion',true);await click(zoom.page,'manual');await fit(zoom.page,'200% tutorial');await zoom.page.screenshot({path:resolve(screens,'text-200-390.png'),fullPage:true});await zoom.c.close();
 // A hanging optional host is bounded and never indefinitely blocks play.
 const hanging=await context(390,844);await hanging.c.addInitScript(()=>{window.PorcelainHost={complete:()=>new Promise(()=>{})};});await ready(hanging.page);await click(hanging.page,'tutorial-skip');await click(hanging.page,'continue');for(let i=0;i<LEVELS[0].solution.length;i++)await directCell(hanging.page,i,LEVELS[0].solution[i]);await hanging.page.locator('.win-banner').waitFor();await click(hanging.page,'undo');assert.equal((await stored(hanging.page)).current.cursor,15);assert.equal((await stored(hanging.page)).outbox.length,1);await hanging.c.close();results.push({label:'hanging optional host bounded',passed:true});
 // Denied storage cannot send rewards; persistence recover reuses original completion ID.
 const denied=await context(390,844);await denied.c.addInitScript(()=>{window.sent=[];window.PorcelainHost={complete:e=>{window.sent.push(e);return true;}};window.allowSave=false;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(!window.allowSave)throw Error('quota');return original.call(this,k,v);};});await ready(denied.page);await click(denied.page,'tutorial-skip');await click(denied.page,'continue');for(let i=0;i<LEVELS[0].solution.length;i++)await directCell(denied.page,i,LEVELS[0].solution[i]);await denied.page.locator('.win-banner').waitFor();assert.equal(await denied.page.evaluate(()=>window.sent.length),0);await denied.page.evaluate(()=>{window.allowSave=true;});await click(denied.page,'retry-save');await denied.page.waitForFunction(()=>window.sent.length===1);assert.equal((await stored(denied.page)).outbox.length,0);await denied.c.close();results.push({label:'denied storage -> retry -> one event',passed:true});
 // Native version adapter is exercised in actual built runtime, with no browser writes.
 const nat=await context(390,844);await nat.c.addInitScript(()=>{window.mockData={};window.mockWrites=0;window.xhs={launchOptions:{miniToolEnv:{buildVersion:9462004}},miniTool:{getStorage:async({key})=>({data:window.mockData[key]||null}),setStorage:async({key,data})=>{window.mockData[key]=data;window.mockWrites++;}}};Storage.prototype.setItem=function(){throw Error('web must not write');};});await ready(nat.page);await click(nat.page,'tutorial-skip');await click(nat.page,'continue');await directCell(nat.page,0,LEVELS[0].solution[0]);assert.ok(await nat.page.evaluate(()=>window.mockWrites>=2));assert.equal(await nat.page.locator('.storage-warning').count(),0);await nat.c.close();results.push({label:'native 9.46 mock built-runtime',passed:true});
 assert.deepEqual(failures,[]);assert.deepEqual(external,[]);console.log('PASS browser: '+results.length+' measured scenarios; zero page errors and external requests; CSP production bundle.');
 writeFileSync(resolve(base,'release/browser-results.json'),JSON.stringify({engine:'Playwright Google Chrome browser simulation; not official container or physical devices',browserVersion:browser.version(),capturedAt:new Date().toISOString(),bundleSha256:createHash('sha256').update(readFileSync(resolve(root,'app.js'))).digest('hex'),results,pageErrors:failures,externalRequests:external},null,2));
}catch(e){writeFileSync(resolve(base,'release/browser-failure.txt'),e.stack);throw e;}finally{await browser.close();await new Promise(done=>server.close(done));}
