(function(){
 const root=document.getElementById('app'),overlay=document.getElementById('overlay');let storage;try{storage=window.localStorage;}catch(e){storage={getItem:()=>null,setItem:()=>{throw Error('unavailable');}};}
 let data=CityStore.load(storage,CityLevels),p=null,state=null,session=null,sessionKey='',selected=0,note=false,chapter=0,focusBefore=null,tutorialPage=0,view='home',notice='';
 const descriptions=['读懂街角的可见楼数','从 1 和最高楼开始推理','每行每列，各有秩序','把两个方向连起来想','用候选补齐缺席视角','让整座城市彼此呼应'];
 function persist(){const ok=CityStore.save(storage,data);if(!ok)notice='存储不可用：本次进度仅保留在当前页面。';return ok;}
 function sync(){CityStore.deliver(storage,data,window.cloudstepCompletionHost);}
 function button(text,action,cls){return '<button data-action="'+action+'"'+(cls?' class="'+cls+'"':'')+'>'+text+'</button>';}
 function shell(body,playing){root.innerHTML='<main class="shell"><header><div class="brand">⌂ 云阶筑城</div><div class="header-actions">'+button(playing?'章节':'天际线',playing?'home':'collection')+button('玩法','tutorial')+'</div></header>'+body+'</main>';}
 function progress(c){return CityLevels.filter(x=>x.chapter===c&&data.records[x.id]).length;}
 function home(){view='home';p=null;shell('<section class="hero"><div class="hero-copy"><div class="eyebrow">A CITY IN THE CLOUDS</div><h1>高低之间<br>自有天地。</h1><p>摆好每一栋楼，从街角望向城市。<br>让四面的风景，都恰好符合线索。</p>'+button('今日街区 →','daily','primary')+'</div><img src="./assets/city.svg" alt="陶土色建筑与晨雾组成的装饰城市"></section><div class="section-title"><h2>六段筑城旅程</h2><span class="muted">'+Object.keys(data.records).length+' / 60 完成</span></div><section class="chapters">'+CityChapters.map((x,i)=>'<button class="chapter" data-action="chapter:'+i+'"><span class="number">CHAPTER 0'+(i+1)+'</span><strong>'+x+'</strong><span class="muted">'+descriptions[i]+'</span><span class="mini-line"><i style="width:'+progress(i)*10+'%"></i></span><span class="muted">'+progress(i)+' / 10</span></button>').join('')+'</section><div class="footer">每天一座街区，按自己的节奏。候选笔记不影响独立完成记录。<br>'+button('规则与来源','source')+'</div>');}
 function chapters(c){view='chapter';chapter=c;p=null;shell('<div class="eyebrow">CHAPTER 0'+(c+1)+'</div><h1>'+CityChapters[c]+'</h1><p class="muted">'+descriptions[c]+' · 点击任意关卡开始</p><div class="level-grid">'+CityLevels.filter(x=>x.chapter===c).map((x,i)=>button(String(i+1).padStart(2,'0')+'<small>'+(data.records[x.id]?(data.records[x.id].hints?'✓ 完成':'✦ 独立完成'):x.n+' × '+x.n)+'</small>','level:'+CityLevels.indexOf(x))).join('')+'</div>'+button('← 六章旅程','home'));}
 function start(i,mode){p=CityLevels[i];chapter=p.chapter;view='play';sessionKey=mode==='daily'?'daily:'+localDate()+':'+p.id:p.id;session=data.sessions[sessionKey];if(!session||session.mode!==mode){session={runId:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10),actions:[],hints:0,mode:mode};data.sessions[sessionKey]=session;}state=City.replay(p,session.actions);selected=p.givens.findIndex(v=>!v);note=false;notice=City.evaluate(p,state).complete?'这座街区已完成，可以重开挑战。':'点选空地，再选择楼高。';persist();play();let read=false;try{read=storage.getItem(CityStore.tutorialKey)==='seen';}catch(e){}if(!read)tutorial(0);}
 function board(){const n=p.n,ev=City.evaluate(p,state);let html='<div class="board" style="--n:'+n+';--cell:52px" aria-label="'+n+'乘'+n+'城市棋盘">';for(let r=-1;r<=n;r++)for(let c=-1;c<=n;c++){
  if(r<0||r===n||c<0||c===n){if((r<0||r===n)&&(c<0||c===n)){html+='<span></span>';continue;}const side=r<0?'top':r===n?'bottom':c<0?'left':'right',idx=r<0||r===n?c:r;html+='<span class="clue '+(ev.edges.includes(side+':'+idx)?'bad':'')+'" aria-label="'+({top:'上',bottom:'下',left:'左',right:'右'}[side])+'侧第'+(idx+1)+'条线索 '+(p.clues[side][idx]||'缺失')+'">'+(p.clues[side][idx]||'·')+'</span>';continue;}
  const i=r*n+c,v=state.values[i],notes=Array.from({length:n},(_,j)=>j+1).filter(v=>state.notes[i]&(1<<v)).join(' ');html+='<button class="cell'+(selected===i?' selected':'')+(p.givens[i]?' fixed':'')+(ev.bad.includes(i)?' bad':'')+'" data-action="cell:'+i+'" aria-label="第'+(r+1)+'行第'+(c+1)+'列，'+(v?'楼高'+v:'空格')+(p.givens[i]?'，固定':'')+'" aria-pressed="'+(selected===i)+'">'+(v?'<span class="building" style="height:'+(v/n*70)+'%"></span><span class="value">'+v+'</span>':'<span class="notes">'+(notes||'·')+'</span>')+'</button>';
 }return html+'</div>';}
 function play(){if(!p)return;const row=Math.floor(selected/p.n),a=City.line(p,state.values,'left',row),complete=a.every(Boolean),ev=City.evaluate(p,state);shell('<div class="play-layout"><section class="play-main"><div class="play-title"><div class="eyebrow">'+(session.mode==='daily'?'DAILY · '+sessionKey.split(':')[1]:'CHAPTER 0'+(chapter+1))+'</div><h1>'+CityChapters[chapter]+' <span class="badge">'+'第 '+p.id.slice(-2)+' 关</span></h1><p class="muted">1–'+p.n+' 行列不重复 · 四边数字是可见楼数</p></div>'+board()+'<div class="numbers">'+Array.from({length:p.n},(_,i)=>button(i+1,'value:'+(i+1))).join('')+'</div><div class="tools">'+button(note?'候选：开':'候选','note',note?'active':'')+button('擦除','erase')+button('撤销','undo')+button('提示','hint')+button('重开','restart')+'</div><div class="status" role="status">'+(notice||(ev.bad.length||ev.edges.length?'虚线格或波浪线提示需要复查。':'每一条视线，都能成为下一步线索。'))+'</div></section><aside class="play-side"><section class="side-card"><h2>第 '+(row+1)+' 排 · 从左望去 →</h2><div class="skyline">'+a.map(v=>'<div style="height:'+(v?20+v/p.n*75:6)+'%">'+(v||'')+'</div>').join('')+'</div><p>'+(complete?'能看见 '+City.visible(a)+' 栋楼；左侧要求 '+(p.clues.left[row]||'未给出')+'。':'高楼会挡住后面的矮楼。填满后比较这排的可见数。')+'</p></section><section class="side-card"><h2>慢慢想，城市会亮起来</h2><p>四边的「·」表示没有线索。带圆点的是固定楼。候选只是笔记，不算落子。</p><p>本局提示 '+session.hints+' 次</p>'+button('重看教程','tutorial')+'</section></aside></div>',true);resize();}
 function resize(){const b=root.querySelector('.board');if(b){const cell=(b.clientWidth-(innerWidth<=400?6:16)- (innerWidth<=400?48:52))/p.n-(innerWidth<=400?2:4);b.style.setProperty('--cell',Math.max(44,Math.min(48,cell))+'px');}}
 function act(a){const next=City.move(p,state,a);if(next===state){notice=p.givens[a.i]?'固定楼不能修改。':'这个操作没有改变棋盘。';play();return;}state=next;session.actions.push(a);notice='';const complete=City.evaluate(p,state).complete;if(complete)CityStore.settle(data,p,session,new Date().toISOString());persist();play();if(complete){sync();win();}}
 function win(){modal('<div class="win-mark">✦</div><h2>这座街区，落成了。</h2><p>每行每列各不重复，四面的风景也都对上了。</p><p class="hint-line">'+(session.hints?'借助 '+session.hints+' 次提示完成':'独立完成 · 无提示解出这座街区')+'<br>本章进度 '+progress(chapter)+' / 10。'+(progress(chapter)===10?'已收藏这一章的城市天际线。':'再点亮一些街区，就能收藏本章天际线。')+'</p><div class="modal-actions">'+button('返回章节','win-back')+button('下一街区 →','next','primary')+'</div>');}
 function modal(html){if(overlay.hidden)focusBefore=document.activeElement;overlay.hidden=false;root.setAttribute('aria-hidden','true');overlay.innerHTML='<section class="modal" role="dialog" aria-modal="true" aria-label="云阶筑城对话框" tabindex="-1">'+html+'</section>';document.body.style.overflow='hidden';overlay.querySelector('.modal').scrollTop=0;overlay.querySelector('button').focus();}
 function close(){overlay.hidden=true;overlay.innerHTML='';root.removeAttribute('aria-hidden');document.body.style.overflow='';if(focusBefore&&document.contains(focusBefore))focusBefore.focus();else {const b=root.querySelector('button');if(b)b.focus();}}
 function tutorial(i){tutorialPage=i;const titles=['看见几栋，就写几','先从最明确的视线开始','让四面的风景一起成立'],texts=['格子里填楼高 1、2、3，每行每列不能重复。四边线索表示从那边能看见几栋楼；高楼会挡住后面的矮楼。','这张固定教程题左侧第一排为 1，所以最前面必须是最高楼 3。点第一格，再按 3，完成一次合法落子。','同一题完成后，第一排是 3、1、2，从左只见 1 栋，从右见 2 栋。所有行列不重复，全部线索同时满足，才算落成。'];modal('<div class="close-row"><span class="eyebrow">筑城手册 '+(i+1)+' / 3</span>'+button('跳过','tutorial-close')+'</div><h2>'+titles[i]+'</h2><img src="./assets/tutorial-'+i+'.svg" alt="'+texts[i]+'"><p>'+texts[i]+'</p><div class="modal-actions">'+(i?button('上一张','tutorial-prev'):'<span></span>')+button(i===2?'开始筑城':'下一张 →',i===2?'tutorial-close':'tutorial-next','primary')+'</div>');}
 function hint(){const solutions=City.solve(p,state.values,2).solutions;if(!solutions.length){modal('<h2>先检查已有楼高</h2><p>当前填写不能组成满足全部线索的城市。可以撤销最近一步，或擦除你不确定的楼高。</p><div class="modal-actions">'+button('回去检查','close','primary')+'</div>');return;}let i=selected;if(p.givens[i]||state.values[i])i=state.values.findIndex(v=>!v);if(i<0)return;let v=solutions[0][i];const candidates=[];for(let k=1;k<=p.n;k++){const b=state.values.slice();b[i]=k;if(City.solve(p,b,1).solutions.length)candidates.push(k);}if(candidates.length!==1)return;const r=Math.floor(i/p.n),c=i%p.n;modal('<h2>给一块空地找依据</h2><p class="hint-line">第 '+(r+1)+' 行第 '+(c+1)+' 列：把 1–'+p.n+' 分别代入，结合行列不重复及四边视线，只有 '+v+' 还能完成整盘。</p><p>这是全盘排除提示。确认落子会记录一次提示，候选笔记不会影响评级。</p><div class="modal-actions">'+button('自己再想想','close')+button('确认填入 '+v,'hint-fill:'+i+':'+v,'primary')+'</div>');}
 function collection(c){chapter=(c+6)%6;view='collection';p=null;const won=progress(chapter)===10;shell('<div class="eyebrow">CITY COLLECTION · 0'+(chapter+1)+' / 06</div><h1>'+CityChapters[chapter]+'</h1><img class="collection-art '+(won?'':'locked')+'" src="./assets/city-'+chapter+'.svg" alt="'+CityChapters[chapter]+'城市天际线'+(won?'已收藏':'未解锁')+'"><p>'+(won?'这座天际线，记录了你走过的十个街区。':'完成本章 10 个街区后收藏这座天际线。')+'</p><p class="muted">'+progress(chapter)+' / 10 完成 · '+(won?'已收藏':'待点亮')+'</p><div class="pager">'+button('← 上一座','collect-prev')+button('去本章筑城','chapter:'+chapter,'primary')+button('下一座 →','collect-next')+'</div>'+button('返回旅程','home'));}
 function localDate(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
 function dispatch(action){const parts=action.split(':'),a=parts[0];if(a==='close'){close();return;}if(a==='home'){close();home();}else if(a==='chapter'){close();chapters(+parts[1]);}else if(a==='level')start(+parts[1],'chapter');else if(a==='daily')start(City.daily(localDate(),CityLevels.length),'daily');else if(a==='tutorial')tutorial(0);else if(a==='tutorial-next')tutorial(tutorialPage+1);else if(a==='tutorial-prev')tutorial(tutorialPage-1);else if(a==='tutorial-close'){try{storage.setItem(CityStore.tutorialKey,'seen');}catch(e){}close();}else if(a==='collection')collection(0);else if(a==='collect-next')collection(chapter+1);else if(a==='collect-prev')collection(chapter-1);else if(a==='source')modal('<h2>规则与来源</h2><p>玩法为 Towers / Skyscrapers：在 N×N 格内填 1–N，每行每列不重复，从各侧看见的楼数须符合线索。没有线索的方向不作约束。</p><p>规则来源：Simon Tatham’s Portable Puzzle Collection。参考本仓库 neon-skyline 的 MIT 实现，固定提交 55cdddb。云阶筑城主题、交互与素材由本项目制作，使用 AI 辅助开发。</p><p>60 个已验证唯一解的主线题；每日街区从同一题库按本地日期选取。使用提示与独立完成分别记录。</p>'+button('知道了','close','primary'));
 else if(p){if(a==='cell'){selected=+parts[1];notice='';play();const b=root.querySelector('[data-action="cell:'+selected+'"]');if(b)b.focus();}else if(a==='value')act({type:note?'note':'set',i:selected,v:+parts[1]});else if(a==='erase')act({type:'set',i:selected,v:0});else if(a==='note'){note=!note;play();}else if(a==='undo'){session.actions.pop();state=City.replay(p,session.actions);notice='已撤销。';persist();play();}else if(a==='hint')hint();else if(a==='hint-fill'){session.hints++;close();act({type:'set',i:+parts[1],v:+parts[2]});}else if(a==='restart')modal('<h2>重新规划这座街区？</h2><p>清空本局填写和候选，已获得的收藏与记录保留。</p><div class="modal-actions">'+button('继续思考','close')+button('确认重开','restart-confirm','primary')+'</div>');else if(a==='restart-confirm'){const i=CityLevels.indexOf(p),mode=session.mode;delete data.sessions[sessionKey];close();start(i,mode);}else if(a==='win-back'){close();chapters(chapter);}else if(a==='next'){const i=CityLevels.indexOf(p);close();if(i===59)home();else start(i+1,'chapter');}}
 }
 document.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(b)dispatch(b.getAttribute('data-action'));});
 document.addEventListener('keydown',e=>{if(!overlay.hidden){if(e.key==='Escape'){e.preventDefault();if(overlay.querySelector('[data-action="tutorial-close"]'))dispatch('tutorial-close');else close();}if(e.key==='Tab'){const all=overlay.querySelectorAll('button'),first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(!p)return;if(/^[1-5]$/.test(e.key)){e.preventDefault();act({type:note?'note':'set',i:selected,v:+e.key});}else if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();act({type:'set',i:selected,v:0});}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-p.n,ArrowDown:p.n}[e.key];selected=(selected+delta+p.n*p.n)%(p.n*p.n);play();root.querySelector('[data-action="cell:'+selected+'"]').focus();}});
 window.addEventListener('resize',resize);CityStore.recover(data,CityLevels,new Date().toISOString());persist();sync();home();
})();
