(function(){
 'use strict';var E=LoomEngine,S=LoomStorage,V=LoomView,levels=LoomLevels,store;try{store=window.localStorage;}catch(e){store={getItem:function(){return null;},setItem:function(){throw Error('unavailable');}};}
 var data=S.load(store,levels),main=document.getElementById('main'),modal=document.getElementById('modal'),body=document.getElementById('modal-body'),actions=document.getElementById('modal-actions'),focusBefore=null,onDismiss=null,p=null,s=null,cells=null,selected=-1,notes={},noteMode=false,saved=true;
 var names=['第一针','留一针','一半月色','经纬相遇','疏星留白','长卷成章'];var desc=['从三连限制落下第一针','在两端与夹心中寻找空位','让每一行列昼夜各半','让横纵线索彼此照应','留白渐多，推理慢慢展开','把已学的线索织成一卷'];var motifs=['初日','月隙','半照','交星','星野','长明'];
 function el(id){return document.getElementById(id);}function button(label,fn,primary){var b=document.createElement('button');b.textContent=label;if(primary)b.className='primary';b.addEventListener('click',fn);return b;}
 function persist(){saved=S.save(store,data);return saved;}
 function notify(){S.flush(data,store,typeof window.onDaynightComplete==='function'?window.onDaynightComplete:null);}
 function dateKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
 function count(ch){return levels.filter(function(l){return (!ch||l.chapter===ch)&&data.completed[l.id];}).length;}
 function close(){if(onDismiss){var callback=onDismiss;onDismiss=null;callback();}modal.hidden=true;document.body.style.overflow='';if(focusBefore&&document.contains(focusBefore))focusBefore.focus();}
 function dialog(html,buttons){onDismiss=null;if(modal.hidden)focusBefore=document.activeElement;body.innerHTML=html;actions.innerHTML='';buttons.forEach(function(b){actions.appendChild(button(b[0],b[1],b[2]));});modal.hidden=false;document.body.style.overflow='hidden';modal.querySelector('section').scrollTop=0;modal.querySelector('section').focus();}
 modal.addEventListener('keydown',function(e){if(e.key==='Escape'){e.preventDefault();close();return;}if(e.key==='Tab'){var items=modal.querySelectorAll('button:not(:disabled)'),first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===modal.querySelector('section'))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===modal.querySelector('section'))){e.preventDefault();first.focus();}}});
 function home(){close();p=null;s=null;main.innerHTML='<section class="hero"><div class="hero-copy"><div class="eyebrow">DAY & NIGHT · A WOVEN PUZZLE</div><h1>把昼夜，<br>织成一卷。</h1><p>太阳与月亮，各占一半。<br>循着线索，落下确定的一针。</p><div class="stat"><strong>'+count()+' / 72</strong><span>织片已完成</span></div></div><img class="hero-art" src="./assets/scroll.svg" alt="日月星纹刺绣长卷装饰"></section><section class="daily"><div><strong>今日织片 <span aria-hidden="true">✧</span></strong><p>'+dateKey()+' · 每天一题，不赶时间</p></div><button id="daily" class="primary">'+(data.completed['daily:'+dateKey()]?'再织一次':'织一片')+'</button></section><nav class="chapter-tabs" aria-label="章节"></nav><div id="chapter-content"></div>';
 for(var ch=1;ch<=6;ch++)(function(c){var b=button(String(c).padStart(2,'0')+' '+names[c-1],function(){data.chapter=c;persist();renderChapter();});b.dataset.chapter=c;main.querySelector('.chapter-tabs').appendChild(b);})(ch);
 el('daily').addEventListener('click',function(){start(levels[E.daily(dateKey(),levels.length)],'daily');});renderChapter();}
 function renderChapter(){var ch=data.chapter;main.querySelectorAll('[data-chapter]').forEach(function(b){b.classList.toggle('active',Number(b.dataset.chapter)===ch);b.setAttribute('aria-current',Number(b.dataset.chapter)===ch?'page':'false');});el('chapter-content').innerHTML='<div class="chapter-head"><div><h2>'+names[ch-1]+'</h2><p class="muted">'+desc[ch-1]+'</p></div><span class="muted">'+count(ch)+' / 12</span></div><div class="levels"></div><button id="collection" class="collection-button">✧ 展开织卷图鉴 · '+motifs[ch-1]+'</button>';
 levels.filter(function(l){return l.chapter===ch;}).forEach(function(l){var b=button('',function(){start(l,'chapter');});b.className='level'+(data.completed[l.id]?' done':'');b.dataset.level=l.id;b.setAttribute('aria-label',names[ch-1]+' 第'+l.level+'关'+(data.completed[l.id]?' 已完成':''));b.innerHTML='<strong>'+String(l.level).padStart(2,'0')+'</strong><small>'+l.n+' × '+l.n+' · '+(data.completed[l.id]?'已织成':data.sessions[l.id]?'续织':'待织')+'</small>';main.querySelector('.levels').appendChild(b);});el('collection').addEventListener('click',function(){collection(ch);});}
 function collection(ch){var done=count(ch);dialog('<div class="eyebrow">织卷图鉴 · '+ch+' / 6</div><h2 id="modal-title">'+motifs[ch-1]+'</h2><img class="collection-art" src="./assets/motif-'+ch+'.svg" alt="'+motifs[ch-1]+'刺绣纹样"><div class="collection-progress"><span style="width:'+done/12*100+'%"></span></div><p>'+done+' / 12 片已织成。'+(done===12?'这一段长卷已完整展开。':'每完成一片，便让这段长卷更近一步。')+'</p>',[['上一段',function(){collection(ch===1?6:ch-1);}],['收起',close],['下一段',function(){collection(ch===6?1:ch+1);}]]);}
 function tutorial(page){var titles=['看懂这一片昼夜','落下确定的一针','让经纬都均衡'];var texts=['太阳是昼，月牙是夜。小圆点标记固定格。每行每列昼夜各半，横竖都不能连续三个相同。','图中金框是同一题的一次真实填入：'+LoomTutorial.hint.text+'选中空格，再按昼或夜。','这是同一题的真实完成状态：每行、每列各两昼两夜，没有三连，也没有空格。无需让各行各列互不相同。'];function finish(){close();}
 dialog('<div class="eyebrow">织卷指南 · '+(page+1)+' / 3</div><h2 id="modal-title">'+titles[page]+'</h2><img src="./assets/tutorial-'+page+'.svg" alt="固定教程关'+['初始题面','一次合法操作后的题面','通过规则验证的完成题面'][page]+'"><p>'+texts[page]+'</p>',[['跳过',finish],[page===2?'开始织卷':'下一张',page===2?finish:function(){tutorial(page+1);},true]]);onDismiss=function(){try{store.setItem(S.TUTORIAL,'seen');}catch(e){}};}
 function start(level,mode){close();p=level;var day=mode==='daily'?dateKey():'',key=mode==='daily'?'daily:'+day:p.id;s=data.sessions[key]||S.session(p,mode,day);if(s.levelId!==p.id)s=S.session(p,mode,day);data.sessions[key]=s;cells=E.replay(p,s.events);selected=cells.findIndex(function(v,i){return p.givens[i]===-1;});notes={};noteMode=false;persist();play();var seen=false;try{seen=store.getItem(S.TUTORIAL)==='seen';}catch(e){}if(!seen)tutorial(0);}
 function play(){main.innerHTML='<div class="play-heading"><div><div class="eyebrow">'+(s.mode==='daily'?'今日织片 · '+s.date:'第 '+p.chapter+' 章 · '+String(p.level).padStart(2,'0')+' / 12')+'</div><h1>'+names[p.chapter-1]+'</h1></div><button id="back" class="quiet">返回章节</button></div><div class="play-layout"><div class="loom"><div class="rod"></div><div class="fabric"><div id="board" class="board n'+p.n+'" aria-label="昼夜棋盘"></div><p id="selection" class="sel-caption"></p></div><div class="rod"></div></div><aside class="play-side"><p class="rule-strip">一行一列，昼夜各半。<br>横竖相连，不可同三。</p><div class="input-bar"><button id="day" class="primary">☀ 昼</button><button id="night">☾ 夜</button><button id="erase" class="quiet">擦除</button></div><div class="tools"><button id="undo" class="quiet">撤销</button><button id="hint" class="quiet">找线索</button><button id="restart" class="quiet">重开</button><button id="settings" class="quiet">设置</button></div><div class="mode-row"><button id="notes" class="quiet" aria-pressed="false">候选笔记：关</button><button id="cycle" class="quiet">轻点循环：'+(data.cycle?'开':'关')+'</button></div><p id="status" class="status" role="status" aria-live="polite"></p><p id="save-status" class="storage-warning"></p></aside></div>';
 cells.forEach(function(v,i){var b=button('',function(){select(i);if(data.cycle&&p.givens[i]===-1)apply(cells[i]===-1?1:cells[i]===1?0:-1);});b.className='tile';b.dataset.cell=i;b.addEventListener('keydown',function(e){var delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-p.n,ArrowDown:p.n}[e.key];if(delta!==undefined){e.preventDefault();var j=(i+delta+cells.length)%cells.length;select(j);main.querySelector('[data-cell="'+j+'"]').focus();}});el('board').appendChild(b);});
 el('back').addEventListener('click',home);el('day').addEventListener('click',function(){apply(1);});el('night').addEventListener('click',function(){apply(0);});el('erase').addEventListener('click',function(){apply(-1);});el('undo').addEventListener('click',function(){if(!s.events.length)return;s.events.pop();cells=E.replay(p,s.events);persist();render();});el('restart').addEventListener('click',function(){dialog('<h2 id="modal-title">重新织这一片？</h2><p>清空本局填入和候选笔记，已经获得的织片会保留。</p>',[['继续当前局',close],['重新开始',function(){var key=s.mode==='daily'?'daily:'+s.date:p.id;s=S.session(p,s.mode,s.date);data.sessions[key]=s;cells=E.fresh(p);notes={};noteMode=false;close();persist();play();},true]]);});
 el('settings').addEventListener('click',function(){dialog('<h2 id="modal-title">织卷方式</h2><p>候选笔记只标记可能的昼夜，不改变答案。轻点循环开启后，点击可编辑格会按昼、夜、空格轮换。</p>',[['笔记：'+(noteMode?'开':'关'),function(){noteMode=!noteMode;close();render();}],['循环：'+(data.cycle?'开':'关'),function(){data.cycle=!data.cycle;persist();close();render();}],['完成',close]]);});el('notes').addEventListener('click',function(){noteMode=!noteMode;render();});el('cycle').addEventListener('click',function(){data.cycle=!data.cycle;persist();render();});el('hint').addEventListener('click',hint);render();if(E.analyze(cells,p.n).complete){S.settle(data,s,p,store);notify();}}
 function select(i){selected=i;render();}
 function apply(v){if(p.givens[selected]!==-1){el('status').textContent='这是一根固定经线，不能改动。';return;}if(E.analyze(cells,p.n).complete)return;
 if(noteMode){if(cells[selected]!==-1){el('status').textContent='候选笔记只写在空格中，不参与判胜。';return;}var a=notes[selected]||[];if(v===-1)a=[];else if(a.indexOf(v)>=0)a=a.filter(function(x){return x!==v;});else a.push(v);notes[selected]=a;render();return;}
 var next=E.move(p,cells,selected,v);if(!next)return;cells=next;s.events.push([selected,v]);delete notes[selected];persist();render();if(E.analyze(cells,p.n).complete)win();}
 function render(){if(!p)return;var result=E.analyze(cells,p.n);main.querySelectorAll('[data-cell]').forEach(function(b){var i=Number(b.dataset.cell),v=cells[i];b.className='tile '+(v===1?'day':v===0?'night':'empty')+(p.givens[i]!==-1?' fixed':'')+(i===selected?' selected':'')+(result.bad.indexOf(i)>=0?' conflict':'');b.innerHTML=v===-1&&notes[i]&&notes[i].length?'<span class="note">'+notes[i].map(V.symbol).join('')+'</span>':V.symbol(v);b.setAttribute('aria-label','第'+(Math.floor(i/p.n)+1)+'行第'+(i%p.n+1)+'列 '+(v===1?'昼':v===0?'夜':'空格')+(p.givens[i]!==-1?' 固定':'')+(result.bad.indexOf(i)>=0?' 冲突':''));b.setAttribute('aria-pressed',i===selected?'true':'false');});el('selection').textContent='第'+(Math.floor(selected/p.n)+1)+'行 · 第'+(selected%p.n+1)+'列'+(p.givens[selected]!==-1?' · 固定经线':noteMode?' · 候选笔记':' · 选好后织入昼或夜');el('status').textContent=result.complete?'这一片已经织好，可返回章节继续。':result.valid?'已织 '+cells.filter(function(v){return v!==-1;}).length+' / '+cells.length+' 格 · '+(noteMode?'笔记不计入答案':'不必赶时间，先找确定的一针'):result.reasons[0];el('undo').disabled=s.events.length===0;el('notes').textContent='候选笔记：'+(noteMode?'开':'关');el('notes').setAttribute('aria-pressed',noteMode?'true':'false');el('cycle').textContent='轻点循环：'+(data.cycle?'开':'关');el('cycle').setAttribute('aria-pressed',data.cycle?'true':'false');el('save-status').textContent=saved?'':'本地存储不可用，本次可继续游玩；关闭页面后可能丢失进度。';['day','night','erase'].forEach(function(id){el(id).disabled=result.complete;});}
 function hint(){var h=E.hint(cells,p.n);if(h.i===undefined){dialog('<h2 id="modal-title">先理一理线头</h2><p>'+h.text+'</p>',[['回到织卷',close,true]]);return;}select(h.i);dialog('<div class="eyebrow">第'+(Math.floor(h.i/p.n)+1)+'行 · 第'+(h.i%p.n+1)+'列</div><h2 id="modal-title">这一针的依据</h2><p>'+h.text+'</p><p class="muted">先理解线索，再选择是否填入。使用提示会如实记入本局。</p>',[['自己来',close],['确认填入'+(h.v?'昼':'夜'),function(){close();noteMode=false;s.hints++;apply(h.v);},true]]);}
 function win(){var first=!data.completed[S.claim(s)],result=S.settle(data,s,p,store);saved=result.persisted;notify();render();dialog('<span class="celebrate" aria-hidden="true">✧</span><div class="eyebrow">'+(first?'一片新的昼夜':'再次织好这一片')+'</div><h2 id="modal-title">经纬相遇，昼夜成卷。</h2><div class="win-fabric">'+V.svg(p,cells)+'</div><p>'+s.events.length+' 次填入 · 使用 '+s.hints+' 次提示<br>'+(first?'这片织纹已记入你的长卷。':'这片织纹已收藏，重复完成不重复领奖。')+'</p>'+(saved?'':'<p>存储暂不可用，进度尚未保存。</p>'),[['返回章节',home],['再看织卷',close,true]]);}
 el('home').addEventListener('click',home);el('help').addEventListener('click',function(){tutorial(0);});el('about').addEventListener('click',function(){dialog('<h2 id="modal-title">规则与来源</h2><p>在偶数尺寸棋盘填满昼与夜。每行每列两色各半，横竖无三个连续同色；带小圆点的固定格不可更改。各行各列不要求互不相同。</p><p>提示先展示理由，由你确认落子。候选笔记只作辅助，切换或重开关卡时清空。每关首次完成获得一片织纹；每日织片按本地日期选取固定题库中的题目。</p><p>规则改编自 Simon Tatham’s Portable Puzzle Collection 的 Unruly。规则参考 Ten Realms Arcade（MIT），本游戏主题、界面和题库由 AI 辅助开发。无生成式位图素材。</p><p class="fineprint">版本 1.0.0 · 题库 bank-v1 · 72关<br>来源：chiark.greenend.org.uk/~sgtatham/puzzles/<br>兼容目标 Chrome 61；实体手机与小红书容器尚未实测。</p>',[['回到织卷',close,true]]);});
 document.addEventListener('keydown',function(e){if(!p||!modal.hidden||e.ctrlKey||e.metaKey||e.altKey)return;if(['1','2','Backspace','Delete'].indexOf(e.key)>=0){e.preventDefault();apply(e.key==='1'?1:e.key==='2'?0:-1);}});window.addEventListener('focus',notify);home();notify();
}());
