const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve('dist/xhs'),key='mini-polish:tessera-mural-studio:v1:save',L=require('../levels.js'),P=require('../release/proofs.json').levels;
const server=http.createServer((req,res)=>{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'none'; object-src 'none'; frame-src 'none'");res.setHeader('Content-Type',file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'application/javascript');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const results=[],errors=[],requests=[];
for(const width of [320,359,360,361,390,759,760,761,1280]){const context=await browser.newContext({viewport:{width,height:width===320?720:width>760?720:844},hasTouch:width<761});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(url))requests.push(r.url());});await page.goto(url);await page.waitForSelector('[data-action="tutorial-next"]');assert(await page.locator('#modal img').evaluate(el=>el.complete&&el.naturalWidth>0));await page.locator('[data-action="close"]').click();await page.screenshot({path:`release/home-${width}.png`});await page.locator('[data-action="levels"]').click();await page.locator('[data-action="level:tessera-60"]').click();const metrics=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,minTile:Math.min(...Array.from(document.querySelectorAll('[data-cell]')).map(e=>e.getBoundingClientRect().width))}));assert(metrics.scroll<=metrics.client,'horizontal overflow at '+width);assert(metrics.minTile>=46,'tile too small at '+width);await page.locator('[data-action="mode"]').click();const before=await page.evaluate(k=>localStorage.getItem(k),key);await page.locator('[data-cell="0"]').click();assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),before);await page.screenshot({path:`release/work-${width}.png`,fullPage:true});results.push({width,metrics});await context.close();}
const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.locator('[data-action="close"]').click();await page.locator('[data-action="continue"]').click();await page.locator('[data-cell="0"]').tap();assert.equal(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key)).current.history.length,1);await page.locator('[data-action="undo"]').click();await page.locator('[data-action="redo"]').click();assert.equal(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key)).current.history.length,1);await page.reload();await page.locator('[data-action="continue"]').click();assert.equal(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key)).current.history.length,1);
await page.locator('[data-action="restart"]').click();await page.locator('[data-action="confirm-restart"]').click();for(let i=0;i<P[0].solution.length;i++){await page.locator('[data-action="tool:'+(P[0].solution[i]?'black':'white')+'"]').click();await page.locator('[data-cell="'+i+'"]').tap();}await page.waitForSelector('.success');await page.screenshot({path:'release/complete-390.png',fullPage:true});assert.equal(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key)).completed.length,1);await page.reload();await page.locator('[data-action="continue"]').click();assert.equal(await page.locator('.success').count(),1);await page.locator('[data-action="undo"]').click();await page.locator('[data-action="redo"]').click();assert.equal(JSON.parse(await page.evaluate(k=>localStorage.getItem(k),key)).completed.length,1);await page.locator('[data-action="gallery"]').click();await page.locator('[data-action="colour"]').click();await page.screenshot({path:'release/gallery-390.png',fullPage:true});await page.locator('[data-action="tutorial"]').click();await page.locator('[data-action="tutorial-next"]').click();await page.screenshot({path:'release/tutorial-390.png'});await page.keyboard.press('Escape');
// Use the real explanation path for a full overlap lesson, no answer injection.
await page.locator('[data-action="home"]').click();await page.locator('[data-action="levels"]').click();await page.locator('[data-action="level:tessera-22"]').click();for(let n=0;n<25;n++){if(n===8){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'release/gameplay-390.png'});}await page.locator('[data-action="hint"]').click();await page.locator('[data-action="hint"]').click();if(await page.locator('.clue-name').count()){assert.equal(await page.locator('.clue-name').count(),2);assert(await page.locator('[data-hint-region="common"]').count()>0);assert(await page.locator('[data-hint-region="difference"]').count()>0);await page.screenshot({path:'release/overlap-explanation-390.png',fullPage:true});}await page.locator('[data-action="hint-apply"]').click();}await page.waitForSelector('.success');
// Safe-area and doubled text checks.
await page.locator('[data-action="levels"]').click();await page.locator('[data-action="level:tessera-60"]').click();await page.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');document.querySelectorAll('p,button,strong').forEach(e=>{if(!e.classList.contains('tile'))e.style.fontSize='200%';});});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));await page.screenshot({path:'release/large-text-390.png',fullPage:true});await page.emulateMedia({reducedMotion:'reduce'});await context.close();
assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);fs.writeFileSync('release/browser-results.json',JSON.stringify({results,errors,externalRequests:requests,interaction:'touch, undo/redo, restart, reload restore, victory, reward dedupe, gallery, tutorial escape, 25 real overlap hints, safe-area, doubled-text'},null,2));await browser.close();server.close();console.log('Browser production checks passed');})().catch(e=>{console.error(e);server.close();process.exit(1);});
