const fs=require('fs'),path=require('path'),{execFileSync}=require('child_process'),T=require('../engine.js'),L=require('../levels.js');
const proofs=JSON.parse(fs.readFileSync('release/proofs.json'));
const l=L[0],solution=proofs.levels[0].solution.map(v=>v?1:2),initial=Array(16).fill(0),index=solution.findIndex(v=>v===1),action=T.move(l,initial,index,'black');
function svg(board,state,move){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 290" data-level-id="${l.id}" data-state="${state}" data-board="${board.join(',')}" ${move?`data-action-index="${index}" data-action-tool="black"`:''}><rect width="360" height="290" fill="#e8e5d7"/><text x="24" y="28" font-family="sans-serif" font-size="14" fill="#20333e">${state==='initial'?'同一题 · 所有格未定':state==='action'?'真实一步 · 彩片参与自身九宫':'合法完成 · 16 格全部明确'}</text>${board.map((v,i)=>{const x=68+i%4*56,y=44+Math.floor(i/4)*56;return `<g data-index="${i}" data-value="${v}"><rect x="${x}" y="${y}" width="52" height="52" rx="4" fill="${['#9da8a5','#274b85','#faf8ef'][v]}"/>${v===0?`<path d="M${x+2} ${y+36}l34 -34M${x+10} ${y+50}l40 -40" stroke="#bec9c2"/>`:''}${l.clues[i]===null?'':`<circle cx="${x+26}" cy="${y+24}" r="13" fill="#faf8ef"/><text x="${x+26}" y="${y+30}" text-anchor="middle" font-family="sans-serif" font-size="18" fill="#20333e">${l.clues[i]}</text>`}<text x="${x+44}" y="${y+48}" font-size="11" text-anchor="end" fill="${v===1?'#faf8ef':'#20333e'}">${['·','◆','—'][v]}</text></g>`;}).join('')}</svg>`;}
fs.mkdirSync('assets',{recursive:true});fs.writeFileSync('assets/tutorial-1.svg',svg(initial,'initial'));fs.writeFileSync('assets/tutorial-2.svg',svg(action,'action',true));fs.writeFileSync('assets/tutorial-3.svg',svg(solution,'complete'));
fs.writeFileSync('release/tutorial-metadata.json',JSON.stringify({levelId:l.id,initial,action:{index,tool:'black',board:action},complete:solution},null,2));
const out='dist/xhs';fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});for(const file of ['index.html','styles.css','engine.js','levels.js','session.js','app.js'])fs.copyFileSync(file,path.join(out,file));fs.cpSync('assets',path.join(out,'assets'),{recursive:true});

// License remains in a supported HTML file via inert text content.
const html=fs.readFileSync(path.join(out,'index.html'),'utf8');const license=fs.readFileSync('LICENSE','utf8').replace(/&/g,'&amp;').replace(/</g,'&lt;');fs.writeFileSync(path.join(out,'index.html'),html.replace('</body>',`<template id="license">${license}\nMosaic: Didi Kohen; colour design: Michal Shomer. Rules researched from Simon Tatham and contributors, MIT. Independent implementation and original visuals.</template></body>`));
const zip=path.resolve('dist/tessera-mural-studio-xhs.zip');if(fs.existsSync(zip))fs.unlinkSync(zip);const entries=[];function collect(dir){for(const name of fs.readdirSync(dir).sort()){const file=path.join(dir,name);if(fs.statSync(file).isDirectory())collect(file);else{fs.utimesSync(file,new Date('1980-01-01T00:00:00Z'),new Date('1980-01-01T00:00:00Z'));entries.push(path.relative(out,file));}}}collect(out);execFileSync('zip',['-Xq',zip].concat(entries),{cwd:out,env:Object.assign({},process.env,{TZ:'UTC'})});console.log('Built '+zip);
