const fs=require('fs'),crypto=require('crypto'),T=require('../engine.js'),{solve}=require('./oracle.cjs');
let seed=20261002;function random(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
const chapters=['第一枚彩砾','边框里的数字','重叠的窗','断纹接续','长幅织画','壁画开馆'],motifs=['贝壳边饰','小鱼与浪纹','花叶碎片','几何门楣','竖幅花瓶','庭院拼幅'],levels=[],proofs=[],signatures=new Set();
function trace(l,subset){let b=Array(l.width*l.height).fill(0),steps=[];for(let n=0;n<b.length;n++){const d=T.deduction(l,b,subset);if(!d||d.conflict)break;b[d.index]=d.value;steps.push(d);}return {steps,complete:T.evaluate(l,b).complete};}
for(let ch=0;ch<6;ch++)for(let k=0;k<10;k++){let accepted=false;for(let attempt=0;attempt<10000&&!accepted;attempt++){
const width=ch===0?4:ch===1?(k<4?4:5):ch===2?(k<4?5:6):6,height=ch===0?4:ch<3?5:ch===3?6:ch===4?(k<4?7:8):(k<3?6:8);
const binary=Array.from({length:width*height},(_,i)=>{const y=Math.floor(i/width),x=i%width;const body=ch===0?(x===y||x+y===width-1):ch===1?(y===2||((x===1||x===width-2)&&y===1)):ch===2?((x+y)%3===0):ch===3?(x===0||x===width-1||y%3===1):ch===4?((y<2&&x===2)||(y>=2&&x>0&&x<width-1&&y<height-1)):(y===height-2||x===2||(y===1&&x>2));return random()<.23?Number(!body):Number(body);});
const variants=[];for(let ry=0;ry<2;ry++)for(let rx=0;rx<2;rx++){const a=[];for(let y=0;y<height;y++)for(let x=0;x<width;x++)a.push(binary[(ry?height-1-y:y)*width+(rx?width-1-x:x)]);variants.push(a.join(''));if(width===height){const t=[];for(let y=0;y<height;y++)for(let x=0;x<width;x++)t.push(a[x*width+y]);variants.push(t.join(''));}}const sig=width+'x'+height+':'+variants.sort()[0];if(signatures.has(sig))continue;
const l={id:`tessera-${String(levels.length+1).padStart(2,'0')}`,chapter:ch+1,width,height,title:motifs[ch]+' · '+String(k+1).padStart(2,'0'),clues:[],version:1};l.clues=binary.map((_,i)=>T.neighbours(l,i).reduce((s,j)=>s+binary[j],0));const full=solve(l);if(full.solutions.length!==1||!full.exhaustive)continue;
if(ch<2&&!trace(l,false).complete)continue;
const order=Array.from({length:binary.length},(_,i)=>i);for(let i=order.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}
for(const i of order){const old=l.clues[i];l.clues[i]=null;const r=solve(l);if(r.solutions.length!==1||!r.exhaustive||!trace(l,ch>=2).complete)l.clues[i]=old;}
const tr=trace(l,true),direct=trace(l,false);if(!tr.complete)continue;if(ch>=2&&direct.complete)continue;if(ch===0&&k<4&&!direct.complete)continue;if(ch===0&&!l.clues.some((c,i)=>c===0||c===T.neighbours(l,i).length))continue;
const proof=solve(l),hash=crypto.createHash('sha256').update(JSON.stringify(l.clues)).digest('hex');l.lesson=ch<2?'九宫含自身 · 彩片算数，底片不算':ch===2?'重叠窗相减 · 公共区抵消':ch===3?'无数字格也需明确':'多层重叠 · 完成每一片';levels.push(l);proofs.push({id:l.id,clueHash:hash,solution:proof.solutions[0],nodes:proof.nodes,exhaustive:proof.exhaustive,solutionCount:1,directComplete:direct.complete,subsetSteps:tr.steps.filter(s=>s.kind==='subset').length,trace:tr.steps,signature:sig});signatures.add(sig);accepted=true;}
if(!accepted)throw Error('Cannot construct '+ch+' '+k);console.log(levels.length,proofs[proofs.length-1].subsetSteps);}
// Order teaching samples by board size and measured overlap effort; retain stable pairing.
for(let ch=0;ch<6;ch++){const paired=levels.slice(ch*10,ch*10+10).map((l,i)=>({l,p:proofs[ch*10+i]}));paired.sort((a,b)=>a.l.width*a.l.height-b.l.width*b.l.height||a.p.subsetSteps-b.p.subsetSteps||b.l.clues.filter(v=>v!==null).length-a.l.clues.filter(v=>v!==null).length);paired.forEach((v,k)=>{const id='tessera-'+String(ch*10+k+1).padStart(2,'0');v.l.id=id;v.p.id=id;v.l.title=motifs[ch]+' · '+String(k+1).padStart(2,'0');levels[ch*10+k]=v.l;proofs[ch*10+k]=v.p;});}
fs.writeFileSync('levels.js','const LEVELS = '+JSON.stringify(levels)+';\nif(typeof module !== "undefined") module.exports=LEVELS;\n');fs.writeFileSync('release/proofs.json',JSON.stringify({generatorVersion:1,seed:20261002,chapters,levels:proofs},null,2));
