const assert=require('assert/strict'),fs=require('fs'),vm=require('vm'),T=require('../engine.js'),L=require('../levels.js'),{solve,constraints}=require('./oracle.cjs');global.Tessera=T;const S=require('../session.js');const proofs=require('../release/proofs.json').levels;let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
check('bounded 3x3 includes center and supports corner/edge',()=>{const l={width:3,height:3,clues:Array(9).fill(null)};assert.deepEqual(T.neighbours(l,0),[0,1,3,4]);assert.equal(T.neighbours(l,1).length,6);assert.equal(T.neighbours(l,4).length,9);});
check('all 512 binary boards: production evaluates independent equations',()=>{for(let mask=0;mask<512;mask++){const l={width:3,height:3,clues:[0,null,2,null,4,null,1,null,3]},b=Array.from({length:9},(_,i)=>mask>>i&1?1:2);const good=constraints(l).every(c=>c.vars.reduce((n,i)=>n+(b[i]===1?1:0),0)===c.target);assert.equal(T.evaluate(l,b).complete,good);}});
check('oracle compared to exhaustive enumeration on 3x3',()=>{for(const clues of [[null,null,null,null,4,null,null,null,null],[0,null,null,null,null,null,null,null,null],[1,2,1,2,4,2,1,2,1]]){const l={width:3,height:3,clues};const brute=[];for(let mask=0;mask<512;mask++){const b=Array.from({length:9},(_,i)=>mask>>i&1);if(constraints(l).every(c=>c.vars.reduce((n,i)=>n+b[i],0)===c.target))brute.push(b.join(''));}const r=solve(l,null,513);assert(r.exhaustive);assert.deepEqual(r.solutions.map(b=>b.join('')).sort(),brute.sort());}});
check('cycles, invalid atomic no-ops, null versus zero, unfinished exact, alternate wins',()=>{const l={width:3,height:3,clues:[0,null,null,null,null,null,null,null,null]},blank=Array(9).fill(0);assert.equal(T.move(l,blank,0,'clear'),null);assert.equal(T.move(l,blank,-1,'black'),null);assert.equal(T.move(l,blank,0,'bogus'),null);let b=T.move(l,blank,8,'black');assert.equal(b[8],1);b=T.move(l,b,8,'black');assert.equal(b[8],2);b=T.move(l,b,8,'black');assert.equal(b[8],0);assert.equal(T.move(l,blank,8,'white')[8],2);assert(!T.evaluate(l,blank).complete);const a=Array(9).fill(2);assert(T.evaluate(l,a).complete);a[8]=1;assert(T.evaluate(l,a).complete);a[0]=1;assert(T.evaluate(l,a).clues[0].impossible);});
check('60 independent unique proofs, legal completions, hint entailment and depth',()=>{assert.equal(L.length,60);assert.equal(new Set(proofs.map(p=>p.signature)).size,60);for(let n=0;n<60;n++){const l=L[n],p=proofs[n],r=solve(l);assert(r.exhaustive);assert.equal(r.solutions.length,1);assert.deepEqual(r.solutions[0],p.solution);const history=p.solution.map((v,index)=>({index,tool:v?'black':'white'})),b=T.replay(l,history);assert(T.evaluate(l,b).complete);assert.equal(T.move(l,b,0,'black'),null);assert(T.replay(l,history.slice(0,-1)));assert.equal(T.replay(l,history.concat({index:0,tool:'black'})),null);if(n<20)assert(p.directComplete);else assert(!p.directComplete);for(const d of p.trace){assert.equal(p.solution[d.index],d.value===1?1:0);}assert(p.trace.length===l.width*l.height);}});
check('overlap explanation names both equations and the exact common/difference cells',()=>{let count=0;for(let n=20;n<L.length;n++){const l=L[n];let board=Array(l.width*l.height).fill(0);for(const step of proofs[n].trace){const d=T.deduction(l,board);assert(d&&!d.conflict);if(d.kind==='subset'){const equations=constraints(l);const a=equations.find(c=>l.clues[d.clue]===c.target&&JSON.stringify(c.vars)===JSON.stringify(T.neighbours(l,d.clue))),b=equations.find(c=>JSON.stringify(c.vars)===JSON.stringify(T.neighbours(l,d.other)));const unknownA=a.vars.filter(i=>board[i]===0),unknownB=b.vars.filter(i=>board[i]===0);assert.deepEqual(d.common,unknownB);assert.deepEqual(d.difference,unknownA.filter(i=>!unknownB.includes(i)));assert.equal(d.remainingA,a.target-a.vars.filter(i=>board[i]===1).length);assert.equal(d.remainingB,b.target-b.vars.filter(i=>board[i]===1).length);assert(d.difference.length);count++;}board[step.index]=step.value;}}assert(count>40);});
check('valid replay restore, forged completion rejected, first reward idempotence',()=>{const l=L[0],run={levelId:l.id,version:1,runId:'run-test-one',hints:0,history:proofs[0].solution.map((v,index)=>({index,tool:v?'black':'white'}))};const data=S.normalize({version:1,current:run,completed:[],tutorial:true},L);assert(S.settle(data,l,run));assert(S.settle(data,l,run));assert.equal(data.completed.length,1);assert(data.completed[0].completionId);assert(data.completed[0].rewardClaimId);assert.equal(S.normalize({version:1,completed:[Object.assign({},run,{history:[]})]},L).completed.length,0);assert.equal(S.normalize({version:1,current:Object.assign({},run,{history:[{index:100,tool:'black'}]})},L).current,null);assert.equal(S.normalize(data,L).completed.length,1);});
check('true tutorial initial -> one tool action -> legal complete',()=>{const meta=require('../release/tutorial-metadata.json'),l=L.find(l=>l.id===meta.levelId);assert(meta.initial.every(v=>v===0));assert.deepEqual(T.move(l,meta.initial,meta.action.index,meta.action.tool),meta.action.board);assert(T.evaluate(l,meta.complete).complete);for(let i=1;i<=3;i++){const text=fs.readFileSync('assets/tutorial-'+i+'.svg','utf8');assert(text.includes('data-level-id="'+l.id+'"'));assert(text.includes('data-board='));}});
check('runtime files parse as classic, no source answer embedded in levels',()=>{for(const f of ['engine.js','session.js','levels.js','app.js'])new vm.Script(fs.readFileSync(f,'utf8'));assert(L.every(l=>!l.solution&&!l.referenceMural));});
console.log(checks+' suites passed');
