import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const ctx={};vm.createContext(ctx);for(const f of ['engine','levels'])vm.runInContext(fs.readFileSync(new URL('../src/'+f+'.js',import.meta.url),'utf8'),ctx);const E=ctx.Astral,L=ctx.ASTRAL_LEVELS,plain=x=>JSON.parse(JSON.stringify(x));
// Independent coordinate oracle: each tile's offset is rotated algebraically.
function oracle(b,m){let out=b.slice(),r=Math.floor(m[0]/3),c=m[0]%3;for(let y=0;y<2;y++)for(let x=0;x<2;x++){let nx=m[1]===1?1-y:y,ny=m[1]===1?x:1-x;out[(r+ny)*4+c+nx]=b[(r+y)*4+c+x];}return out;}
test('all 18 rotations match independent oracle; inverses and four turns',()=>{for(const l of L)for(let z=0;z<9;z++)for(const d of [-1,1]){assert.deepEqual(plain(E.rotate(l.board,[z,d])),plain(oracle(l.board,[z,d])));assert.deepEqual(plain(E.rotate(E.rotate(l.board,[z,d]),[z,-d])),plain(l.board));let b=l.board;for(let n=0;n<4;n++)b=E.rotate(b,[z,d]);assert.deepEqual(plain(b),plain(l.board));}});
test('60 distinct valid puzzles and independent full solutions',()=>{assert.equal(L.length,60);assert.equal(new Set(L.map(l=>l.board.join(','))).size,60);for(let ch=1;ch<=6;ch++)assert.equal(L.filter(l=>l.chapter===ch).length,10);for(const l of L){assert(E.valid(l.board));assert(!E.won(l.board));assert.deepEqual(plain(l.scramble.reduce(oracle,E.goal)),plain(l.board));assert.deepEqual(plain(l.solution.reduce(oracle,l.board)),plain(E.goal));let s=E.session(l,'test-run');for(const m of l.solution)assert(E.apply(l,s,m));assert(E.won(E.board(l,s)));assert(!E.apply(l,s,[0,1]));}});
test('invalid input is atomic; replay boundaries and corrupt sessions',()=>{let l=L[0],s=E.session(l,'test-run');for(const m of [null,{},[],[9,1],[-1,1],[0,0],[0,'1'],[NaN,1],[0,1,2]])assert(!E.apply(l,s,m));assert.equal(s.history.length,0);assert.equal(E.restore(l,{levelId:l.id,history:[[99,1]],runId:'test-run',mode:'campaign'}),null);assert.equal(E.replay(l.board,Array(4097).fill([0,1])),null);assert.equal(E.replay(l.board,l.solution.concat([[0,1]]),true),null);assert(!E.won([1,2,3]));});
test('hints only use matching current state, otherwise explicit undo',()=>{for(const l of L){let s=E.session(l,'hint-run');assert.equal(E.hint(l,s).kind,'reference');E.apply(l,s,[8,1]);let h=E.hint(l,s);if(h.kind==='undo')assert.deepEqual(plain(h.move),[8,-1]);let ref=l.board;for(const m of l.solution){if(h.kind==='reference'&&E.board(l,s).join(',')===ref.join(','))assert.deepEqual(plain(h.move),plain(m));ref=E.rotate(ref,m);}}});
test('completion proofs, reload and same-run/first-reward idempotency',()=>{let l=L[0],s=E.session(l,'test-run'),db=E.empty();l.solution.forEach(m=>E.apply(l,s,m));let e=E.completion(l,s,db);assert.equal(e.rewardClaims.length,1);assert.equal(E.completion(l,s,db),null);let loaded=E.load(JSON.stringify(db),L);assert.equal(E.completion(l,s,loaded),null);let s2=E.session(l,'test-other');l.solution.forEach(m=>E.apply(l,s2,m));assert.equal(E.completion(l,s2,loaded).rewardClaims.length,0);let bad=E.load('{broken',L);assert.equal(Object.keys(bad.proofs).length,0);db.proofs[L[1].id]={complete:true};assert.equal(Object.keys(E.load(JSON.stringify(db),L).proofs).length,1);assert.equal(e.completionId,'astral-turn-gallery-test-run');});
test('tutorial is same real three-move puzzle and reaches exact target',()=>{let l=L[9];assert.equal(l.solution.length,3);let b=E.rotate(l.board,l.solution[0]);assert(!E.won(b));assert(E.won(E.replay(b,l.solution.slice(1))));});
test('classic offline artifact has no prohibited runtime and references exist',()=>{let dir=new URL('../dist/xhs/',import.meta.url),html=fs.readFileSync(new URL('index.html',dir),'utf8'),js=fs.readFileSync(new URL('app.js',dir),'utf8');assert(!/type=["']module|<iframe|<object|\son\w+=|https?:/.test(html));assert(!/\bfetch\s*\(|XMLHttpRequest|WebSocket|new Worker|serviceWorker|eval\s*\(|new Function|\bimport\s|\bexport\s|\?\.|\?\?/.test(js));new vm.Script(js);for(const m of html.matchAll(/(?:src|href)="\.\/([^"]+)"/g))assert(fs.existsSync(new URL(m[1],dir)));});
