import fs from 'node:fs';import crypto from 'node:crypto';import {solve,inspect} from './oracle.mjs';
const VERSION='courtyard-gen-1';let seed=2026100206;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(rand()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function values(w,h,a){const clues=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++){let i=y*w+x;if(a[i])continue;let L=x,R=x,T=y,B=y;while(L&&!a[y*w+L-1])L--;while(R+1<w&&!a[y*w+R+1])R++;while(T&&!a[(T-1)*w+x])T--;while(B+1<h&&!a[(B+1)*w+x])B++;const v=R-L+B-T+1;if(v>=2)clues.push([i,v]);}return clues;}
function canonical(l,a){const w=l.width,h=l.height,forms=[];for(let rot=0;rot<4;rot++)for(let mirror=0;mirror<2;mirror++){let ww=rot%2?h:w,hh=rot%2?w:h;const b=Array(ww*hh).fill(0);a.forEach((v,i)=>{let x=i%w,y=Math.floor(i/w),x2=x,y2=y;if(mirror)x=w-1-x;if(rot===0){x2=x;y2=y;}if(rot===1){x2=h-1-y;y2=x;}if(rot===2){x2=w-1-x;y2=h-1-y;}if(rot===3){x2=y;y2=w-1-x;}b[y2*ww+x2]=v;});forms.push(ww+'x'+hh+':'+b.join(''));}return forms.sort()[0];}
const chapterNames=['门庭读光','四臂分配','遮屏间距','一步之桥','交错长视','光庭竣图'];
const titles=[['第一束晴光','走到边界','数字不挡光','也算脚下这格','门前小径','一面短屏','白点是笔记','入口竣图'],['向北量一量','两臂相抵','窗边读数','交叉测距','回廊两端','四向分账','余光所在','回廊竣图'],['屏边留白','四邻留路','斜角可相遇','框住一束光','短臂与长臂','角落的余量','相隔一格','框景竣图'],['留一条白路','左右相连','请留下一步','桥格不能黑','看见与走通','转角的连接','两片白地','连廊竣图'],['长视线交叠','南北余量','层间测距','蓝线相交','一处两用','交错的屏风','远端读光','层叠竣图'],['重读门庭','复核四臂','留白的理由','短屏长路','角点不是桥','对角并不相连','最后一张图','公共庭竣图']];
const levels=[],proofs=[],used=new Set();let attempts=0;
while(levels.length<48){const k=levels.length,ch=Math.floor(k/8),local=k%8;let w=5,h=5;if(ch===2&&local>=4)w=6;if(ch===3){h=6;if(local>=4)w=6;}if(ch===4||ch===5){w=6;h=6;if(ch===5&&local===0){w=5;h=5;}}const originSeed=seed,a=Array(w*h).fill(0),targetBlack=(ch<2?4+Math.floor(rand()*3):ch===2?6+Math.floor(rand()*2):8+Math.floor(rand()*3));for(const i of shuffle(Array.from({length:w*h},(_,i)=>i))){if(a.filter(Boolean).length>=targetBlack)break;const x=i%w,y=Math.floor(i/w);if((x&&a[i-1])||(x+1<w&&a[i+1])||(y&&a[i-w])||(y+1<h&&a[i+w]))continue;a[i]=1;if(!inspect({width:w,height:h,clues:[]},a))a[i]=0;}
 const key=canonical({width:w,height:h},a);attempts++;if(used.has(key))continue;let clues=values(w,h,a);if(clues.length<8)continue;let l={width:w,height:h,clues};if(solve(l,{maxNodes:20000}).count!==1)continue;
 const minClues=[13,10,9,8,7,7][ch];for(const c of shuffle(clues.slice())){if(clues.length<=minClues)break;const next=clues.filter(d=>d!==c);const p=solve({width:w,height:h,clues:next},{maxNodes:20000});if(p.count===1&&p.exhausted&&p.logicalCells>=w*h-next.length&&!(ch<3&&p.trace.some(t=>t.reason.type==='bridge')))clues=next;}
 l={width:w,height:h,clues:clues.sort((a,b)=>a[0]-b[0])};const p=solve(l,{maxNodes:100000});if(p.count!==1||!p.exhausted||p.logicalCells<w*h-clues.length)continue;const mechanics=new Set(p.trace.map(t=>t.reason.type));if(ch<3&&mechanics.has('bridge'))continue;if(ch===2&&!mechanics.has('spacing'))continue;if(ch===4&&!mechanics.has('bridge'))continue;if(ch===5&&local>=6&&(!mechanics.has('bridge')||!mechanics.has('spacing')))continue;
 // The bridge chapter contains genuine puzzles whose connectivity rule excludes an otherwise valid layout.
 let disconnected=null;if(ch===3||ch===5&&local===5){const without=solve(l,{connectivity:false,limit:12,maxNodes:100000});disconnected=without.solutions.find(s=>!inspect(l,s));if(ch===3&&!disconnected)continue;}
 if(k===3){const edge=clues.find(c=>c[0]%w===0||Math.floor(c[0]/w)===0||c[0]%w===w-1||Math.floor(c[0]/w)===h-1);if(!edge)continue;}
 used.add(key);const clueHash=crypto.createHash('sha256').update(JSON.stringify([w,h,l.clues])).digest('hex');const tags=[...new Set(p.trace.map(t=>t.reason.type))];const level={id:'courtyard-'+String(k+1).padStart(2,'0'),title:titles[ch][local],chapter:ch+1,chapterName:chapterNames[ch],width:w,height:h,clues:l.clues,solution:a,seed:originSeed,generatorVersion:VERSION,clueHash,tags,guide:local<2,logic:p.trace,disconnectedExample:disconnected};levels.push(level);proofs.push({id:level.id,clueHash,count:p.count,exhausted:p.exhausted,nodes:p.nodes,logicSteps:p.trace.length,tags,canonical:key,firstSolution:p.solutions[0],difficultyLabel:local<2?'引导':local<6?'组合':'综合',difficultyEvidence:'chapter concept, clue density and complete deterministic deduction trace; external player study not conducted'});console.log(level.id,w+'x'+h,clues.length,tags.join(','),'nodes',p.nodes,'attempts',attempts);}
fs.writeFileSync(new URL('../levels.mjs',import.meta.url),'// Deterministic, independently certified campaign.\nexport const LEVELS='+JSON.stringify(levels)+';\nexport const CHAPTERS='+JSON.stringify(chapterNames)+';\n');fs.writeFileSync(new URL('../release/level-proofs.json',import.meta.url),JSON.stringify({generator:VERSION,initialSeed:2026100206,attempts,levels:proofs},null,2)+'\n');
