/* Independent implementation: row/column intervals, matrix BFS and two-colour search.
   No production engine import; no reading of reference answers. */
export function inspect(l,a,{connectivity=true,spacing=true}={}){
 const w=l.width,h=l.height,n=w*h;if(a.length!==n||a.some(v=>v!==0&&v!==1))return false;
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x;if(spacing&&a[i]===1&&((x+1<w&&a[i+1]===1)||(y+1<h&&a[i+w]===1)))return false;}
 for(const [i,t] of l.clues){if(a[i])return false;const x=i%w,y=Math.floor(i/w);let left=x,right=x,top=y,bottom=y;while(left>0&&!a[y*w+left-1])left--;while(right+1<w&&!a[y*w+right+1])right++;while(top>0&&!a[(top-1)*w+x])top--;while(bottom+1<h&&!a[(bottom+1)*w+x])bottom++;if(right-left+bottom-top+1!==t)return false;}
 if(connectivity){const start=a.indexOf(0),seen=new Set([start]),q=[start];for(let k=0;k<q.length;k++){const i=q[k],x=i%w,y=Math.floor(i/w);for(const j of [x?i-1:-1,x+1<w?i+1:-1,y?i-w:-1,y+1<h?i+w:-1])if(j>=0&&!a[j]&&!seen.has(j)){seen.add(j);q.push(j);}}if(seen.size!==a.filter(v=>!v).length)return false;}return true;
}
function patterns(l){const w=l.width,h=l.height,n=w*h,clueCells=new Set(l.clues.map(c=>c[0]));return l.clues.map(([i,t])=>{const x=i%w,y=Math.floor(i/w),ps=[];for(let L=0;L<=x;L++)for(let R=x;R<w;R++)for(let T=0;T<=y;T++)for(let B=y;B<h;B++){if(R-L+B-T+1!==t)continue;const white=[],black=[];for(let xx=L;xx<=R;xx++)white.push(y*w+xx);for(let yy=T;yy<=B;yy++)if(yy!==y)white.push(yy*w+x);if(L)black.push(y*w+L-1);if(R+1<w)black.push(y*w+R+1);if(T)black.push((T-1)*w+x);if(B+1<h)black.push((B+1)*w+x);if(black.some(j=>clueCells.has(j)))continue;const assignments=Array(n).fill(-1);white.forEach(j=>assignments[j]=0);black.forEach(j=>assignments[j]=1);ps.push(assignments);}return {cell:i,ps};});}
function canConnect(l,a,omit=-1){const w=l.width,h=l.height,first=a.findIndex((v,i)=>v===0&&i!==omit)>=0?a.findIndex((v,i)=>v===0&&i!==omit):a.findIndex((v,i)=>v!==1&&i!==omit);if(first<0)return false;const seen=new Set([first]),q=[first];for(let k=0;k<q.length;k++){const i=q[k],x=i%w,y=Math.floor(i/w);for(const j of [x?i-1:-1,x+1<w?i+1:-1,y?i-w:-1,y+1<h?i+w:-1])if(j>=0&&j!==omit&&a[j]!==1&&!seen.has(j)){seen.add(j);q.push(j);}}return a.every((v,i)=>v!==0||seen.has(i));}
export function solve(l,{limit=2,maxNodes=Infinity,connectivity=true,spacing=true,assumptions=[]}={}){
 const n=l.width*l.height,w=l.width,h=l.height,base=Array(n).fill(-1),pcs=patterns(l),solutions=[];let nodes=0,cutoff=false;const trace=[];l.clues.forEach(c=>base[c[0]]=0);for(const [i,v] of assumptions){if(base[i]!==-1&&base[i]!==v)return {count:0,solutions:[],nodes:0,exhausted:true,trace:[]};base[i]=v;}
 function propagate(a,record){let change=true;while(change){change=false;function fix(i,v,reason){if(a[i]!==-1)return a[i]===v;a[i]=v;change=true;if(record)trace.push({cell:i,mark:v,reason});return true;}
 if(spacing)for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x;if(a[i]!==1)continue;for(const j of [x?i-1:-1,x+1<w?i+1:-1,y?i-w:-1,y+1<h?i+w:-1])if(j>=0&&!fix(j,0,{type:'spacing',source:i}))return false;}
 for(const pc of pcs){const valid=pc.ps.filter(p=>p.every((v,i)=>v===-1||a[i]===-1||v===a[i]));if(!valid.length)return false;for(let i=0;i<n;i++)if(a[i]===-1&&valid[0][i]!==-1&&valid.every(p=>p[i]===valid[0][i]))if(!fix(i,valid[0][i],{type:'reading',source:pc.cell,possibilities:valid.length}))return false;}
 if(connectivity){if(!canConnect(l,a))return false;for(let i=0;i<n;i++)if(a[i]===-1&&!canConnect(l,a,i))fix(i,0,{type:'bridge'});}}
 return true;}
 function visit(a,root=false){if(solutions.length>=limit)return;if(++nodes>maxNodes){cutoff=true;return;}if(!propagate(a,root))return;const unknown=a.map((v,i)=>v===-1?i:-1).filter(i=>i>=0);if(!unknown.length){if(inspect(l,a,{connectivity,spacing}))solutions.push(a.slice());return;}let best=unknown[0],score=-1;unknown.forEach(i=>{const pressure=pcs.reduce((s,p)=>s+((p.cell%w===i%w||Math.floor(p.cell/w)===Math.floor(i/w))?1:0),0);if(pressure>score){score=pressure;best=i;}});for(const v of [1,0]){const b=a.slice();b[best]=v;visit(b);if(solutions.length>=limit||cutoff)return;}}
 visit(base,true);return {count:solutions.length,solutions,nodes,exhausted:!cutoff&&solutions.length<limit,cutoff,trace,logicalCells:trace.length};
}
