// Real Chromium production-page QA using CDP; no automation dependencies.
import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawn} from 'node:child_process';import assert from 'node:assert/strict';import {LEVELS} from '../src/levels.mjs';import {cellEdges,edgeCoordinates} from '../src/render.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const port=Number(process.env.QA_DEBUG_PORT||4286),base=process.env.QA_URL||'http://127.0.0.1:4285';
const chrome=process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const profile=path.join(root,'.qa-browser'),release=path.join(root,'release');await fs.mkdir(release,{recursive:true});await fs.rm(profile,{recursive:true,force:true});
const child=spawn(chrome,['--headless=new','--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-component-update','--disable-sync','--hide-scrollbars','--remote-debugging-port='+port,'--user-data-dir='+profile,'about:blank'],{stdio:'ignore'});
let ws,id=0,touchMode=false;const pending=new Map(),errors=[],checks=[],layouts=[];
const delay=ms=>new Promise(r=>setTimeout(r,ms));
try{
 let tabs;for(let i=0;i<80;i++){try{tabs=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();break;}catch(_){await delay(100);}}
 if(!tabs)throw new Error('Unable to start own Chromium');
 ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 ws.onmessage=event=>{const message=JSON.parse(event.data);if(message.id){const p=pending.get(message.id);pending.delete(message.id);if(message.error)p.reject(new Error(JSON.stringify(message.error)));else p.resolve(message.result);}else if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails.text+' '+JSON.stringify(message.params.exceptionDetails.exception));};
 function send(method,params={}){return new Promise((resolve,reject)=>{const current=++id;pending.set(current,{resolve,reject});ws.send(JSON.stringify({id:current,method,params}));});}
 async function evaluate(expression){const res=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(res.exceptionDetails)throw new Error(JSON.stringify(res.exceptionDetails));return res.result.value;}
 async function waitFor(selector){for(let i=0;i<60;i++){if(await evaluate('!!document.querySelector('+JSON.stringify(selector)+')'))return;await delay(50);}throw new Error('Missing '+selector);}
 async function click(selector){if(selector.indexOf('[data-action="edge"]')===0&&await evaluate('!!document.querySelector(".direction-bar.is-hidden")'))await click('[data-action="input-mode"]');await waitFor(selector);const box=await evaluate('(function(){const e=document.querySelector('+JSON.stringify(selector)+');e.scrollIntoView({block:"nearest"});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()');if(touchMode){await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x,y:box.y}]});await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await delay(120);}else{await send('Input.dispatchMouseEvent',{type:'mousePressed',x:box.x,y:box.y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:box.x,y:box.y,button:'left',clickCount:1});}}
 async function viewport(width,height){touchMode=width<821;await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<821});await send('Emulation.setTouchEmulationEnabled',{enabled:width<821,maxTouchPoints:1});}
 async function shot(name){if(await evaluate('!!document.querySelector("#notice.visible")'))await delay(3100);const data=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await fs.writeFile(path.join(release,name),Buffer.from(data.data,'base64'));}
 async function layout(label){const metrics=await evaluate('(function(){const r=document.querySelector(".board-wrap"),t=document.querySelector(".tools");return {width:innerWidth,height:innerHeight,scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,board:r?{top:r.getBoundingClientRect().top,bottom:r.getBoundingClientRect().bottom}:null,toolsBottom:t?t.getBoundingClientRect().bottom:null,minCell:r?Math.min.apply(null,Array.from(document.querySelectorAll(".cell-hit")).map(e=>Math.min(e.getBoundingClientRect().width,e.getBoundingClientRect().height))):null,buttons:Array.from(document.querySelectorAll("button:not(.cell-hit)")).filter(e=>e.offsetWidth>0&&e.offsetHeight>0).map(e=>({text:e.textContent,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}))};})()');metrics.label=label;layouts.push(metrics);assert(metrics.scroll<=metrics.client,label+' horizontal overflow');if(metrics.minCell)assert(metrics.minCell>=43.9,label+' cell too small');assert(metrics.buttons.every(b=>b.h>=43.9&&b.w>=43.9),label+' short button '+JSON.stringify(metrics.buttons.filter(b=>b.h<43.9||b.w<43.9)));return metrics;}
 async function gesture(points,cancel=false){const rect=await evaluate('(function(){const r=document.querySelector(".board-wrap").getBoundingClientRect();const v=document.querySelector(".board-wrap svg").viewBox.baseVal;return {x:r.x,y:r.y,w:r.width,h:r.height,vw:v.width,vh:v.height};})()');const pts=points.map(p=>({x:rect.x+p[0]/rect.vw*rect.w,y:rect.y+p[1]/rect.vh*rect.h}));await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pts[0]]});for(const point of pts.slice(1))await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point]});await send('Input.dispatchTouchEvent',{type:cancel?'touchCancel':'touchEnd',touchPoints:[]});await delay(130);}
 const state=()=>evaluate('JSON.parse(localStorage.getItem("mini-polish:moon-tide-loop:v1:state"))');
 await send('Page.enable');await send('Runtime.enable');await viewport(390,844);await send('Page.navigate',{url:base});await waitFor('.tutorial-image');await evaluate('new Promise(r=>{const img=document.querySelector(".tutorial-image");if(img.complete)r();else img.onload=r;})');
 assert((await evaluate('document.querySelector(".tutorial-image").naturalWidth'))>0);await shot('tutorial-390.png');await click('[data-action="skip"]');assert(!await evaluate('!!document.querySelector(".modal")'));checks.push('First-entry tutorial appears, actual SVG loads, skip opens playable board');
 await click('[data-action="tutorial"]');await click('[data-action="tutorial-next"]');await click('[data-action="tutorial-next"]');await click('[data-action="tutorial-done"]');checks.push('Reopen and complete all three tutorial cards');
 await gesture([[56,16]]);assert.deepEqual((await state()).current.actions,[{edge:0,value:1}]);await gesture([[56,16]]);assert.equal((await state()).current.actions[1].value,0);await click('[data-action="undo"]');await click('[data-action="undo"]');
 await gesture([[16,16]]);assert.equal((await state()).current.actions.length,0);
 for(const [dx,dy,e] of [[0,-28,0],[28,0,13],[0,28,3],[-28,0,12]]){await gesture([[56,56],[56+dx,56+dy]]);assert.equal((await state()).current.actions[0].edge,e);await click('[data-action="undo"]');}
 await gesture([[56,56],[80,80]]);assert.equal((await state()).current.actions.length,0);await gesture([[56,56],[56,28]],true);assert.equal((await state()).current.actions.length,0);checks.push('Direct taps toggle; four swipes work; ambiguous and cancelled gestures do not commit');
 await click('[data-action="edge"][data-dir="0"]');let before=await state();assert(before.current.actions.length===1);const runId=before.current.runId;await click('[data-action="edge"][data-dir="0"]');assert((await state()).current.actions.length===1);await click('[data-action="undo"]');assert((await state()).current.actions.length===0);checks.push('Real cell-direction input, identical operation no-op, undo');
 await click('[data-action="brush"][data-value="-1"]');await click('[data-action="cell"][data-cell="4"]');await click('[data-action="edge"][data-dir="0"]');await send('Page.reload');await waitFor('.board-wrap');assert((await state()).current.runId===runId);assert((await state()).current.actions[0].value===-1);checks.push('Excluded mark is saved, reload resumes stable runId');
 await click('[data-action="hint"]');assert((await evaluate('document.querySelector(".modal").textContent')).length>60);await click('[data-action="hint-apply"]');await click('[data-action="restart"]');await click('[data-action="restart-confirm"]');assert((await state()).current.runId!==runId);assert((await state()).current.actions.length===0);checks.push('Contextual hint explains and applies a step; restart creates fresh run');
 const solveUI=async puzzle=>{for(let edge=0;edge<puzzle.solution.length;edge++){if(puzzle.solution[edge]!==1)continue;let cell=-1,dir=-1;for(let i=0;i<puzzle.clues.length;i++){const d=cellEdges(puzzle,i).indexOf(edge);if(d>=0){cell=i;dir=d;break;}}await click('[data-action="cell"][data-cell="'+cell+'"]');await click('[data-action="edge"][data-dir="'+dir+'"]');}};
 // A real partial board for the play screenshot.
 await click('[data-action="edge"][data-dir="0"]');await click('[data-action="cell"][data-cell="1"]');await click('[data-action="edge"][data-dir="0"]');await click('[data-action="cell"][data-cell="2"]');await click('[data-action="edge"][data-dir="0"]');await click('[data-action="edge"][data-dir="1"]');await click('[data-action="input-mode"]');await layout('play-390');await shot('play-390.png');
 await click('[data-action="restart"]');await click('[data-action="restart-confirm"]');await solveUI(LEVELS[0]);await waitFor('[data-action="next"]');await shot('complete-390.png');let completed=await state();assert(completed.records.length===1);const claimCount=JSON.stringify(completed.records).length;await click('[data-action="close"]');await send('Page.reload');await waitFor('.hero');assert((await state()).records.length===1);await shot('home-390.png');checks.push('First puzzle completed entirely with real browser pointer clicks; completion persists across refresh');
 await click('[data-action="chapter"][data-id="1"]');await shot('chapter-390.png');await click('[data-action="level"][data-id="moon-01"]');if(await evaluate('!document.querySelector(".gesture-board")'))await click('[data-action="input-mode"]');for(let e=0;e<LEVELS[0].solution.length;e++){if(LEVELS[0].solution[e]!==1)continue;const p=edgeCoordinates(LEVELS[0],e);await gesture([[16+(p[0]+p[2])*40,16+(p[1]+p[3])*40]]);}await click('[data-action="close"]');checks.push('Full first-level completion with 12 direct taps');completed=await state();assert(completed.records.length===2);const claims=completed.records.reduce((all,r)=>all.concat(r.event?r.event.rewardClaims:[]),[]);checks.push('Repeat clear creates separate attempt; idempotent rewards covered by storage tests');
 await click('[data-action="home"]');await click('[data-action="daily"]');assert((await state()).current.mode==='daily');await click('[data-action="home"]');await click('[data-action="seed"]');await click('[data-action="seed-start"]');assert((await state()).current.levelId.indexOf('seed-')===0);await send('Page.reload');await waitFor('.board-wrap');assert((await state()).current.mode==='seed');checks.push('Daily and Chinese seed bottle modes enter and resume');
 await click('[data-action="home"]');await click('[data-action="chapter"][data-id="6"]');await click('[data-action="level"][data-id="moon-72"]');
 for(const [w,h] of [[320,720],[349,720],[350,720],[351,720],[390,844],[699,844],[700,844],[701,844],[819,844],[820,844],[821,844],[1280,720]]){await viewport(w,h);await delay(30);const m=await layout('max-board-'+w);if(w===320||w===390)assert(m.toolsBottom<=h,'core controls not one screen '+JSON.stringify(m));if(w===320)await shot('play-320.png');if(w===390)await shot('deep-sea-390.png');if(w===1280)await shot('play-desktop.png');}
 await viewport(320,720);await click('[data-action="input-mode"]');await layout('precise-320');await shot('precise-320.png');await click('[data-action="input-mode"]');await gesture([[56,56],[56,28]]);assert.equal((await state()).current.actions.length,1);await click('[data-action="undo"]');checks.push('6x6 swipe at 320px and optional precise mode');await click('[data-action="tutorial"]');await layout('tutorial-320');await shot('tutorial-320.png');await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape'});assert(!await evaluate('!!document.querySelector(".modal")'));checks.push('Escape closes modal; background unlocks');
 await click('[data-action="home"]');await layout('home-320');await shot('home-320.png');await viewport(1280,720);await layout('home-desktop');await shot('home-desktop.png');
 await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert(await evaluate('matchMedia("(prefers-reduced-motion: reduce)").matches'));checks.push('Reduced-motion CSS media emulation');
 // Render genuine original vector artwork at deliverable raster size inside this QA-owned tab.
 await viewport(512,512);await evaluate('document.body.innerHTML="<img src=\\"./assets/icon.svg\\" style=\\"width:512px;height:512px\\">";document.body.style.margin="0";new Promise(r=>{document.querySelector("img").onload=r;})');await shot('icon-512.png');
 await viewport(1200,1000);await evaluate('document.body.innerHTML="<img src=\\"./assets/coast.svg\\" style=\\"width:1200px;height:1000px;max-width:none\\">";new Promise(r=>{document.querySelector("img").onload=r;})');await shot('coast-art.png');
 await viewport(1080,1440);const poster=await fs.readFile(path.join(release,'cover.svg'),'utf8');await evaluate('document.body.innerHTML='+JSON.stringify(poster)+';');await shot('cover-xhs.png');
 assert.equal(errors.length,0,'Browser runtime errors');
 const report={status:'PASS',browser:await send('Browser.getVersion'),url:base,checks,layouts,errors,limitations:['Desktop Chromium touch/viewport emulation, not physical mobile','Chrome61 / iOS Safari / Xiaohongshu native container not available']};await fs.writeFile(path.join(release,'browser-qa.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:checks.length,layouts:layouts.length,errors:errors.length,screenshots:release},null,2));
}catch(error){await fs.writeFile(path.join(release,'browser-qa-failure.json'),JSON.stringify({error:String(error),errors,checks,layouts},null,2));throw error;}finally{if(ws)ws.close();child.kill('SIGTERM');await delay(300);await fs.rm(profile,{recursive:true,force:true}).catch(()=>{});}
