(function () {
  'use strict';
  var E=BellEngine,S=BellStore,D=BellLevels,R=BellRender,app=document.getElementById('app'),modalRoot=document.getElementById('modal-root');
  var storage;try{storage=window.localStorage;}catch(e){storage={getItem:function(){return null;},setItem:function(){throw Error('Storage unavailable');}};}
  var data=S.load(storage),view='home',chapter=0,selected=-1,session=null,level=null,state=null,modalOpen=false,lastFocus=null,notice='',saveOK=true,tutorialStep=0,albumPage=0;
  var descriptions=['从轻轻一敲开始，看见翻转与复原。','十字回响有边界，角落也有自己的回应。','每口铃的风线不同，先看清，再敲响。','两次翻转相抵，让回响彼此成全。','在更深的夜色中，慢慢理顺十六口铃。','汇集学过的回响，点亮这一整座庭院。'];
  var poems=['晚风拂过第一枝。','花影在相邻的铃下相逢。','曲折的风，也有去处。','回声相抵，留下温柔。','夜色渐深，庭中有光。','愿这一庭铃光，陪你片刻。'];
  function esc(x){return String(x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function button(action,text,cls,extra){return '<button type="button" data-action="'+action+'" class="'+(cls||'')+'" '+(extra||'')+'>'+text+'</button>';}
  function persist(){data.session=session||data.session;saveOK=S.flush(storage,data,window.eveningBellCompletionHost);return saveOK;}
  function done(l){var r=data.records[l.id];return !!(r&&(r.best||r.solo));}
  function count(ch){return D.levels.filter(function(l){return l.chapter===ch&&done(l);}).length;}
  function top(play){return '<header class="topbar '+(play?'play-top':'')+'"><span class="brand">◌ 晚风铃庭</span><nav>'+button('home',play?'返回庭院':'庭院','plain')+button('rules','规则','plain')+'</nav></header>';}
  function warning(){return saveOK?'':'<p class="save-warning">当前浏览器无法保存进度；本轮仍可游玩，请勿关闭页面。</p>';}
  function drawHome(){app.className='';view='home';session=null;app.innerHTML=top(false)+warning()+'<main><section class="hero"><div class="hero-copy"><p class="eyebrow">A LITTLE GARDEN AT DUSK</p><h1>让晚风<br>捎一庭铃光</h1><p class="intro">敲一口铃，风线相连的铃一起明暗翻转。慢慢来，让它们同时亮起。</p><div class="hero-actions">'+button('continue',data.session?'继续上次的回响':'从第一阵风开始','primary')+button('daily','今日曲谱')+'</div></div><img class="hero-art" src="./assets/hero.svg" alt="暮色拱门下悬着三口铜铃与花枝，主题插画"></section><div class="section-head"><h3>六段晚风 · 六十道回响</h3>'+button('album','庭景收藏 '+D.chapters.filter(function(_,i){return count(i)===10;}).length+'/6','plain')+'</div><div class="chapter-grid">'+D.chapters.map(function(name,i){var n=count(i);return button('chapter','<span class="num">CHAPTER 0'+(i+1)+'</span><strong>'+name+'</strong><small>'+n+' / 10 已点亮</small><div class="progress"><i style="width:'+n*10+'%"></i></div>','chapter', 'data-chapter="'+i+'"');}).join('')+'</div><p class="footnote">不计时 · 随时撤销 · 不开声音也能玩</p></main>';}
  function drawChapter(){app.className='';view='chapter';app.innerHTML=top(false)+warning()+'<main><p class="eyebrow">CHAPTER 0'+(chapter+1)+'</p><h2>'+D.chapters[chapter]+'</h2><p class="chapter-description">'+descriptions[chapter]+'</p><div class="level-grid">'+D.levels.filter(function(l){return l.chapter===chapter;}).map(function(l,j){var r=data.records[l.id];return button('level','<b>'+String(j+1).padStart(2,'0')+'</b><span>'+l.name+'<small>'+(r?(r.solo?'✦ 独立点亮':'◉ 已点亮 · 曾用提示'):'○ 待点亮 · '+l.size+' × '+l.size)+'</small></span>','level-card'+(r?' collected':''),'data-level="'+l.id+'"');}).join('')+'<p class="footnote">所有关卡均可直接进入。每一关的风线都可以先看再敲。</p></main>';}
  function newRun(){return 'run-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,11);}
  function enter(key,resume){level=S.resolve(key);if(!level)return;session=resume||{key:key,runId:newRun(),history:[],assisted:false};state=E.replay(level,session.history);chapter=level.chapter;selected=-1;notice='';view='play';persist();drawPlay();var seen=false;try{seen=storage.getItem(S.tutorialKey)==='1';}catch(e){}if(!seen)showTutorial(0);else if(E.won(level,state))complete();}
  function cellHeight(){
    var padding=window.getComputedStyle(app),baseTop=window.innerWidth<=350?12:20,safe=Math.max(0,(parseFloat(padding.paddingTop)||baseTop)-baseTop)+Math.max(0,(parseFloat(padding.paddingBottom)||30)-30);
    var mobile=window.innerWidth<=700,width=mobile?Math.min(window.innerWidth-(window.innerWidth<=350?24:34),390)-20:Math.min((Math.min(window.innerWidth,1080)-52)*.54,510)-22;
    var maxBoard=window.innerHeight-safe-(mobile?338:250),spacing=(level.size-1)*(mobile?5:6);
    return Math.max(44,Math.min(90,Math.floor((width-spacing)/level.size),Math.floor((maxBoard-22-spacing)/level.size)));
  }
  function windLines(){if(selected<0)return '';var s=level.size,unit=100/s,x=(selected%s+.5)*unit,y=(Math.floor(selected/s)+.5)*unit;return '<svg class="wind-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">'+level.templates[selected].filter(function(j){return j!==selected;}).map(function(j){var tx=(j%s+.5)*unit,ty=(Math.floor(j/s)+.5)*unit,dx=tx-x,dy=ty-y,len=Math.sqrt(dx*dx+dy*dy),ex=tx-dx/len*unit*.22,ey=ty-dy/len*unit*.22;return '<path d="M'+x+' '+y+'L'+ex+' '+ey+'l'+(-dx/len*2-dy/len)+' '+(-dy/len*2+dx/len)+'M'+ex+' '+ey+'l'+(-dx/len*2+dy/len)+' '+(-dy/len*2-dx/len)+'"/>';}).join('')+'</svg>';}
  function drawPlay(focusCell){
    app.className='playing';
    var lit=state.lights.reduce(function(a,b){return a+b;},0),aff=selected<0?[]:level.templates[selected],finished=E.won(level,state);
    app.innerHTML=top(true)+warning()+'<main><header class="play-header"><div><p class="eyebrow">'+(session.key.indexOf('daily-')===0?'今日曲谱 · '+session.key.slice(9):D.chapters[chapter]+' · '+level.id.slice(-2))+'</p><h2>'+level.name+'</h2></div>'+button('tutorial','玩法图解','plain')+'</header><div class="play-layout"><section class="board-side"><div class="stats"><span>已点亮 <b>'+lit+' / '+state.lights.length+'</b></span><span>已敲 <b id="moves">'+state.moves+'</b> 次</span><span>最少 <b>'+level.minimum+'</b> 次</span></div><div class="board" style="--size:'+level.size+';--cell-height:'+cellHeight()+'px"><div class="bells">'+state.lights.map(function(on,i){return button('bell',R.bell(on)+'<span class="cell-number">'+(i+1)+'</span>'+(aff.indexOf(i)>=0?'<span class="affected-mark">↻</span>':''),'bell'+(on?' lit':'')+(aff.indexOf(i)>=0?' affected':'')+(selected===i?' selected':''),'data-cell="'+i+'" aria-label="'+(i+1)+'号铃，'+(on?'亮，铃舌展开':'暗，铃口闭合')+'" aria-pressed="'+(selected===i)+'"'+(finished?' disabled':''));}).join('')+'</div>'+windLines()+'</div><p class="legend">展开铃舌＝亮　闭合铃口＝暗　虚线框＝将翻转</p></section><aside class="play-aside"><p class="eyebrow">FOLLOW THE WIND</p><div class="instruction" aria-live="polite">'+(selected<0?'<strong>先选一口铃</strong>看看它会带动谁。目标是让所有铃同时亮起。':'<strong>'+ (selected+1)+' 号铃的回响</strong>将翻转 '+aff.map(function(i){return i+1;}).join('、')+' 号。箭头从所选铃指向被带动的铃。')+'</div>'+button('strike',finished?'这一庭已亮起':selected<0?'选好铃，再轻敲':'轻敲 '+(selected+1)+' 号铃','primary confirm',(selected<0||finished?'disabled':''))+'<div class="tools">'+button('undo','↶ 撤销','',state.moves===0?'disabled':'')+button('hint','看一步','',finished?'disabled':'')+button('restart','重新开始')+'</div>'+button('quick',(data.quick?'☑':'☐')+' 快捷单击：'+(data.quick?'点铃立即敲击':'先预览，再确认'),'quick','aria-pressed="'+data.quick+'"')+'<p class="status-line" role="status">'+esc(notice||(session.assisted?'本局用过提示；下次再收独立徽记。':''))+'</p></aside></div></main>';
    if(typeof focusCell==='number'){var b=app.querySelector('[data-cell="'+focusCell+'"]');if(b)b.focus();}
  }
  function strike(i){if(modalOpen||view!=='play'||E.won(level,state))return;if(state.moves>=10000){notice='本局操作已达上限，请撤销或重开。';drawPlay();return;}state=E.press(level,state,i);session.history=state.history.slice();notice='';persist();drawPlay(i);if(E.won(level,state))complete();}
  function openModal(title,body,actions){if(!modalOpen)lastFocus=document.activeElement;modalOpen=true;document.body.style.overflow='hidden';app.setAttribute('aria-hidden','true');modalRoot.innerHTML='<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-top"><h2 id="modal-title">'+title+'</h2>'+button('close','×','plain','aria-label="关闭"')+'</div>'+body+'<div class="modal-actions">'+actions+'</div></section></div>';var m=modalRoot.querySelector('.modal');m.scrollTop=0;var focus=modalRoot.querySelector('button');if(focus)focus.focus();}
  function closeModal(){modalOpen=false;modalRoot.innerHTML='';document.body.style.overflow='';app.removeAttribute('aria-hidden');if(lastFocus&&document.documentElement.contains(lastFocus))lastFocus.focus();else{var b=app.querySelector('button');if(b)b.focus();}}
  function markTutorial(){try{storage.setItem(S.tutorialKey,'1');}catch(e){}}
  function showTutorial(step){tutorialStep=step;markTutorial();var titles=['先读明暗与风线','轻敲一次，一起翻转','让整座庭院同时亮起'];var texts=['同一题面：展开铃舌是亮，闭合铃口是暗。选中 1 号铃，线会指出它影响的 1、2、4 号铃。每口铃都有固定范围；正式游玩时随时可看。','轻敲 1 号铃：1、2、4 号同时翻转，其他铃不变。明亮的铃也可能暂时变暗。同铃敲两次会复原，敲击顺序可以交换。','再敲 5 号铃，2、4、5、6、8 号一起翻转，九口铃全亮。这是同一题面的真实两步解。其他关卡的范围可能不对称，点选后再确认。'];openModal('跟着晚风试两步','<p class="step-label">0'+(step+1)+' / 03 · '+titles[step]+'</p><img src="./assets/tutorial-'+step+'.svg" alt="'+texts[step]+'"><p>'+texts[step]+'</p>',button('tutorial-skip','跳过')+button(step<2?'tutorial-next':'tutorial-done',step<2?'下一张':'我来敲一敲','primary'));}
  function complete(){var payload=S.settle(data,session,new Date().toISOString());persist();var assisted=session.assisted,r=data.records[session.key],best=r.solo?r.solo.history.length:null;
    openModal('满庭铃光','<div class="win"><img class="flower" src="./assets/bloom.svg" alt="全部铃点亮后，庭中花枝舒展"><p class="eyebrow">THE GARDEN ANSWERS</p><div class="stat-big">'+state.moves+' <small>次轻敲</small></div><p>'+poems[chapter]+'</p><p>'+(assisted?'借着提示走到了这里。下次试试自己点亮，收下独立曲谱。':state.moves===level.minimum?'✦ 独立点亮 · 已达最少步数，收下效率曲谱。':'✦ 独立点亮，收下一页曲谱。')+'</p><p class="muted">'+(best!==null?'独立最佳 '+best+' 次 · ':'')+'最少 '+level.minimum+' 次'+(payload&&payload.rewardClaims.length?' · 新收获 '+payload.rewardClaims.length+' 枚徽记':'')+'</p>'+(!saveOK?'<p>保存暂不可用，本轮结果仅保留在此页面。</p>':'')+'</div>',button('back-chapter','回到章节')+button('next-level',session.key.indexOf('daily-')===0?'回到庭院':D.levels.indexOf(level)===59?'赏一庭花景':'下一道回响','primary'));
  }
  function rules(){openModal('规则与来源','<p>每口铃都有固定的联动范围。点选后，箭头与虚线框会显示这次影响谁；确认敲击，范围内所有铃同时明暗翻转。</p><p>目标：全部亮起。亮铃也能敲，同铃两次复原，顺序可交换。撤销会恢复到上一状态并撤回该步计数；重开是一局新的尝试。</p><p>“最少次数”逐关经两种独立算法核验，只说明最短长度，不要求唯一顺序。“看一步”会说明并预选一口铃，由你确认；本局记为提示通关，独立徽记不发放。撤销不消除提示标记。</p><p>每关独立首次、独立达到最少次数各收一枚曲谱徽记。同成绩重玩不重复领取。章节十关点亮后收藏对应庭景。每日曲谱从已验证题库按本地日期固定挑选，无断签惩罚。</p><p>规则改编自 Simon Tatham 的 Flip（binary matrix toggling）。参考 Ten Realms Arcade 的 MIT 实现（55cdddb）；本作主题、界面、引擎与素材由本项目以 AI 辅助制作。许可：MIT。来源地址供识别：chiark.greenend.org.uk/~sgtatham/puzzles/。</p>',(view==='play'?button('quick','快捷单击：'+(data.quick?'开':'关')):'')+button('close','回到庭院里的风','primary'));}
  function album(){var n=count(albumPage),claimed=S.claimsFor(data).length;openModal('庭景与曲谱','<div class="album-card"><p class="step-label">0'+(albumPage+1)+' / 06 · 曲谱徽记 '+claimed+' 枚</p><img src="./assets/garden-'+albumPage+'.svg" alt="'+D.chapters[albumPage]+'的花庭插画" style="opacity:'+(n===10?'1':'.32')+'"><h3>'+D.chapters[albumPage]+'</h3><p>'+(n===10?poems[albumPage]:'已点亮 '+n+' / 10 关；这一章全亮时收藏庭景。')+'</p></div>',button('album-prev','上一庭','',albumPage===0?'disabled':'')+button('album-next','下一庭','',albumPage===5?'disabled':''));}
  function dispatch(action,b){
    if(action==='close'||action==='tutorial-skip'||action==='tutorial-done'){closeModal();return;}
    if(action==='tutorial-next'){showTutorial(tutorialStep+1);return;}
    if(action==='tutorial'){showTutorial(0);return;}
    if(action==='rules'){rules();return;}
    if(action==='album'){albumPage=0;album();return;}
    if(action==='album-prev'||action==='album-next'){albumPage+=action==='album-prev'?-1:1;album();return;}
    if(action==='home'){closeModal();drawHome();return;}
    if(action==='chapter'){chapter=Number(b.getAttribute('data-chapter'));drawChapter();return;}
    if(action==='back-chapter'){closeModal();drawChapter();return;}
    if(action==='level'){enter(b.getAttribute('data-level'));return;}
    if(action==='continue'){if(data.session)enter(data.session.key,data.session);else enter(D.levels[0].id);return;}
    if(action==='daily'){var k='daily-v1-'+S.dateKey(new Date());enter(k,data.session&&data.session.key===k?data.session:null);return;}
    if(action==='next-level'){var idx=D.levels.indexOf(level);closeModal();if(session.key.indexOf('daily-')===0){drawHome();return;}if(idx===59){drawHome();albumPage=5;album();return;}enter(D.levels[idx+1].id);return;}
    if(action==='bell'){var i=Number(b.getAttribute('data-cell'));selected=i;if(data.quick)strike(i);else drawPlay(i);return;}
    if(action==='strike'){if(selected>=0)strike(selected);return;}
    if(action==='undo'){if(data.receipts[session.runId+':complete'])session.runId=newRun();state=E.undo(level,state);session.history=state.history.slice();notice='已撤回上一敲。';persist();drawPlay();return;}
    if(action==='quick'){data.quick=!data.quick;persist();drawPlay();if(modalOpen)rules();return;}
    if(action==='restart'){openModal('让这阵风重新来过','<p>这一局的敲击会归零，已收藏的曲谱与最佳记录保留。</p>',button('close','继续想想')+button('restart-confirm','重新开始','primary'));return;}
    if(action==='restart-confirm'){var rk=session.key;closeModal();enter(rk);return;}
    if(action==='hint'){var solution=E.solve(level,state.lights);if(!solution||!solution.presses.length)return;var h=solution.presses[0];session.assisted=true;selected=h;persist();drawPlay();openModal('借一缕风看下一步','<p>当前局面还可用 '+solution.minimum+' 次敲击全亮。一个最短方案从 '+(h+1)+' 号开始：它会翻转 '+level.templates[h].map(function(j){return j+1;}).join('、')+' 号。</p><p>其余几敲会抵消重叠处的变化，最后恰好翻转当前所有暗铃。单看这一步不一定让亮铃变多。</p><p>本局已记为使用提示。关闭后已预选这口铃，你可确认敲击或另选。</p>',button('close','回棋盘看看','primary'));return;}
  }
  function click(e){var b=e.target.closest('button[data-action]');if(!b||b.disabled)return;if(modalOpen&&!modalRoot.contains(b))return;dispatch(b.getAttribute('data-action'),b);}
  document.addEventListener('click',click);
  // Native buttons synthesize click for keyboard, pointer and touch without duplicate strikes.
  if(window.PointerEvent)app.addEventListener('pointerdown',function(e){var b=e.target.closest('button[data-cell]');if(b)b.classList.add('touching');});
  document.addEventListener('keydown',function(e){if(!modalOpen)return;if(e.key==='Escape'){e.preventDefault();closeModal();return;}if(e.key==='Tab'){var bs=Array.prototype.slice.call(modalRoot.querySelectorAll('button:not([disabled])'));var first=bs[0],last=bs[bs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
  window.addEventListener('resize',function(){if(view==='play'){var board=app.querySelector('.board');if(board)board.style.setProperty('--cell-height',cellHeight()+'px');}});
  persist();drawHome();
}());
