import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import {dependency} from './dependencies.mjs';import {oracle} from './oracle.mjs';import vm from 'node:vm';
const {chromium}=dependency('playwright');const ctx=vm.createContext({});vm.runInContext(fs.readFileSync('src/levels.js','utf8'),ctx);const levels=ctx.LoomLevels;const csp="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'none'; object-src 'none'; frame-src 'none'; worker-src 'none'; font-src 'self'";
const server=http.createServer((req,res)=>{const path=decodeURIComponent(req.url.split('?')[0]);if(path.includes('..')){res.writeHead(403).end();return;}try{const f='dist/xhs'+(path==='/'?'/index.html':path);res.setHeader('Content-Security-Policy',csp);res.setHeader('Content-Type',({'html':'text/html','js':'text/javascript','css':'text/css','svg':'image/svg+xml','png':'image/png'})[f.split('.').pop()]||'application/octet-stream');res.end(fs.readFileSync(f));}catch(e){res.writeHead(404).end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});const report={viewports:[],flows:[],errors:[],externalRequests:[],csp,device:'Playwright Chromium desktop/mobile viewport simulation; no physical device'};
try{
 for(const [width,height] of [[320,720],[359,720],[360,720],[361,720],[390,844],[759,720],[760,720],[761,720],[1280,720]]){
  const context=await browser.newContext({viewport:{width,height},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(url))report.externalRequests.push(r.url());});
  await page.goto(url);await page.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');});
  async function fits(){const x=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));assert(x.sw<=x.cw,`${width} overflow ${JSON.stringify(x)}`);}
  await fits();if(width===390)await page.screenshot({path:'release/home-mobile.png',fullPage:true});
  await page.locator('[data-level]').first().click();await page.getByRole('dialog').waitFor();await page.locator('#modal img').waitFor();assert(await page.locator('#modal img').evaluate(img=>img.complete&&img.naturalWidth>0));if(width===390)await page.screenshot({path:'release/tutorial-mobile.png',fullPage:true});await page.getByRole('button',{name:'跳过',exact:true}).click();
  await page.getByRole('button',{name:'返回章节',exact:true}).click();await page.locator('[data-chapter="6"]').click();await page.locator('[data-level]').first().click();await fits();
  const geometry=await page.locator('.tile').evaluateAll(bs=>bs.map(b=>({w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height})));assert(geometry.every(g=>g.w>=44&&g.h>=44),`${width} undersized tile ${JSON.stringify(geometry[0])}`);
  if(width===390)await page.screenshot({path:'release/gameplay-mobile.png',fullPage:true});if(width===1280)await page.screenshot({path:'release/gameplay-desktop.png',fullPage:true});if(width===320)await page.screenshot({path:'release/gameplay-320-safe.png',fullPage:true});
  await page.locator('#help').click();await page.getByRole('button',{name:'下一张',exact:true}).click();await page.getByRole('button',{name:'下一张',exact:true}).click();await page.getByRole('button',{name:'开始织卷',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'help');
  report.viewports.push({width,height,safeTop:44,safeBottom:34,minCell:geometry[0],noHorizontalOverflow:true});await context.close();
 }
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url);await page.locator('[data-level]').first().click();await page.getByRole('button',{name:'跳过',exact:true}).click();
 const p=levels[0],empty=p.givens.indexOf(-1),fixed=p.givens.findIndex(v=>v!==-1),solution=oracle(p.givens,p.n).solutions[0];
 await page.locator(`[data-cell="${fixed}"]`).click();await page.locator('#day').click();assert((await page.locator('#status').textContent()).includes('固定'));
 await page.locator(`[data-cell="${empty}"]`).click();await page.locator('#settings').click();await page.getByRole('button',{name:/^笔记：/}).click();await page.locator('#day').click();assert(await page.locator(`[data-cell="${empty}"] .note`).count());await page.locator('#settings').click();await page.getByRole('button',{name:/^笔记：/}).click();await page.locator(solution[empty]?'#day':'#night').click();assert(!(await page.locator(`[data-cell="${empty}"] .note`).count()));
 await page.reload();await page.locator('[data-level]').first().click();assert((await page.locator(`[data-cell="${empty}"]`).getAttribute('aria-label')).includes(solution[empty]?'昼':'夜'));await page.locator('#undo').click();assert((await page.locator(`[data-cell="${empty}"]`).getAttribute('aria-label')).includes('空格'));
 await page.locator('#hint').click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'自己来',exact:true}).click();assert((await page.locator(`[data-cell="${empty}"]`).getAttribute('aria-label')).includes('空格'));
 await page.locator('#hint').click();await page.getByRole('button',{name:/确认填入/}).click();await page.locator('#restart').click();await page.getByRole('button',{name:'重新开始',exact:true}).click();
 async function solveUI(){for(let i=0;i<p.givens.length;i++)if(p.givens[i]===-1){await page.locator(`[data-cell="${i}"]`).click();await page.locator(solution[i]?'#day':'#night').click();}}
 await solveUI();await page.getByRole('heading',{name:'经纬相遇，昼夜成卷。'}).waitFor();await page.locator('.win-fabric').evaluate(async e=>{if(e.getAnimations)await Promise.all(e.getAnimations().map(a=>a.finished));});await page.screenshot({path:'release/completion-mobile.png',fullPage:true});await page.getByRole('button',{name:'再看织卷',exact:true}).click();
 const save=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('mini-polish:daynight-scroll:v1:save')));assert.equal(Object.keys((await save()).completed).length,1);await page.reload();await page.locator('[data-level]').first().click();assert((await page.locator('#status').textContent()).includes('已经织好'));await page.locator('#restart').click();await page.getByRole('button',{name:'重新开始',exact:true}).click();await solveUI();assert.equal(Object.keys((await save()).completed).length,1);assert.equal((await save()).outbox.length,1);await page.getByRole('button',{name:'返回章节',exact:true}).last().click();
 await page.locator('#collection').click();await page.getByRole('button',{name:'下一段',exact:true}).click();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'collection');
 await page.evaluate(()=>{localStorage.setItem('other-game','retained');localStorage.setItem('mini-polish:daynight-scroll:v1:save','{broken');});await page.reload();assert.equal(await page.evaluate(()=>localStorage.getItem('other-game')),'retained');await page.locator('#daily').click();assert((await page.locator('.play-heading').textContent()).includes('今日织片'));
 report.flows=['first tutorial / skip / full tutorial / reopen / focus restore','fixed cell no-op','candidate notes separated','legal input / undo / reload replay','hint explanation / confirm / cancel','restart confirmation','real UI completion / reload / repeat completion no duplicate claim','collection pagination / Escape','corrupted storage isolated','daily entry'];
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.externalRequests,[]);await context.close();fs.writeFileSync('release/browser-qa.json',JSON.stringify(report,null,2));console.log('Browser matrix and flows passed');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
