import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,act,analyze,normalize,replay} from '../src/engine.mjs';import {solve,structureKey} from '../src/solver.mjs';import {LEVELS} from '../src/levels.mjs';
// Exhaustive bit-mask oracle has no engine/solver calls and no stored answers.
function oracle(p){const n=p.n,N=n*n,results=[];for(let mask=0;mask<2**N;mask++){
 let valid=true,start=-1,white=0;for(let i=0;i<N&&valid;i++)if((mask>>>i)&1){if(i%n<n-1&&((mask>>>(i+1))&1)||i+n<N&&((mask>>>(i+n))&1))valid=false;}else{start=i;white++;for(let j=i+1;j<N;j++)if(!((mask>>>j)&1)&&p.cells[i]===p.cells[j]&&((i/n|0)===(j/n|0)||i%n===j%n)){valid=false;break;}}
 if(!valid||start<0)continue;const stack=[start],seen=new Set();while(stack.length){const i=stack.pop();if(seen.has(i))continue;seen.add(i);for(const j of [i-n,i+n,i%n?i-1:-1,i%n<n-1?i+1:-1])if(j>=0&&j<N&&!((mask>>>j)&1)&&!seen.has(j))stack.push(j);}
 if(seen.size===white)results.push(Array.from({length:N},(_,i)=>(mask>>>i)&1));}return results;}
test('60 unique structurally distinct boards, chapter sizes, independent exhaustive CSP',()=>{assert.equal(LEVELS.length,60);assert.equal(new Set(LEVELS.map(structureKey)).size,60);for(let c=1;c<=6;c++)assert.equal(LEVELS.filter(p=>p.chapter===c).length,10);for(const p of LEVELS){const proof=solve(p);assert.equal(proof.solutions.length,1,p.id);assert.equal(proof.exhausted,true);assert.deepEqual(proof.solutions[0],p.solution);assert.equal(analyze(p,{modes:p.solution,moves:0}).complete,true);assert.equal(analyze(p,fresh(p)).complete,false);}});
test('all thirty 4x4 boards cross-checked by full 65536-state oracle',()=>{for(const p of LEVELS.filter(p=>p.n===4))assert.deepEqual(oracle(p),[p.solution],p.id);});
test('oracle and independent solver agree for all 2x2 1/2 boards including impossible/multiple',()=>{for(let mask=0;mask<16;mask++){const p={n:2,cells:Array.from({length:4},(_,i)=>1+(mask>>i&1))};assert.equal(solve(p,100).solutions.length,oracle(p).length);}});
test('circle notes and unmarked white are equivalent, no answer matching',()=>{for(const p of LEVELS){const s={modes:p.solution.map(x=>x===0?2:x),moves:0};assert.equal(analyze(p,s).complete,true);const other=Object.assign({},p,{solution:[]});assert.equal(analyze(other,s).complete,true);}});
test('illegal inputs are atomic no-op, duplicate choices count no moves',()=>{const p=LEVELS[0],s=fresh(p);for(const [i,m] of [[-1,1],[99,1],[0,3],[0,0],[0.5,1],['1',1]])assert.equal(act(p,s,i,m),s);assert.equal(normalize(p,{modes:[],moves:0}),null);assert.equal(replay(p,[[0,0]]),null);});
test('adjacent black, diagonal white disconnection, empty white rejected',()=>{const p={n:2,cells:[1,2,2,1]};assert.equal(analyze(p,{modes:[1,1,0,0],moves:2}).complete,false);const a=analyze(p,{modes:[1,0,0,1],moves:2});assert.equal(a.touching.length,0);assert.equal(a.disconnected.length,1);assert.equal(a.complete,false);assert.equal(analyze(p,{modes:[1,1,1,1],moves:0}).complete,false);});
