import test from 'node:test';import assert from 'node:assert/strict';
import {LEVELS} from '../src/levels.mjs';import {act,fresh,analyze,replay} from '../src/engine.mjs';import {solve} from '../src/solver.mjs';
import {SAVE_KEY,TUTORIAL_KEY,loadSave,persist,newSession,changeSession,undoSession,finish,flush,dailyIndex,dayStamp} from '../src/session.mjs';import {tutorialStates,boardMarkup} from '../src/render.mjs';import {getHint} from '../src/hints.mjs';
function storage(){const data={unrelated:'keep'};return {data,getItem:k=>data[k]||null,setItem:(k,v)=>{data[k]=v;}};}
function completeSession(p,hints=0){let s=newSession(p);for(let i=0;i<p.cells.length;i++)if(p.solution[i])s=changeSession(p,s,i,1);s.hints=hints;return s;}
test('replay restoring, undo and illegal no-op; circles persist as notes',()=>{const p=LEVELS[0];let s=newSession(p);assert.equal(changeSession(p,s,-1,1),s);s=changeSession(p,s,0,2);assert.equal(replay(p,s.log).modes[0],2);const st=storage(),save=loadSave(st,LEVELS);save.session=s;persist(st,save);assert.deepEqual(loadSave(st,LEVELS).session,s);assert.equal(undoSession(s).log.length,0);assert.equal(undoSession(newSession(p)).log.length,0);});
test('invalid storage/completion booleans are not trusted and other keys survive',()=>{const st=storage();for(const data of ['{','null',JSON.stringify({schemaVersion:1,session:{modes:[]},records:{'ma-v1-01':{complete:true}}})]){st.setItem(SAVE_KEY,data);assert.equal(Object.keys(loadSave(st,LEVELS).records).length,0);}const save=loadSave(st,LEVELS);persist(st,save);assert.equal(st.data.unrelated,'keep');});
test('completion/outbox persist before host call and retries keep ID; no duplicate first reward',async()=>{const p=LEVELS[0],st=storage(),save=loadSave(st,LEVELS);save.session=completeSession(p);assert.equal(finish(save,p,st).persisted,true);assert.equal(Object.keys(save.records).length,1);assert.equal(save.outbox.length,1);finish(save,p,st);assert.equal(save.outbox.length,1);const ids=[];await flush(save,st,async e=>{ids.push(e.completionId);assert.equal(JSON.parse(st.getItem(SAVE_KEY)).outbox.length,1);throw Error('offline');});assert.equal(save.outbox.length,1);const restored=loadSave(st,LEVELS);await flush(restored,st,async e=>{ids.push(e.completionId);return true;});assert.equal(new Set(ids).size,1);assert.equal(restored.outbox.length,0);restored.session=completeSession(p);finish(restored,p,st);assert.equal(restored.outbox.length,0);});
test('hinted vs independent clear upgrade and undo do not erase hint history',()=>{const p=LEVELS[0],st=storage(),save=loadSave(st,LEVELS);save.session=completeSession(p,2);finish(save,p,st);assert.deepEqual(save.outbox[0].claims,[p.id+':first']);assert.equal(undoSession(save.session).hints,2);save.session=completeSession(p,0);finish(save,p,st);assert.deepEqual(save.outbox[1].claims,[p.id+':independent']);assert.equal(save.records[p.id].hints,0);save.session=completeSession(p,5);finish(save,p,st);assert.equal(save.records[p.id].hints,0);assert.equal(save.outbox.length,2);});
test('full disk does not deliver unpersisted claims; retry recovers',async()=>{const p=LEVELS[0],st=storage(),save=loadSave(st,LEVELS);save.session=completeSession(p);const bad={getItem:st.getItem,setItem:()=>{throw Error('full');}};assert.equal(finish(save,p,bad).persisted,false);let calls=0;assert.equal(await flush(save,bad,()=>{calls++;return true;}),false);assert.equal(calls,0);await flush(save,st,()=>{calls++;return true;});assert.equal(calls,1);});
test('daily is deterministic local-calendar 60 day rotation; progress separate from main',()=>{const date=new Date(2026,8,22,12);assert.equal(dayStamp(date),'2026-09-22');const next=new Date(2026,8,82,12);assert.equal(dailyIndex(date),dailyIndex(next));const p=LEVELS[dailyIndex(date)],st=storage(),save=loadSave(st,LEVELS);save.session=Object.assign(completeSession(p),{mode:'daily',date:dayStamp(date)});finish(save,p,st);assert.equal(save.records[p.id],undefined);assert.ok(save.records['daily:2026-09-22:'+p.id]);});
test('tutorial shares formal renderer and exact action, complete verified; tutorial version independent',()=>{const p=LEVELS[0],cards=tutorialStates(p);assert.deepEqual(cards[0].state,fresh(p));assert.deepEqual(cards[1].state,act(p,fresh(p),p.solution.indexOf(1),1));assert.ok(analyze(p,cards[2].state).complete);for(const card of cards){assert.equal((boardMarkup(p,card.state,-1,false).match(/class="cell /g)||[]).length,16);}const st=storage(),save=loadSave(st,LEVELS);save.session=completeSession(p);finish(save,p,st);st.setItem(TUTORIAL_KEY,'seen');assert.equal(Object.keys(loadSave(st,LEVELS).records).length,1);});
test('hints solve all 60 boards using valid operations; wrong black corrected',()=>{for(const p of LEVELS){let s=fresh(p);for(let i=0;i<p.cells.length;i++){if(analyze(p,s).complete)break;const h=getHint(p,s);assert.ok(Number.isInteger(h.index),p.id);s=act(p,s,h.index,h.mode);}assert.ok(analyze(p,s).complete,p.id);const wrong=p.solution.indexOf(0),bad=act(p,fresh(p),wrong,1),hint=getHint(p,bad);assert.equal(hint.index,wrong);assert.equal(hint.mode,0);}});
test('daily tampering and mismatched finish are rejected; log cap stays atomic',()=>{const st=storage(),p=LEVELS[0],save=loadSave(st,LEVELS);save.session=completeSession(p);assert.equal(finish(save,LEVELS[1],st).completed,false);save.session.mode='daily';save.session.date='2026-02-31';persist(st,save);assert.equal(loadSave(st,LEVELS).session,null);const s=newSession(p);s.log=Array.from({length:10000},(_,i)=>[0,i%2?0:1]);assert.equal(changeSession(p,s,1,1),s);});
