import './review-gallery.mjs';
import fs from 'node:fs';import os from 'node:os';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';import {server} from './serve.mjs';import {root} from './lib.mjs';
let pw;try{pw=await import('playwright');}catch{const bundled=process.env.PLAYWRIGHT_MODULE||os.homedir()+'/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';pw=await import(pathToFileURL(bundled));}
const executablePath=process.env.CHROME_PATH||('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome');
const browser=await pw.chromium.launch({headless:true,...(fs.existsSync(executablePath)?{executablePath}:{})});const srv=await server(),url='http://127.0.0.1:'+srv.address().port,report={browser:await browser.version(),csp:true,viewports:[],flows:[],errors:[],externalRequests:[]};
const shot=async(p,name)=>{await p.waitForFunction(()=>Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0));return p.screenshot({path:fileURLToPath(new URL('release/'+name+'.png',root)),fullPage:true});};
const click=(p,act)=>p.locator('[data-action="'+act+'"]:visible').first().click();
async function solve(p){const taps=await p.evaluate(()=>{const s=BellStore.load(localStorage).session,l=BellStore.resolve(s.key);return BellEngine.solve(l,BellEngine.replay(l,s.history).lights).presses;});for(const i of taps){await p.locator('[data-cell="'+i+'"]').click();await click(p,'strike');}}
try{
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1});const p=await context.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(url))report.externalRequests.push(r.url());});await p.goto(url);await shot(p,'home-mobile');await click(p,'continue');assert(await p.locator('[role=dialog]').isVisible());await shot(p,'tutorial-mobile');await click(p,'tutorial-next');await click(p,'tutorial-next');await click(p,'tutorial-done');assert.equal(await p.locator('[role=dialog]').count(),0);report.flows.push('first tutorial / three cards / done');
 await p.locator('[data-cell="0"]').click();assert(await p.locator('.wind-lines').isVisible());await shot(p,'gameplay-mobile');await click(p,'strike');if(await p.locator('[role=dialog]').count())await click(p,'close');await click(p,'undo');assert.equal(await p.locator('#moves').textContent(),'0');await p.locator('[data-cell="0"]').click();await click(p,'strike');if(await p.locator('[role=dialog]').count())await click(p,'close');await p.reload();await click(p,'continue');if(await p.locator('[role=dialog]').count())await click(p,'close');assert.equal(await p.locator('#moves').textContent(),'1');report.flows.push('select / strike / undo / refresh-history');
 await click(p,'restart');await click(p,'restart-confirm');await solve(p);assert(await p.locator('[role=dialog]').isVisible());await shot(p,'completion-mobile');const claims=await p.evaluate(()=>BellStore.claimsFor(BellStore.load(localStorage)).length);assert.equal(claims,2);await p.reload();await click(p,'continue');assert(await p.locator('[role=dialog]').isVisible());assert.equal(await p.evaluate(()=>BellStore.claimsFor(BellStore.load(localStorage)).length),claims);await click(p,'close');await click(p,'restart');await click(p,'restart-confirm');await solve(p);assert.equal(await p.evaluate(()=>BellStore.claimsFor(BellStore.load(localStorage)).length),claims);report.flows.push('win / reload-win / replay-win / claims-idempotent');
 await click(p,'next-level');await click(p,'hint');await click(p,'close');await solve(p);assert.equal(await p.evaluate(()=>BellStore.claimsFor(BellStore.load(localStorage)).length),claims);report.flows.push('hint / no independent reward');await click(p,'back-chapter');await p.locator('[data-level="chapter-01-level-03"]').click();await click(p,'tutorial');await p.keyboard.press('Escape');assert.equal(await p.locator('[role=dialog]').count(),0);assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('data-action')),'tutorial');report.flows.push('tutorial replay / Esc / focus restore');
 await click(p,'home');await click(p,'daily');const dailyKey=await p.evaluate(()=>BellStore.load(localStorage).session.key);assert(dailyKey.startsWith('daily-v1-'));await solve(p);await click(p,'next-level');await click(p,'album');await click(p,'album-next');await click(p,'close');report.flows.push('daily / collection pagination');
 await p.evaluate(()=>{localStorage.setItem('foreign-game','preserved');const d=BellStore.load(localStorage);d.session={key:'chapter-01-level-01',history:[999],runId:'run-corrupt'};localStorage.setItem(BellStore.key,JSON.stringify(d));});await p.reload();assert.equal(await p.evaluate(()=>BellStore.load(localStorage).session),null);assert.equal(await p.evaluate(()=>localStorage.getItem('foreign-game')),'preserved');report.flows.push('corrupt session recovery / namespace isolation');
 for(const [w,h] of [[320,720],[349,720],[350,720],[351,720],[390,844],[699,720],[700,720],[701,720],[1280,720]]){
  await p.setViewportSize({width:w,height:h});await p.goto(url);await p.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');});await p.locator('[data-chapter="5"]').click();await p.locator('[data-level="chapter-06-level-10"]').click();await p.locator('[data-cell="12"]').click();await p.evaluate(()=>window.scrollTo(0,0));
  const metrics=await p.evaluate(()=>{const buttons=Array.from(document.querySelectorAll('.bell')),board=document.querySelector('.board').getBoundingClientRect(),tools=document.querySelector('.tools').getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,minCellWidth:Math.min(...buttons.map(x=>x.getBoundingClientRect().width)),minCellHeight:Math.min(...buttons.map(x=>x.getBoundingClientRect().height)),boardTop:board.top,boardBottom:board.bottom,toolsBottom:tools.bottom,scrollHeight:document.documentElement.scrollHeight};});report.viewports.push({width:w,height:h,safeTop:44,safeBottom:34,...metrics});assert(!metrics.overflow,JSON.stringify({w,metrics}));assert(metrics.boardBottom<=h-34&&metrics.toolsBottom<=h-34,JSON.stringify({w,metrics}));assert(metrics.minCellWidth>=44&&metrics.minCellHeight>=44,JSON.stringify({w,metrics}));await shot(p,'qa-'+w+'x'+h);await click(p,'tutorial');assert.equal(await p.evaluate(()=>document.body.style.overflow),'hidden');await click(p,'tutorial-skip');
 }
 await p.setViewportSize({width:390,height:844});await click(p,'home');await p.locator('[data-chapter="2"]').click();await p.locator('[data-level="chapter-03-level-04"]').click();await p.locator('[data-cell="4"]').click();await shot(p,'gameplay-mobile');await click(p,'strike');await shot(p,'operation-mobile');
 await p.setViewportSize({width:1280,height:720});await click(p,'home');await shot(p,'home-desktop');await p.emulateMedia({reducedMotion:'reduce'});await click(p,'continue');await p.locator('[data-cell="0"]').focus();await p.keyboard.press('Enter');await click(p,'strike');report.flows.push('reduced motion / keyboard activation');
 // Storage denial must preserve local play and explain persistence loss.
 const denied=await browser.newContext({viewport:{width:320,height:720}});await denied.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('quota');};});const dp=await denied.newPage();await dp.goto(url);assert(await dp.locator('.save-warning').isVisible());await click(dp,'continue');await click(dp,'tutorial-skip');const deniedPath=await dp.evaluate(()=>BellEngine.solve(BellLevels.levels[0],BellLevels.levels[0].initial).presses);for(const i of deniedPath){await dp.locator('[data-cell="'+i+'"]').click();await click(dp,'strike');}assert(await dp.locator('[role=dialog]').isVisible());await denied.close();report.flows.push('storage denial still playable, visible warning');
 // Fast taps are one operation each; mobile option is accessible from rules.
 await p.setViewportSize({width:390,height:844});await click(p,'home');await p.locator('[data-chapter="2"]').click();await p.locator('[data-level="chapter-03-level-04"]').click();await click(p,'rules');await click(p,'quick');await click(p,'close');await p.locator('[data-cell="0"]').click();assert.equal(await p.locator('#moves').textContent(),'1');await p.locator('[data-cell="0"]').click();assert.equal(await p.locator('#moves').textContent(),'2');await click(p,'undo');assert.equal(await p.locator('#moves').textContent(),'1');report.flows.push('quick tap / double tap / undo');
 // Raster exports from original vector assets, separate from real gameplay screenshots.
 const artServer=await server(new URL('../',import.meta.url));const artPage=await context.newPage();await artPage.setViewportSize({width:1080,height:1440});await artPage.goto('http://127.0.0.1:'+artServer.address().port+'/release/cover.svg');await artPage.screenshot({path:fileURLToPath(new URL('release/cover.png',root))});await artPage.setViewportSize({width:512,height:512});await artPage.goto('http://127.0.0.1:'+artServer.address().port+'/assets/icon.svg');await artPage.screenshot({path:fileURLToPath(new URL('release/icon.png',root))});for(let c=1;c<=6;c++){await artPage.setViewportSize({width:1280,height:670});await artPage.goto('http://127.0.0.1:'+artServer.address().port+'/release/level-review-'+c+'.svg');await artPage.screenshot({path:fileURLToPath(new URL('release/level-review-'+c+'.png',root))});}await artPage.close();artServer.close();
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.externalRequests,[]);report.status='PASS';await context.close();
}finally{fs.writeFileSync(new URL('release/browser-qa.json',root),JSON.stringify(report,null,2));await browser.close();srv.close();}
console.log(JSON.stringify(report,null,2));
