(function(){'use strict';
var E=window.SandEngine,R=window.SandRender,L=window.SandLevels,S=window.SandStore,$=function(id){return document.getElementById(id);},backend;
try{backend=window.localStorage;}catch(e){backend={getItem:function(){throw e;},setItem:function(){throw e;}};}
var store=S.open(backend,L),session=store.db.current||S.fresh(L[0]),level=L.find(function(l){return l.id===session.levelId;}),state=E.replay(level,session.log),selected=-1,noteMode=false,dayMode=false,modalReturn=null,tutorialStep=0;
var lessons=['数字下划线是固定线索。先找到 1，再沿箭头投递。','箭头指向一整条射线，隔着站点也能连接。','用固定号码检查中间还应经过几站。','可以先连接局部片段，再把片段接起来。','留意未连接的站点：邮路不能绕成小环。','综合号码、方向和剩余站点，串起完整邮路。'];
function save(){store.db.current=session;store.save();$('saveinfo').textContent=store.error()||'自动保存在此设备 · 无需联网';}
function render(message){
 var v=E.inspect(level,state),index=L.indexOf(level),focus=document.activeElement&&document.activeElement.getAttribute('data-cell');
 $('chapter').textContent=(dayMode?'每日来信 · ':'第'+level.chapter+'章 · ')+level.chapterName;$('serial').textContent=String(index+1).padStart(2,'0')+' / 60';$('leveltitle').textContent='第'+(index+1)+'封 · '+level.role;$('lesson').textContent=lessons[level.chapter-1];
 $('drawing').innerHTML=R.svg(level,state,selected,session.notes);$('cells').style.gridTemplateColumns='repeat('+level.size+',1fr)';$('cells').style.gridTemplateRows='repeat('+level.size+',1fr)';
 $('cells').innerHTML=state.map(function(_,i){return '<button data-cell="'+i+'" aria-label="'+R.label(level,state,i)+'" aria-pressed="'+(selected===i)+'"></button>';}).join('');
 $('linked').textContent=v.edges;$('total').textContent='/ '+(state.length-1)+' 段邮路';$('bar').style.width=(100*v.edges/(state.length-1))+'%';
 $('route').innerHTML=v.chains.map(function(chain){return '<div class="chain">'+chain.map(function(c){return (v.numbers[c]||'?')+'·'+String.fromCharCode(65+c%level.size)+(Math.floor(c/level.size)+1);}).join(' → ')+'</div>';}).join('');
 $('route-label').textContent=v.chains.length+' 个片段，最终汇成一条邮路。';$('undo').disabled=!session.log.length;$('cut').disabled=selected<0;$('note').setAttribute('aria-pressed',String(noteMode));$('note').textContent=noteMode?'● 笔记中':'○ 笔记';$('win').hidden=!v.won;$('hint').disabled=v.won;
 if(v.won){store.settle(level,session);store.flush(window.SandscriptHost);$('wintext').textContent=session.hints?'已收录邮册 · 本封使用过提示':'独立完成 ★ · 一枚新的时砂邮戳';}
 $('count').textContent=Object.keys(store.db.records).length+'/60';if(message)$('message').textContent=message;save();
 if(focus!==null&&focus!==undefined){var el=$('cells').querySelector('[data-cell="'+focus+'"]');if(el)el.focus();}
}
function action(a){if(session.log.length>=5000){$('message').textContent='本封记录已满，请撤销或重新投递';return;}var r=E.apply(level,state,a);if(r.changed){state=r.next;session.log.push(a);selected=-1;}render(r.reason);}
function cell(i){if(noteMode){var pos=session.notes.indexOf(i);if(pos<0)session.notes.push(i);else session.notes.splice(pos,1);render('笔记圆点仅作标记，不参与通关判断。');return;}
 if(selected<0){selected=i;render('已选 '+String.fromCharCode(65+i%level.size)+(Math.floor(i/level.size)+1)+'，再点虚线框落点；再点本站可取消。');}else if(selected===i){selected=-1;render('已取消选中。');}else action({type:'link',a:selected,b:i});}
$('cells').addEventListener('click',function(e){var b=e.target.closest('button[data-cell]');if(b)cell(Number(b.getAttribute('data-cell')));});
$('cells').addEventListener('keydown',function(e){var b=e.target.closest('button[data-cell]');if(!b)return;var i=Number(b.getAttribute('data-cell')),j=i;if(e.key==='ArrowRight')j=Math.min(state.length-1,i+1);else if(e.key==='ArrowLeft')j=Math.max(0,i-1);else if(e.key==='ArrowDown')j=Math.min(state.length-1,i+level.size);else if(e.key==='ArrowUp')j=Math.max(0,i-level.size);else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();action({type:'cut',a:i});return;}else if(e.key==='Escape'){selected=-1;render('已取消选中。');return;}else return;e.preventDefault();$('cells').querySelector('[data-cell="'+j+'"]').focus();});
$('undo').addEventListener('click',function(){if(session.log.length){session.log.pop();state=E.replay(level,session.log);selected=-1;render('已撤销上一条操作。提示记录保留。');}});
$('cut').addEventListener('click',function(){action({type:'cut',a:selected});});$('note').addEventListener('click',function(){noteMode=!noteMode;selected=-1;render(noteMode?'笔记模式：点击站点切换圆点。':'连线模式：先选起点，再选落点。');});
function start(l,daily){save();level=l;session=S.fresh(l);state=E.empty(l);selected=-1;noteMode=false;dayMode=!!daily;showPlay();window.scrollTo(0,0);render(daily?'每日来信来自 60 题轮换，以设备本地日期为准。':'先找到固定 1，再沿箭头连接。');}
$('next').addEventListener('click',function(){start(L[(L.indexOf(level)+1)%L.length]);});
function close(){ if($('dialogbody').querySelector('img[src^="./tutorial-"]')){store.db.seen=true;save();} $('modal').hidden=true;document.body.classList.remove('modal-open');if(modalReturn&&document.contains(modalReturn))modalReturn.focus();else $('help').focus();}
function openModal(content,actions){if($('modal').hidden)modalReturn=document.activeElement;$('dialogbody').innerHTML=content;$('dialogactions').innerHTML='';actions.forEach(function(a){var b=document.createElement('button');b.textContent=a.text;if(a.primary)b.className='primary';b.addEventListener('click',a.fn);$('dialogactions').appendChild(b);});$('modal').hidden=false;document.body.classList.add('modal-open');document.querySelector('.dialog').scrollTop=0;$('close').focus();}
$('close').addEventListener('click',close);
$('modal').addEventListener('keydown',function(e){if(e.key==='Escape'){close();return;}if(e.key==='Tab'){var nodes=Array.prototype.slice.call($('modal').querySelectorAll('button')),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
$('restart').addEventListener('click',function(){openModal('<h2 id="dialogtitle">重新投递这一封？</h2><p>当前连线会清空，已收录的邮戳保留。</p>',[{text:'继续思考',fn:close},{text:'重新开始',primary:true,fn:function(){close();start(level,dayMode);}}]);});
$('hint').addEventListener('click',function(){var path=window.SandAnswers[level.id],wrong=state.findIndex(function(b,a){return b>=0&&path[path.indexOf(a)+1]!==b;}),a,b;
 if(wrong>=0){a=wrong;b=state[a];}else for(var k=0;k<path.length-1;k++)if(state[path[k]]!==path[k+1]){a=path[k];b=path[k+1];break;}
 if(a===undefined)return;openModal('<h2 id="dialogtitle">留一点线索给你</h2><p>先看箭头射线，再用固定号码排除不合适的落点。可连接不代表一定正确。</p><p>如需具体提示，本封将记录为「提示完成」。</p>',[{text:'我再想想',fn:close},{text:'查看具体一段',primary:true,fn:function(){session.hints++;selected=a;noteMode=false;close();render(wrong>=0?'检查 '+coord(a)+' → '+coord(b)+'：这段不在最终邮路中，可先断开。':'试着连接 '+coord(a)+' → '+coord(b)+'。提示不会替你连线。');}}]);});
function coord(i){return String.fromCharCode(65+i%level.size)+(Math.floor(i/level.size)+1);}
function tutorial(step){tutorialStep=step;var texts=[['先认出固定号码','带下划线的号码不能改。箭头指出下一站的方向，终点是信箱。'],['先选起点，再选落点','这是同一封来信完成一次合法连接后的样子。箭头可以跨格，线条也可以交叉。'],['每一站，都在同一条邮路上','从 1 到最后的号码，恰好经过全部站点。固定号码要吻合，小环或漏站不能送达。']];openModal('<h2 id="dialogtitle">'+(step+1)+' / 3 · '+texts[step][0]+'</h2><img src="./tutorial-'+step+'.svg" alt="首封来信'+['初始状态，零条连接','一次合法连接后的状态','全部站点连成完整邮路的通关状态'][step]+'"><p>'+texts[step][1]+'</p><small>同一题真实状态 · sand-01 · sandscript-post-tutorial-v1</small>',[{text:step?'上一张':'跳过',fn:function(){if(step)tutorial(step-1);else finishTutorial();}},{text:step===2?'开始投递':'下一张',primary:true,fn:function(){if(step===2)finishTutorial();else tutorial(step+1);}}]);}
function finishTutorial(){store.db.seen=true;save();close();}
$('help').addEventListener('click',function(){tutorial(0);});
function showPlay(){$('play').hidden=false;$('collection').hidden=true;$('playtab').classList.add('active');$('album').classList.remove('active');}
$('playtab').addEventListener('click',showPlay);
$('daily').addEventListener('click',function(){var d=new Date(),day=Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/86400000);openModal('<h2 id="dialogtitle">今天也有一封来信</h2><p>从 60 道主线题中按设备日期轮换，每 60 天循环。进入会替换当前未完成进度。</p>',[{text:'留在本封',fn:close},{text:'拆开今日来信',primary:true,fn:function(){close();start(L[((day%60)+60)%60],true);}}]);});
function collection(){$('play').hidden=true;$('collection').hidden=false;$('playtab').classList.remove('active');$('album').classList.add('active');$('chapters').innerHTML=Array.from({length:6},function(_,c){var group=L.slice(c*10,c*10+10),done=group.filter(function(l){return !!store.db.records[l.id];}).length;return '<article class="chapter-card"><h3>'+String(c+1).padStart(2,'0')+' / '+group[0].chapterName+' <small>'+done+'/10</small></h3><p>'+lessons[c]+'</p><div class="level-grid">'+group.map(function(l){var rec=store.db.records[l.id];return '<button data-level="'+l.id+'" class="'+(rec?'done':'')+'" aria-label="第'+(L.indexOf(l)+1)+'封'+(rec?rec.session.hints?'，提示完成':'，独立完成':'，未完成')+'">'+(rec?rec.session.hints?'✓':'★':String(L.indexOf(l)+1).padStart(2,'0'))+'</button>';}).join('')+'</div></article>';}).join('');}
$('album').addEventListener('click',collection);$('chapters').addEventListener('click',function(e){var b=e.target.closest('button[data-level]');if(!b)return;var l=L.find(function(x){return x.id===b.getAttribute('data-level');});if(l.id===level.id){showPlay();return;}openModal('<h2 id="dialogtitle">拆开第'+(L.indexOf(l)+1)+'封？</h2><p>切换会替换当前未完成进度，邮册记录仍保留。</p>',[{text:'留在本封',fn:close},{text:'开始这封',primary:true,fn:function(){close();start(l);}}]);});
$('sources').addEventListener('click',function(){openModal('<h2 id="dialogtitle">规则与来源</h2><p>基于 Simon Tatham 谜题集的 Signpost（箭头序链），由 James Harvey 贡献，原型 Pfeilpfad 归功于 Janko；中文参考 ebnbin/puzzles。</p><p>本作独立实现主题、题库与界面。采用全手动连线，不自动补线。新线会替换起点旧出线与落点旧入线；方向、固定数字或小环冲突时整次操作不生效。几何交叉不影响合法性。</p><p>笔记圆点不参与判胜。撤销不撤回已收录邮戳；提示使用记录不因撤销清除。存档在本机，清理容器数据可能丢失。六章 60 题均经独立搜索验证唯一。难度为设计分组，尚待玩家反馈。</p><p>AI 辅助开发与测试。版本 1.0.0 · MIT License</p><pre>'+window.SandLicense+'</pre>',[{text:'回到邮路',primary:true,fn:close}]);});
window.addEventListener('sandscript:ready',function(){store.flush(window.SandscriptHost);});
render(store.error()||'先点起点，再点箭头方向的站点。');store.flush(window.SandscriptHost);if(!store.db.seen)tutorial(0);
})();
