import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { createLevel, solve, geometryFingerprint } from '../core.mjs';
import { generateProvenLevel, analyzeSolution } from '../generate.mjs';

const tutorial = [
  ['点火', '向右点火，回收第一枚能源芯。', '飞船一旦启动就会滑行，直到前方是舱壁。', ['######','#@..e#','#....#','#....#','#....#','######']],
  ['借墙转向', '先想好停在哪里，再决定下一次点火。', '舱壁可以当刹车，撞墙不会受损。', ['######','#@..e#','#....#','#....#','#...e#','######']],
  ['斜线航道', '尝试右下方向，穿过对角线上的能源芯。', '八个方向都可航行；斜行只检查下一格。', ['######','#@...#','#....#','#..e.#','#....#','######']],
  ['掠过星光', '沿整条航段回收能源，留意最终停靠的位置。', '能源芯不会刹车；同一航段可以连续回收多枚。', ['#######','#@e.e.#','#.....#','#.....#','#.....#','#.....#','#######']],
  ['引力停泊', '斜向停在中央引力锚，再向上寻找能源。', '引力锚强制停船，让你能在航区中途改线。', ['#######','#.....#','#..e..#','#..o..#','#.....#','#@....#','#######']],
  ['归航信标', '原点也是引力锚。把返航作为航线的一部分。', '离开起点之后，再次进入它会立刻停下。', ['#######','#ee...#','#.....#','#..@..#','#..e..#','#.....#','#######']],
  ['危险余程', '能源芯后方仍有失控反应堆，先绕到安全的一侧。', '收齐后仍须完成本次滑行；途中撞上反应堆仍然失败。', ['#######','#@.e.x#','#.....#','#..o..#','#.....#','#.....#','#######']],
  ['试航毕业', '把墙面、斜线与引力锚组合成一条完整回收路线。', '出发前看清整条航段；需要时可无限撤销。', ['#######','#e....#','#..xe.#','#..o..#','#.....#','#@..e.#','#######']],
];
const names = [
 [],
 ['折光门','边界回声','舷窗之间','切角航线','双层船坞','残骸缺口','长距折返','几何之眼'],
 ['微引力井','双锚接力','停泊顺序','中途改线','环心停靠','远近之间','交叉中继','无声枢纽'],
 ['红区边缘','危险尾迹','安全着陆','侧翼切入','余程检查','穿针航道','窄门之后','寂静雷区'],
 ['多点回收','逆向思考','错层废墟','最后一枚','内环外环','一线之隔','曲折星桥','航线编织'],
 ['深空入口','失落造船厂','无光中继','暗潮航路','反应堆群','破碎星环','引力交响','向星海进发'],
];
const briefs = [
 [],
 ['利用舱壁，把远处的能源串成回收链。','短暂停留也有价值：先规划下一段直线。','平直的边缘中，藏着跨越航区的斜线。','试着从目标的反方向推算停靠点。','不要只看最近的能源，留意整条返回路线。','缺口能改变停靠位置，也能打开新的航线。','有些能源需要先飞远，再折返回收。','综合运用八向滑行，完成这个航区的几何考验。'],
 ['引力锚是改变航线的支点。','借助多个引力锚，连续调整航向。','同样的停泊点，不同的访问顺序会改变效率。','在航区内部停下来，为下一条斜线找好角度。','先进入中心，再决定如何驶向边缘。','远处的锚点可能通向最近的能源。','把锚点视作航线网络中的中继。','选择停靠顺序，将散落能源连接起来。'],
 ['每次点火前，沿整条航段查看危险。','即使能源就在前方，也要看清它的后方。','回收之后仍需安全停靠。','从侧翼接近，绕开正面的失控反应堆。','收齐能源之后的余程同样重要。','用斜向航路穿越反应堆之间的空隙。','进入狭窄航道之前，先确认出口。','保持冷静，把高风险路线拆成安全的短段。'],
 ['能源更加分散，试着让每次折返都有收获。','从最后一枚能源倒推你的安全停靠点。','废墟让长直线分成多个层次。','提前安排最后一枚，避免在末段被迫绕路。','连接内部锚点与外围舱壁。','关键停靠点可能只隔着一格墙。','在多个转向点之间架起回收航线。','把一路积累的技巧织成完整航图。'],
 ['星图到这里变得稀疏，耐心读懂每一处停靠点。','大型残骸的缺口能成为意外的制动器。','追踪能源之间的安全交点。','多次空航也许是抵达目标必需的准备。','所有能源都在危险航区；每次停靠都要留出后路。','在破碎星环中寻找连续的安全航段。','协调多个引力锚，让复杂航线形成节奏。','最后一次远行，把整片航区重新点亮。'],
];
const lessons = ['', '借墙制动与斜向切入。', '利用锚点建立中途转向路线。', '检查完整航段，避免收齐后的致命余程。', '预先安排能源访问顺序与无收获的定位航段。', '综合规划墙、锚点、反应堆与多点能源的访问顺序。'];
const levels = [];
const seen = new Set();
for (let i = 0; i < tutorial.length; i++) {
 const [name, briefing, lesson, grid] = tutorial[i];
 const base = createLevel({ id: `campaign-${String(i+1).padStart(2,'0')}`, name, chapter: 0, number: i+1, campaignIndex:i, mode:'campaign', briefing, lesson, grid, seed:`handcrafted-${i+1}` });
 const proof = solve(base);
 if (!proof.path) throw new Error(`Unsolvable tutorial ${i+1}`);
 const level={...base, par:proof.path.length, solution:proof.path, proof:{algorithm:'BFS',visited:proof.visited,shortest:true},metrics:analyzeSolution(base,proof.path)};
 levels.push(level); seen.add(geometryFingerprint(level));
 console.log(`${i+1} ${name} par=${level.par} ${proof.path.join(',')}`);
}
for (let chapter=1;chapter<6;chapter++) {
 for (let i=0;i<8;i++) {
  const number=chapter*8+i+1;
  const minPar=[0,4,6,7,9,12][chapter]+Math.floor(i/3);
  const level=generateProvenLevel(`star-drift-campaign-v1-${number}`,chapter,{attempts:3000,minPar,maxPar:minPar+3,
   reject:l=>seen.has(geometryFingerprint(l))});
  if(!level) throw new Error(`No candidate for ${number}`);
  const final={...level,id:`campaign-${String(number).padStart(2,'0')}`,name:names[chapter][i],chapter,number,campaignIndex:number-1,mode:'campaign',briefing:briefs[chapter][i],lesson:lessons[chapter]};
  levels.push(final); seen.add(geometryFingerprint(final));
  console.log(`${number} ${final.name} par=${final.par} attempts=${level.generation.attempt+1} visited=${level.proof.visited}`);
 }
}
const minimal=levels.map(({start,energy,mines,stops,width,height,...level})=>level);
const target = new URL('../levels.mjs', import.meta.url);
const footer = existsSync(target) ? readFileSync(target,'utf8').split('// END GENERATED CAMPAIGN')[1] ?? '' : '';
writeFileSync(target, `// Generated by tools/generate-levels.mjs. Handcrafted tutorial + deterministically curated layouts.\nconst CAMPAIGN_DATA = ${JSON.stringify(minimal,null,2)};\n// END GENERATED CAMPAIGN${footer}`);
writeFileSync(new URL('../level-report.json', import.meta.url),JSON.stringify({generatorVersion:1,levelCount:levels.length,distinctUnderRotationAndReflection:seen.size,proof:'Breadth-first search in position × remaining energy; no deaths accepted; exact shortest successful slide count.',chapters:Array.from({length:6},(_,chapter)=>({chapter,count:8,minPar:Math.min(...levels.filter(l=>l.chapter===chapter).map(l=>l.par)),maxPar:Math.max(...levels.filter(l=>l.chapter===chapter).map(l=>l.par))})),levels:levels.map(({id,name,chapter,par,seed,proof,metrics})=>({id,name,chapter,par,seed,proof,metrics}))},null,2)+'\n');
