import test from 'node:test';import assert from 'node:assert/strict';import {initial,setMark,beam,evaluate,replay,validateLevel,clueAt} from '../core.mjs';import {LEVELS} from '../levels.mjs';import {solve,inspect} from '../scripts/oracle.mjs';import {tutorialFrames} from '../view.mjs';
test('48 puzzles: only visible clues, complete second-solution search and independent predicate',()=>{assert.equal(LEVELS.length,48);for(const l of LEVELS){assert(validateLevel(l));const puzzle={width:l.width,height:l.height,clues:l.clues};const p=solve(puzzle);assert.equal(p.count,1,l.id);assert.equal(p.exhausted,true,l.id);assert.equal(p.cutoff,false);assert.deepEqual(p.solutions[0],l.solution,l.id);assert(inspect(puzzle,l.solution));assert(evaluate(l,{marks:l.solution}).complete);assert.equal(p.trace.length,l.width*l.height-l.clues.length);}});
test('every logical deduction is forced by original clues; notes are not assumed',()=>{for(const l of LEVELS){const assumed=[];for(const t of l.logic){const reverse=solve({width:l.width,height:l.height,clues:l.clues},{assumptions:assumed.concat([[t.cell,1-t.mark]])});assert.equal(reverse.count,0,l.id+':'+t.cell);assert(reverse.exhausted);assumed.push([t.cell,t.mark]);}}});
test('all 3x3 layouts: oracle exhaustive cross-check, including singleton possible-white islands',()=>{const w=3,h=3;const fixtures=[[[0,3],[4,3],[8,3]],[[1,3],[3,3],[5,3]],[[0,5],[8,5]],[[1,2],[6,2]],[[0,2],[5,3]],[[4,1]],[[2,4],[6,4]]];for(const clues of fixtures){const l={width:w,height:h,clues};const expected=[];for(let m=0;m<512;m++){const a=Array.from({length:9},(_,i)=>(m>>i)&1);if(inspect(l,a))expected.push(a.join(''));}const p=solve(l,{limit:1000});assert(p.exhausted);assert.deepEqual(p.solutions.map(a=>a.join('')).sort(),expected.sort(),JSON.stringify(clues));}});
test('production rays include self once, penetrate clue and notes, stop at first black',()=>{const l={width:5,height:5,clues:[[12,9],[13,9],[0,9]]};let s=initial(l);assert.equal(beam(l,s.marks,12).count,9);assert(beam(l,s.marks,12).cells.includes(13));s=setMark(l,s,11,0);assert.equal(s.moves,0);assert.equal(beam(l,s.marks,12).count,9);s=setMark(l,s,14,1);assert.equal(beam(l,s.marks,12).count,8);assert(!beam(l,s.marks,12).cells.includes(14));assert.equal(s.moves,1);assert.equal(setMark(l,s,12,1),null);assert.equal(setMark(l,s,25,1),null);assert.equal(setMark(l,s,14,1),null);});
test('diagonal black permitted, orthogonal black forbidden; accurate readings do not override disconnection',()=>{const l=LEVELS[26],bad={marks:l.disconnectedExample},e=evaluate(l,bad);assert(e.readings.every(b=>b.count===b.target));assert.equal(e.pairs.length,0);assert(e.groups.length>1);assert(!e.complete);assert(!inspect(l,bad.marks));const plain={width:5,height:5,clues:[[24,9]]},m=Array(25).fill(-1);m[24]=0;m[6]=1;m[12]=1;assert.equal(evaluate(plain,{marks:m}).pairs.length,0);m[7]=1;assert(evaluate(plain,{marks:m}).pairs.length>0);});
test('unknown and white notes are rule-equivalent; all levels can finish using black actions only',()=>{for(const l of LEVELS){let s=initial(l);l.solution.forEach((v,i)=>{if(v)s=setMark(l,s,i,1);});assert(evaluate(l,s).complete);assert(s.marks.includes(-1));assert.equal(s.moves,l.solution.filter(Boolean).length);const dotted={marks:s.marks.map(v=>v===-1?0:v),moves:s.moves};assert(evaluate(l,dotted).complete);}});
test('same certified tutorial puzzle: initial, one legal black placement, completed without filling dots',()=>{const f=tutorialFrames(LEVELS[0]);assert(!f[0].complete);assert(!f[1].complete);assert(f[2].complete);assert.equal(f[1].state.moves,1);assert.equal(f[1].state.marks.filter(v=>v===1).length,1);assert(f[2].state.marks.includes(-1));assert.notEqual(f[0].reading.count,f[1].reading.count);assert.equal(f[2].reading.count,f[2].reading.target);});
test('clue validity and timeline rejects illegal or forged state',()=>{const l=LEVELS[0];assert.equal(replay(l,[{cell:l.clues[0][0],mark:1,selected:l.clues[0][0]}]),null);assert.equal(replay(l,[{cell:99,mark:1,selected:l.clues[0][0]}]),null);assert.equal(validateLevel({...l,clues:[[0,1],[0,2],[3,8]]}),false);assert.equal(evaluate(l,{marks:l.solution.map(()=>2)}).invalid,true);});
