import test from 'node:test';import assert from 'node:assert/strict';import {LEVELS} from '../levels.mjs';import {fresh,restore,ensure,state,mark,undo,restart,settle,KEY,hint} from '../session.mjs';import {backend,commit} from '../storage.mjs';import {evaluate} from '../core.mjs';
const l=LEVELS[0];function finish(d,lvl=l){ensure(lvl,d);lvl.solution.forEach((v,i)=>{if(v)mark(lvl,d,i,1);});return settle(LEVELS,lvl,d);}
test('notes, full undo selected state, restart and refresh replay',()=>{const d=fresh(LEVELS),r=ensure(l,d),i=l.logic[0].cell;const before=r.selected;mark(l,d,i,0);assert.equal(state(l,r).moves,0);r.selected=l.clues[1][0];undo(l,d);assert.equal(r.selected,before);assert.equal(state(l,r).marks[i],-1);mark(l,d,i,1);const restored=restore(LEVELS,JSON.parse(JSON.stringify(d)));assert.deepEqual(state(l,ensure(l,restored)),state(l,r));restart(l,d);assert.equal(state(l,ensure(l,d)).moves,0);});
test('completion id and first reward dedup: notes after completion, replay, damaged layout and new run',()=>{const d=fresh(LEVELS),event=finish(d);assert(event);assert.equal(event.generatorVersion,l.generatorVersion);assert.equal(event.seed,l.seed);assert.equal(event.clueHash,l.clueHash);assert.equal(d.xp,10);const id=ensure(l,d).id;assert.equal(settle(LEVELS,l,d),null);const white=l.solution.findIndex((v,i)=>!v&&!l.clues.some(c=>c[0]===i));mark(l,d,white,0);assert.equal(ensure(l,d).id,id);assert.equal(settle(LEVELS,l,d),null);let restored=restore(LEVELS,JSON.parse(JSON.stringify(d)));assert.equal(restored.xp,10);const black=l.solution.indexOf(1);mark(l,restored,black,-1);assert.notEqual(ensure(l,restored).id,id);assert(!evaluate(l,state(l,ensure(l,restored))).complete);mark(l,restored,black,1);assert.equal(settle(LEVELS,l,restored),null);assert.equal(restored.xp,10);assert.equal(restored.evidence.length,1);restart(l,restored);finish(restored);assert.equal(restored.xp,10);});
test('forged booleans, xp, claims, malformed actions, tutorial upgrade rejected without wiping earned progress',()=>{const d=fresh(LEVELS);finish(d);const raw=JSON.parse(JSON.stringify(d));raw.xp=999;raw.claims=['fake'];raw.runs[l.id].completed=false;raw.tutorialVersion='old';raw.seenTutorial=true;let x=restore(LEVELS,raw);assert.equal(x.xp,10);assert.equal(x.seenTutorial,false);assert.equal(ensure(l,x).completed,true);raw.evidence[0].run.actions=[];x=restore(LEVELS,raw);assert.equal(x.xp,0);raw.runs[l.id].actions[0].cell=999;assert.equal(restore(LEVELS,raw).runs[l.id],undefined);});
test('six chapter badges derive from verified distinct completions only',()=>{const d=fresh(LEVELS);LEVELS.forEach(l=>finish(d,l));assert.equal(d.xp,480);assert.equal(d.claims.filter(c=>c.includes(':chapter:')).length,6);assert.equal(restore(LEVELS,d).xp,480);});
test('highest hints recorded, wrong white notes not trusted, original-chain hint result',()=>{const d=fresh(LEVELS),r=ensure(l,d),h=hint(l,r,2);assert(h.originalOnly);assert(l.logic.some(t=>t.cell===h.cell&&t.mark===h.mark));assert(h.text.length);const black=l.solution.indexOf(1);mark(l,d,black,0);let steps=0;while(!evaluate(l,state(l,r)).complete&&steps++<100){const next=hint(l,r,3);assert(next);mark(l,d,next.cell,next.mark);}assert(evaluate(l,state(l,r)).complete);});
test('persist before host, same-id retry, native storage 9.46 and web fallback; failed native never silently splits storage',async()=>{const d=fresh(LEVELS),event=finish(d),calls=[],host=async e=>{calls.push(e.completionId);throw Error('offline');};const store={write:async x=>{calls.push('saved:'+x.xp);}};assert((await commit(store,d,host)).ok);assert.equal(calls[0],'saved:10');await commit(store,d,host);assert.equal(calls.filter(c=>c===event.completionId).length,2);assert.equal(d.outbox.length,1);const r=await commit({write:async()=>{throw Error('disk');}},d,async()=>calls.push('bad'));assert(!r.ok);assert(!calls.includes('bad'));let saved=null;const native=await backend({xhs:{launchOptions:{miniToolEnv:{buildVersion:9462004}},miniTool:{getStorage:async()=>({data:saved}),setStorage:async v=>{saved=v.data;}}},localStorage:{setItem:()=>assert.fail('web should not be used')}});assert.equal(native.kind,'native-9.46');await native.write(d);assert.equal((await native.read()).xp,10);let webkey=null;const web=await backend({localStorage:{setItem:(k,v)=>{webkey=k;saved=v;},getItem:()=>saved}});await web.write(d);assert.equal(webkey,KEY);assert.equal(web.kind,'web-fallback');});

test('4096 action boundary preserves current state and refresh; no silent reset',()=>{const d=fresh(LEVELS),r=ensure(l,d),i=l.logic[0].cell;for(let k=0;k<4096;k++)assert(mark(l,d,i,k%2?-1:0));const before=state(l,r);assert.equal(mark(l,d,i,before.marks[i]===0?-1:0),false);assert.deepEqual(state(l,r),before);assert.deepEqual(state(l,ensure(l,restore(LEVELS,d))),before);});
test('1000 identical replays are compact; later first completion and lower hints survive restore',()=>{const d=fresh(LEVELS);ensure(l,d).hintLevel=3;finish(d);for(let k=0;k<1000;k++){restart(l,d);ensure(l,d).hintLevel=3;finish(d);}assert.equal(d.evidence.length,1);finish(d,LEVELS[1]);assert.equal(restore(LEVELS,d).xp,20);restart(l,d);ensure(l,d).hintLevel=0;assert(finish(d));assert.equal(d.evidence.length,3);assert.equal(restore(LEVELS,d).evidence.length,3);assert.equal(d.outbox.length,3);});
