import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import assert from 'node:assert/strict';
const root=new URL('../dist/xhs/',import.meta.url);const html=fs.readFileSync(new URL('index.html',root),'utf8'),js=fs.readFileSync(new URL('app.js',root),'utf8'),css=fs.readFileSync(new URL('styles.css',root),'utf8');
const forbidden=[/\bfetch\s*\(/,/XMLHttpRequest/,/new\s+(Worker|SharedWorker|WebSocket|EventSource|RTCPeerConnection|Function)\s*\(/,/\beval\s*\(/,/navigator\.(serviceWorker|clipboard|geolocation|bluetooth|usb|hid|serial|credentials|locks|connection|getBattery)/,/WebAssembly/,/window\.(open|prompt)\s*\(/,/localStorage\.clear/,/location\.(href\s*=|assign\s*\()/,/\b(import|export)\s/,/\?\./,/\?\?/,/replaceAll\s*\(/,/structuredClone\s*\(/,/Object\.hasOwn\s*\(/];
for(const re of forbidden)assert.ok(!re.test(js),'Forbidden JS '+re);
assert.ok(!/<script(?![^>]*src=)[^>]*>/i.test(html),'inline script');assert.ok(!/\bon\w+\s*=|type=["']module|<iframe|<object|<base|javascript:|target=["']_blank/i.test(html));assert.ok(!/url\(\s*["']?https?:|@import/i.test(css));assert.ok(!/(clamp|min|max)\(|aspect-ratio|\binset:|:has\(|[;{]gap:|color-mix|\bdvh\b/.test(css),'CSS baseline regression');
const refs=[...html.matchAll(/(?:src|href)="(\.\/[^"#]+)"/g),...js.matchAll(/src=\\?"(\.\/assets\/[^"+']+)\\?"/g)].map(x=>x[1]);for(const ref of refs)assert.ok(fs.existsSync(new URL(ref,root)),'missing '+ref);
const zip=fs.readFileSync(new URL('../dist/season-dye-journey-xhs.zip',import.meta.url));assert.ok(zip.length<=10*1024*1024);let n=0,offset=0,expanded=0,names=[];
while(zip.readUInt32LE(offset)===0x04034b50){const size=zip.readUInt32LE(offset+18),rawSize=zip.readUInt32LE(offset+22),len=zip.readUInt16LE(offset+26),extra=zip.readUInt16LE(offset+28),name=zip.subarray(offset+30,offset+30+len).toString();assert.ok(/\.(html|css|js|png|svg|json|webp)$/.test(name),name);assert.ok(!/\.\.|node_modules|\.map$/.test(name));const data=zip.subarray(offset+30+len+extra,offset+30+len+extra+size),raw=zlib.inflateRawSync(data);assert.equal(raw.length,rawSize);assert.deepEqual(raw,fs.readFileSync(new URL(name,root)));names.push(name);expanded+=rawSize;offset+=30+len+extra+size;n++;}
assert.ok(names.includes('index.html'));assert.equal(names.filter(n=>n.endsWith('.html')).length,1);assert.ok(names.includes('assets/icon.png'));
const result={passed:true,files:n,zipBytes:zip.length,expandedBytes:expanded,externalResources:0,classicScript:true,forbiddenCapabilities:0,checks:'Offline paths, JS/CSS baseline scan, ZIP entries and byte equality; Chrome61 device not run'};fs.writeFileSync(new URL('../release/zip-audit.json',import.meta.url),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
