import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import http from 'node:http';
import {pathToFileURL,fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const {chromium}=process.env.DYE_PLAYWRIGHT_MODULE?await import(pathToFileURL(process.env.DYE_PLAYWRIGHT_MODULE).href):await import('playwright');
const browser=await chromium.launch(process.env.DYE_CHROME?{headless:true,executablePath:process.env.DYE_CHROME}:{headless:true,channel:'chrome'});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.json':'application/json'};
const server=http.createServer((req,res)=>{let url=decodeURIComponent(req.url.split('?')[0]);let file=path.join(root,'dist/xhs',url==='/'?'index.html':url);if(!file.startsWith(path.join(root,'dist/xhs')))return res.end();try{res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('missing');}});
await new Promise(resolve=>server.listen(4188,'127.0.0.1',resolve));
const base='http://127.0.0.1:4188',errors=[],reports=[],scenarios=[];
const K='mini-polish:season-dye-journey:v1:journal';
async function fresh(width=390,height=844,options={}){const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:2,isMobile:width<701,hasTouch:width<701,...options});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push('HTTP '+r.status()+' '+r.url());});await page.goto(base);return{context,page};}
async function act(page,action,extra=''){const locator=page.locator('[data-action="'+action+'"]'+extra).first();await locator.click();}
async function skip(page){await act(page,'tutorial-skip');}
async function getSession(page){return page.evaluate(k=>JSON.parse(localStorage.getItem(k)).session.state,K);}
async function geometry(page,name){const data=await page.evaluate(()=>{const board=document.querySelector('.loom-area'),tools=document.querySelector('.tool-row'),buttons=[...document.querySelectorAll('.dye-button')];const b=board&&board.getBoundingClientRect(),t=tools&&tools.getBoundingClientRect();return{width:innerWidth,height:innerHeight,documentWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth,board:b?{top:b.top,bottom:b.bottom,width:b.width}:null,tools:t?{top:t.top,bottom:t.bottom}:null,palette:buttons.map(el=>{const r=el.getBoundingClientRect();return{width:r.width,height:r.height};})};});assert.ok(data.documentWidth<=data.width&&data.bodyWidth<=data.width,'horizontal overflow '+name);if(data.tools)assert.ok(data.tools.bottom<=data.height,'tools below screen '+name);for(const b of data.palette){assert.ok(b.width>=44&&b.height>=44,'touch target below 44 '+name);}reports.push({name,...data});}
try{
 const {page,context}=await fresh();
 assert.equal(await page.locator('[role=dialog]').count(),1);await page.locator('.tutorial-picture').waitFor({state:'visible'});await page.screenshot({path:path.join(root,'release/tutorial-mobile.png')});
 for(let i=0;i<3;i++){await page.waitForFunction(()=>{const el=document.querySelector('.tutorial-picture');return el&&el.complete&&el.naturalWidth>0;});const img=await page.locator('.tutorial-picture').evaluate(el=>({loaded:el.complete&&el.naturalWidth>0,width:el.naturalWidth,height:el.naturalHeight}));assert.deepEqual(img,{loaded:true,width:720,height:720});await act(page,'tutorial-next');}
 assert.equal(await page.locator('[role=dialog]').count(),0);assert.equal((await getSession(page)).timeline.length,0);scenarios.push('First-launch three-picture tutorial fully viewed and playable');
 await act(page,'home');await page.screenshot({path:path.join(root,'release/home-mobile.png'),fullPage:true});await act(page,'continue');
 await act(page,'dye','[data-color="0"]');assert.equal((await getSession(page)).timeline.length,0);
 await act(page,'dye','[data-color="2"]');assert.equal((await getSession(page)).timeline.length,1);assert.match(await page.locator('.live-note').innerText(),/未接入新格/);await act(page,'undo');assert.equal((await getSession(page)).timeline.length,0);scenarios.push('Same colour no-op; zero expansion counts; undo restores');
 await act(page,'hint');assert.match(await page.locator('.live-note').innerText(),/接入 8 格/);await page.locator('[data-action="dye"][data-color="1"]').tap();await page.screenshot({path:path.join(root,'release/play-mobile.png')});
 const before=await getSession(page);await page.reload();await act(page,'continue');assert.deepEqual(await getSession(page),before);scenarios.push('Touch move, useful current-state hint and refresh replay preserve run');
 await act(page,'home');await act(page,'tutorial');for(let i=0;i<3;i++)await act(page,'tutorial-next');assert.deepEqual(await getSession(page),before);scenarios.push('Rewatch tutorial preserves existing unfinished run');
 await page.locator('[data-action="dye"][data-color="2"]').tap();assert.match(await page.locator('[role=dialog]').innerText(),/合幅/);await page.screenshot({path:path.join(root,'release/win-mobile.png')});
 const won=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),K);assert.equal(won.evidence.length,1);assert.equal(won.evidence[0].claims.length,4);
 await act(page,'close');await act(page,'undo');assert.notEqual((await getSession(page)).runId,won.session.state.runId);await act(page,'dye','[data-color="2"]');const branched=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),K);assert.equal(branched.evidence.length,2);assert.equal(branched.evidence[1].claims.length,0);scenarios.push('Win, branch by undo and win again keep stable old rewards and new run identity');
 await act(page,'close');await act(page,'restart');await act(page,'restart-confirm');await page.keyboard.press('2');await page.keyboard.press('3');assert.match(await page.locator('[role=dialog]').innerText(),/合幅/);const replay=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),K);assert.equal(replay.evidence.length,3);assert.equal(replay.evidence[2].claims.length,0);scenarios.push('Restart and keyboard solve; repeat completion cannot farm claims');
 await act(page,'close');await act(page,'home');
 const firstChapter=await page.evaluate(()=>Dye.Levels.all.slice(1,12).map(l=>({id:l.id,path:l.referencePath})));
 for(const l of firstChapter){await act(page,'chapter','[data-id="1"]');await act(page,'level','[data-id="'+l.id+'"]');for(const c of l.path)await act(page,'dye','[data-color="'+c+'"]');await act(page,'close');await act(page,'home');}
 await act(page,'collection');assert.equal(await page.locator('.swatch').count(),12);await page.screenshot({path:path.join(root,'release/collection-mobile.png')});await act(page,'close');
 await act(page,'chapter','[data-id="4"]');await act(page,'level','[data-id="c4-07"]');const middle=await page.evaluate(()=>Dye.Levels.get('c4-07').referencePath.slice(0,3));for(const c of middle)await act(page,'dye','[data-color="'+c+'"]');await page.screenshot({path:path.join(root,'release/play-midgame.png')});await act(page,'home');
 scenarios.push('First 12 main levels solved through actual palette buttons; populated collection and midgame screenshot');
 await act(page,'daily');const daily=await getSession(page);assert.ok(daily.levelId.startsWith('daily:'));await act(page,'home');await act(page,'workshop');await page.locator('#seed').fill('山间微雨');await page.locator('#size').selectOption('10');await page.locator('#colours').selectOption('6');await act(page,'workshop-start');assert.equal(await page.locator('.dye-button').count(),6);await geometry(page,'390x844-workshop');await page.screenshot({path:path.join(root,'release/workshop-mobile.png')});scenarios.push('Daily, seed workshop, collection and 10×10 six-dye interaction');
 await context.close();
 for(const [w,h] of [[320,720],[358,720],[359,720],[360,720],[390,739],[390,740],[390,741],[699,844],[700,844],[701,844],[702,844],[1280,720]]){
   const p=await fresh(w,h);await skip(p.page);await geometry(p.page,w+'x'+h+'-home');
   if(w===1280)await p.page.screenshot({path:path.join(root,'release/home-desktop.png'),fullPage:true});
   await act(p.page,'chapter','[data-id="6"]');await act(p.page,'level','[data-id="c6-12"]');await geometry(p.page,w+'x'+h+'-last-level');
   if(w===320||w===1280)await p.page.screenshot({path:path.join(root,'release/play-'+w+'.png')});
   await act(p.page,'hint');assert.equal(await p.page.locator('.hinted').count(),1);await p.page.locator('.hinted').click();assert.equal((await getSession(p.page)).timeline.length,1);
   await act(p.page,'tutorial');assert.equal(await p.page.locator('body.modal-open').count(),1);await p.page.keyboard.press('Escape');assert.equal(await p.page.locator('body.modal-open').count(),0);
   await p.context.close();
 }
 scenarios.push('12 viewport/breakpoint combinations: zero horizontal overflow, all dye targets ≥44px, tools entirely visible, hint move and tutorial Escape');
 const fail=await fresh();await skip(fail.page);await act(fail.page,'continue');await act(fail.page,'dye','[data-color="1"]');await fail.page.evaluate(k=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key===k&&JSON.parse(value).evidence.length)throw new Error('simulated quota');return original.call(this,key,value);};},K);await act(fail.page,'dye','[data-color="2"]');assert.match(await fail.page.locator('[role=dialog]').innerText(),/暂未保存/);assert.equal((await fail.page.evaluate(k=>JSON.parse(localStorage.getItem(k)),K)).evidence.length,0);scenarios.push('Final atomic persistence failure is visibly disclosed in win dialog, no false saved claim');await fail.context.close();
 const lost=await fresh();await skip(lost.page);await lost.page.evaluate(k=>{let state=Dye.Engine.create(Dye.Levels.all[0],'qa-interrupted-win');for(const c of [1,2])state=Dye.Engine.move(state,Dye.Levels.all[0],c).state;Dye.Storage.create(localStorage,Dye.Levels.get).saveSession(state);},K);await lost.page.reload();const recovered=await lost.page.evaluate(k=>JSON.parse(localStorage.getItem(k)),K);assert.equal(recovered.evidence.length,1);await lost.page.reload();assert.equal((await lost.page.evaluate(k=>JSON.parse(localStorage.getItem(k)),K)).evidence.length,1);scenarios.push('Interrupted won session is settled idempotently on reload');await lost.context.close();
 const reduced=await fresh(320,720,{reducedMotion:'reduce'});await skip(reduced.page);await act(reduced.page,'continue');await act(reduced.page,'dye','[data-color="1"]');assert.equal(await reduced.page.locator('.dye-spread').first().evaluate(el=>getComputedStyle(el).animationName),'none');await geometry(reduced.page,'reduced-motion-320');await reduced.context.close();scenarios.push('Reduced-motion state remains readable with no spread animation');
 const full=await fresh();await skip(full.page);
 await full.page.evaluate(()=>{const store=Dye.Storage.create(localStorage,Dye.Levels.get),level=Dye.Levels.all[0];for(let i=0;i<256;i++){let st=Dye.Engine.create(level,'qa-queue-'+i);for(const c of level.referencePath)st=Dye.Engine.move(st,level,c).state;store.saveCompletion(st);}});
 await full.page.reload();await act(full.page,'chapter','[data-id="1"]');await act(full.page,'level','[data-id="c1-02"]');const route=await full.page.evaluate(()=>Dye.Levels.get('c1-02').referencePath);for(const c of route)await act(full.page,'dye','[data-color="'+c+'"]');assert.match(await full.page.locator('[role=dialog]').innerText(),/本地布样已保存/);const journal=await full.page.evaluate(k=>JSON.parse(localStorage.getItem(k)),K);assert.equal(journal.outbox.length,256);assert.equal(journal.evidence.length,257);await full.context.close();scenarios.push('Full sync queue still saves new campaign collection and truthfully displays local-only status');
 const cover=await browser.newPage({viewport:{width:1080,height:1440},deviceScaleFactor:1});await cover.goto(pathToFileURL(path.join(root,'release/cover.html')).href);await cover.screenshot({path:path.join(root,'release/cover.png')});await cover.close();
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(root,'release/browser-qa.json'),JSON.stringify({passed:true,browser:await browser.version(),device:'Chrome desktop with mobile viewport/touch emulation, no physical device',scenarios,geometry:reports,errors},null,2));console.log(JSON.stringify({passed:true,scenarios:scenarios.length,viewports:reports.length,browser:await browser.version(),errors},null,2));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
