// Offline authoring tool. Running this replaces only this game's levels.mjs.
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { certify } from './proof.mjs';
import { readings } from './engine.mjs';

const chapters = [
  { title: '浅层开窗', width: 4, height: 4, minMines: 2, maxMines: 3, minMoves: 2 },
  { title: '旗记勘界', width: 5, height: 5, minMines: 4, maxMines: 6, minMoves: 5 },
  { title: '邻域相减', width: 6, height: 5, minMines: 5, maxMines: 7, minMoves: 8, subset: 1 },
  { title: '双窗拼接', width: 6, height: 6, minMines: 6, maxMines: 9, minMoves: 10, subset: 1 },
  { title: '长层勘探', width: 6, height: 7, minMines: 7, maxMines: 10, minMoves: 13, subset: 2 },
  { title: '标本交接', width: 6, height: 8, minMines: 8, maxMines: 12, minMoves: 16, subset: 2 },
];
const names = [
  ['树脂初光','砂面八邻','琥珀开窗','北缘印迹','零层回声','浅坑读数','石英边角','薄层勘线','松脂暗格','第一枚标本'],
  ['小旗试桩','苔痕边线','双读核对','标桩手记','狭隙气泡','封土猜想','数字已满','枝影警戒','安全余地','旗记交接'],
  ['两片窗口','叶脉差集','折叠边界','两个窗口之间','共享砂格','一线之差','边角相减','树皮残痕','邻域对照','叶脉入册'],
  ['气泡双窗','边界转译','相邻地层','第三处读数','重叠印迹','全盘余量','砂线回流','两侧核验','深色气泡','双窗汇合'],
  ['长层起点','剖面折返','深砂之下','远端回应','一条叶脉','多轮标记','上下传递','暗层清点','长层回路','昆虫剪影'],
  ['层积开卷','旧线新证','全盘勘界','隔层回响','树脂封缄','交叉读数','最后的气泡','深层传讯','所有安全格','透明层积座'],
];
function random(seed) {
  let state = seed >>> 0;
  return () => { state ^= state << 13; state ^= state >>> 17; state ^= state << 5; return (state >>> 0) / 4294967296; };
}
function canonical(width, height, mines) {
  const transforms = width === height ? 8 : 4;
  const forms = [];
  for (let t = 0; t < transforms; t++) {
    const mapped = mines.map(i => {
      let x = i % width, y = Math.floor(i / width);
      if (t & 1) x = width - 1 - x;
      if (t & 2) y = height - 1 - y;
      if (t & 4) [x, y] = [y, x];
      return y * width + x;
    }).sort((a, b) => a - b);
    forms.push(mapped.join(','));
  }
  return `${width}x${height}:${forms.sort()[0]}`;
}

const levels = [], seen = new Set();
for (let ch = 0; ch < chapters.length; ch++) {
  const spec = chapters[ch], rng = random(0xA4B3C2 + ch * 91283);
  let attempts = 0;
  while (levels.filter(level => level.chapter === ch + 1).length < 10 && attempts < 120000) {
    attempts++;
    const count = spec.width * spec.height;
    const mineCount = spec.minMines + Math.floor(rng() * (spec.maxMines - spec.minMines + 1));
    const positions = Array.from({ length: count }, (_, i) => i);
    for (let i = positions.length - 1; i > 0; i--) {
      const j = Math.floor(rng() * (i + 1));
      [positions[i], positions[j]] = [positions[j], positions[i]];
    }
    const mines = positions.slice(0, mineCount).sort((a, b) => a - b);
    const key = canonical(spec.width, spec.height, mines);
    if (seen.has(key)) continue;
    const skeleton = { width: spec.width, height: spec.height, mines, seed: attempts + ch * 100000 };
    const grid = readings(skeleton);
    const starts = grid.flatMap((n, i) => n === 0 ? [i] : []);
    if (!starts.length) continue;
    const firstSafe = starts[Math.floor(rng() * starts.length)];
    const candidate = { ...skeleton, firstSafe };
    const proof = certify(candidate);
    if (!proof || proof.timeline.length < spec.minMoves || proof.counts.subset < (spec.subset ?? 0)) continue;
    if (ch < 2 && (proof.counts.subset || proof.counts.total || proof.counts.enumeration)) continue;
    if (ch === 2 && proof.counts.enumeration) continue;
    if (ch === 3 && !(proof.counts.total || proof.counts.enumeration)) continue;
    if (ch === 5 && !proof.counts.enumeration) continue;
    const ordinal = levels.filter(level => level.chapter === ch + 1).length;
    levels.push({ id: `amber-${String(levels.length + 1).padStart(2, '0')}`, chapter: ch + 1,
      title: names[ch][ordinal], ...candidate,
      certificate: { moves: proof.timeline.length, methods: proof.counts } });
    seen.add(key);
  }
  if (levels.filter(level => level.chapter === ch + 1).length !== 10) throw new Error(`Chapter ${ch + 1}: only ${levels.length - ch * 10} levels after ${attempts} attempts`);
  console.log(`Chapter ${ch + 1}: 10 certified levels in ${attempts} candidates`);
}
const target = fileURLToPath(new URL('./levels.mjs', import.meta.url));
await writeFile(target, `// Generated by generate.mjs; each fixed starting point was solved from public readings.\nexport const CHAPTERS = ${JSON.stringify(chapters.map(({ title }) => title), null, 2)};\nexport const LEVELS = ${JSON.stringify(levels, null, 2)};\nexport const levelById = id => LEVELS.find(level => level.id === id) || LEVELS[0];\n`);
console.log(`Wrote ${levels.length} levels`);
