// Generated by generate.mjs; each fixed starting point was solved from public readings.
export const CHAPTERS = [
  "浅层开窗",
  "旗记勘界",
  "邻域相减",
  "双窗拼接",
  "长层勘探",
  "标本交接"
];
export const LEVELS = [
  {
    "id": "amber-01",
    "chapter": 1,
    "title": "树脂初光",
    "width": 4,
    "height": 4,
    "mines": [
      6,
      15
    ],
    "seed": 10,
    "firstSafe": 12,
    "certificate": {
      "moves": 6,
      "methods": {
        "single": 5,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-02",
    "chapter": 1,
    "title": "砂面八邻",
    "width": 4,
    "height": 4,
    "mines": [
      2,
      6
    ],
    "seed": 15,
    "firstSafe": 12,
    "certificate": {
      "moves": 5,
      "methods": {
        "single": 4,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-03",
    "chapter": 1,
    "title": "琥珀开窗",
    "width": 4,
    "height": 4,
    "mines": [
      9,
      14
    ],
    "seed": 31,
    "firstSafe": 2,
    "certificate": {
      "moves": 7,
      "methods": {
        "single": 6,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-04",
    "chapter": 1,
    "title": "北缘印迹",
    "width": 4,
    "height": 4,
    "mines": [
      2,
      7
    ],
    "seed": 38,
    "firstSafe": 4,
    "certificate": {
      "moves": 4,
      "methods": {
        "single": 3,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-05",
    "chapter": 1,
    "title": "零层回声",
    "width": 4,
    "height": 4,
    "mines": [
      3,
      14
    ],
    "seed": 47,
    "firstSafe": 12,
    "certificate": {
      "moves": 6,
      "methods": {
        "single": 5,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-06",
    "chapter": 1,
    "title": "浅坑读数",
    "width": 4,
    "height": 4,
    "mines": [
      10,
      15
    ],
    "seed": 80,
    "firstSafe": 12,
    "certificate": {
      "moves": 4,
      "methods": {
        "single": 3,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-07",
    "chapter": 1,
    "title": "石英边角",
    "width": 4,
    "height": 4,
    "mines": [
      10,
      14,
      15
    ],
    "seed": 96,
    "firstSafe": 4,
    "certificate": {
      "moves": 3,
      "methods": {
        "single": 2,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-08",
    "chapter": 1,
    "title": "薄层勘线",
    "width": 4,
    "height": 4,
    "mines": [
      0,
      4,
      13
    ],
    "seed": 140,
    "firstSafe": 3,
    "certificate": {
      "moves": 6,
      "methods": {
        "single": 5,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-09",
    "chapter": 1,
    "title": "松脂暗格",
    "width": 4,
    "height": 4,
    "mines": [
      10,
      12,
      13
    ],
    "seed": 152,
    "firstSafe": 3,
    "certificate": {
      "moves": 7,
      "methods": {
        "single": 6,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-10",
    "chapter": 1,
    "title": "第一枚标本",
    "width": 4,
    "height": 4,
    "mines": [
      9,
      10,
      11
    ],
    "seed": 173,
    "firstSafe": 1,
    "certificate": {
      "moves": 9,
      "methods": {
        "single": 8,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-11",
    "chapter": 2,
    "title": "小旗试桩",
    "width": 5,
    "height": 5,
    "mines": [
      2,
      6,
      15,
      20
    ],
    "seed": 100003,
    "firstSafe": 22,
    "certificate": {
      "moves": 7,
      "methods": {
        "single": 6,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-12",
    "chapter": 2,
    "title": "苔痕边线",
    "width": 5,
    "height": 5,
    "mines": [
      6,
      16,
      21,
      23,
      24
    ],
    "seed": 100009,
    "firstSafe": 9,
    "certificate": {
      "moves": 14,
      "methods": {
        "single": 13,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-13",
    "chapter": 2,
    "title": "双读核对",
    "width": 5,
    "height": 5,
    "mines": [
      13,
      17,
      19,
      24
    ],
    "seed": 100021,
    "firstSafe": 6,
    "certificate": {
      "moves": 8,
      "methods": {
        "single": 7,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-14",
    "chapter": 2,
    "title": "标桩手记",
    "width": 5,
    "height": 5,
    "mines": [
      1,
      6,
      17,
      20
    ],
    "seed": 100025,
    "firstSafe": 19,
    "certificate": {
      "moves": 12,
      "methods": {
        "single": 11,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-15",
    "chapter": 2,
    "title": "狭隙气泡",
    "width": 5,
    "height": 5,
    "mines": [
      0,
      9,
      19,
      22,
      24
    ],
    "seed": 100034,
    "firstSafe": 10,
    "certificate": {
      "moves": 9,
      "methods": {
        "single": 8,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-16",
    "chapter": 2,
    "title": "封土猜想",
    "width": 5,
    "height": 5,
    "mines": [
      4,
      9,
      13,
      20,
      22
    ],
    "seed": 100051,
    "firstSafe": 6,
    "certificate": {
      "moves": 11,
      "methods": {
        "single": 10,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-17",
    "chapter": 2,
    "title": "数字已满",
    "width": 5,
    "height": 5,
    "mines": [
      3,
      4,
      19,
      24
    ],
    "seed": 100054,
    "firstSafe": 1,
    "certificate": {
      "moves": 5,
      "methods": {
        "single": 4,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-18",
    "chapter": 2,
    "title": "枝影警戒",
    "width": 5,
    "height": 5,
    "mines": [
      2,
      7,
      9,
      14,
      15
    ],
    "seed": 100061,
    "firstSafe": 5,
    "certificate": {
      "moves": 14,
      "methods": {
        "single": 13,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-19",
    "chapter": 2,
    "title": "安全余地",
    "width": 5,
    "height": 5,
    "mines": [
      3,
      5,
      9,
      15,
      20
    ],
    "seed": 100065,
    "firstSafe": 19,
    "certificate": {
      "moves": 11,
      "methods": {
        "single": 10,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-20",
    "chapter": 2,
    "title": "旗记交接",
    "width": 5,
    "height": 5,
    "mines": [
      8,
      13,
      18,
      19
    ],
    "seed": 100078,
    "firstSafe": 5,
    "certificate": {
      "moves": 11,
      "methods": {
        "single": 10,
        "subset": 0,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-21",
    "chapter": 3,
    "title": "两片窗口",
    "width": 6,
    "height": 5,
    "mines": [
      12,
      15,
      21,
      22,
      23,
      25
    ],
    "seed": 200003,
    "firstSafe": 3,
    "certificate": {
      "moves": 17,
      "methods": {
        "single": 14,
        "subset": 1,
        "total": 1,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-22",
    "chapter": 3,
    "title": "叶脉差集",
    "width": 6,
    "height": 5,
    "mines": [
      0,
      6,
      9,
      13,
      21,
      25
    ],
    "seed": 200006,
    "firstSafe": 23,
    "certificate": {
      "moves": 21,
      "methods": {
        "single": 19,
        "subset": 1,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-23",
    "chapter": 3,
    "title": "折叠边界",
    "width": 6,
    "height": 5,
    "mines": [
      1,
      6,
      11,
      13,
      18
    ],
    "seed": 200009,
    "firstSafe": 3,
    "certificate": {
      "moves": 11,
      "methods": {
        "single": 9,
        "subset": 1,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-24",
    "chapter": 3,
    "title": "两个窗口之间",
    "width": 6,
    "height": 5,
    "mines": [
      13,
      15,
      17,
      24,
      27,
      28,
      29
    ],
    "seed": 200015,
    "firstSafe": 2,
    "certificate": {
      "moves": 17,
      "methods": {
        "single": 15,
        "subset": 1,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-25",
    "chapter": 3,
    "title": "共享砂格",
    "width": 6,
    "height": 5,
    "mines": [
      6,
      7,
      13,
      14,
      16,
      17,
      26
    ],
    "seed": 200021,
    "firstSafe": 3,
    "certificate": {
      "moves": 21,
      "methods": {
        "single": 19,
        "subset": 1,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-26",
    "chapter": 3,
    "title": "一线之差",
    "width": 6,
    "height": 5,
    "mines": [
      2,
      7,
      8,
      17,
      22,
      23,
      28
    ],
    "seed": 200022,
    "firstSafe": 26,
    "certificate": {
      "moves": 16,
      "methods": {
        "single": 13,
        "subset": 1,
        "total": 1,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-27",
    "chapter": 3,
    "title": "边角相减",
    "width": 6,
    "height": 5,
    "mines": [
      0,
      1,
      4,
      16,
      21,
      23,
      25
    ],
    "seed": 200023,
    "firstSafe": 12,
    "certificate": {
      "moves": 22,
      "methods": {
        "single": 20,
        "subset": 1,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-28",
    "chapter": 3,
    "title": "树皮残痕",
    "width": 6,
    "height": 5,
    "mines": [
      4,
      6,
      13,
      17,
      23
    ],
    "seed": 200027,
    "firstSafe": 26,
    "certificate": {
      "moves": 13,
      "methods": {
        "single": 11,
        "subset": 1,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-29",
    "chapter": 3,
    "title": "邻域对照",
    "width": 6,
    "height": 5,
    "mines": [
      9,
      10,
      15,
      22,
      26
    ],
    "seed": 200028,
    "firstSafe": 0,
    "certificate": {
      "moves": 17,
      "methods": {
        "single": 9,
        "subset": 5,
        "total": 2,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-30",
    "chapter": 3,
    "title": "叶脉入册",
    "width": 6,
    "height": 5,
    "mines": [
      1,
      7,
      15,
      20,
      27,
      29
    ],
    "seed": 200039,
    "firstSafe": 17,
    "certificate": {
      "moves": 15,
      "methods": {
        "single": 13,
        "subset": 1,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-31",
    "chapter": 4,
    "title": "气泡双窗",
    "width": 6,
    "height": 6,
    "mines": [
      0,
      2,
      4,
      6,
      10,
      23,
      29,
      32,
      35
    ],
    "seed": 300014,
    "firstSafe": 18,
    "certificate": {
      "moves": 17,
      "methods": {
        "single": 14,
        "subset": 1,
        "total": 0,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-32",
    "chapter": 4,
    "title": "边界转译",
    "width": 6,
    "height": 6,
    "mines": [
      3,
      7,
      10,
      28,
      30,
      31
    ],
    "seed": 300024,
    "firstSafe": 20,
    "certificate": {
      "moves": 25,
      "methods": {
        "single": 10,
        "subset": 11,
        "total": 2,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-33",
    "chapter": 4,
    "title": "相邻地层",
    "width": 6,
    "height": 6,
    "mines": [
      1,
      10,
      16,
      24,
      28,
      32
    ],
    "seed": 300040,
    "firstSafe": 14,
    "certificate": {
      "moves": 22,
      "methods": {
        "single": 11,
        "subset": 8,
        "total": 2,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-34",
    "chapter": 4,
    "title": "第三处读数",
    "width": 6,
    "height": 6,
    "mines": [
      2,
      15,
      23,
      25,
      27,
      32,
      34
    ],
    "seed": 300041,
    "firstSafe": 0,
    "certificate": {
      "moves": 20,
      "methods": {
        "single": 16,
        "subset": 2,
        "total": 0,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-35",
    "chapter": 4,
    "title": "重叠印迹",
    "width": 6,
    "height": 6,
    "mines": [
      7,
      13,
      15,
      18,
      19,
      26,
      29,
      31
    ],
    "seed": 300042,
    "firstSafe": 11,
    "certificate": {
      "moves": 25,
      "methods": {
        "single": 15,
        "subset": 8,
        "total": 1,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-36",
    "chapter": 4,
    "title": "全盘余量",
    "width": 6,
    "height": 6,
    "mines": [
      3,
      7,
      12,
      19,
      24,
      28,
      29,
      32
    ],
    "seed": 300044,
    "firstSafe": 16,
    "certificate": {
      "moves": 23,
      "methods": {
        "single": 20,
        "subset": 1,
        "total": 1,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-37",
    "chapter": 4,
    "title": "砂线回流",
    "width": 6,
    "height": 6,
    "mines": [
      1,
      6,
      11,
      17,
      25,
      27
    ],
    "seed": 300046,
    "firstSafe": 15,
    "certificate": {
      "moves": 21,
      "methods": {
        "single": 11,
        "subset": 7,
        "total": 2,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-38",
    "chapter": 4,
    "title": "两侧核验",
    "width": 6,
    "height": 6,
    "mines": [
      1,
      3,
      4,
      10,
      15,
      22,
      26,
      28,
      30
    ],
    "seed": 300055,
    "firstSafe": 13,
    "certificate": {
      "moves": 26,
      "methods": {
        "single": 14,
        "subset": 7,
        "total": 3,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-39",
    "chapter": 4,
    "title": "深色气泡",
    "width": 6,
    "height": 6,
    "mines": [
      14,
      17,
      24,
      25,
      26,
      29,
      32,
      33
    ],
    "seed": 300067,
    "firstSafe": 12,
    "certificate": {
      "moves": 20,
      "methods": {
        "single": 17,
        "subset": 1,
        "total": 1,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-40",
    "chapter": 4,
    "title": "双窗汇合",
    "width": 6,
    "height": 6,
    "mines": [
      0,
      6,
      10,
      12,
      20,
      24,
      27
    ],
    "seed": 300088,
    "firstSafe": 35,
    "certificate": {
      "moves": 23,
      "methods": {
        "single": 18,
        "subset": 3,
        "total": 0,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-41",
    "chapter": 5,
    "title": "长层起点",
    "width": 6,
    "height": 7,
    "mines": [
      2,
      9,
      11,
      14,
      20,
      33,
      36,
      41
    ],
    "seed": 400001,
    "firstSafe": 22,
    "certificate": {
      "moves": 22,
      "methods": {
        "single": 19,
        "subset": 2,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-42",
    "chapter": 5,
    "title": "剖面折返",
    "width": 6,
    "height": 7,
    "mines": [
      4,
      16,
      20,
      23,
      26,
      28,
      31
    ],
    "seed": 400002,
    "firstSafe": 12,
    "certificate": {
      "moves": 25,
      "methods": {
        "single": 17,
        "subset": 6,
        "total": 1,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-43",
    "chapter": 5,
    "title": "深砂之下",
    "width": 6,
    "height": 7,
    "mines": [
      1,
      4,
      10,
      15,
      17,
      20,
      23,
      36,
      41
    ],
    "seed": 400010,
    "firstSafe": 18,
    "certificate": {
      "moves": 25,
      "methods": {
        "single": 16,
        "subset": 6,
        "total": 1,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-44",
    "chapter": 5,
    "title": "远端回应",
    "width": 6,
    "height": 7,
    "mines": [
      0,
      9,
      14,
      21,
      28,
      36,
      37
    ],
    "seed": 400011,
    "firstSafe": 40,
    "certificate": {
      "moves": 19,
      "methods": {
        "single": 16,
        "subset": 2,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-45",
    "chapter": 5,
    "title": "一条叶脉",
    "width": 6,
    "height": 7,
    "mines": [
      10,
      19,
      25,
      26,
      36,
      38,
      39,
      40
    ],
    "seed": 400014,
    "firstSafe": 29,
    "certificate": {
      "moves": 22,
      "methods": {
        "single": 17,
        "subset": 3,
        "total": 0,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-46",
    "chapter": 5,
    "title": "多轮标记",
    "width": 6,
    "height": 7,
    "mines": [
      1,
      4,
      7,
      13,
      23,
      24,
      29,
      33
    ],
    "seed": 400016,
    "firstSafe": 21,
    "certificate": {
      "moves": 29,
      "methods": {
        "single": 20,
        "subset": 4,
        "total": 2,
        "enumeration": 2
      }
    }
  },
  {
    "id": "amber-47",
    "chapter": 5,
    "title": "上下传递",
    "width": 6,
    "height": 7,
    "mines": [
      6,
      16,
      20,
      25,
      29,
      31,
      32
    ],
    "seed": 400018,
    "firstSafe": 5,
    "certificate": {
      "moves": 29,
      "methods": {
        "single": 26,
        "subset": 2,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-48",
    "chapter": 5,
    "title": "暗层清点",
    "width": 6,
    "height": 7,
    "mines": [
      9,
      11,
      19,
      27,
      28,
      35,
      39
    ],
    "seed": 400019,
    "firstSafe": 0,
    "certificate": {
      "moves": 28,
      "methods": {
        "single": 20,
        "subset": 4,
        "total": 0,
        "enumeration": 3
      }
    }
  },
  {
    "id": "amber-49",
    "chapter": 5,
    "title": "长层回路",
    "width": 6,
    "height": 7,
    "mines": [
      1,
      2,
      6,
      10,
      16,
      20,
      31
    ],
    "seed": 400021,
    "firstSafe": 41,
    "certificate": {
      "moves": 24,
      "methods": {
        "single": 20,
        "subset": 3,
        "total": 0,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-50",
    "chapter": 5,
    "title": "昆虫剪影",
    "width": 6,
    "height": 7,
    "mines": [
      1,
      4,
      6,
      7,
      13,
      21,
      33,
      40
    ],
    "seed": 400023,
    "firstSafe": 17,
    "certificate": {
      "moves": 26,
      "methods": {
        "single": 20,
        "subset": 4,
        "total": 1,
        "enumeration": 0
      }
    }
  },
  {
    "id": "amber-51",
    "chapter": 6,
    "title": "层积开卷",
    "width": 6,
    "height": 8,
    "mines": [
      2,
      4,
      7,
      8,
      12,
      15,
      19,
      32,
      40,
      44,
      47
    ],
    "seed": 500005,
    "firstSafe": 29,
    "certificate": {
      "moves": 30,
      "methods": {
        "single": 21,
        "subset": 7,
        "total": 0,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-52",
    "chapter": 6,
    "title": "旧线新证",
    "width": 6,
    "height": 8,
    "mines": [
      0,
      1,
      11,
      15,
      16,
      22,
      25,
      39,
      40,
      44,
      45
    ],
    "seed": 500056,
    "firstSafe": 12,
    "certificate": {
      "moves": 34,
      "methods": {
        "single": 20,
        "subset": 10,
        "total": 2,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-53",
    "chapter": 6,
    "title": "全盘勘界",
    "width": 6,
    "height": 8,
    "mines": [
      0,
      2,
      5,
      18,
      22,
      34,
      38,
      39
    ],
    "seed": 500110,
    "firstSafe": 26,
    "certificate": {
      "moves": 30,
      "methods": {
        "single": 25,
        "subset": 2,
        "total": 0,
        "enumeration": 2
      }
    }
  },
  {
    "id": "amber-54",
    "chapter": 6,
    "title": "隔层回响",
    "width": 6,
    "height": 8,
    "mines": [
      8,
      15,
      18,
      19,
      24,
      29,
      39,
      42,
      43,
      45
    ],
    "seed": 500112,
    "firstSafe": 47,
    "certificate": {
      "moves": 27,
      "methods": {
        "single": 22,
        "subset": 2,
        "total": 0,
        "enumeration": 2
      }
    }
  },
  {
    "id": "amber-55",
    "chapter": 6,
    "title": "树脂封缄",
    "width": 6,
    "height": 8,
    "mines": [
      6,
      15,
      19,
      25,
      33,
      36,
      39,
      46,
      47
    ],
    "seed": 500127,
    "firstSafe": 3,
    "certificate": {
      "moves": 29,
      "methods": {
        "single": 25,
        "subset": 2,
        "total": 0,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-56",
    "chapter": 6,
    "title": "交叉读数",
    "width": 6,
    "height": 8,
    "mines": [
      2,
      9,
      10,
      19,
      24,
      30,
      32,
      41
    ],
    "seed": 500132,
    "firstSafe": 6,
    "certificate": {
      "moves": 31,
      "methods": {
        "single": 18,
        "subset": 6,
        "total": 0,
        "enumeration": 6
      }
    }
  },
  {
    "id": "amber-57",
    "chapter": 6,
    "title": "最后的气泡",
    "width": 6,
    "height": 8,
    "mines": [
      7,
      24,
      29,
      32,
      33,
      37,
      39,
      41,
      43
    ],
    "seed": 500177,
    "firstSafe": 20,
    "certificate": {
      "moves": 27,
      "methods": {
        "single": 18,
        "subset": 5,
        "total": 2,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-58",
    "chapter": 6,
    "title": "深层传讯",
    "width": 6,
    "height": 8,
    "mines": [
      6,
      10,
      17,
      22,
      35,
      37,
      40,
      43,
      45
    ],
    "seed": 500183,
    "firstSafe": 26,
    "certificate": {
      "moves": 27,
      "methods": {
        "single": 20,
        "subset": 4,
        "total": 1,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-59",
    "chapter": 6,
    "title": "所有安全格",
    "width": 6,
    "height": 8,
    "mines": [
      5,
      11,
      15,
      26,
      36,
      38,
      41,
      43,
      45,
      47
    ],
    "seed": 500190,
    "firstSafe": 23,
    "certificate": {
      "moves": 19,
      "methods": {
        "single": 15,
        "subset": 2,
        "total": 0,
        "enumeration": 1
      }
    }
  },
  {
    "id": "amber-60",
    "chapter": 6,
    "title": "透明层积座",
    "width": 6,
    "height": 8,
    "mines": [
      8,
      10,
      12,
      16,
      19,
      23,
      31,
      38,
      42,
      43,
      47
    ],
    "seed": 500204,
    "firstSafe": 35,
    "certificate": {
      "moves": 32,
      "methods": {
        "single": 25,
        "subset": 2,
        "total": 1,
        "enumeration": 3
      }
    }
  }
];
export const levelById = id => LEVELS.find(level => level.id === id) || LEVELS[0];
