(function(){'use strict';const E=window.AuroraEngine,S=window.AuroraSession,R=window.AuroraRenderer,O=window.AuroraOracle,L=window.AuroraLevels,$=id=>document.getElementById(id);
const stations=['初光哨所','逆风观测台','静雪中继站','冰湾计量所','极地观星台','长夜灯塔'];const lessons=['先选一个双格信标，再安排一正一负；同极不能上下左右相邻。','箭头表示左到右或上到下，试着反向安排正负极。','○ ○ 是明确中性，不计正负数量；问号仍是未填写。','同时满足行、列的正负配额。圆点没有配额限制，数字 0 有。','同极只能对角相望，不能上下左右接触。先排除相邻冲突。','结合配额、中性和邻接关系，完成整座极夜站点的联调。'];
function runId(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);}let raw=null;try{raw=localStorage.getItem(S.PREFIX+'save');}catch(e){}let data=S.restore(raw,L,runId()),p=L.find(x=>x.id===data.session.levelId),selected=0,feedback='',saveError=false,lastFocus=null,card=0,dailyMode=false;
function save(){try{S.commit(p,data,localStorage,window.AuroraHost&&window.AuroraHost.complete);saveError=false;}catch(e){saveError=true;}}
function close(){ $('modal').hidden=true;document.body.classList.remove('modal-open');$('app').removeAttribute('aria-hidden');if(lastFocus&&document.contains(lastFocus))lastFocus.focus();else $('tutorial').focus();}
function modal(title,body,actions){if($('modal').hidden)lastFocus=document.activeElement;$('dialogTitle').textContent=title;$('dialogBody').innerHTML=body;$('dialogActions').innerHTML=actions||'';$('modal').hidden=false;$('app').setAttribute('aria-hidden','true');document.body.classList.add('modal-open');document.querySelector('.dialog').scrollTop=0;$('close').focus();}
function draw(){const ev=E.inspect(p,data.session.state),count=Object.keys(data.records).length,stationCount=stations.filter((_,c)=>L.filter(x=>x.chapter===c).every(x=>data.records[x.id])).length;
 $('board').innerHTML=R.board(p,data.session.state,selected,true);$('levelTitle').textContent='第 '+(L.indexOf(p)+1)+' 关 · '+p.title;$('phase').textContent=(dailyMode?'今日轮换 · ':'第 '+(p.chapter+1)+' 章 · ')+p.phase;$('lesson').textContent=lessons[p.chapter];$('progress').textContent=count+' / 60';$('collection').textContent='已点亮 '+stationCount+' / 6 座站点';$('stationName').textContent='0'+(p.chapter+1)+' · '+stations[p.chapter];document.querySelector('.landscape').classList.toggle('lit',ev.complete);$('selection').textContent='已选信标 '+(selected+1)+' · '+(p.slots[selected][1]-p.slots[selected][0]===p.w?'竖向：从上到下 ↓':'横向：从左到右 →');$('undo').disabled=!data.session.actions.length;$('next').hidden=!ev.complete;$('next').textContent=L.indexOf(p)===59?'回看全部航线 →':'前往下一处信标 →';
 $('status').className=ev.conflicts.length||ev.bad.length?'error':'';$('status').textContent=saveError?'本机存储不可用，本次进度尚未保存。请保留页面。':feedback||(ev.complete?'信标校准完成，极夜又亮了一点。':ev.conflicts.length?'同极相邻了：试着反向，或改为中性。':ev.bad.length?'有配额无法满足，请调整或撤销。':'已安排 '+data.session.state.values.filter(v=>v!==null).length+' / '+p.slots.length+' 个信标。');}
function start(q,isDaily){p=q;dailyMode=!!isDaily;data.session=S.fresh(p,runId());selected=0;feedback='';save();draw();}
function action(a){let next=S.act(p,data.session,a);if(next===data.session)return;data.session=next;feedback='';save();draw();}
$('board').addEventListener('click',e=>{let g=e.target.closest('[data-slot]');if(g){selected=Number(g.getAttribute('data-slot'));draw();document.querySelector('[data-slot="'+selected+'"]').focus();}});
$('board').addEventListener('keydown',e=>{let g=e.target.closest('[data-slot]');if(!g)return;selected=Number(g.getAttribute('data-slot'));if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();selected=(selected+1)%p.slots.length;draw();document.querySelector('[data-slot="'+selected+'"]').focus();}else if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();selected=(selected+p.slots.length-1)%p.slots.length;draw();document.querySelector('[data-slot="'+selected+'"]').focus();}else if(['1','2','3','Backspace','Delete'].indexOf(e.key)>=0){e.preventDefault();action({type:'set',slot:selected,value:e.key==='1'?1:e.key==='2'?-1:e.key==='3'?0:null});document.querySelector('[data-slot="'+selected+'"]').focus();}else if(e.key==='Enter'||e.key===' '){e.preventDefault();$('selection').focus();document.querySelector('[data-value]').focus();}});
document.querySelectorAll('[data-value]').forEach(b=>b.addEventListener('click',()=>action({type:'set',slot:selected,value:JSON.parse(b.getAttribute('data-value'))})));
function selectSlot(delta){selected=(selected+delta+p.slots.length)%p.slots.length;draw();} $('prevSlot').onclick=()=>selectSlot(-1);$('nextSlot').onclick=()=>selectSlot(1);
$('undo').onclick=()=>{if(!data.session.actions.length)return;data.session=S.undo(p,data.session);feedback='已撤销上一步，笔记也一起恢复。';save();draw();};$('note').onclick=()=>action({type:'note',slot:selected});
$('restart').onclick=()=>{modal('重新调试这一关？','<p>清空当前安排与笔记，已获得的站点收藏保留。</p>','<button id="confirmRestart" class="primary">重新开始</button>');$('confirmRestart').onclick=()=>{close();start(p,dailyMode);};};
function levels(){modal('极夜航线 · 60 关',stations.map((name,ch)=>'<section class="chapter"><h3>0'+(ch+1)+' '+name+' · '+L[ch*10].title+'</h3><div class="level-grid">'+L.filter(q=>q.chapter===ch).map(q=>'<button data-level="'+q.id+'" class="'+(data.records[q.id]?'done':'')+'">'+(L.indexOf(q)+1)+(data.records[q.id]?' ✓':'')+'</button>').join('')+'</div></section>').join(''));document.querySelectorAll('[data-level]').forEach(b=>{if(b.tagName.toLowerCase()!=='button')return;b.onclick=()=>{let q=L.find(x=>x.id===b.getAttribute('data-level'));close();if(q.id!==p.id)start(q);};});}
$('levels').onclick=levels;$('next').onclick=()=>{let i=L.indexOf(p);if(i===59)levels();else start(L[i+1]);};$('daily').onclick=()=>{const q=S.daily(new Date(),L);modal('每日调试','<p>今日选自第 '+(L.indexOf(q)+1)+' 关。按本机日期在 60 道主线题中循环，每 60 天重复；不另发重复首通奖励。</p>','<button id="beginDaily" class="primary">开始今日调试</button>');$('beginDaily').onclick=()=>{close();start(q,true);};};
$('archive').onclick=()=>modal('六处极地站点',stations.map((n,ch)=>{let done=L.filter(q=>q.chapter===ch&&data.records[q.id]).length;return '<div class="station-card"><strong>'+(done===10?'✦':'◇')+' '+n+'</strong><small>'+done+' / 10 关 · '+(done===10?'站点已亮起':'完成本章，点亮站点')+'</small></div>';}).join(''));
$('hint').onclick=()=>{const state=data.session.state,ev=E.inspect(p,state);if(ev.complete){feedback='所有信标已经校准。';draw();return;}if(!ev.consistent){feedback='先修正高亮配额或同极邻接冲突；可以撤销最近一步。';draw();return;}
 let i=state.values.findIndex((v,j)=>v!==null&&v!==p.solution[j]);if(i>=0){selected=i;feedback='这个安排局部看似可行，但整盘无解。请先检查信标 '+(i+1)+'，再结合行列配额回看。';draw();return;}
 i=state.values.findIndex((v,j)=>v===null&&E.candidates(p,state,j).length===1);if(i>=0){selected=i;let v=E.candidates(p,state,i)[0];feedback='信标 '+(i+1)+'：其余安排会造成同极邻接或配额不足 / 超额，仅剩'+(v===0?'中性':v===1?'正负':'负正')+'。提示不自动填写。';draw();return;}
 let j=state.values.indexOf(null);selected=j;draw();modal('再看深一步','<p>当前需要组合多个配额与邻接关系。可以先做笔记；若仍卡住，可揭示选中信标的唯一解安排。</p>','<button id="reveal" class="primary">揭示一个信标（不自动填写）</button>');$('reveal').onclick=()=>{close();feedback='唯一解参考：信标 '+(j+1)+' 为'+(p.solution[j]===0?'中性':p.solution[j]===1?'正负':'负正')+'。可沿相关行列继续推理。';draw();};};
function tutorial(){let images=['tutorial-1.svg','tutorial-2.svg','tutorial-3.svg'];let texts=['每个铜边槽是一枚双格信标。上 / 左数正极，下 / 右数负极；圆点是无线索，0 表示一个也不能有。','先点整个槽，再选正负、负正或中性；横槽从左到右，竖槽从上到下。这张图只比上一张多填了一个信标。','全部槽都要明确填写，给定配额同时满足，同极不能上下左右相邻。问号未填与 ○ 中性不同；✧ 只是笔记。'];modal('信标手册 · '+(card+1)+' / 3','<img class="tutorial-image" src="./'+images[card]+'" alt="'+['固定教程题初始状态，所有槽未填','同一教程题执行一次合法赋值','同一教程题通过引擎判定的完成状态'][card]+'"><p>'+texts[card]+'</p>','<div class="tutorial-nav"><button id="skip">跳过</button><button id="tutorialNext">'+(card===2?'开始调试':'下一张 →')+'</button></div>');$('skip').onclick=finishTutorial;$('tutorialNext').onclick=()=>{if(card<2){card++;tutorial();}else finishTutorial();};}
function finishTutorial(){try{localStorage.setItem(S.PREFIX+'aurora-beacons-tutorial-v1','seen');}catch(e){}close();}
$('tutorial').onclick=()=>{card=0;tutorial();};$('close').onclick=close;$('about').onclick=()=>modal('规则与来源','<p>每个固定双格槽可填 ＋−、−＋ 或 ○○。所有已给正负配额必须满足；同极不能正交相邻。未填不算中性，笔记不参与判胜。错误安排可以保留以便推理，不会通关。</p><p>点击槽后用底部按钮精确填写。键盘方向键换槽，1 正负、2 负正、3 中性、Delete 清空。支持无惩罚撤销和离线保存。</p><p>规则原型：Simon Tatham 谜题集 Magnets；创意来源 Janko，由 James Harvey 贡献。主题与程序为 AI 辅助独立开发。MIT 许可。没有联网追踪。</p><p>60 关 / 6 章，每日从主线题库循环。保存只在当前设备；清理平台缓存可能丢失进度。</p>');
document.addEventListener('keydown',e=>{if($('modal').hidden)return;if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const list=Array.from($('modal').querySelectorAll('button,[tabindex="0"]')).filter(x=>!x.disabled),first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
save();draw();try{if(localStorage.getItem(S.PREFIX+'aurora-beacons-tutorial-v1')!=='seen')tutorial();}catch(e){tutorial();}
})();
