import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
let pw;try{pw=await import('playwright');}catch(e){const require=createRequire(import.meta.url);pw=require(process.env.CLOUDSTEP_PLAYWRIGHT||'playwright');}
const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'};
const server=http.createServer((req,res)=>{const path='dist/xhs'+(req.url==='/'?'/index.html':req.url.split('?')[0]);if(path.includes('..')){res.writeHead(403).end();return;}try{const body=fs.readFileSync(path);res.writeHead(200,{'Content-Type':types[path.slice(path.lastIndexOf('.'))]||'application/octet-stream','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'none'; worker-src 'none'; frame-src 'none'; object-src 'none'"});res.end(body);}catch(e){res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const browser=await pw.chromium.launch({channel:'chrome',headless:true});const reports=[],errors=[];fs.mkdirSync('release',{recursive:true});
try{
 for(const [width,height] of [[320,720],[390,844],[1280,720],[399,720],[400,720],[401,720],[759,720],[760,720],[761,720]]){
 const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce'});await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');}));const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(url))errors.push('external '+r.url());});await page.goto(url);await page.evaluate(()=>{document.documentElement.style.setProperty('--safe-area-inset-top','44px');document.documentElement.style.setProperty('--safe-area-inset-bottom','34px');});
 await page.locator('[data-action="chapter:0"]').click();await page.locator('[data-action="level:0"]').click();await page.locator('[data-action="tutorial-next"]').click();await page.locator('[data-action="tutorial-next"]').click();await page.waitForFunction(()=>{const img=document.querySelector('#overlay img');return img&&img.complete&&img.naturalWidth>0;});const dialogBounds=await page.locator('.modal').evaluate(el=>{const r=el.getBoundingClientRect();return {top:r.top,bottom:r.bottom};});assert.ok(dialogBounds.top>=44&&dialogBounds.bottom<=height-34,JSON.stringify({width,height,dialogBounds}));if(width===390)await page.screenshot({path:'release/tutorial-mobile.png',fullPage:true});await page.locator('[data-action="tutorial-close"]').last().click();
 await page.locator('[data-action="note"]').click();const editable=await page.evaluate(()=>CityLevels[0].givens.findIndex(v=>!v));await page.locator('[data-action="cell:'+editable+'"]').click();await page.locator('[data-action="value:1"]').click();await page.locator('[data-action="undo"]').click();await page.locator('[data-action="note"]').click();const val=await page.evaluate(i=>CityLevels[0].solution[i],editable);await page.locator('[data-action="value:'+val+'"]').click();await page.reload();await page.locator('[data-action="chapter:0"]').click();await page.locator('[data-action="level:0"]').click();assert.ok((await page.locator('[data-action="cell:'+editable+'"]').textContent()).includes(String(val)));
 if(width===390)await page.screenshot({path:'release/gameplay-mobile.png',fullPage:true});
 const solution=await page.evaluate(()=>CityLevels[0].solution);const givens=await page.evaluate(()=>CityLevels[0].givens);for(let i=0;i<solution.length;i++){if(givens[i]||i===editable)continue;await page.locator('[data-action="cell:'+i+'"]').click();await page.locator('[data-action="value:'+solution[i]+'"]').click();}await page.getByText('这座街区，落成了。').waitFor();if(width===390)await page.screenshot({path:'release/completion-mobile.png',fullPage:true});
 const claims=await page.evaluate(()=>JSON.parse(localStorage.getItem(CityStore.key)).claims.length);assert.equal(claims,2);await page.locator('[data-action="win-back"]').click();await page.locator('[data-action="level:0"]').click();await page.locator('[data-action="restart"]').click();await page.locator('[data-action="restart-confirm"]').click();for(let i=0;i<solution.length;i++){if(givens[i])continue;await page.locator('[data-action="cell:'+i+'"]').click();await page.locator('[data-action="value:'+solution[i]+'"]').click();}assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(CityStore.key)).claims.length),2);await page.locator('[data-action="win-back"]').click();await page.locator('[data-action="home"]').click();await page.locator('[data-action="chapter:5"]').click();await page.locator('[data-action="level:59"]').click();
 const layout=await page.evaluate(()=>{const b=document.querySelector('.board').getBoundingClientRect(),cells=Array.from(document.querySelectorAll('.cell')).map(x=>x.getBoundingClientRect());return {overflow:document.documentElement.scrollWidth>innerWidth,minCell:Math.min.apply(null,cells.map(x=>x.width)),boardBottom:b.bottom,toolsBottom:document.querySelector('.tools').getBoundingClientRect().bottom};});assert.equal(layout.overflow,false,JSON.stringify({width,layout}));assert.ok(layout.minCell>=44-0.1,JSON.stringify({width,layout}));assert.ok(layout.toolsBottom<=height-34,JSON.stringify({width,layout}));reports.push({width,height,safeArea:'44/34',layout,status:'pass'});if(width===320)await page.screenshot({path:'release/gameplay-320.png',fullPage:true});if(width===1280)await page.screenshot({path:'release/gameplay-desktop.png',fullPage:true});await context.close();
 }
 const extraContext=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const extra=await extraContext.newPage();extra.on('pageerror',e=>errors.push(e.message));await extra.goto(url);await extra.screenshot({path:'release/home-mobile.png',fullPage:true});await extra.locator('[data-action="chapter:0"]').tap();await extra.locator('[data-action="level:0"]').tap();await extra.getByRole('button',{name:'跳过',exact:true}).tap();assert.equal(await extra.locator('#overlay').isVisible(),false);await extra.locator('[data-action="hint"]').tap();await extra.getByRole('button',{name:'自己再想想'}).tap();assert.equal(await extra.evaluate(()=>JSON.parse(localStorage.getItem(CityStore.key)).sessions[CityLevels[0].id].hints),0);await extra.locator('[data-action="hint"]').tap();await extra.locator('[data-action^="hint-fill:"]').tap();assert.equal(await extra.evaluate(()=>JSON.parse(localStorage.getItem(CityStore.key)).sessions[CityLevels[0].id].hints),1);await extra.locator('[data-action="tutorial"]').first().tap();await extra.keyboard.press('Escape');assert.equal(await extra.locator('#overlay').isVisible(),false);assert.equal(await extra.evaluate(()=>document.activeElement.getAttribute('data-action')),'tutorial');await extra.locator('[data-action="home"]').tap();await extra.locator('[data-action="collection"]').tap();await extra.locator('[data-action="collect-next"]').tap();assert.ok((await extra.locator('h1').textContent()).includes('高楼之后'));await extra.locator('[data-action="home"]').tap();await extra.locator('[data-action="daily"]').tap();assert.ok((await extra.locator('.eyebrow').first().textContent()).includes('DAILY'));await extra.evaluate(()=>localStorage.setItem(CityStore.key,'{damaged'));await extra.reload();await extra.locator('[data-action="chapter:0"]').tap();await extra.locator('[data-action="level:0"]').tap();assert.equal(await extra.locator('.cell').count(),9);await extraContext.close();reports.push({suite:'touch, tutorial skip/reopen/focus, hint cancel/confirm, collection paging, daily, corrupted save',status:'pass'});
 const recoveryContext=await browser.newContext({viewport:{width:320,height:720}});const recovery=await recoveryContext.newPage();recovery.on('pageerror',e=>errors.push(e.message));await recovery.goto(url);await recovery.evaluate(()=>{const p=CityLevels[0],d=CityStore.empty(),actions=[];p.solution.forEach((v,i)=>{if(!p.givens[i])actions.push({type:'set',i,v});});d.sessions[p.id]={actions,hints:0,runId:'interrupted-browser',mode:'chapter'};localStorage.setItem(CityStore.key,JSON.stringify(d));});await recovery.reload();assert.ok((await recovery.locator('.section-title').textContent()).includes('1 / 60'));assert.equal(await recovery.evaluate(()=>JSON.parse(localStorage.getItem(CityStore.key)).claims.length),2);await recovery.reload();assert.equal(await recovery.evaluate(()=>JSON.parse(localStorage.getItem(CityStore.key)).outbox.length),1);await recoveryContext.close();
 const quotaContext=await browser.newContext({viewport:{width:320,height:720}});await quotaContext.addInitScript(()=>{Storage.prototype.setItem=function(){throw new Error('quota exceeded');};window.hostCalls=0;window.cloudstepCompletionHost=()=>{window.hostCalls++;return true;};});const quota=await quotaContext.newPage();quota.on('pageerror',e=>errors.push(e.message));await quota.goto(url);await quota.locator('[data-action="chapter:0"]').click();await quota.locator('[data-action="level:0"]').click();await quota.getByRole('button',{name:'跳过',exact:true}).click();assert.ok((await quota.locator('.status').textContent()).includes('存储不可用'));await quota.locator('[data-action="value:3"]').click();assert.ok((await quota.locator('.status').textContent()).includes('存储不可用'));assert.equal(await quota.evaluate(()=>window.hostCalls),0);await quotaContext.close();reports.push({suite:'interrupted settlement recovery, reload deduplication, storage quota failure',status:'pass'});
 assert.deepEqual(errors,[]);fs.writeFileSync('release/browser-report.json',JSON.stringify({browser:'Chrome headless desktop simulation',reports,errors},null,2));console.log('Browser matrix passed:',reports.filter(x=>x.width).length,'viewports plus touch flow');
}finally{await browser.close();server.close();}
