import fs from 'node:fs';import vm from 'node:vm';import {execFileSync} from 'node:child_process';
fs.mkdirSync('dist/xhs/assets',{recursive:true});fs.mkdirSync('assets',{recursive:true});
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync('src/engine.js','utf8')+fs.readFileSync('src/render.js','utf8'),ctx);const E=ctx.City;
const tutorial={id:'cloudstep-city-tutorial-v1',n:3,givens:Array(9).fill(0),solution:[3,1,2,1,2,3,2,3,1]};tutorial.clues=E.clues(3,tutorial.solution);const initial=E.initial(tutorial),action={type:'set',i:0,v:3},next=E.move(tutorial,initial,action);const states=[initial.values,next.values,tutorial.solution];
if(!E.evaluate(tutorial,{values:states[2]}).complete)throw Error('tutorial');states.forEach((b,i)=>fs.writeFileSync('assets/tutorial-'+i+'.svg',ctx.CityRender.svg(tutorial,b)));fs.writeFileSync('release/tutorial-truth.json',JSON.stringify({puzzle:tutorial,action,states},null,2));
function art(k){let body='';for(let i=0;i<11;i++){const x=28+i*32,h=55+((i*47+k*31)%130),y=257-h;body+='<rect x="'+x+'" y="'+y+'" width="29" height="'+h+'" rx="3" fill="'+(['#ba795c','#d7aa85','#8a9b80','#bd9679'][(i+k)%4])+'"/><path d="M'+x+' '+y+' l14 -9 15 9" fill="#e8caae"/>';for(let j=0;j<3;j++)body+='<rect x="'+(x+7)+'" y="'+(y+15+j*20)+'" width="5" height="8" rx="1" fill="#fff4d9" opacity=".8"/>';}
return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 420 320"><circle cx="238" cy="128" r="105" fill="#ced9c5"/><circle cx="305" cy="68" r="25" fill="#f8edd0"/><path d="M10 265 Q 190 190 410 265 L370 290 70 290Z" fill="#adbca0"/>'+body+'<path d="M0 256 Q90 227 185 262 T420 251 L420 320H0Z" fill="#e7ecdf" opacity=".85"/><path d="M34 290 Q200 245 392 284" fill="none" stroke="#faf7e9" stroke-width="12"/></svg>';}
fs.writeFileSync('assets/city.svg',art(0));for(let i=0;i<6;i++)fs.writeFileSync('assets/city-'+i+'.svg',art(i));
for(const name of fs.readdirSync('assets'))fs.copyFileSync('assets/'+name,'dist/xhs/assets/'+name);
fs.copyFileSync('src/index.html','dist/xhs/index.html');fs.copyFileSync('src/styles.css','dist/xhs/styles.css');fs.writeFileSync('dist/xhs/app.js',['engine','levels','store','render','app'].map(x=>fs.readFileSync('src/'+x+'.js','utf8')).join('\n'));
try{fs.unlinkSync('dist/cloudstep-city-xhs.zip');}catch(e){if(e.code!=='ENOENT')throw e;}execFileSync('zip',['-q','-r','../cloudstep-city-xhs.zip','index.html','app.js','styles.css','assets'],{cwd:'dist/xhs'});console.log('Built classic offline package');
