'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'dist/xhs'),zip=path.join(root,'dist/scarlet-knot-atlas-xhs.zip');
const official=process.env.MINITOOL_AUDIT||'/Users/qiu/Documents/ChatGPT/小游戏/docs/platform/minitool-zip-builder-1.7.0/minitool-zip-builder/scripts/audit_artifact.py';
const files=[];function walk(dir){for(const n of fs.readdirSync(dir).sort()){const f=path.join(dir,n);if(fs.statSync(f).isDirectory())walk(f);else files.push({path:path.relative(out,f),bytes:fs.statSync(f).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')});}}walk(out);
const html=fs.readFileSync(path.join(out,'index.html'),'utf8'),js=fs.readFileSync(path.join(out,'app.js'),'utf8'),css=fs.readFileSync(path.join(out,'styles.css'),'utf8');
assert(!/<script(?![^>]*src=)[^>]*>\s*[^<]/i.test(html));assert(!/(type\s*=\s*["']module|\son\w+\s*=|javascript:|<iframe|<object|<base|http-equiv=["']Content-Security-Policy)/i.test(html));
for(const m of html.matchAll(/(?:src|href)="([^"]+)"/g)){assert(m[1].startsWith('./'));assert(fs.existsSync(path.join(out,m[1])),'Missing '+m[1]);}
for(const m of css.matchAll(/url\(['"]?([^'"\)]+)['"]?\)/g)){assert(m[1].startsWith('./'));assert(fs.existsSync(path.join(out,m[1])));}
const code=js.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/[^\n]*/g,'');
assert(!/\b(fetch\s*\(|XMLHttpRequest|WebSocket|EventSource|RTCPeerConnection|Worker|SharedWorker|WebAssembly|eval\s*\(|new\s+Function|serviceWorker|geolocation|clipboard|window\.open|window\.prompt)\b/.test(code));
assert(!/(\?\.|\?\?|\.\.\.|\bglobalThis\b|\b\d+n\b|Object\.fromEntries|\.replaceAll\s*\(|\.at\s*\(|\.flat\s*\(|^\s*(?:import|export)\s)/m.test(code),'ES2018+ syntax or newer runtime API');
assert(!/(?:clamp\(|aspect-ratio|:has\(|color-mix\(|\bdvh\b|\binset\s*:|#[0-9a-f]{8}\b|(?:^|[;{])\s*gap\s*:)/i.test(css),'CSS lacks Chrome61 baseline');
cp.execFileSync(process.execPath,['--check',path.join(out,'app.js')]);
const officialResults=[out,zip].map(target=>({target:target===out?'directory':'zip',stdout:cp.execFileSync('python3',[official,target],{encoding:'utf8'}).trim(),exitCode:0}));
const zipInspection=JSON.parse(cp.execFileSync('python3',['-c',`import zipfile,json,pathlib,xml.etree.ElementTree as E\np=pathlib.Path(${JSON.stringify(zip)})\nwith zipfile.ZipFile(p) as z:\n assert z.testzip() is None\n names=z.namelist();assert names.count('index.html')==1\n assert all('..' not in pathlib.PurePosixPath(n).parts and not n.startswith('/') for n in names)\n assert all(pathlib.Path(n).suffix.lower() in ['.html','.css','.js','.svg','.webp','.json'] for n in names)\n assert not any(n.endswith('.map') or '.git' in n or 'node_modules' in n for n in names)\n for n in names:\n  if n.endswith('.svg'): E.fromstring(z.read(n))\n print(json.dumps({'CRC':'passed','rootEntry':'index.html','files':names,'bytes':p.stat().st_size,'uncompressedBytes':sum(i.file_size for i in z.infolist())}))`],{encoding:'utf8'}));
const truth=JSON.parse(fs.readFileSync(path.join(root,'release/tutorial-truth.json')));const xmlResult=JSON.parse(cp.execFileSync('python3',['-c',`import json,pathlib,xml.etree.ElementTree as E\np=pathlib.Path(${JSON.stringify(root)});t=json.loads((p/'release/tutorial-truth.json').read_text())\nfor s in t['states']:\n r=E.parse(p/'assets'/s['file']).getroot();assert r.attrib['data-level']==t['levelId'];assert int(r.attrib['data-crossings'])==len(s['crossingPairs'])\n nodes=[n for n in r.iter() if 'data-node' in n.attrib];assert len(nodes)==len(s['points'])\n for n,point in zip(nodes,s['points']):\n  assert int(n.attrib['data-node'])==point['id'] and float(n.attrib['data-x'])==point['x'] and float(n.attrib['data-y'])==point['y']\n assert len([n for n in r.iter() if 'data-edge' in n.attrib])==len(s['edges'])\nprint(json.dumps({'SVG_XML':'passed','tutorialStates':3,'crossingCounts':[len(s['crossingPairs']) for s in t['states']]}))`],{encoding:'utf8'}));
function luminance(h){const vs=[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4));return vs[0]*.2126+vs[1]*.7152+vs[2]*.0722;}
const pairs=[['text','#241b20','#f6ebd9',4.5],['muted','#655452','#fff9ef',4.5],['line','#9f3040','#f6ebd9',3],['button','#ffffff','#9f3040',4.5],['seal-border','#815c29','#fff9ec',3],['selection','#2e6e66','#f6ebd9',3]];
const contrast=pairs.map(([role,fg,bg,target])=>{const a=luminance(fg),b=luminance(bg),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);assert(ratio>=target);return {role,fg,bg,ratio:Number(ratio.toFixed(2)),target};});
const report={date:new Date().toISOString(),status:'local_static_candidate_passed_not_platform_ready',officialSpec:'1.7.0 archived manifest; latest online document unavailable',officialScriptSHA256:crypto.createHash('sha256').update(fs.readFileSync(official)).digest('hex'),officialResults,files,zip:{...zipInspection,sha256:crypto.createHash('sha256').update(fs.readFileSync(zip)).digest('hex')},syntax:'Node parse and explicit ES2017/newer API static gate; not Chrome61 execution',XML:xmlResult,contrast,limitations:['latest online rules unavailable','official container not tested','Chrome61 engine not tested','physical iOS/Android not tested']};
fs.writeFileSync(path.join(root,'release/package-audit.json'),JSON.stringify(report,null,2)+'\n');console.log('PASS local package: '+zipInspection.bytes+' bytes, '+files.length+' files, CRC/XML/relative refs/static capability gates/contrast; official audit 0 warnings.');
