'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const L=require('../levels.js'),C=require('../core.js'),S=require('../session.js');
const root=path.resolve(__dirname,'../dist/xhs'),release=path.resolve(__dirname,'../release'),key='mini-polish:scarlet-knot-atlas:v1:ledger';
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+(req.url==='/'?'/index.html':req.url));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp'})[path.extname(f)]||'text/html');res.setHeader('Content-Security-Policy',"default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'none'");res.end(fs.readFileSync(f));});
const report={date:new Date().toISOString(),campaign:[],cases:[],errors:[]};let browser;
async function pause(p){await p.waitForTimeout(25);}
async function ledger(p){return p.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);}
async function fresh(browser,origin,init,options){const ctx=await browser.newContext(Object.assign({viewport:{width:390,height:844},reducedMotion:'reduce'},options));if(init)await ctx.addInitScript(init);const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(origin);await p.locator('[data-action="continue"]').waitFor();return {ctx,p};}
async function skip(p){if(await p.locator('[data-action="tutorial-skip"]').count())await p.locator('[data-action="tutorial-skip"]').click();await pause(p);}
async function hintSolve(p,max){let hints=0;while(!await p.locator('#win').isVisible()){assert(hints<max,'hint path did not converge');await p.locator('[data-action="hint"]').click();await pause(p);if(await p.locator('[data-action="hint-apply"]').count())await p.locator('[data-action="hint-apply"]').click();else await p.locator('#close-modal').click();await pause(p);hints++;}return hints;}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});report.browser=browser.version();
let {ctx,p}=await fresh(browser,origin,()=>{localStorage.setItem('unrelated-game','kept');localStorage.setItem('mini-polish:scarlet-knot-atlas:v1:tutorial','{"version":1}');});
for(let i=0;i<L.length;i++){
 if(i===0)await p.locator('[data-action="continue"]').click();else{await p.locator('[data-action="chapters"]').click();await p.locator('[data-action="level"][data-index="'+i+'"]').click();}await pause(p);
 if([0,8,16,24,32,47].includes(i))await p.screenshot({path:path.join(release,'chapter-'+L[i].chapter+'-game-390.png'),fullPage:true});
 const hints=await hintSolve(p,L[i].initial.length*3+3),d=await ledger(p),state=d.sessions[L[i].id];assert(C.solved(state.points,L[i].edges));assert(C.restore(L[i],state));assert.equal(Object.keys(d.claims).length,i+1);assert.equal(Object.keys(d.collection).length,i+1);
 if([0,8,16,24,32,47].includes(i))await p.screenshot({path:path.join(release,'chapter-'+L[i].chapter+'-complete-390.png'),fullPage:true});
 report.campaign.push({id:L[i].id,chapter:L[i].chapter,referenceHints:hints,moves:state.history.length,zeroCrossings:true,claimCount:i+1});if((i+1)%8===0)console.log('Chapter '+L[i].chapter+' UI reference-hint replay passed.');
}
await p.locator('[data-action="collection"]').click();assert.equal(await p.locator('[data-action="inspect"]').count(),8);await p.locator('[data-action="archive-chapter"][data-index="5"]').click();await p.screenshot({path:path.join(release,'collection-390.png'),fullPage:true});await p.locator('[data-action="inspect"][data-index="47"]').click();await p.screenshot({path:path.join(release,'collection-detail-390.png'),fullPage:true});await p.locator('#close-modal').click();
let all=await ledger(p);assert.equal(Object.keys(S.restore(L,all).collection).length,48);await p.reload();await p.locator('[data-action="collection"]').click();assert((await p.locator('h1').innerText()).includes('缘签图鉴'));assert.equal(Object.keys((await ledger(p)).claims).length,48);assert.equal(await p.evaluate(()=>localStorage.getItem('unrelated-game')),'kept');report.cases.push('48 levels completed through real hint/apply UI; 48 replay-verified layouts; 48 distinct first claims; gallery eight per chapter; full refresh recovery');
await p.evaluate(k=>{var d=JSON.parse(localStorage.getItem(k));d.current=0;d.sessions['scarlet-tutorial-01'].elapsedMs=2000;localStorage.setItem(k,JSON.stringify(d));},key);await p.reload();await p.locator('[data-action="continue"]').click();await pause(p);await p.evaluate(()=>{window.qaNow=Date.now();Date.now=function(){return window.qaNow;};document.dispatchEvent(new Event('visibilitychange'));});await pause(p);await p.evaluate(()=>{window.qaNow+=10000;document.dispatchEvent(new Event('visibilitychange'));});await pause(p);assert.equal((await ledger(p)).sessions[L[0].id].elapsedMs,2000);report.cases.push('completed-session timer remains stopped across visibility events');await ctx.close();
// Actual Chromium touch input via CDP, not synthetic direct state mutations.
({ctx,p}=await fresh(browser,origin,null,{isMobile:true,hasTouch:true}));await p.locator('[data-action="continue"]').tap();await skip(p);const session=await ctx.newCDPSession(p),r=await p.locator('#board').boundingBox();let start={x:r.x+18+.2*(r.width-36),y:r.y+20+.2*(r.height-40)},end={x:r.x+18+.2*(r.width-36),y:r.y+20+.55*(r.height-40)};
await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let j=1;j<=8;j++)await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*j/8,y:start.y+(end.y-start.y)*j/8}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await pause(p);assert.equal((await ledger(p)).sessions[L[0].id].history.length,1);await p.locator('[data-action="pick"]').first().tap();await p.locator('[data-action="select"][data-id="3"]').tap();await p.locator('[data-action="nudge"][data-dx="1"]').tap();await pause(p);assert.equal((await ledger(p)).sessions[L[0].id].history.length,2);await p.screenshot({path:path.join(release,'touch-390.png'),fullPage:true});report.cases.push('Chrome CDP touch drag + tap picker + direction button');await ctx.close();
// Pointer absent: test touch fallback including cancel recovery.
({ctx,p}=await fresh(browser,origin,()=>{Object.defineProperty(window,'PointerEvent',{value:undefined});},{hasTouch:true,isMobile:true}));await p.locator('[data-action="continue"]').tap();await skip(p);await p.locator('#board').evaluate(b=>{var node=b.querySelector('.node-hit'),r=node.getBoundingClientRect(),t={clientX:r.x+22,clientY:r.y+22};function send(name,point){var e=new Event(name,{bubbles:true,cancelable:true});Object.defineProperty(e,'touches',{value:point?[point]:[]});b.dispatchEvent(e);}send('touchstart',t);send('touchmove',{clientX:t.clientX+20,clientY:t.clientY+30});send('touchcancel',null);});assert.equal((await ledger(p)).sessions[L[0].id].history.length,0);report.cases.push('PointerEvent absent touch fallback + touchcancel no step');await ctx.close();
// Native storage adapter is mocked to validate its contract, not a real container.
({ctx,p}=await fresh(browser,origin,()=>{window.nativeMap={};window.xhs={launchOptions:{miniToolEnv:{buildVersion:9462004}},miniTool:{getStorage(o){o.success({data:window.nativeMap[o.key]||null});},setStorage(o){window.nativeMap[o.key]=o.data;o.success({});}}};}));await p.locator('[data-action="continue"]').click();await skip(p);await hintSolve(p,12);assert.equal(await p.evaluate(()=>JSON.parse(window.nativeMap['mini-polish:scarlet-knot-atlas:v1:ledger']).outbox.length),1);assert.equal(await p.evaluate(()=>localStorage.getItem('mini-polish:scarlet-knot-atlas:v1:ledger')),null);report.cases.push('Mock native 9.46 Storage preferred over Web; completion ledger persisted');await ctx.close();
({ctx,p}=await fresh(browser,origin,()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='mini-polish:scarlet-knot-atlas:v1:ledger')throw new Error('quota');return original.call(this,k,v);};window.sent=[];window.ScarletRewardHost=async e=>{window.sent.push(e);return true;};}));await p.locator('[data-action="continue"]').click();await skip(p);await hintSolve(p,12);assert((await p.locator('#save-status').innerText()).includes('未能保存'));assert.equal(await p.evaluate(()=>window.sent.length),0);report.cases.push('Storage write failure visible, no host reward sent');await ctx.close();
({ctx,p}=await fresh(browser,origin,null));await p.evaluate(k=>localStorage.setItem(k,'{broken'),key);await p.reload();await p.locator('[data-action="continue"]').click();await skip(p);assert.equal((await ledger(p)).sessions[L[0].id].history.length,0);report.cases.push('Corrupt JSON fallback, no other namespace cleared');await ctx.close();
({ctx,p}=await fresh(browser,origin,null));await p.locator('[data-action="continue"]').click();await skip(p);await p.addStyleTag({content:fs.readFileSync(path.join(root,'styles.css'),'utf8').replace(/font-size:(\d+)px/g,(_,n)=>'font-size:'+(Number(n)*2)+'px')});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));await p.locator('[data-action="tutorial"]').click();await p.locator('[data-action="tutorial-next"]').click();await p.screenshot({path:path.join(release,'text-200-tutorial-390.png'),fullPage:true});report.cases.push('200% CSS text scale including controls/dialog body; SVG pictorial labels stay fixed, system scaling on real devices not tested');await ctx.close();
assert.deepEqual(report.errors,[]);fs.writeFileSync(path.join(release,'boundary-qa.json'),JSON.stringify(report,null,2)+'\n');console.log('PASS all 48 UI reference paths and '+report.cases.length+' boundary cases.');
})().catch(e=>{report.failure=e.stack;fs.writeFileSync(path.join(release,'boundary-qa.json'),JSON.stringify(report,null,2)+'\n');console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
