import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
const base=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dist=path.join(base,'dist'),out=path.join(dist,'xhs');
execFileSync(process.execPath,[path.join(base,'scripts/generate-art.mjs')],{stdio:'inherit'});
fs.mkdirSync(dist,{recursive:true});
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
let html=fs.readFileSync(path.join(base,'index.html'),'utf8');
html=html.replace(/  <script src="\.\/src\/[^\"]+"><\/script>\n/g,'');
html=html.replace('</body>','  <script src="./app.js"></script>\n</body>');
fs.writeFileSync(path.join(out,'index.html'),html);
const scripts=['engine.js','levels.js','art.js','storage.js','app.js'];
fs.writeFileSync(path.join(out,'app.js'),scripts.map(name=>fs.readFileSync(path.join(base,'src',name),'utf8')).join('\n;\n'));
fs.copyFileSync(path.join(base,'style.css'),path.join(out,'style.css'));
fs.cpSync(path.join(base,'assets'),path.join(out,'assets'),{recursive:true});
fs.writeFileSync(path.join(out,'credits.json'),JSON.stringify({title:'纸鹤归旅',license:'MIT',copyright:'2026 Ten Realms Arcade contributors',rule:'Pegs by Simon Tatham and contributors',source:'ebnbin/puzzles@5a9e1795a3324e0f6433b79fbe31cbd9b12048a3',notice:fs.readFileSync(path.join(base,'LICENSE'),'utf8'),sources:fs.readFileSync(path.join(base,'release/SOURCES.md'),'utf8')},null,2));
execFileSync(process.execPath,['--check',path.join(out,'app.js')],{stdio:'inherit'});
const zip=path.join(dist,'paper-crane-journey-xhs.zip');fs.rmSync(zip,{force:true});
execFileSync('zip',['-q','-r',zip,'.'],{cwd:out,stdio:'inherit'});
execFileSync(process.execPath,[path.join(base,'scripts/audit.mjs')],{stdio:'inherit'});
console.log('Built offline classic-script package: '+zip);
