import test from 'node:test';import assert from 'node:assert/strict';import '../core.js';import '../levels.js';import '../storage.js';import '../tutorial.js';const C=globalThis.LanternCore,L=globalThis.LanternLevels,S=globalThis.LanternStorage;
// Oracle stores each column bottom-first, discovers components via union-find;
// no production group, collapse or solver calls inside oracle.
function oracle(b){const h=b.length,w=b[0].length,parent=Array.from({length:h*w},(_,i)=>i);function root(i){while(parent[i]!==i)i=parent[i];return i;}for(let y=0;y<h;y++)for(let x=0;x<w;x++){if(b[y][x]==null)continue;for(const [dy,dx]of [[1,0],[0,1]])if(b[y+dy]&&b[y+dy][x+dx]===b[y][x])parent[root(y*w+x)]=root((y+dy)*w+x+dx);}const groups={};for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(b[y][x]!=null){const k=root(y*w+x);(groups[k]||(groups[k]=[])).push([y,x]);}return Object.values(groups).filter(g=>g.length>1);}
function collapse(b,g){const h=b.length,w=b[0].length,rm=new Set(g.map(p=>p.join())),columns=[];for(let x=0;x<w;x++){const col=[];for(let y=h-1;y>=0;y--)if(b[y][x]!=null&&!rm.has([y,x].join()))col.push(b[y][x]);if(col.length)columns.push(col);}return Array.from({length:h},(_,y)=>Array.from({length:w},(_,x)=>columns[x]&&columns[x][h-1-y]!=null?columns[x][h-1-y]:null));}
const norm=g=>g.map(a=>a.map(p=>p.join()).sort().join('|')).sort();
test('exhaustive 3x2 boards: independent components and stable columns',()=>{for(let n=0;n<729;n++){let v=n;const b=Array.from({length:2},()=>Array.from({length:3},()=>{const t=v%3;v=Math.floor(v/3);return t===2?null:t;}));assert.deepEqual(norm(C.groups(b)),norm(oracle(b)));for(const g of oracle(b))assert.deepEqual(C.stages(b,g).board,collapse(b,g));}});
test('diagonals, full component, preview immutability, no automatic chain',()=>{const b=[[0,1],[1,0]];assert.equal(C.groups(b).length,0);assert.equal(C.move(C.initial({board:b}),0,0),null);const s=C.initial({board:[[0,0,1],[2,2,1],[2,2,1]]}),snapshot=JSON.stringify(s),p=C.preview(s,0,0);assert.equal(p.delta,0);assert.equal(p.group.length,2);assert.equal(JSON.stringify(s),snapshot);const next=C.move(s,0,0);assert.equal(next.removed,2);assert.equal(next.score,0);assert.equal(next.status,'playing');assert.equal(C.group([[1,1,1],[1,0,1]],0,0).length,5);assert.equal(C.move(C.initial({board:[[0,0]]}),0,0).status,'cleared');assert.equal(C.move(C.initial({board:[[0,0]]}),0,0).score,0);});
test('all 60 witnesses independently replay to empty, exact score and no color duplicates',()=>{assert.equal(L.length,60);const seen=new Set();for(const l of L){let b=l.board,score=0;const map=new Map(),key=b[0].length+'x'+b.length+':'+b.flat().map(v=>{if(!map.has(v))map.set(v,map.size);return map.get(v);}).join();assert.ok(!seen.has(key));seen.add(key);for(const a of l.path){const g=oracle(b).find(g=>g.some(p=>p.join()===a.join()));assert.ok(g,'legal oracle move '+l.id);score+=(g.length-2)**2;b=collapse(b,g);}assert.ok(b.flat().every(v=>v===null));assert.equal(score,l.referenceScore);assert.equal(C.replay(l,l.path).score,score);if(l.chapter>=2){assert.ok(l.tags.bridges>0);assert.ok(l.tags.provenLosingFirstMoves.length>0);}if(l.chapter===5){const alt=C.replay(l,l.alternate.path);assert.equal(alt.status,'cleared');assert.notEqual(alt.score,score);}}});
test('tutorial exact chain',()=>{const t=globalThis.LanternTutorial.level,s=C.replay(t,globalThis.LanternTutorial.path);assert.equal(s.status,'cleared');assert.equal(s.score,2);assert.equal(s.moves,3);});
test('replay validates corrupted save, recomputes scores and first claim is idempotent',()=>{const d=S.fresh(),l=L[0];assert.equal(S.claim(d,l,l.path),true);assert.equal(S.claim(d,l,l.path),false);d.completed[1].score=999999;d.active={level:0,path:l.path,runId:'same'};const good=S.validate(d,L);assert.equal(good.completed[1].score,l.referenceScore);assert.equal(good.active.runId,'same');d.active.path=[[999,999]];assert.equal(S.validate(d,L).active,null);d.completed[1].path=[[0.5,0]];assert.equal(S.validate(d,L).completed[1],undefined);assert.equal(S.validate({version:9},L).tutorial,0);});
test('search cutoff never claims proof',()=>{const s=C.solve(L[40].board,0);assert.equal(s.exhaustive,false);});
function independentSearch(b){const failed=new Set();let nodes=0;function search(a){nodes++;if(a.flat().every(v=>v==null))return true;const key=JSON.stringify(a);if(failed.has(key))return false;const freq={};a.flat().forEach(v=>{if(v!=null)freq[v]=(freq[v]||0)+1;});if(Object.values(freq).some(n=>n===1))return false;for(const g of oracle(a))if(search(collapse(a,g)))return true;failed.add(key);return false;}return {solvable:search(b),nodes};}
test('each advertised losing first move independently proven by complete search',()=>{for(const l of L.filter(l=>l.chapter>=2)){const a=l.tags.provenLosingFirstMoves[0],g=oracle(l.board).find(g=>g.some(p=>p.join()===a.join()));assert.ok(g);assert.equal(independentSearch(collapse(l.board,g)).solvable,false,'losing branch '+l.id);}});
test('representative smaller-first lure and late alternative routes exist',()=>{const representative=L.find(l=>l.chapter>=2&&l.tags.provenLosingFirstMoves.some(a=>{const g=C.group(l.board,...a),max=Math.max(...C.groups(l.board).map(g=>g.length));return g.length===max&&C.group(l.board,...l.path[0]).length<max;}));assert.ok(representative);console.log('smaller-first representative',representative.id);});
