import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {solve,canonical} from '../scripts/oracle.mjs';
const ctx=vm.createContext({});for(const n of ['engine','levels','storage','renderer'])vm.runInContext(fs.readFileSync('src/'+n+'.js','utf8'),ctx);const E=ctx.SandEngine,L=ctx.SandLevels,S=ctx.SandStore,plain=x=>JSON.parse(JSON.stringify(x));
function solved(l){const path=solve(l).solutions[0],log=path.slice(0,-1).map((a,k)=>({type:'link',a,b:path[k+1]}));return {log,path,state:E.replay(l,log)};}
function memory(){const data={unrelated:'safe'};return {data,getItem:k=>data[k]||null,setItem:(k,v)=>{data[k]=v;}};}
test('60 puzzles independently unique, dihedral distinct, sequential engine replays win only at last edge',()=>{assert.equal(L.length,60);const keys=new Set();for(const l of L){const s=solve(l);assert.equal(s.count,1,l.id);assert.equal(s.exhausted,true);keys.add(canonical(l));let state=E.empty(l);for(let k=0;k<s.solutions[0].length-1;k++){const path=s.solutions[0],r=E.apply(l,state,{type:'link',a:path[k],b:path[k+1]});assert.equal(r.changed,true);state=r.next;assert.equal(E.inspect(l,state).won,k===path.length-2);}assert.equal(l.proof.nodes,s.nodes);}assert.equal(keys.size,60);});
test('oracle detects multiple/no solutions and marks budget truncation',()=>{const l=plain(L[59]);assert.equal(solve(l,2,1).truncated,true);l.givens={0:1,1:25};l.arrows[0]=-1;assert.equal(solve(l).count,0);let ambiguous=false;for(const original of L){const x=plain(original);x.givens=Object.fromEntries(Object.entries(x.givens).filter(([,n])=>n===1||n===x.size*x.size));if(solve(x).count===2){ambiguous=true;break;}}assert.ok(ambiguous);});
test('eight rays include distant targets, exclude opposite/unequal diagonals/self/out-of-range',()=>{const l={size:5,arrows:Array(25).fill(0),givens:{}};for(let d=0;d<8;d++){l.arrows[12]=d;for(let b=0;b<25;b++){const x=b%5-2,y=(b/5|0)-2,v=E.vectors[d],expected=(x!==0||y!==0)&&x*v[1]===y*v[0]&&x*v[0]+y*v[1]>0;assert.equal(E.ray(l,12,b),expected);}}assert.equal(E.ray(l,-1,4),false);assert.equal(E.ray(l,12,25),false);});
test('atomic invalid/no-op, fixed conflicts, endpoint replacement, cuts and undo replay',()=>{const l=L[0],{log,path,state:finished}=solved(l);let state=E.empty(l);const bad=E.apply(l,state,{type:'link',a:path[0],b:path[0]});assert.equal(bad.next,state);assert.equal(bad.changed,false);state=E.apply(l,state,log[0]).next;assert.equal(E.apply(l,state,log[0]).changed,false);const cut=E.apply(l,finished,{type:'cut',a:path[3]});assert.equal(E.inspect(l,cut.next).edges,l.arrows.length-3);assert.equal(E.inspect(l,cut.next).won,false);assert.deepEqual(plain(E.replay(l,log.slice(0,-1))),plain(E.apply(l,finished,{type:'cut',a:path[path.length-1]}).next));
const custom={size:3,arrows:[2,2,4,2,2,4,2,2,-1],givens:{0:1,8:9}},before=E.empty(custom);before[0]=1;const changed=E.apply(custom,before,{type:'link',a:0,b:2});assert.ok(changed.changed);assert.equal(changed.next[0],2);assert.equal(before[0],1);
const conflict={size:3,arrows:[2,2,4,2,2,4,2,2,-1],givens:{0:1,2:5,8:9}};assert.equal(E.apply(conflict,E.empty(conflict),{type:'link',a:0,b:2}).changed,false);});
test('subcycles forbidden; geometric intersections accepted; isolated fragments never win',()=>{const l={size:3,arrows:[3,2,6,2,1,4,1,2,-1],givens:{1:1,8:9}},s=E.empty(l);s[0]=4;s[4]=2;assert.equal(E.apply(l,s,{type:'link',a:2,b:0}).changed,false);const c={size:3,arrows:[3,2,5,2,2,4,1,2,-1],givens:{1:1,8:9}};let st=E.empty(c);st=E.apply(c,st,{type:'link',a:0,b:8}).next;st=E.apply(c,st,{type:'link',a:2,b:6}).next;assert.equal(E.inspect(c,st).edges,2);assert.equal(E.inspect(c,st).won,false);});
test('random operations preserve invariants; replay exactly reconstructs every accepted action',()=>{let seed=7;const rand=n=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%n;};for(const l of [L[0],L[25],L[59]]){let state=E.empty(l),log=[];for(let k=0;k<500;k++){const a={type:k%5?'link':'cut',a:rand(state.length),b:rand(state.length)},r=E.apply(l,state,a);if(r.changed){log.push(a);state=r.next;}else assert.equal(r.next,state);assert.ok(E.inspect(l,state).valid);assert.deepEqual(plain(E.replay(l,log)),plain(state));}}});
test('store validates replay, rejects forged completion/corrupt session and preserves foreign keys',()=>{const mem=memory(),store=S.open(mem,L),s=S.fresh(L[0]);s.log=solved(L[0]).log;s.hints=2;assert.ok(store.settle(L[0],s));const restored=S.open(mem,L);assert.equal(restored.db.current.log.length,8);assert.equal(Object.keys(restored.db.records).length,1);assert.equal(mem.data.unrelated,'safe');const tampered=JSON.parse(mem.data[S.prefix+'ledger']);tampered.current.log[0]={type:'link',a:1,b:1};tampered.records[L[0].id].session.log=[];mem.setItem(S.prefix+'ledger',JSON.stringify(tampered));const invalid=S.open(mem,L);assert.equal(invalid.db.current,null);assert.equal(Object.keys(invalid.db.records).length,0);mem.setItem(S.prefix+'ledger','{broken');assert.equal(S.open(mem,L).db.current,null);});
test('stable claims, persistent outbox before send, failures retried, concurrent retries deduplicated',async()=>{const mem=memory(),store=S.open(mem,L),s=S.fresh(L[0]);s.log=solved(L[0]).log;store.settle(L[0],s);store.settle(L[0],s);assert.equal(Object.keys(store.db.outbox).length,1);let calls=0,id;await store.flush({complete:p=>{calls++;id=p.completionId;assert.ok(JSON.parse(mem.data[S.prefix+'ledger']).outbox[id]);throw Error('offline');}});assert.equal(Object.keys(store.db.outbox).length,1);const host={complete:async p=>{calls++;assert.equal(p.completionId,id);return {accepted:true};}};await Promise.all([store.flush(host),store.flush(host)]);assert.equal(calls,2);assert.equal(Object.keys(store.db.outbox).length,0);store.settle(L[0],s);assert.equal(Object.keys(store.db.outbox).length,0);});
test('write failure never emits reward and unsupported schema rejected',async()=>{const store=S.open({getItem:()=>null,setItem:()=>{throw Error('full');}},L),s=S.fresh(L[0]);s.log=solved(L[0]).log;assert.equal(store.settle(L[0],s),false);let calls=0;await store.flush({complete:()=>calls++});assert.equal(calls,0);assert.ok(store.error());});
test('tutorial files are produced by formal renderer for initial/legal-one/win states',()=>{const proof=JSON.parse(fs.readFileSync('release/tutorial-proof.json')),l=L[0];assert.equal(proof.level,l.id);assert.equal(E.inspect(l,proof.states[0]).edges,0);assert.deepEqual(plain(E.apply(l,proof.states[0],proof.firstAction).next),proof.states[1]);assert.equal(E.inspect(l,proof.states[2]).won,true);proof.states.forEach((state,i)=>{const actual=fs.readFileSync('dist/xhs/tutorial-'+i+'.svg','utf8');assert.equal(actual,ctx.SandRender.svg(l,state,-1,[]));assert.equal((actual.match(/data-cell=/g)||[]).length,9);});});
test('all pending runs survive improved result and reload with independently validated evidence',async()=>{const mem=memory(),store=S.open(mem,L);for(const hints of [2,0]){const s=S.fresh(L[0]);s.log=solved(L[0]).log;s.hints=hints;store.settle(L[0],s);}assert.equal(Object.keys(store.db.outbox).length,2);const again=S.open(mem,L);assert.equal(Object.keys(again.db.outbox).length,2);assert.equal(again.db.records[L[0].id].session.hints,0);const ids=[];await again.flush({complete:p=>{ids.push(p.completionId);return true;}});assert.equal(new Set(ids).size,2);assert.equal(Object.keys(S.open(mem,L).db.outbox).length,0);});
