(function(){'use strict';var C=window.HoneyCore,V=window.HoneyView,S=window.HoneySession,L=window.HoneyLevels,CH=window.HoneyChapters,app=document.getElementById('app'),modal=document.getElementById('modal'),store=S.store(window),data,view='home',chapter=0,cell=0,mode=1,lastEdge=null,hint=null,hintTier=0,tutorialPage=0,dialogType=null,focusBefore=null,persistOk=true,deliveryBusy=false;
function level(){return L.filter(function(l){return l.id===data.current.level;})[0]||L[0];}function button(text,act,extra){return '<button data-act="'+act+'" '+(extra||'')+'>'+text+'</button>';}
function header(){return '<header><span class="brand">✿ 蜜田巡界</span><div>'+button(view==='home'?'规则':'田庄','home')+button('?', 'tutorial','aria-label="重看教程"')+'</div></header>';}
function tally(ch){return L.filter(function(l){return l.chapter===ch&&data.ledger[l.id];}).length;}
function render(){var active=document.activeElement,focusQuery=null;if(active&&app.contains(active)&&active.getAttribute('data-act')){focusQuery='[data-act="'+active.getAttribute('data-act')+'"]';['data-cell','data-mode','data-direction','data-level','data-chapter','data-flower'].forEach(function(k){if(active.hasAttribute(k))focusQuery+='['+k+'="'+active.getAttribute(k)+'"]';});}var l=level(),r=C.analyze(l,data.current.state),body='';if(view==='cover'){app.innerHTML='<div class="cover-poster"><div class="eyebrow">HONEYFIELD · FIELD JOURNAL</div><h1>蜜田巡界</h1><div class="stamp">花带上的<br>田契</div><p class="cover-sub">数字数墙，外框也算<br>围出同样大小的连通蜜田</p><div class="poster-board">'+V.board(l,data.current.state)+'</div><div class="poster-foot"><span>真实游戏渲染 · 第 '+l.id.slice(-2)+' 关</span><span>6 章 / 60 关 · 无时间压力</span></div><p class="small" style="margin-top:26px;font-size:22px">Palisade 规则 · 每区 '+l.k+' 格 · 方格田地，沿边立篱</p></div>';return;}
if(view==='home'){body='<section class="hero paper"><div class="hero-copy"><div class="seal">蜜田巡界 · 巡田册</div><div class="eyebrow">A LITTLE FIELD JOURNAL</div><h1>花带上的<br>每一张田契</h1><p class="hero-description">竖起短篱，留好通路。数字数墙，<br>每片相连的田都要一样大。</p><p class="small">'+CH[l.chapter-1]+' · 第 '+l.id.slice(-2)+' 关 / 60</p>'+button('继续巡田 →','play','class="primary"')+'</div><div class="hero-art" role="img" aria-label="原创蜜田纸地图与木尺，角落蜂蜜瓶；装饰不是实际题面"></div></section><div class="home-nav">'+button('<b>巡田册</b><span>六章田契，逐步学会分界</span>','chapters')+button('<b>压花收藏</b><span>'+Object.keys(data.ledger).length+' / 60 张田契已记入</span>','collection')+button('<b>如何巡界</b><span>三张真实棋盘，读懂数墙</span>','tutorial')+'</div><div class="rule-strip"><b>不必抢时间，也没有失败惩罚。</b><p class="small">墙数包括固定外框；每区按共享边连通，不能靠角相接。未知和“无墙”都可通行。</p></div><p class="small" style="margin-top:16px">每日田契：已证明题库按本地日期轮换 · '+button('巡一张','daily')+'</p>';}
else if(view==='chapters'){body='<div class="page-title"><div class="eyebrow">FIELD RECORDS</div><h2>六章巡田册</h2><p>按自己的节奏来。每章十张，不锁住好奇心。</p></div><div class="chapters">';CH.forEach(function(name,j){var num=j+1,done=tally(num);body+='<section class="chapter paper"><div class="chapter-top"><div><h3>'+name+'</h3><p class="small">'+L[j*10].focus+' · '+done+'/10 已巡</p></div><span class="ordinal">0'+num+'</span></div><div class="progress"><span style="width:'+done*10+'%"></span></div>'+button(chapter===num?'收起田契':'展开十张田契','chapter','data-chapter="'+num+'"');if(chapter===num){body+='<div class="level-list">';L.filter(function(x){return x.chapter===num;}).forEach(function(x){body+=button('<span class="number">'+(data.ledger[x.id]?'✓ ':'')+x.id.slice(-2)+'</span> '+x.name+'<small>'+x.n+'×'+x.n+' · 每区 '+x.k+' 格</small>','level','data-level="'+x.id+'"');});body+='</div>';}body+='</section>';});body+='</div>';}
else if(view==='collection'){body='<div class="page-title"><div class="eyebrow">PRESSED FLOWERS</div><h2>田契里的压花</h2><p>每章巡完十张，留下一枚花型。提示落边或示范属于练习，不发首通田契。</p></div><div class="collection">';CH.forEach(function(name,j){var count=tally(j+1);body+='<section class="paper collect-card '+(count===10?'':'locked')+'">'+V.flower(j)+'<h3>'+name+'</h3><p>'+count+' / 10 张</p><p class="small">'+(count===10?'花型已收集 · 田契完整':'还差 '+(10-count)+' 张 · 花影待压')+'</p>'+button('看巡田心得','flower','data-flower="'+j+'"')+'</section>';});body+='</div>';}
else if(view==='play'){body='<div class="page-title game-title"><div class="eyebrow">'+CH[l.chapter-1]+' · FIELD '+l.id.slice(-2)+'</div><h2>'+l.name+'</h2><p>每区 <b>'+l.k+' 格</b> · 共 '+l.n*l.n/l.k+' 区 · 数字含外框</p></div><div class="game-layout"><section class="field"><div class="board-wrap">'+V.board(l,data.current.state,{cell:cell,edge:lastEdge})+'<div class="cell-grid" style="grid-template-columns:repeat('+l.n+',1fr);grid-template-rows:repeat('+l.n+',1fr)">';l.clues.forEach(function(c,i){body+=button('','cell','data-cell="'+i+'" aria-label="第'+(Math.floor(i/l.n)+1)+'行第'+(i%l.n+1)+'列，'+(c===null?'无线索':'线索'+c)+'" aria-pressed="'+(cell===i)+'"');});body+='</div></div><div class="status" role="status" aria-live="polite">'+(r.complete?'✓ 每区格数、所有数字和分界一致。':r.over.length?'! 有 '+r.over.length+' 格墙数超过数字，可擦除或撤销。':r.stray.length?(r.sizes?'! 有墙两侧绕路仍相连，需调整分界。':'篱边还有开口，两侧仍可绕行；继续围成等格田区。'):r.groups.length+' 片可通行范围 · 尚未全部围成 '+l.k+' 格。')+'</div><p class="small">土色仅作材质。通关后，同一区显相同花纹。<br>外框固定 🔒；对角接触不能连通。</p>';if(r.complete)body+='<div class="success"><h3>这片田，界线清楚了</h3><div class="checks">✓ 每区 '+l.k+' 格 / 共 '+l.n+' 区<br>✓ 全部线索满足<br>✓ 每道内墙确实分隔不同区</div><p>'+ (data.current.practice?'练习完成 · 本次不记首通田契':data.ledger[l.id]?'田契已记入 · 重复巡田不重复发放':'正在核验田契')+'</p>'+button('下一张田契','next','class="primary"')+button('看压花','collection')+'</div>';body+='</section><aside class="paper input-paper"><div class="stage-tag">01 先点一格 · 02 选方向边</div><div class="selected-line">已选 <b>第'+(Math.floor(cell/l.n)+1)+'行第'+(cell%l.n+1)+'列</b><br>'+(lastEdge?'双圈标出刚选的边':'方向键会按当前模式直接设置该边')+'</div><div class="directions">';['↑ 上边','→ 右边','↓ 下边','← 左边'].forEach(function(t,d){var k=C.side(l,cell,d);body+=button(t+(k===null?' 🔒':''),'edge','data-direction="'+d+'" '+(k===null?'disabled':'')+' aria-label="设置所选格'+t.slice(2)+'"');});body+='</div><p class="small">固定外框计入数字，不能修改。</p><div class="modes">'+button('┃ 墙','mode','data-mode="1" class="'+(mode===1?'chosen':'')+'" aria-pressed="'+(mode===1)+'"')+button('┄ 无墙','mode','data-mode="2" class="'+(mode===2?'chosen':'')+'" aria-pressed="'+(mode===2)+'"')+button('□ 擦除','mode','data-mode="0" class="'+(mode===0?'chosen':'')+'" aria-pressed="'+(mode===0)+'"')+'</div><div class="tools">'+button('撤销','undo',data.current.undo.length?'':'disabled')+button('重做','redo',data.current.redo.length?'':'disabled')+button('提示','hint')+'</div><p class="small">无墙是确定通路的笔记；擦除回到未知。<br>编辑 '+data.current.state.moves+' 次 · 无时间压力</p>';if(hint){body+='<div class="hint" aria-live="polite"><b>巡田木尺 · '+hintTier+'/3</b><p>'+ (hintTier===1?'先看双框格的数字与相连范围。':hint.reason)+'</p>'+button(hintTier<2?'解释原因':hintTier===2?'设置这条边（练习）':'继续找提示',hintTier<2?'explain':hintTier===2?'apply-hint':'hint')+'</div>';}body+='<div class="extra">'+button('重开本张田契','restart')+button('田形示范 · 练习','demonstrate')+button(data.muted?'声音：关闭':'声音：开启','sound')+button('巡田册','chapters')+'</div><p class="small">键盘：方向键选格；Shift+方向键设边；1墙 / 2无墙 / 0擦除；Z撤销 / Y重做。</p></aside></div>';}
app.innerHTML='<main class="shell">'+header()+body+(!persistOk?'<p class="notice" role="status">本局可玩，进度暂无法保存。请保留当前页面。</p>':'')+'</main>';if(focusQuery&&!dialogType){var target=app.querySelector(focusQuery);if(target&&!target.disabled)target.focus();}}
async function flush(){var ok=await store.save(data);persistOk=ok;if(ok)await deliver();return ok;}
async function deliver(){if(deliveryBusy||!window.HoneyfieldHost||typeof window.HoneyfieldHost.complete!=='function')return;deliveryBusy=true;try{var keys=Object.keys(data.ledger);for(var i=0;i<keys.length;i++){var v=data.ledger[keys[i]];if(v.delivered)continue;try{var ack=await window.HoneyfieldHost.complete({game:'honeyfield-boundaries',levelId:keys[i],completionId:v.completionId,claimId:v.claimId,reward:1});if(ack===true){v.delivered=true;await store.save(data);}}catch(e){}}}finally{deliveryBusy=false;}}
function settle(){var l=level();S.claim(l,data);flush().then(function(){if(view==='play')render();});}
function tone(){if(data.muted)return;var AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;try{var ctx=new AC(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=410;gain.gain.setValueAtTime(.025,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.08);osc.start();osc.stop(ctx.currentTime+.1);osc.onended=function(){ctx.close();};}catch(e){}}
function moveEdge(d){var l=level(),key=C.side(l,cell,d);if(key===null)return;lastEdge=key;if(S.edit(l,data.current,key,mode)){hint=null;hintTier=0;tone();settle();}render();}
function change(id){var l=L.filter(function(x){return x.id===id;})[0];if(!l)return;if(data.current.level!==id)data.current=S.run(l);cell=0;lastEdge=null;hint=null;hintTier=0;view='play';flush();render();window.scrollTo(0,0);}
var tutorialMeta=null;function getTutorial(){var l=L[0],start=C.fresh(l),a=l.hintTrace[0],step=C.set(l,start,a.key,a.value),end={edges:Object.assign({},l.solution),moves:C.edges(l).filter(function(k){return l.solution[k]===1;}).length};return {l:l,a:a,states:[start,step,end]};}
function showDialog(type){if(dialogType)closeDialog(false);focusBefore=document.activeElement;dialogType=type;document.body.style.overflow='hidden';drawDialog();}
function closeDialog(read){if(dialogType==='tutorial'&&read){data.tutorial=1;flush();}dialogType=null;modal.hidden=true;modal.innerHTML='';document.body.style.overflow='';if(focusBefore&&document.contains(focusBefore))focusBefore.focus();else{var b=app.querySelector('button');if(b)b.focus();}}
function drawDialog(){var title='',body='',foot='';if(dialogType==='tutorial'){var t=getTutorial(),titles=['数字数墙，外框也算','点格、选模式，再选方向','同样大小，沿共享边连通'],texts=['这是真实第一关初态。奶油标签的数字表示该格四边共有几道墙，外圈木篱也在内。最后每个连通田区恰好四格。','同一题从初态执行了一次真实输入。双框标出相关格，双圈标出这次设置的边：'+(t.a.value===1?'木篱实线是墙。':'蓝灰虚线是“无墙”笔记。')+'选格后，用四个方向按钮精确设置边，不用挤着点交叉处。','同一题的真实完成态。四个区各四格、所有数字满足，每道内墙的两侧属于不同区。区可以有折角；同一区绕路还能相连的两侧不能隔墙。'];title='如何巡界';body='<div class="stage-tag">0'+(tutorialPage+1)+' / 03 · '+(tutorialPage===0?'元素':tutorialPage===1?'操作':'通关')+'</div><h3>'+titles[tutorialPage]+'</h3><div class="tutorial-board">'+V.board(t.l,t.states[tutorialPage],{cell:tutorialPage===1?t.a.cell:undefined,edge:tutorialPage===1?t.a.key:null,caption:'真实教程第'+(tutorialPage+1)+'图'})+'</div><p>'+texts[tutorialPage]+'</p><p class="small">无墙和未知都可通行；笔记不必补齐才通关。提示第三级和田形示范为练习。可以随时重看。</p>';foot=button(tutorialPage?'上一张':'跳过',tutorialPage?'tutorial-prev':'close')+button(tutorialPage===2?'看完，去巡田':'下一张',tutorialPage===2?'tutorial-done':'tutorial-next','class="primary"');}
else if(dialogType==='restart'){title='重新巡这张田契';body='<p>本张的篱笆与撤销记录会重新开始。已核验的首通田契和压花会保留。</p>';foot=button('保留当前','close')+button('重开','restart-confirm','class="primary"');}
else if(dialogType==='demonstrate'){title='看看完整田形';body='<p>展示本张真实解，并标为练习。本局不发首通田契；重开即可独立巡田。</p>';foot=button('继续自己巡','close')+button('进入示范','demonstrate-confirm','class="primary"');}
else if(dialogType.indexOf('flower:')===0){var j=+dialogType.split(':')[1];title=CH[j];body=V.flower(j)+'<p>'+['角格先计两面外框；相邻格共用同一道篱；数字已足时留通路。','数字缺几面就补几面；明确无墙帮助传递；局部全对还要核验整片田。','连通区可以转折；容量满格就封边；对角接触不属于通路。','五格代替四格，规则不变；细长区仍合法；留意被围小的块。','用四方向精确设边；合并超六格就封边；双圈帮助复核选中边。','同时核对数字与容量；去掉同区冗余墙；全局连通后再收田契。'][j]+'</p>';foot=button('回到压花','close');}
modal.hidden=false;modal.innerHTML='<div class="modal-backdrop"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div class="dialog-head"><h2 id="dialog-title">'+title+'</h2>'+button('×','close','aria-label="关闭"')+'</div><div class="dialog-body">'+body+'</div><div class="dialog-foot">'+foot+'</div></section></div>';modal.querySelector('.dialog-body').scrollTop=0;modal.querySelector('button').focus();}
function makeHint(){var l=level(),r=data.current;var wrong=C.edges(l).filter(function(k){return r.state.edges[k]!==0&&r.state.edges[k]!==l.solution[k];})[0];if(wrong)hint={key:wrong,value:0,cell:C.adjacent(l,wrong)[0],reason:'这条已设置的边与本题唯一解冲突。先擦除它，再用数字与容量核对。'};else hint=C.deduction(l,r.state)||l.hintTrace.filter(function(a){return r.state.edges[a.key]!==a.value;})[0];if(!hint)return;cell=hint.cell;lastEdge=null;hintTier=1;r.hints++;flush();render();}
function act(el){var a=el.getAttribute('data-act');if(!a)return;if(a==='close'){closeDialog(true);return;}if(a==='tutorial-next'){tutorialPage++;drawDialog();return;}if(a==='tutorial-prev'){tutorialPage--;drawDialog();return;}if(a==='tutorial-done'){closeDialog(true);view='play';render();return;}if(a==='tutorial'){tutorialPage=0;showDialog('tutorial');return;}if(a==='home'){if(view==='home'){tutorialPage=0;showDialog('tutorial');}else{view='home';render();}return;}if(['play','chapters','collection'].includes(a)){view=a;render();window.scrollTo(0,0);return;}if(a==='chapter'){chapter=chapter===+el.dataset.chapter?0:+el.dataset.chapter;render();return;}if(a==='level'){change(el.dataset.level);return;}if(a==='next'){var idx=L.indexOf(level());change(L[(idx+1)%L.length].id);return;}if(a==='daily'){var now=new Date(),day=Math.floor(Date.UTC(now.getFullYear(),now.getMonth(),now.getDate())/86400000);change(L[day%60].id);return;}if(a==='flower'){showDialog('flower:'+el.dataset.flower);return;}if(a==='cell'){cell=+el.dataset.cell;lastEdge=null;render();var b=app.querySelector('[data-cell="'+cell+'"]');if(b)b.focus();return;}if(a==='mode'){mode=+el.dataset.mode;render();return;}if(a==='edge'){moveEdge(+el.dataset.direction);return;}if(a==='undo'||a==='redo'){S[a](data.current);lastEdge=null;hint=null;settle();render();return;}if(a==='hint'){makeHint();return;}if(a==='explain'){hintTier=2;render();return;}if(a==='apply-hint'&&hint){data.current.practice=true;lastEdge=hint.key;S.edit(level(),data.current,hint.key,hint.value);hintTier=3;settle();render();return;}if(a==='restart'||a==='demonstrate'){showDialog(a);return;}if(a==='restart-confirm'){data.current=S.run(level());cell=0;lastEdge=null;hint=null;hintTier=0;closeDialog(false);flush();render();return;}if(a==='demonstrate-confirm'){var l=level();data.current.practice=true;C.edges(l).forEach(function(k){S.edit(l,data.current,k,l.solution[k]);});lastEdge=null;hint=null;closeDialog(false);settle();render();return;}if(a==='sound'){data.muted=!data.muted;flush();render();}}
document.addEventListener('click',function(e){var el=e.target.closest('button[data-act]');if(el&&!el.disabled)act(el);});
document.addEventListener('keydown',function(e){if(dialogType){if(e.key==='Escape'){e.preventDefault();closeDialog(true);}if(e.key==='Tab'){var bs=Array.from(modal.querySelectorAll('button:not([disabled])')),first=bs[0],last=bs[bs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(view!=='play'||e.ctrlKey||e.metaKey||e.altKey)return;var dirs={ArrowUp:0,ArrowRight:1,ArrowDown:2,ArrowLeft:3};if(e.key in dirs){e.preventDefault();var d=dirs[e.key];if(e.shiftKey)moveEdge(d);else{var n=level().n,x=cell%n,y=Math.floor(cell/n);if(d===0)y=Math.max(0,y-1);if(d===1)x=Math.min(n-1,x+1);if(d===2)y=Math.min(n-1,y+1);if(d===3)x=Math.max(0,x-1);cell=y*n+x;lastEdge=null;render();app.querySelector('[data-cell="'+cell+'"]').focus();}}else if(['0','1','2'].includes(e.key)){mode=+e.key;render();}else if(e.key.toLowerCase()==='z'){S.undo(data.current);hint=null;lastEdge=null;settle();render();}else if(e.key.toLowerCase()==='y'){S.redo(data.current);hint=null;lastEdge=null;settle();render();}});
document.addEventListener('visibilitychange',function(){if(data)flush();});
store.init().then(function(result){persistOk=result.ok;data=S.restore(L,result.data);if(window.location.search==='?cover'){view='cover';render();return;}render();if(!data.tutorial){tutorialPage=0;showDialog('tutorial');}settle();});
})();
