(function(root){'use strict';var C=root.HoneyCore,KEY='mini-polish:honeyfield-boundaries:v1:save';
function hash(l){var t=JSON.stringify([l.id,l.n,l.k,l.clues]),h=2166136261;for(var i=0;i<t.length;i++)h=Math.imul(h^t.charCodeAt(i),16777619);return (h>>>0).toString(16);}
function uid(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10);}
function run(l){return {level:l.id,checksum:hash(l),runId:uid(),state:C.fresh(l),undo:[],redo:[],practice:false,hints:0};}
function normalizeRun(l,r){if(!r||r.level!==l.id||r.checksum!==hash(l)||typeof r.runId!=='string'||!r.runId.length||r.runId.length>100)return null;var s=C.normalize(l,r.state);if(!s)return null;function hist(a){return Array.isArray(a)?a.slice(-200).map(function(x){return C.normalize(l,x);}).filter(Boolean):[];}return {level:l.id,checksum:r.checksum,runId:r.runId,state:s,undo:hist(r.undo),redo:hist(r.redo),practice:r.practice===true,hints:Number.isInteger(r.hints)&&r.hints>=0?r.hints:0};}
function blank(levels){return {schema:1,current:run(levels[0]),ledger:{},tutorial:0,muted:true};}
function restore(levels,data){var b=blank(levels);if(!data||data.schema!==1)return b;var l=levels.filter(function(x){return data.current&&x.id===data.current.level;})[0];b.current=l&&normalizeRun(l,data.current)||b.current;b.tutorial=data.tutorial===1?1:0;b.muted=data.muted!==false;if(data.ledger&&typeof data.ledger==='object')levels.forEach(function(x){var v=data.ledger[x.id];if(v&&v.checksum===hash(x)&&C.solved(x,v.proof)&&v.claimId==='honeyfield-boundaries:'+x.id+':first-v1'&&typeof v.runId==='string')b.ledger[x.id]={checksum:v.checksum,proof:C.normalize(x,v.proof),claimId:v.claimId,completionId:'honeyfield-boundaries:'+x.id+':'+v.runId,runId:v.runId,delivered:v.delivered===true};});return b;}
function edit(l,r,key,v){var next=C.set(l,r.state,key,v);if(!next)return false;r.undo.push(r.state);r.undo=r.undo.slice(-200);r.redo=[];r.state=next;return true;}
function undo(r){if(!r.undo.length)return false;r.redo.push(r.state);r.state=r.undo.pop();return true;}
function redo(r){if(!r.redo.length)return false;r.undo.push(r.state);r.state=r.redo.pop();return true;}
function claim(l,b){var r=b.current;if(r.practice||!C.solved(l,r.state)||b.ledger[l.id])return null;var v={checksum:hash(l),proof:C.normalize(l,r.state),claimId:'honeyfield-boundaries:'+l.id+':first-v1',completionId:'honeyfield-boundaries:'+l.id+':'+r.runId,runId:r.runId,delivered:false};b.ledger[l.id]=v;return v;}
function store(env){var backend=null,queue=Promise.resolve();async function init(){var x=env.xhs,mt=x&&x.miniTool,launch=x&&x.launchOptions;if(mt&&typeof mt.getLaunchOptions==='function'&&!launch)try{launch=await mt.getLaunchOptions();}catch(e){}var version=launch&&launch.miniToolEnv&&launch.miniToolEnv.buildVersion;if(Math.floor((+version||0)/1000)>=9460&&mt&&typeof mt.getStorage==='function'&&typeof mt.setStorage==='function')backend={read:async function(){var r=await mt.getStorage({key:KEY});return r.data;},write:async function(s){await mt.setStorage({key:KEY,data:s});}};else backend={read:async function(){return env.localStorage.getItem(KEY);},write:async function(s){env.localStorage.setItem(KEY,s);}};try{var raw=await backend.read();return {ok:true,data:raw?JSON.parse(raw):null};}catch(e){return {ok:false,data:null};}}
function save(b){var raw;try{raw=JSON.stringify(b);}catch(e){return Promise.resolve(false);}var task=queue.then(async function(){try{await backend.write(raw);return true;}catch(e){return false;}});queue=task.then(function(){});return task;}return {init:init,save:save};}
root.HoneySession={KEY:KEY,hash:hash,run:run,restore:restore,blank:blank,edit:edit,undo:undo,redo:redo,claim:claim,store:store};})(typeof window!=='undefined'?window:globalThis);
