var HarborStore=(function(){'use strict';var KEY='mini-polish:cloudharbor-chart:v1:save',api=null,queue=Promise.resolve();
async function init(){var x=typeof window!=='undefined'&&window.xhs,m=x&&x.miniTool,opts=x&&x.launchOptions;if(!opts&&m&&typeof m.getLaunchOptions==='function'){try{opts=await m.getLaunchOptions();}catch(e){}}
var build=Number(opts&&opts.miniToolEnv&&opts.miniToolEnv.buildVersion)||0;if(Math.floor(build/1000)>=9460&&m&&typeof m.getStorage==='function'&&typeof m.setStorage==='function')api=m;}
async function read(){await init();try{var value=api?(await api.getStorage({key:KEY})).data:localStorage.getItem(KEY);return {ok:true,data:value?JSON.parse(value):null};}catch(e){return {ok:false,data:null};}}
function write(data){var text=JSON.stringify(data);var task=queue.then(async function(){try{if(api)await api.setStorage({key:KEY,data:text});else localStorage.setItem(KEY,text);return true;}catch(e){return false;}});queue=task.then(function(){});return task;}
function fresh(){return {version:1,level:0,session:null,completed:{},claims:{},outbox:[],tutorial:0,settings:{sound:false}};}
function validate(data,levels){var clean=fresh();if(!data||data.version!==1)return clean;clean.level=Number.isInteger(data.level)&&levels[data.level]?data.level:0;clean.tutorial=data.tutorial===1?1:0;clean.settings.sound=!!(data.settings&&data.settings.sound);
if(data.session&&data.session.level===clean.level){var p=levels[clean.level],s=data.session;if(typeof s.runId==='string'&&s.runId.length<100&&Harbor.valid(p,s.state)&&Array.isArray(s.history)&&s.history.length<=100&&s.history.every(function(t){return Harbor.valid(p,t);})&&Number.isInteger(s.hints)&&s.hints>=0)clean.session=s;}
levels.forEach(function(p){var c=data.completed&&data.completed[p.id];if(c&&Harbor.valid(p,c.state)&&Harbor.inspect(p,c.state).complete&&typeof c.runId==='string'){clean.completed[p.id]=c;clean.claims['first:'+p.id]=true;if(c.noHint)clean.claims['nohint:'+p.id]=true;}});
// Claims and outbox are rebuilt from verified complete networks, never trusted booleans.
Object.keys(clean.completed).forEach(function(id){var c=clean.completed[id];if(c.delivered)return;clean.outbox.push({gameId:'cloudharbor-chart',levelId:id,generatorVersion:'cloudharbor-gen-1',seed:levels.find(function(p){return p.id===id;}).seed,runId:c.runId,completionId:'cloudharbor-chart:'+id+':'+c.runId,rewardClaimId:'first:'+id});});return clean;}
function claim(save,p,session){if(!Harbor.inspect(p,session.state).complete)return false;var first=!save.claims['first:'+p.id];if(first){save.completed[p.id]={state:Harbor.clone(session.state),runId:session.runId,noHint:session.hints===0};save.claims['first:'+p.id]=true;save.outbox.push({gameId:'cloudharbor-chart',levelId:p.id,generatorVersion:'cloudharbor-gen-1',seed:p.seed,runId:session.runId,completionId:'cloudharbor-chart:'+p.id+':'+session.runId,rewardClaimId:'first:'+p.id});}if(session.hints===0){save.claims['nohint:'+p.id]=true;save.completed[p.id].noHint=true;}return first;}
return {read:read,write:write,fresh:fresh,validate:validate,claim:claim,key:KEY};}());
if(typeof module!=='undefined')module.exports=HarborStore;
