import test from 'node:test';import assert from 'node:assert/strict';
import {LEVELS} from '../src/levels.mjs';import {initial,change,inspect,pathState,validState,DIRS,TILES,pop,neighbor} from '../src/engine.mjs';import {solve,analyze} from '../scripts/oracle.mjs';import {tutorialStates,boardSvg} from '../src/render.mjs';
test('all 60 stable puzzles: independent exhaustive uniqueness + exact engine replay',()=>{
 assert.equal(LEVELS.length,60);assert.equal(new Set(LEVELS.map(p=>p.id)).size,60);
 for(const p of LEVELS){const noAnswer={n:p.n,entry:p.entry,exit:p.exit,rows:p.rows,cols:p.cols,givens:p.givens};const result=solve(noAnswer);assert.equal(result.count,1,p.id);assert.equal(result.exhausted,true,p.id);assert.deepEqual(result.solutions[0],p.path);const solved=pathState(p,result.solutions[0]);assert.equal(inspect(p,solved).status,'won');let s=initial(p);assert(validState(p,s));assert.notEqual(inspect(p,s).status,'won');for(const i of p.path){const r=change(p,s,i,solved.masks[i]);if(r.ok)s=r.state;}assert.equal(inspect(p,s).status,'won',p.id+' replay');assert.deepEqual(inspect(p,s).rows,p.rows);assert.deepEqual(inspect(p,s).cols,p.cols);}
});
test('atomic invalid actions preserve exact object, moves and notes; shared edges match',()=>{
 for(const p of [LEVELS[0],LEVELS[30],LEVELS[59]]){const s=initial(p),before=JSON.stringify(s);for(let i=-1;i<=p.n*p.n;i++)for(const tile of [0,1,3,5,6,7,9,10,12,15,16]){const r=change(p,s,i,tile);assert.equal(JSON.stringify(s),before);if(!r.ok)assert.equal(r.state,s);else{assert(validState(p,r.state));assert.equal(r.state.moves,1);for(const d of DIRS){const j=neighbor(p,i,d);if(j>=0)assert.equal(!!(r.state.masks[i]&d.bit),!!(r.state.masks[j]&d.op));}}}}
});
test('unknown, candidate and exclusion are separate from formal tracks and quotas',()=>{const p=LEVELS[0],s=initial(p),i=s.masks.findIndex(x=>!x);const a=change(p,s,i,1,'note'),b=change(p,s,i,2,'note');assert(a.ok&&b.ok);assert.deepEqual(a.state.masks,s.masks);assert.deepEqual(inspect(p,a.state).rows,inspect(p,s).rows);assert.notEqual(inspect(p,a.state).status,'won');assert.equal(b.state.notes[i],2);const goal=pathState(p,p.path);assert.equal(inspect(p,goal).status,'won');assert(goal.notes.every(x=>x===0));});
test('detached ring cannot satisfy global victory even when ports and quotas match',()=>{
 const p={n:4,entry:0,exit:0,rows:[1,3,3,1],cols:[4,0,2,2],givens:[[0,12],[12,5]]};const s={masks:[12,0,0,0,5,0,6,12,5,0,3,9,5,0,0,0],notes:Array(16).fill(0),moves:0};assert(validState(p,s));const v=inspect(p,s);assert.deepEqual(v.rows,p.rows);assert.deepEqual(v.cols,p.cols);assert.equal(v.status,'conflict');assert.equal(v.path.length,0);
});
test('dead ends with exact quotas, bad fixed pieces, out of bounds and branches never win',()=>{const p=LEVELS[59],goal=pathState(p,p.path),bad=JSON.parse(JSON.stringify(goal));const index=p.path[5],next=p.path[6],d=DIRS.find(d=>neighbor(p,index,d)===next);bad.masks[index]&=~d.bit;bad.masks[next]&=~d.op;assert.notEqual(inspect(p,bad).status,'won');const corrupt=JSON.parse(JSON.stringify(goal));corrupt.masks[0]=15;assert(!validState(p,corrupt));assert.equal(inspect(p,corrupt).status,'conflict');});
test('oracle matches a completely enumerated tile assignment model on a small puzzle',()=>{
 const p={n:2,entry:0,exit:1,rows:[2,1],cols:[1,2],givens:[]};let count=0;
 for(const a of [0,...TILES])for(const b of [0,...TILES])for(const c of [0,...TILES])for(const d of [0,...TILES]){const masks=[a,b,c,d];const board={masks,notes:[0,0,0,0],moves:0};if(validState(p,board)&&inspect(p,board).status==='won')count++;}
 const result=solve(p,{limit:100});assert(result.exhausted);assert.equal(result.count,count);assert(count>0);
});
test('budget truncation is never a proof',()=>{const r=solve(LEVELS[59],{budget:1});assert(r.truncated);assert(!r.exhausted);});
test('tutorial is same real puzzle at initial, legal action and verified completion',()=>{const p=LEVELS[0],t=tutorialStates(p);assert.deepEqual(t.states[0],initial(p));assert.deepEqual(t.states[1],change(p,t.states[0],t.action.cell,t.action.mask).state);assert.equal(t.states[1].moves,1);assert.equal(inspect(p,t.states[2]).status,'won');for(const s of t.states){const svg=boardSvg(p,s,-1,false);assert.equal((svg.match(/class="cell /g)||[]).length,p.n*p.n);assert(svg.includes('data-level="fr-001"'));}});
test('six chapters have ten structurally distinct levels, later chapters reduce fixed clues',()=>{for(let c=0;c<6;c++){const ps=LEVELS.filter(p=>p.chapter===c);assert.equal(ps.length,10);if(c===2)assert(ps.every(p=>p.rows.includes(0)||p.cols.includes(0)));}const first=LEVELS.slice(0,10).reduce((a,p)=>a+p.metrics.fixedRatio,0),last=LEVELS.slice(50).reduce((a,p)=>a+p.metrics.fixedRatio,0);assert(first>last*2);assert(LEVELS[59].metrics.unresolved>0);});
