import test from 'node:test';import assert from 'node:assert/strict';import {LEVELS} from '../src/levels.mjs';import {pathState,initial,inspect,change} from '../src/engine.mjs';import {blank,newRun,normalize,complete,flush,perform,undo,TUTORIAL,daily} from '../src/session.mjs';import {createStorage,PREFIX} from '../src/storage.mjs';
const p=LEVELS[0];
function won(data,level=p,mode='main',key=level.id){const run=newRun(level,mode);run.board=pathState(level,level.path);data.sessions[key]=run;return run;}
test('undo and restart preserve state semantics and do not erase earned rewards',()=>{const run=newRun(p),solved=pathState(p,p.path);const i=p.path.find(i=>change(p,run.board,i,solved.masks[i]).ok),before=JSON.stringify(run.board);assert(perform(p,run,i,solved.masks[i]).ok);assert(undo(run));assert.equal(JSON.stringify(run.board),before);const data=blank(),finished=won(data);complete(data,p,finished,LEVELS,p.id);const oldClaims=data.claims.slice();data.sessions[p.id]=newRun(p);assert.deepEqual(data.claims,oldClaims);assert(data.records[p.id]);});
test('one run settles once, replays do not duplicate first/solo/station rewards',()=>{const data=blank(),run=won(data);const e=complete(data,p,run,LEVELS,p.id);assert.equal(e.schemaVersion,1);assert.equal(e.completionId,'fr:'+run.runId);assert.deepEqual(e.rewardClaims,['first:fr-001','solo:fr-001']);assert.equal(complete(data,p,run,LEVELS,p.id),null);assert.equal(data.outbox.length,1);const second=won(data);const e2=complete(data,p,second,LEVELS,p.id);assert.deepEqual(e2.rewardClaims,[]);for(const q of LEVELS.slice(1,10)){const r=won(data,q);complete(data,q,r,LEVELS,q.id);}assert.equal(data.claims.filter(c=>c==='station:0').length,1);});
test('hint completion is labeled and later independent completion improves record once',()=>{const data=blank(),r=won(data);r.hints=1;const e=complete(data,p,r,LEVELS,p.id);assert(e.metrics.assisted);assert.equal(data.records[p.id].assisted,true);assert(!data.claims.includes('solo:'+p.id));const solo=won(data);const improved=complete(data,p,solo,LEVELS,p.id);assert.deepEqual(improved.rewardClaims,['solo:'+p.id]);assert(!data.records[p.id].assisted);});
test('outbox persists before host, rejected/throwing host retains stable completion ID',async()=>{const data=blank(),r=won(data);complete(data,p,r,LEVELS,p.id);const id=data.outbox[0].completionId;const calls=[];const store={write:async data=>{calls.push('save');return true;}};await flush(data,store,async()=>{calls.push('host');throw Error('offline');});assert.equal(calls[0],'save');assert.equal(data.outbox[0].completionId,id);await flush(data,store,async e=>{assert.equal(e.completionId,id);assert(!('proof'in e));return {accepted:true};});assert.equal(data.outbox.length,0);});
test('failed persistence prevents host delivery and rolls back failed acknowledgement persistence',async()=>{const data=blank(),r=won(data);complete(data,p,r,LEVELS,p.id);let sent=0;assert.equal(await flush(data,{write:async()=>false},()=>{sent++;return true;}),false);assert.equal(sent,0);let saves=0;assert.equal(await flush(data,{write:async()=>++saves===1},()=>true),false);assert.equal(data.outbox.length,1);});
test('damaged/forged saves are revalidated; tutorial version migration keeps real records',()=>{assert.deepEqual(normalize(null,LEVELS),blank());const fake=blank();fake.records[p.id]={completed:true,board:initial(p),completionId:'fr:fake'};fake.claims=['station:0'];assert.equal(Object.keys(normalize(fake,LEVELS).records).length,0);const data=blank(),r=won(data);complete(data,p,r,LEVELS,p.id);data.tutorial='old-version';const clean=normalize(JSON.parse(JSON.stringify(data)),LEVELS);assert(clean.records[p.id]);assert.equal(clean.tutorial,'old-version');clean.tutorial=TUTORIAL;assert(clean.claims.includes('first:'+p.id));assert.equal(clean.sessions[p.id].runId,r.runId);assert.equal(complete(clean,p,clean.sessions[p.id],LEVELS,p.id),null);});
test('daily is Beijing calendar fixed-library selection, replay is idempotent',()=>{const a=daily(LEVELS,new Date('2026-09-22T15:59:59Z')),b=daily(LEVELS,new Date('2026-09-22T16:00:00Z'));assert.equal(a.date,'2026-09-22');assert.equal(b.date,'2026-09-23');assert.notEqual(a.level.id,b.level.id);const data=blank(),r=won(data,a.level,'daily',a.key);complete(data,a.level,r,LEVELS,a.key);assert(data.claims.includes(a.key));assert.equal(Object.keys(data.records).length,0);assert(normalize(data,LEVELS).claims.includes(a.key));});
test('browser storage is private, catches denied/corrupt storage and never clears other games',async()=>{const seen=[];const root={localStorage:{getItem:k=>{seen.push(k);return '{bad';},setItem:(k,v)=>{seen.push(k);throw Error('quota');},clear:()=>assert.fail('clear')}};const s=await createStorage(root);assert.equal(s.mode,'browser');assert.equal(await s.read(),null);assert.equal(await s.write(blank()),false);assert(seen.every(k=>k===PREFIX+'profile'));});
test('native storage uses version without build suffix, imports old browser data once',async()=>{let native=null,legacy=JSON.stringify(blank());const calls=[];const root={xhs:{launchOptions:{miniToolEnv:{buildVersion:9462004}},miniTool:{getStorage:async x=>{calls.push('get');return {data:native};},setStorage:async x=>{calls.push('set');native=x.data;}}},localStorage:{getItem:()=>legacy,setItem:()=>assert.fail('native must not write fallback')}};const s=await createStorage(root);assert.equal(s.mode,'native');assert.deepEqual(await s.read(),blank());assert.equal(calls.join(','),'get,set');await s.write({version:1});assert.deepEqual(native,{version:1});});
test('async launch options fallback and unavailable bridge leave browser playable',async()=>{const root={xhs:{miniTool:{getLaunchOptions:async()=>({miniToolEnv:{buildVersion:9459999}}),getStorage:()=>assert.fail('old client')}},localStorage:{getItem:()=>null,setItem:()=>{}}};const s=await createStorage(root);assert.equal(s.mode,'browser');assert.equal(await s.write(blank()),true);});
test('daily first claim survives restarting, refresh and same-day replay',()=>{const data=blank(),d=daily(LEVELS,new Date('2026-09-22T00:00:00Z')),r=won(data,d.level,'daily',d.key);complete(data,d.level,r,LEVELS,d.key);data.sessions[d.key]=newRun(d.level,'daily');const restored=normalize(data,LEVELS);assert(restored.claims.includes(d.key));const r2=won(restored,d.level,'daily',d.key);assert.deepEqual(complete(restored,d.level,r2,LEVELS,d.key).rewardClaims,[]);});
test('transient native read failure never overwrites an existing save with blank progress',async()=>{let writes=0;const root={xhs:{launchOptions:{miniToolEnv:{buildVersion:9462004}},miniTool:{getStorage:async()=>{throw Error('temporary');},setStorage:async()=>{writes++;},getStorageInfo:async()=>({keys:[PREFIX+'profile']})}}};const s=await createStorage(root);await assert.rejects(()=>s.read());assert.equal(await s.write(blank()),false);assert.equal(writes,0);});
